### ISSUE TITLE
cowsierscipiszczy.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1000]
https://cowsierscipiszczy.pl/sklad-karmy/
Należy scrollować stronę najpierw w dół, a później w górę
![opera zdjecie_2018-08-08_090854_cowsierscipiszczy pl](https://user-images.githubusercontent.com/36385327/43822006-16c3ada8-9aeb-11e8-8bdd-db69fe986132.png)
Po długim czasie (nie mogę określić konkretnego czasu)
![opera zdjecie_2018-08-08_092102_cowsierscipiszczy pl](https://user-images.githubusercontent.com/36385327/43822525-a3a52c8c-9aec-11e8-9f64-61263db4f69b.png)

I nie wiem czy nie ukryć też tego
![opera zdjecie_2018-08-08_092411_cowsierscipiszczy pl](https://user-images.githubusercontent.com/36385327/43822603-dc597e16-9aec-11e8-9a59-bde4ae6db0b8.png)

### Typ elementu/problemu
- [] błąd
- [] czat
- [ ] newsletter
- [] otagowany link wewnętrzny
- [x] popup
- [] prawy klik
- [] przycisk
- [] push
- [] pytanie
- [] scrollujący filmik
- [] strzałka
- [] ulepszenie
- [] widżet

**Comment by hawkeye116477** [comment]
`cowsierscipiszczy.pl##.optin-monster-saas-overlay`
U mnie tylko pop-up jest.

**Comment by hawkeye116477** [comment]
Prawdopodobnie `cowsierscipiszczy.pl##.CampaignType--floating`, ale to od F4z, ja nie testowalem, bo u mnie ten pasek się nie pojawia w ogóle.

**Comment by krystian3w** [comment]
Jak dla mnie ten Jowisz to newsletter dlatego zaznaczyłem.

**Comment by hawkeye116477** [comment]
Jowisz? Pop-upy nie liczymy jako newslettery, nawet jeżeli jest w nich newsletter :smile:.
