### ISSUE TITLE
okiemrolnika.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1003]
### Typ elementu/problemu
- [] błąd
- [] czat
- [] newsletter
- [] otagowany link wewnętrzny
- [x] popup
- [] prawy klik
- [] przycisk
- [] push
- [] pytanie
- [] scrollujący filmik
- [] strzałka
- [] ulepszenie
- [] widżet

![opera zdjecie_2018-08-17_035250_www okiemrolnika pl](https://user-images.githubusercontent.com/36385327/44243753-16f21200-a1d1-11e8-9712-cf6b929920eb.png)

**Comment by krystian3w** [comment]
`okiemrolnika.pl##.ls-popup-visible.ls-popup, .ls-popup-overlay` :question:
