### ISSUE TITLE
termyszaflary.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1011]
![opera zdjecie_2018-08-28_124626_www termyszaflary com](https://user-images.githubusercontent.com/36385327/44718580-cd52d280-aac0-11e8-8d31-0fdeb10eb3b1.png)

### Typ elementu/problemu
- [] błąd
- [] czat
- [] newsletter
- [] otagowany link wewnętrzny
- [x] popup
- [] prawy klik
- [] przycisk
- [] push
- [] pytanie
- [] scrollujący filmik
- [] strzałka
- [] ulepszenie
- [] widżet

**Comment by hawkeye116477** [comment]
```
termyszaflary.com##.fancybox-overlay
termyszaflary.com##.fancybox-lock:style(overflow: auto !important; margin-right: 0px !important;)
```
