### ISSUE TITLE
moduł "Widżety Kontaktowe/Informacji Zwrotnej" nie chce się zaktualizować

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters#1012]
### Typ elementu/problemu
- [x] błąd
- [] czat
- [] newsletter
- [] otagowany link wewnętrzny
- [] popup
- [] prawy klik
- [] przycisk
- [] push
- [] pytanie
- [] scrollujący filmik
- [] strzałka
- [] ulepszenie
- [] widżet

### Moja konfiguracja
**Przeglądarka internetowa:** Firefox 62

**System operacyjny:** Android 7

**Bloker:** uBo 1.16.21b7

**Używane filtry:**
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
4. 
5. 

### Link bezpośredni (opcjonalny)

-- | -- | -- | -- | -- | --
-- | -- | -- | -- | -- | --
17:34:23 |   |   |   | xhr | `https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB_uBlock_AdGuard/widgety_kontaktowe_informacji_zwrotnej_uBO.txt?_=213439`
17:34:22 |   |   |   | xhr | `https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_contact_feedback_widgets.txt?_=213439`

### Inne ważne informacje mogące mieć znaczenie (opcjonalne):

ikona, nie chce zniknąć, że plik zaktualizowany i mam dodatkowo ikonę błędu sieciowego.

**Comment by hawkeye116477** [comment]
No faktycznie coś nie halo, tylko ciekawe o co chodzi.
