### ISSUE TITLE
Mobilna strona filtrów

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters#1013]
### Typ elementu/problemu
- [x] błąd
- [ ] czat
- [ ] newsletter
- [ ] otagowany link wewnętrzny
- [ ] popup
- [ ] prawy klik
- [ ] przycisk
- [ ] push
- [ ] pytanie
- [ ] scrollujący filmik
- [ ] strzałka
- [x] ulepszenie
- [ ] widżet

### Moja konfiguracja
**Przeglądarka internetowa:** Firefox 62.0.1

**System operacyjny:** Android 7 

**Bloker:** uBo 1.16.20

**Używane filtry:**
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
4. 
5. 

### Link bezpośredni (opcjonalny)

https://polishannoyancefilters.netlify.com/

### Zrzut ekranu (opcjonalny)

N/A

### Inne ważne informacje mogące mieć znaczenie (opcjonalne):

Coś nie tak jest z przyciskiem subskrypcji filtrów w niebieskim nagłówku, jakby RWD było jakieś "lewe".
W trybie PC normalnie działa.

Jak coś inne linki wykrywa uBo normalnie i proponuje subskrypcje.

Może przeinstaluje Firefox, bo już je resetowałem czyszczeniem danych aplikacji i instalacją stabilnego uBo (dev się wywaliło szybko i przestały działać reguły CSS).

**Comment by krystian3w** [comment]
Jak coś, to bot źle wykrył listę do zaznaczania jak w nawiasach są spacje?

**Comment by hawkeye116477** [comment]
@krystian3w Ok, chyba wiem w czym problem, jak patrzyłem w przykładach jak te warunki się robi, to najwyraźniej usunięcie/zamiana tego mi umknęło => `context.payload.issue.body.includes('- [ ]'))` https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/edit/master/.github/probot.js. Bo tak to jeżeli jest spacja, to daje label „odrzucone". W takim razie, trzeba będzie zamienić tę spację na x i wstawić wykrzyknik przed context, to wtedy powinno być ok :smile:.
A co do strony, to raczej zgłoszenia dot. niej powinny być tutaj => `https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters.netlify.com/issues` :smile:. Tak czy siak, to u mnie jest ok, więc może :fox_face: chytrusek do przeinstalowania. Jakbyś chciał coś poprawić odnośnie strony, to też możesz na tamtym repo śmiało wszystko edytować, ewentualnie w razie wątpliwości dać PR, po zrobieniu PR, boty Netlify generują podgląd zmian jakie zostaną dokonane po  jego zaakceptowaniu. Można też lokalnie bawić się, trzeba tylko mieć Hugo Extended i wklepać do konsoli `hugo serve` i zmienić w config.yaml - use_sass na true, ja dałem na false, dlatego, że obecnie Netlify nie ma rozszerzonej wersji Hugo i w tym celu muszę używać gulpa do konwersji scss na css.

**Comment by krystian3w** [comment]
Po przeinstalowaniu dalej coś nie chula i nawet waterfox beta z uBo 1.16.20 ma problem z linkiem.

Czyli zostaje mi tylko zresetować telefon i potem zgadywanie co się buguje (Firefox 62, uBo 1.16.20, Android) 😰.

**Comment by hawkeye116477** [comment]
@krystian3w A czekasz aż pasek wczytywania zniknie? Bo jak jest pasek, to wtedy nie zadziała. Czasem też zauważyłem, że nawet jak już się do końca wczyta, to i tak nie reaguje i muszę wtedy go zminimalizować albo 2 razy stuknąć w przycisk subskrypcji i dopiero wtedy jest ok, ale na Yandexie zawsze jest ok, więc powiedziałbym, że to bug mobilnego Firefoksa. Możesz spróbować też `wejść w about:config i ustawić network.preload na true`.

**Comment by krystian3w** [comment]
Raczej już są załadowane, bo na przykład ten z dołu do subskrypcji Cookies (podstrona modułów) lub z tabel działają normalnie.

**Comment by hawkeye116477** [comment]
@krystian3w A teraz jest ok czy nadal nie działa?
