### ISSUE TITLE
tvs.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1014]
https://tvs.pl/informacje/jaworzno-karambol-na-trasie-s1-policja-zatrzymala-dwoch-mezczyzn-podejrzanych-o-podpalenie-opon-pod-wiaduktem/
![zrzut ekranu z 2018-09-21 05-41-57](https://user-images.githubusercontent.com/36385327/45859148-16fda880-bd61-11e8-99e4-d85f07429bd8.png)

### Typ elementu/problemu
- [ ] Newsletter (nie popup)
- [ ] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [ ] Powiadomienie push
- [ ] Scrollujący filmik
- [ ] Strzałka
- [ ] Widżet kontaktowy/informacji zwrotnej
- [ ] Wyskakujące okienko (popup)
- [ ] Zablokowane kliknięcie prawym przyciskiem myszy
- [x] Inny element
- [ ] Błąd
- [ ] Pytanie
- [ ] Ulepszenie

**Comment by hawkeye116477** [comment]
@xMaap Widzę, że skopiowałeś stary formularz. A ja trochę pozmieniałem nazewnictwo, by inni lepiej wiedzieli o co kaman i teraz np. **widżet** to I**nny element**, ale to tak tylko w fomularzu, label został ten sam :smile:.
