### ISSUE TITLE
www.pomponik.pl

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters#1015]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [x] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Zablokowane kliknięcie prawym przyciskiem myszy
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

### Moja konfiguracja
**Przeglądarka internetowa:** Firefox 62

**System operacyjny:** Windows 10

**Bloker:** uBo 1.16.20

**Używane filtry:**
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących = w modułach (może jakiś pominąłem)
4.
5.

### Link bezpośredni (opcjonalny)

`https://www.pomponik.pl/plotki/news-milosne-uniesienia-zbigniewa-wodeckiego-wyjda-na-jaw-szykuje,nId,2634138`

### Zrzut ekranu (opcjonalny)

![obraz](https://user-images.githubusercontent.com/35370833/45905141-a5207000-bdef-11e8-9960-44e561aa7573.png)

### Inne ważne informacje mogące mieć znaczenie (opcjonalne):

N/A

**Comment by hawkeye116477** [comment]
Już jest `||webpush.interia.pl/scripts/*/push.js` w filtrach, pominąłeś moduł „powiadomienia"?

**Comment by krystian3w** [comment]
Chyba nie:

![obraz](https://user-images.githubusercontent.com/35370833/45907307-bbcac500-bdf7-11e8-9a2c-520907af2f49.png)

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/45907387-f59bcb80-bdf7-11e8-919c-be0ecd6ab399.png)

**Comment by hawkeye116477** [comment]
Ok, najwyraźniej problem dotyczy tylko :fox_face: .

**Comment by krystian3w** [comment]
Mogę jeszcze spróbować jako jeden plik, może wtedy nie ma buga.

**Comment by hawkeye116477** [comment]
Wydaje mi się, że raczej to nie bug, po prostu dla FF mają inny skrypt.
