### ISSUE TITLE
www.sellizer.pl

### ISSUE THREAD

**Issue by dswinicki** [PolishFiltersTeam/PolishAnnoyanceFilters#1018]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Zablokowane kliknięcie prawym przyciskiem myszy
- [] Inny element
- [x] Błąd
- [] Pytanie
- [] Ulepszenie

### Moja konfiguracja
**Przeglądarka internetowa:**
Chrome Wersja 69.0.3497.100 (Oficjalna wersja) (64-bitowa)

**System operacyjny:**
Windows 10

**Bloker:**

**Używane filtry:**

1. uBlock filters
2. uBlock filters – Badware risks
3. uBlock filters – Privacy​​​​​
4. uBlock filters – Resource abuse​
5. uBlock filters – Unbreak​​​​​
6. EasyList​​​​​
7. EasyPrivacy​
8. Malware Domain List
9. Malware domains​​​​
10. Peter Lowe’s Ad and tracking server list
11. POL: polskie filtry do Adblocka i uBlocka​
12. AlleBlock​​​​​
13. KAD - Przekręty​​​​​
14. NoCoin Filter List​​​​​
15. Polish Privacy Filters​​​​​
**16. Polskie Filtry Elementów Irytujących <--- Strona nie wyświetla się gdy jest aktywny**
**17. Polskie Filtry RODO-Ciasteczkowe​​​​​​​​​ <--- Strona nie wyświetla się gdy jest aktywny**
18. Polskie Filtry RSS​​​​​
19. Polskie Filtry Społecznościowe​​​​​

### Link bezpośredni (opcjonalny)
http://www.sellizer.pl

### Zrzut ekranu (opcjonalny)
![slr-scr](https://user-images.githubusercontent.com/43745201/46283250-2e643f00-c574-11e8-839d-81998f392f56.png)

### Inne ważne informacje mogące mieć znaczenie (opcjonalne):
Strona de facto wczytuje się jednak w momencie ładowania widgetu intercom nie wyświetla się.

**Comment by krystian3w** [comment]
Od wersji `201810011255` powinno być ok, spróbuj zaktualizować ręcznie listę elementów irytujących do wersji `201810011257`.

**Comment by hawkeye116477** [comment]
Generalnie Lista EI zawiera już Ciasteczkowe, więc nie musisz zgłaszać w oba miejsca, ale ok, tak jak mówi @krystian3w poprawione, a do @MajkiIT zaraz trafi jak wrzucę PR :smile:..
@krystian3w `do Listy Elementów Irytujących nie ładuje się uzupełnienie filtrów ciasteczkowych dla uBlock Origin.
Sam update nie wskoczy, trzeba ręcznie odpalić skrypt. Przynajmniej na razie tak jest, może kiedyś dorobimy tak, by po updatcie ciasteczkowych, od razu updatowała się lista EI.

**Comment by dswinicki** [comment]
@hawkeye116477 dzięki za info. Na przyszłość będę wiedział.

**Comment by krystian3w** [comment]
Obawiałbym się chyba wtedy, że nagle coś komuś wytnie i za dwa dni dopiero się scroll odblokuje - tak to jest, jak edytuje pliki pojedynczo...
