### ISSUE TITLE
dziennikwschodni.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1023]
![opera zdjecie_2018-10-19_125118_www dziennikwschodni pl](https://user-images.githubusercontent.com/36385327/47214340-e3cd2a00-d39d-11e8-9e58-e8d549154dd9.png)

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Zablokowane kliknięcie prawym przyciskiem myszy
- [x] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by hawkeye116477** [comment]
Dziwne, ja tego nie mam, za to wyskakuje elegancki komunikat o Adblocku :smile:.

**Comment by xMaap** [comment]
Nie mam pojęcia co się stało, ale teraz tego nie mam i również pojawia się komunikat o adblocku.

**Comment by gzenio22** [comment]
Też mam tylko monit o adblocku
