### ISSUE TITLE
esportmania.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1024]
https://esportmania.pl/misja-esport/misja-esport-snax-na-lawce-w-mousesports-worlds-2018-team-kinguin-ultraliga-izako/67schb8
![opera zdjecie_2018-10-19_125444_esportmania pl](https://user-images.githubusercontent.com/36385327/47214430-360e4b00-d39e-11e8-890e-2a62831fae27.png)
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Zablokowane kliknięcie prawym przyciskiem myszy
- [x] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by hawkeye116477** [comment]
`esportmania.pl###nitro-block`
