### ISSUE TITLE
generacjasmart.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1025]
![opera zdjecie_2018-10-19_125617_generacjasmart pl](https://user-images.githubusercontent.com/36385327/47219666-b7220e00-d3af-11e8-9456-c42222568e16.png)

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Zablokowane kliknięcie prawym przyciskiem myszy
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by hawkeye116477** [comment]
`generacjasmart.pl##.mcwidget-overlay`
