### ISSUE TITLE
subiektywnieofinansach.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1026]
https://subiektywnieofinansach.pl/taksowkarze-protest-uber-taxify-swiat-sie-zmienia/
![opera zdjecie_2018-10-19_141700_subiektywnieofinansach pl](https://user-images.githubusercontent.com/36385327/47217794-d9189200-d3a9-11e8-9bad-1261f75f7952.png)

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Zablokowane kliknięcie prawym przyciskiem myszy
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by hawkeye116477** [comment]
`subiektywnieofinansach.pl###similar-overlay-wrapper`
