### ISSUE TITLE
zblogowani.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1028]
Strony się nie ładują

https://zblogowani.pl/wpis/37334678/venom-2018-nie-taki-symbiant-straszny-jak-go-maluja
https://zblogowani.pl/wpis/37334487/nalesniki-zapiekane-z-szynka-i-serem
https://zblogowani.pl/wpis/37334488/ostatnia-sagra-w-domowych-pieleszach
http://zblogowani.pl/wpis/37334080/co-sadzicie-o-halloween

Włączony
![opera zdjecie_2018-10-29_071428_zblogowani pl](https://user-images.githubusercontent.com/36385327/47632434-5aaab580-db4a-11e8-80dd-788889b4bf5c.png)
Wyłączony
![opera zdjecie_2018-10-29_071442_zblogowani pl](https://user-images.githubusercontent.com/36385327/47632442-64341d80-db4a-11e8-9f62-deb7e37c682b.png)

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Zablokowane kliknięcie prawym przyciskiem myszy
- [] Inny element
- [x] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by hawkeye116477** [comment]
`zblogowani.pl#@##ouibounce-modal`
