### ISSUE TITLE
kawro.pl

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishAnnoyanceFilters#1031]
Co robimy z tym paskiem na dole ? Ja na początku chciałem to usunąć lecz @hawkeye116477 twierdzi że to ważne info dlatego teraz proponuje to unieruchomić na dole strony co o tym sądzicie, prosze o opinie @krystian3w 

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Zablokowane kliknięcie prawym przyciskiem myszy
- [] Inny element
- [] Błąd
- [x] Pytanie
- [] Ulepszenie

**Comment by hawkeye116477** [comment]
@krystian3w 
Może
```
kawro.pl##.infobar-bar:style(position: static !important; clear: both;)
kawro.pl##.infobar-dismiss:style(position: relative !important; bottom: 70px !important; right: 0 !important;)
```

**Comment by krystian3w** [comment]
X uciekł ale lepsze.
