### ISSUE TITLE
naszemiasto.pl

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishAnnoyanceFilters#1032]
http://kwidzyn.naszemiasto.pl/artykul/planeta-singli-powraca-na-ekrany-10-listopada-film,4863596,artgal,t,id,tm.html

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [x] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/1ae058f60485feaa42fa78400fe60aca8e54c4a4/PPB/scroll_film.txt#L2

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/1ae058f60485feaa42fa78400fe60aca8e54c4a4

**Comment by krystian3w** [comment]
Jak nie starcza to trzeba coś lepszego.

**Comment by krystian3w** [comment]
Chyba przydałaby się reguła skryptowa, bo tak to niby można je wyciąć, ale leci w tle i jedynie tylko jak jest się pod umieszczonym to wycięcie coś daje i się stopuje.

**Comment by hawkeye116477** [comment]
Zamiast kosmetycznych można dać 
`||s-nsk.ppstatic.pl/assets/nsk/v1.6.2/js/compiled/atoms/article/sticky-video.js`. Jedynie nadal jest problem z tym, że samo w trakcie przesuwania zaczyna się odpalać mimo, że ktoś zatrzymał.

**Comment by gwarser** [comment]
Może: `naszemiasto.pl##+js(addEventListener-defuser.js, scroll, xlinkEvent)`

To siedzi w `https://prodxnews1blob.blob.core.windows.net/cdn/js/xlink-i.js`

**Comment by hawkeye116477** [comment]
@gwarser Dziękujemy, działa świetnie :smile:.

**Comment by krystian3w** [comment]
A blokowanie skryptu out czy częściowe pocieszenie dla osób bez uBlock Origin?

**Comment by hawkeye116477** [comment]
@krystian3w Skrypt też musi być blokowany, bo inaczej filmik nadal będzie się scrollował, wstrzyknięcie js jedynie zatrzymuje samoczynne odtwarzanie w trakcie scrollowania.
