### ISSUE TITLE
bankier.pl

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters#1036]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [x] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

### Moja konfiguracja
**Przeglądarka internetowa:** Opera 56

**System operacyjny:** Windows 7

**Bloker:** uBO 1.17.0

**Używane filtry:**
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
4.
5.

### Link bezpośredni (opcjonalny)

`https://www.bankier.pl/`

### Zrzut ekranu (opcjonalny)

![image](https://user-images.githubusercontent.com/35370833/48191599-d0323500-e345-11e8-90b9-5878118ec2ab.png) |
--- |

### Inne ważne informacje mogące mieć znaczenie (opcjonalne):

możliwe, że coś popsułem w uBO.

**Comment by hawkeye116477** [comment]
@krystian3w Wystarczy tylko `bankier.pl##.miniplayer` :stuck_out_tongue:
