### ISSUE TITLE
insert.com.pl

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishAnnoyanceFilters#1038]
Push

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [x] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by hawkeye116477** [comment]
Już ogarnąłem to 22 minuty temu => `https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/1684a28eca7b48d70701b7bc77cef751d9f0ebab` :stuck_out_tongue:
