### ISSUE TITLE
pirbinstytut.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1043]
### Typ elementu/problemu
- [x] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Mam taki w pop-up:

> ![image](https://user-images.githubusercontent.com/35370833/48470501-e7639d80-e7f1-11e8-85ff-85ae741f8b1e.png) |
> --- |
>
