### ISSUE TITLE
Zabezpieczenie zgłoszeń PolishJarvis

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters#1046]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [x] Pytanie
- [] Ulepszenie

### Moja konfiguracja
**Przeglądarka internetowa:** Opera 56

**System operacyjny:** Windows 7

**Bloker:** uBO 1.17.0

**Używane filtry:**
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
4.
5.

### Link bezpośredni (opcjonalny)

`https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/new`

### Inne ważne informacje mogące mieć znaczenie (opcjonalne):

Niby ktoś zgłasza boty i potem są timeout-owane, a to może spowodować wyparowanie anonimowych zgłoszeń.

**Comment by hawkeye116477** [comment]
@krystian3w Jak z GH znikną, to zawsze jeszcze są u wujka Google. Bo najpierw to trafia do Google Forms, gdzie jest podpięty skrypt, który wysyła to do GitHuba.
