### ISSUE TITLE
polki.pl

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishAnnoyanceFilters#1049]
Skrollujący filmik w artykułach, np tu : https://polki.pl/moda-i-uroda/perfumy-i-kosmetyki,black-friday-2018-jakie-promocje-szykuje-sephora,10430014,artykul.html

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [x] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
```
polki.pl##.ediplayer-skin-polki.ediplayer.ediplayer-ui-floating:not(.ediplayer-ui-fullscreen) .ediplayer-container:style(position: static !important; width: 100%)
```

I tu też raczej nie da się by zadziałało w AdBlock / Ablock Plus (przynajmniej na moją cierpliwość/wytrwałość).

Potem eksperymentalnie wrzucę CSS i się podmieni na wstrzykiwanie skryptów lub sieciowe blokowanie zasobu jak jest to takie `ez` / `izi`.
