### ISSUE TITLE
gotujmy.pl

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishAnnoyanceFilters#1050]
Skrollujący filmik w artykułach, np tu : https://gotujmy.pl/jak-suszyc-orzechy-wloskie,artykuly-kulinarne-abc-artykul,20064.html

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [x] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Nie chce mi się przeglądać skryptu, nie można go ubić to mam CSS:

```
gotujmy.pl##.ediplayer-skin-gotujmy.ediplayer.ediplayer-ui-floating:not(.ediplayer-ui-fullscreen) .ediplayer-container:style(position: static !important; width: 100%)
```

**Comment by blocker999** [comment]
Może @hawkeye116477 pomoże ?

**Comment by krystian3w** [comment]
CSS wrzucony, a @hawkeye116477 może namierzy nowe zmienne / wartości:

`gotujmy.pl,mamotoja.pl,party.pl,polki.pl,viva.pl,wizaz.pl##script:inject(addEventListener-defuser.js, scroll, d.stopPropagation)`

Skoro kiedyś działało.

**Comment by hawkeye116477** [comment]
@krystian3w Działa nadal, jak zatrzymasz, to już nie będzie scrollować, trochę lipa, ale @F4z nic lepszego nie wymyślił.

**Comment by krystian3w** [comment]
Jedno dobre, że CSS, nie psuje za bardzo strony (przynajmniej ja nie widzę błędów po dodaniu CSS-a u usuwaniu szarej luki robionej odstępami CSS), z pomponikiem i Interią już się tak nie da zrobić by strona nie skakała lub coś migało w rogu.
