### ISSUE TITLE
film.interia.pl

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishAnnoyanceFilters#1051]
Skrollujący filmik w artykułach, np tu : https://film.interia.pl/telewizja/news-dorota-gardias-lubie-to-co-robie,nId,2684606

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [x] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
`##.vjs-fixedmonitor-fixed.vjs-fixedmonitor-wrapper-fixed:not(.vjs-fixedmonitor-fixed-slide-down)`

Ale ma to wadę, że miga przy przewijaniu i już nie mówiąc, że pewnie będzie odtwarzać się dalej.
