### ISSUE TITLE
finanse.wp.pl

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishAnnoyanceFilters#1053]
Skrollujący filmik w artykułach, np tu : https://finanse.wp.pl/leszek-czarnecki-chroni-swoja-prywatnosc-mieszka-w-miami-6318930932107393a

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [x] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Mnie tam coś wycina wideo i komentarze.

**Comment by xMaap** [comment]
@krystian3w ponownie 

https://finanse.wp.pl/leszek-czarnecki-chroni-swoja-prywatnosc-mieszka-w-miami-6318930932107393a
![opera zdjecie_2018-12-01_100958_finanse wp pl](https://user-images.githubusercontent.com/36385327/49326350-48f56d00-f551-11e8-9852-1e9ef88d345e.png)

**Comment by krystian3w** [comment]
Bot drugi raz nie zamyka?

**Comment by krystian3w** [comment]
`finanse.wp.pl###Player0.floating:style(visibility: hidden;)`

Nic lepszego nie wymyślę.

**Comment by krystian3w** [comment]
Reguła działa z Nano Adblockerem.

Nie wiem co na nią uBlock Origin, bo Nano nie zdzierży `!imporant;` w CSS.

---

@hawkeye116477  ja bym na taką okoliczność wolałbym jakieś wykrywanie braku userCSS.
