### ISSUE TITLE
mamotoja.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1055]
https://mamotoja.pl/ukladanie-puzzli-pomaga-w-nauce-czytania-i-pisania-dlaczego,gry-i-zabawy-przedszkolak-artykul,26375,r1.html
![opera zdjecie_2018-11-27_150731_mamotoja pl](https://user-images.githubusercontent.com/36385327/49087067-527f8c00-f256-11e8-9494-431644b4f94b.png)

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [x] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
```
mamotoja.pl##.ediplayer-ui-floating > .ediplayer-main > .ediplayer-aspect-container > .ediplayer-aspect-padding
mamotoja.pl##.ediplayer-ui-floating:not(.ediplayer-ui-fullscreen) .ediplayer-container:style(position: static !important; width: 100% !important;)
```

stop trzeba by zewnętrznym dodatkiem i ja raczej lepszego czegoś nie wymyślę.
