### ISSUE TITLE
Padłe domeny i literówki - do wyjaśnienia

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/PolishAnnoyanceFilters#1058]
Ja odnośnie tego ...

```
Host cardsplitter.pl.sklepmaniek.pl not found: 3(NXDOMAIN) UNKNOWN
Host pomyslnawszystko.pl not found: 3(NXDOMAIN) UNKNOWN
Host tuelblag.pl not found: 3(NXDOMAIN) UNKNOWN
```

ad1 chyba przecinek miał być

https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/dead-domains/ppb_dead.txt

**Comment by krystian3w** [comment]
Najpewniej tak, no każdemu się może zdarzyć :wink:

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/2709bfb48e698adaa20e9953c3e610071e325263

**Comment by MajkiIT** [comment]
@krystian3w No wiem. Nie wytykam tylko daje znać i tyle. :D
