### ISSUE TITLE
plotek.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1059]
![opera zdjecie_2018-12-01_095556_www plotek pl](https://user-images.githubusercontent.com/36385327/49326228-514ca880-f54f-11e8-944e-2ae87123dfb0.png)

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [x] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
`##.closer.miniplayer.desktop.alwplayer.checkvisc`
