### ISSUE TITLE
wiadomosci.gazeta.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1060]
![opera zdjecie_2018-12-01_095838_wiadomosci gazeta pl](https://user-images.githubusercontent.com/36385327/49326247-b1dbe580-f54f-11e8-9b7d-b863e04031f9.png)

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [x] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
`##.miniplayer.desktop.alwplayer.checkvisc`
