### ISSUE TITLE
groomer.com.pl

### ISSUE THREAD

**Issue by gargaamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1080]
popup (newsletter/subskrybcja/zapisz się itp.)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.)

![ss_012](https://user-images.githubusercontent.com/44813765/49891477-e51f4e00-fe46-11e8-944b-0f2f692b74e1.png)

### Typ elementu/problemu
* [] Newsletter (nie popup)
* [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
* [] Powiadomienie push
* [] Scrollujący filmik
* [] Strzałka
* [] Widżet kontaktowy/informacji zwrotnej
* [x]  Wyskakujące okienko (popup)
* [] Inny element
* [] Błąd
* [] Pytanie
* [] Ulepszenie

**Comment by blocker999** [comment]
@gargaamel OK zgłaszaj co chcesz a że ja przy okazji usuwam inne elementy lub zgłaszam Majkiemu to nic chyba złego

**Comment by gargaamel** [comment]
Cześć @blocker999 , co słychać, jasne nie ma sprawy, róbta co chceta, mi nic nie przeszkadza, ja tłukę narazie tylko te newslettery bo nie idzie już z nimi wytrzymać, w zasadzie to ten sam badziew co ciasteczka/rodo, zalany tym jest cały internet.

**Comment by krystian3w** [comment]
do zrobienia
