### ISSUE TITLE
sklep.apet.pl

### ISSUE THREAD

**Issue by gargaamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1087]
popup (newsletter/subskrybcja/zapisz się itp.)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.)

![ss_020](https://user-images.githubusercontent.com/44813765/49892913-7512c700-fe4a-11e8-8aa3-f41734e56c6e.png)

### Typ elementu/problemu
* [] Newsletter (nie popup)
* [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
* [] Powiadomienie push
* [] Scrollujący filmik
* [] Strzałka
* [] Widżet kontaktowy/informacji zwrotnej
* [x]  Wyskakujące okienko (popup)
* [] Inny element
* [] Błąd
* [] Pytanie
* [] Ulepszenie

**Comment by krystian3w** [comment]
`##.wf2-popover.grwf2-wrapper, .grwf2_backdrop`
