### ISSUE TITLE
optes.pl

### ISSUE THREAD

**Issue by gargaamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1091]
popup (newsletter/subskrybcja/zapisz się itp.)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.)

![ss_024](https://user-images.githubusercontent.com/44813765/49893400-94f6ba80-fe4b-11e8-9498-5b64afa559b9.png)

### Typ elementu/problemu
* [] Newsletter (nie popup)
* [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
* [] Powiadomienie push
* [] Scrollujący filmik
* [] Strzałka
* [] Widżet kontaktowy/informacji zwrotnej
* [x]  Wyskakujące okienko (popup)
* [] Inny element
* [] Błąd
* [] Pytanie
* [] Ulepszenie

**Comment by krystian3w** [comment]
`###ctk_np_popup, .reveal-modal-bg`

**Comment by krystian3w** [comment]
`||optes.pl/sw.js$script,first-party`

**Comment by krystian3w** [comment]
`optes.pl##.top_button`

**Comment by gargaamel** [comment]
> 
> krystian3w :
> `||optes.pl/sw.js$script,first-party`

Tylko się tak zapytam, a nie `~third-party` ? (bo tylko ono jest kompatybilne z ABP).

**Comment by krystian3w** [comment]
I tak wklejam do gotowca, tak piszę, by inni mieli pogląd co blokuje i uBO nie pozwala wyłączyć mi first party bez dodatkowych kliknięć.

**Comment by krystian3w** [comment]
gotowe
