### ISSUE TITLE
decoliving.pl

### ISSUE THREAD

**Issue by gargaamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1093]
popup (newsletter/subskrybcja/zapisz się itp.) nie jestem pewien - możliwe, że to push

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.)

![ss_026](https://user-images.githubusercontent.com/44813765/49893585-19e1d400-fe4c-11e8-88db-df6f74ee0cb9.png)

### Typ elementu/problemu
* [] Newsletter (nie popup)
* [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
* [] Powiadomienie push
* [] Scrollujący filmik
* [] Strzałka
* [] Widżet kontaktowy/informacji zwrotnej
* [x]  Wyskakujące okienko (popup)
* [] Inny element
* [] Błąd
* [] Pytanie
* [] Ulepszenie

**Comment by krystian3w** [comment]
Prawie na pewno, ale pewnie da się go poprawić.

Pewnie będzie trzeba jak będzie głupiał przy 1 z 3 nagłówków.

**Comment by gargaamel** [comment]
No ja nie byłbym pewien czy to przez to, bo na wzór brałem to takie samo zgłoszenie jak moje, w którym bot etykietował: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1059

**Comment by krystian3w** [comment]
No to połowicznie się wywalił.

**Comment by krystian3w** [comment]
I jakby co duże "push" mają iść do pop-up-ów. Tego się dowiedziałem kiedyś przy omawianiu jednej strony.

**Comment by gargaamel** [comment]
Hmm może to przez gwiazki w moim formularzu, bo na początku przy pierwszym zgłoszeniu coś wcięło mi w pierwszym komentarzu formularz i wziąłem quote reply do tego komentarza https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1059#issue-386439390 i skopiowałem, tylko, że quote reply zamienia minusy `-` na gwiazdki `*`
<details not-open>
<summary>co mam w swoich komentarzach:</summary>

```
### Typ elementu/problemu
* [] Newsletter (nie popup)
* [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
* [] Powiadomienie push
* [] Scrollujący filmik
* [] Strzałka
* [] Widżet kontaktowy/informacji zwrotnej
* [x]  Wyskakujące okienko (popup)
* [] Inny element
* [] Błąd
* [] Pytanie
* [] Ulepszenie
```

</details>
<br>
<details not-open>
<summary>a co ma domyślny formularz</summary>

```
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie
```

</details>
<br>

zaraz zamienię formularz na minusy i zobaczymy, czy bot zaskoczy.

**Comment by krystian3w** [comment]
`decoliving.pl###pop-up-newsletter`

**Comment by krystian3w** [comment]
`##div.zwin.col-sm-3.footer-links.footer-widget:nth-of-type(3)`

**Comment by krystian3w** [comment]
powycinane wszystkie 3
