### ISSUE TITLE
recea.pl

### ISSUE THREAD

**Issue by gargaamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1096]
### Typ elementu/problemu
* [] Newsletter (nie popup)
* [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
* [] Powiadomienie push
* [] Scrollujący filmik
* [] Strzałka
* [] Widżet kontaktowy/informacji zwrotnej
* [x]  Wyskakujące okienko (popup)
* [] Inny element
* [] Błąd
* [] Pytanie
* [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się itp.)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.)

![ss_028](https://user-images.githubusercontent.com/44813765/49893985-0f740a00-fe4d-11e8-96f3-d2722dae1e2d.png)

**Comment by krystian3w** [comment]
O to chyba jednak grubsza sprawa z tym botem, anonimowe ogarnia.

**Comment by krystian3w** [comment]
Mnie nie wyskakuje, jakiś brak w modułach lub w złym module?

**Comment by krystian3w** [comment]
`||cloudfront.net/edrone_2_0.js`
