### ISSUE TITLE
hairbyjul.pl

### ISSUE THREAD

**Issue by gargaamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1097]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się itp.)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.)

![ss_029](https://user-images.githubusercontent.com/44813765/49895020-b22d8800-fe4f-11e8-927a-04cf13b2e169.png)

**Comment by krystian3w** [comment]
scroll...

**Comment by krystian3w** [comment]
`##.popmake-overlay`

**Comment by krystian3w** [comment]
wycięty i odblokowany scroll
