### ISSUE TITLE
miaucafe.pl

### ISSUE THREAD

**Issue by gargaamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1104]
### Typ elementu/problemu
- [x] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [ ] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

widżet (newsletter/subskrybcja/zapisz się itp.)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.)

![ss_037](https://user-images.githubusercontent.com/44813765/49896905-f66f5700-fe54-11e8-9431-27c6a50666a4.png)

**Comment by krystian3w** [comment]
kontaktowy to np. chat lub zgłoś sugestię itd.

**Comment by krystian3w** [comment]
`miaucafe.pl##.et_bloom_animated.et_bloom_flyin_right.et_bloom_flyin`

**Comment by gargaamel** [comment]
Acha, bo wydawało mi się , że w https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1082 to `widżet` dałeś dla newslettera, a jednak to ta druga etykieta `newsletter`, , czyli osadzony statycznie newsletter i w postaci okienka w rogu to ta sama etykieta `newsletter`.
