### ISSUE TITLE
bot test after breaking

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters#1107]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [x] Błąd
- [] Pytanie
- [] Ulepszenie

### Moja konfiguracja
**Przeglądarka internetowa:** Testowa

**System operacyjny:**

**Bloker:**

**Używane filtry:**
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
4.
5.

**Comment by krystian3w** [comment]
sam dodał?

**Comment by hawkeye116477** [comment]
@krystian3w Nie, to ja mu pomogłem. Ale po samej edycji chyba już nie dodaje drugi raz. Ale wywalił mi jakiś error:
```
18:46:41.090Z  INFO probot: Webhook received

  event: {

    "id": "3d66a5f0-111a-11e9-9e13-2034f35b6978",

    "event": "issues.edited",

    "repository": "PolishFiltersTeam/PolishAnnoyanceFilters",

    "installation": 129513

  }

18:46:41.093Z  INFO http: POST / 200 - 3.27 ms (id=c05192c2ea2f8a84)

18:46:41.166Z ERROR event:  (id=3d66a5f0-111a-11e9-9e13-2034f35b6978, err=issues.labeled)

  event: {

    "id": "3d66a5f0-111a-11e9-9e13-2034f35b6978",

    "event": "issues.edited",

    "repository": "PolishFiltersTeam/PolishAnnoyanceFilters",

    "installation": 129513

  }
```

**Comment by krystian3w** [comment]
Ale nie mieli w kółko wszystkich, już kij że kiedyś dodawał i na mobilnym było z 10 etykiet jak było 10 edycji, to raczej znów zabawa dla twórców bota.

**Comment by hawkeye116477** [comment]
@krystian3w Nie mieli.
No ciekawe tylko czy by się odezwali, pisałem, że projekty nie działają `https://github.com/bkeepers/workflow/issues/21` i odezwał się tylko jakiś kolega twórcy z pytaniem, którą wersję Node używam, ja odpowiedziałem oczywiście i nic, 0 odpowiedzi od 7 maja 2018. A ten twórca, to chyba jakaś wielka szycha, bo napisane ma GitHub Staff, widać czasu nie ma by zajmować się swoim dziełem.
