### ISSUE TITLE
e-forma.pl

### ISSUE THREAD

**Issue by garrgamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1128]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się itp.)

![ss_063](https://user-images.githubusercontent.com/45873234/50017712-322d2c80-ffcd-11e8-89bc-62f0d0dce9b9.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 2 modułów:
- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 2 modułach.

**Comment by hawkeye116477** [comment]
Tutaj problem jest taki, że jak schowam ten popup, to przy okazji zepsuje się podgląd zdjęć w popupie, np tutaj => `https://www.e-forma.pl/3574,muscle-care-pro-bcaa-350g-aminokwasy.html`, nawet jak dam -abp-has, to nadal coś się blokuje.
Jedynie reguła dla FF działa poprawnie => `e-forma.pl##^#newsletter_colorbox`.

**Comment by krystian3w** [comment]
Niby udałoby się to naprawić w uBO dev 1.17.5b8:

https://github.com/uBlockOrigin/uBlock-issues/issues/341

Zobacz czy to coś pomoże dla Chromowatych i AdGuard.

**Comment by krystian3w** [comment]
Możliwe, że tu jest zupełnie inaczej i nie błąd w nadmiarowym ukrywaniu elementu.

**Comment by hawkeye116477** [comment]
Już tam te tło to nie aż takie ważne, ale potwierdzam w dev jest ok, a więc dodamy dopiero jak będzie nowa wersja stabilna :smile:

**Comment by krystian3w** [comment]
No to już prędzej bo mniej proceduralne a bardziej CSS 2.1/3/4.

**Comment by hawkeye116477** [comment]
@krystian3w No nie wiem czy same tło jest sens im usuwać, bo ta reguła na blokowanie popupa niestety nie zadziała poprawnie dla AB i ABP :smile:.

**Comment by krystian3w** [comment]
Może irytować, takie paskowate i czemu ABP miało by jej nie lubić.

**Comment by hawkeye116477** [comment]
@krystian3w ABP nie lubi reguły chowającej popupa, bo jest tak samo jak w uBO stable, ten sam bug czy jak to nazwać.

**Comment by krystian3w** [comment]
Czyli dalej problem, że tylko dla uBO beta i AdGuard latest rozwiązanie?

**Comment by hawkeye116477** [comment]
@krystian3w Zgadza się, a tak w ogóle to fajnie by było jak była możliwość użycia jakiejś szybszej reguły, bo ta trochę wolno ukrywa, ale zdaje się, że chyba tylko dla FF jest taka możliwość.

**Comment by krystian3w** [comment]
Chyba tylko skryptowa wymierzona w  newsletter.

**Comment by hawkeye116477** [comment]
@krystian3w Ale właśnie ta skryptowa w tym przypadku chyba nie za bardzo wypali. Jakbyśmy mogli upiec :cookie: , to wtedy inna sprawa :smile:.

**Comment by krystian3w** [comment]
Fajna opcja, jak chcesz ją używać i zachęcać to możesz dodać gdzieś taki filtr, tyle że na "wiki" by trzeba dodać artykuł i napisać na jaką wersje Nano Adblockera jest to planowane.

**Comment by krystian3w** [comment]
No to na razie problem rozwiązany z wydaniem i popularyzacją uBO 1.17.6 lub 1.18.0 jakby takie miało nowy numer stabilny.

Nie wiem jak zgłosić bug `ABP/AdBlock does not unhide nodes no longer matching procedural cosmetic filters` do ich twróców...

**Comment by krystian3w** [comment]
No to na razie problem rozwiązany z wydaniem i popularyzacją uBO 1.17.6 lub 1.18.0 jakby takie miało nowy numer stabilny (chromowate).

Firefox ma html filtering, a `###colorbox:not(:has(.cboxPhoto))` u mnie działa szybko, może `i5 3XXX` dużo lepsze od `AMD amd athlon 64 x2 5200+`.

Minus wycina wszystko co nie jest galerią, może kolejne not pomogą, ale też pewnie mocno spowolnią o ile będą uznawane za poprawną regułę.

Nie wiem jak zgłosić bug `ABP/AdBlock does not unhide nodes no longer matching procedural cosmetic filters` do ich twróców...

**Comment by hawkeye116477** [comment]
@krystian3w Ja mam AMD Athlon II X4 620. No to skoro nie działa jak należy, to wywalamy z listy i czekamy, aż pojawi się uBO Stable 1.17.6. Jak to zgłosić, po prostu chyba, że ten -abp-has w tym przypadku nie chce działać, a powinien :smile:

**Comment by krystian3w** [comment]
Czekanie nie wystarczy, popularność wydania też musi być.

**Comment by krystian3w** [comment]
https://adblockplus.org/forum/viewtopic.php?f=4&t=60999

Mam nadzieje, że zrozumieją i pomogą lub przekażą dalej.

**Comment by krystian3w** [comment]
> aż pojawi się uBO Stable 1.17.6

Czekanie nie wystarczy, popularność wydania też musi być.

`:not(:has(...))` dla starych uBO jest nieczytelne i ignorowane.

**Comment by krystian3w** [comment]
> No to skoro nie działa jak należy, to wywalamy z listy i czekamy

Wycina każdy pop-up co nie jest grafiką galerii (nie ma newslettera, galeria jest, inne pop-up-y niesety znikną np. jak zakładkę kontakt wpychają do pop-up-a).

a ABP / AdBlock i tak dużo wolniej by wycinały pomijają, że są też narażone na ten bug z galerią.

**Comment by krystian3w** [comment]
> aż pojawi się uBO Stable 1.17.6

Czekanie nie wystarczy, popularność wydania też musi być.

`:not(:has(...))` dla starych uBO jest nieczytelne i ignorowane.

**Comment by krystian3w** [comment]
> Jak to zgłosić, po prostu chyba, że ten -abp-has w tym przypadku nie chce działać, a powinien smile

https://adblockplus.org/forum/viewtopic.php?f=4&t=60999
https://help.getadblock.com/support/tickets/59223

Mam nadzieje, że zrozumieją i pomogą lub przekażą dalej.

Jedynie w tickecie `getadblock` zły dałem tytuł używając określenia `procedural cosmetic filters` zamiast skrócić do `:-abp-has(...)` jak na `adblockplus.org`.

I tu pomijam błąd z zgłoszeniem do złego działu i źle odpowiadając na pytania pomocnicze.

**Comment by krystian3w** [comment]
> No to skoro nie działa jak należy, to wywalamy z listy i czekamy

Wycina każdy pop-up co nie jest grafiką galerii (nie ma newslettera, galeria jest, inne pop-up-y niestety znikną np. jak zakładkę kontakt wpychają do pop-up-a).

a ABP / AdBlock i tak dużo wolniej by wycinały pomijając, że są też narażone na ten bug z galerią.

**Comment by krystian3w** [comment]
> aż pojawi się uBO Stable 1.17.6

Czekanie nie wystarczy, popularność wydania też musi być.

`:not(:has(...))` dla starych uBO jest nieczytelne i ignorowane.

**Comment by krystian3w** [comment]
> Jak to zgłosić, po prostu chyba, że ten -abp-has w tym przypadku nie chce działać, a powinien smile

https://adblockplus.org/forum/viewtopic.php?f=4&t=60999
https://help.getadblock.com/support/tickets/59223

Mam nadzieje, że zrozumieją i pomogą lub przekażą dalej.

Jedynie w tickecie `getadblock` zły dałem tytuł używając określenia `procedural cosmetic filters` zamiast skrócić do `:-abp-has(...)` jak na `adblockplus.org`.

I tu pomijam błąd z zgłoszeniem do złego działu i źle odpowiadając na pytania pomocnicze.

**Comment by krystian3w** [comment]
```

e-forma.pl,homeoapteka.pl###cboxOverlay:not([style="opacity: 0.9; visibility: visible; display: block; cursor: pointer;"])
e-forma.pl,homeoapteka.pl###cboxOverlay:not([style="opacity: 0.9; visibility: visible; display: block; cursor: pointer;"]) ~ #colorbox
```

i w ogóle odkryłem że AdBlock Beta Fish nie kuma:

`e-forma.pl,homeoapteka.pl#?##colorbox:-abp-has(#newsletter_colorbox)`

a takie coś już śmiało:

`e-forma.pl,homeoapteka.pl#?#div#colorbox:-abp-has(#newsletter_colorbox)`

**Comment by krystian3w** [comment]
Obejście kompatybilne z AdBlock / Adblock Plus ale dalej wycina wszystkie pop-up-y gdzie tło jest inne niż dla galerii i dalej wolne w tych dwóch (nie sprawdzałem w uBO / AdGuard):

```

e-forma.pl,homeoapteka.pl###cboxOverlay:not([style="opacity: 0.9; visibility: visible; display: block; cursor: pointer;"])
e-forma.pl,homeoapteka.pl###cboxOverlay:not([style="opacity: 0.9; visibility: visible; display: block; cursor: pointer;"]) ~ #colorbox
```

**Comment by krystian3w** [comment]
i w ogóle odkryłem że AdBlock Beta Fish nie kuma:

`e-forma.pl,homeoapteka.pl#?##colorbox:-abp-has(#newsletter_colorbox)`

a takie coś już śmiało:

`e-forma.pl,homeoapteka.pl#?#div#colorbox:-abp-has(#newsletter_colorbox)`

**Comment by hawkeye116477** [comment]
@krystian3w Te specyficzne obejście to coś u mnie niestety nie działa poprawnie.

**Comment by krystian3w** [comment]
No zauważyłem, musi się nie dogadywać z html filteringiem i z tym... zakaceptowanie go w przeszłości.

**Comment by krystian3w** [comment]
Jak coś już zakomentowuje i powinno się zaktualizować do 3 min i trudno że komuś wytnie na okres 1-2 dni...

**Comment by hawkeye116477** [comment]
@krystian3w Ale tło to chyba działało ok.

**Comment by krystian3w** [comment]
Może, ale razem z tym wykrywaniem colorobox  (jako brata / siostrę) się nie dogadywało.

Wróciłbym do tego że usuwanie go bez pop-up-a nie ma za bardzo sensu na razie.

**Comment by hawkeye116477** [comment]
@krystian3w Ten not dla overlay też jednak nie działa na starym uBO, tylko na nowym jest ok.

**Comment by krystian3w** [comment]
`http://www.sellsmart.pl/realizacje,28.html`

**Comment by krystian3w** [comment]
I więcej nie znalazłem i przejżałem do galeriamody.pl :arrow_right:  `http://www.sellsmart.pl/realizacje,28.html`

**Comment by krystian3w** [comment]
AdBlock chyba zginrował zgłoszenie błędu jak dodałem informacje o opcji obejścia z:

`###cboxOverlay:not([style="opacity: 0.9; visibility: visible; display: block; cursor: pointer;"]), #cboxOverlay:not([style="opacity: 0.9; visibility: visible; display: block; cursor: pointer;"]) ~ #colorbox`

A Adblock Plus będzie patrzał na to dopiero od nowego roku.
