### ISSUE TITLE
architektura.info

### ISSUE THREAD

**Issue by garrgamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1187]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się itp.)

![ss_124](https://user-images.githubusercontent.com/45873234/50028229-3cf8b900-ffef-11e8-9df7-999a20b7286e.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 2 modułów:
- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 2 modułach.

**Comment by blocker999** [comment]
@hawkeye116477 Jak to klasyfikować ? , chyba to niejest pop-up bo tutaj nic niewyskakuje, ja myśle że to widżet ale niewiem.

**Comment by hawkeye116477** [comment]
Ja bym to uznał jednak za popup :smile:.

**Comment by garrgamel** [comment]
Być może się pomyliłem z etykietą z rozpędu, o ile pamiętam krystian3w zmieniał mi chyba w 2 zgłoszeniach etykietę z `popup` na `newsletter`  właśnie dla takiego newslettera w prawym dolnym rogu.

**Comment by blocker999** [comment]
skoro @hawkeye116477 twierdzi też ze pop-up to może być pop-up
@garrgamel  decyzja

**Comment by garrgamel** [comment]
Mi to bez różnicy naprawdę, nie mam zdania, tylko napisałem, jak kwalifikował to krystian3w, to już wy musicie się między sobą dogadać, ja w to nie wnikam.

**Comment by garrgamel** [comment]
Jak coś to tu jeszcze 2 podobne zgłoszenia elementu w prawym dolnym rogu, dla których dałem `newsletter` zamiast `popup` zgodnie z zaleceniami od krystian3w, więc być może tamte też trzeba rozważyć tak samo: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1160, https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1142 .

**Comment by krystian3w** [comment]
jak nie jest na środku i nie zajmuje połowy ekranu to może jednak dalej newsletter, tak to by trzeba z 30 zgłoszeń przenieść, bo z boku wyskakiwało.

**Comment by krystian3w** [comment]
W przypadku innych rzadziej zgłaszających to by trzeba przejrzeć więcej zgłoszeń.

**Comment by garrgamel** [comment]
> krystian3w
> 
> https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Agarrgamel+label%3Anewsletter+
> 
> Jakby jednak trzeba było przenieść.

Ja te zgłoszenia przeglądałem i tylko te 2 wymienione przeze mnie w https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1187#issuecomment-447581811 mają etykietę `newsletter` nadaną przeze mnie, reszta zgłoszeń posiada etykietę `newsletter` nadaną przez inne osoby i została ona nadana do dodatkowych newsletterów statycznych osadzonych na stronie, a nie jako zamiennik etykiety `popup` bo wtedy etykieta `popup` zostałaby zdjęta, inaczej mówiąc w tych pozostałych zgłoszeniach są 2 newslettery: jeden typu popup i drugi statyczny typu `newsletter`, stąd dodatkowa etykieta `newsletter`, więc te zgłoszenia nie mają nic wspólnego z tym wątkiem.
