### ISSUE TITLE
perfectdating.pl

### ISSUE THREAD

**Issue by garrgamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1202]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się itp.)

![ss_141](https://user-images.githubusercontent.com/45873234/50045227-4fc2ca80-008f-11e9-8a17-6e131429ec3b.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 2 modułów:
- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 2 modułach.

**Comment by krystian3w** [comment]
Blokada przewijania jak na #1033, przewinąć scrollem można jeden ekran.

Na szczęście tylko myszą i działa suwak i strzałki z klawiatury

**Comment by hawkeye116477** [comment]
@krystian3w A będzie jakiś uboczny efekt po zastosowaniu `||perfectdating.pl/media/system/js/modal.js`?

**Comment by krystian3w** [comment]
Hmmm, jak to tylko do tego używają to nie, a tak to może jakieś ustawienia w pop-up-ie może wykombinowali na tym skrypcie (kij wie...).
