### ISSUE TITLE
u-jazdowski.pl

### ISSUE THREAD

**Issue by garrgamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1209]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się itp.)

![ss_148](https://user-images.githubusercontent.com/45873234/50045254-c3fd6e00-008f-11e9-96c5-d2a035b3944c.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 2 modułów:
- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 2 modułach.

**Comment by blocker999** [comment]
@garrgamel To niejest Popup tylko widzet ( inny element ),popup ma tło.

**Comment by hawkeye116477** [comment]
Tak w zasadzie, to jest tzw. fly-in, ale my na razie chyba to dodajemy do innych elementów.
`https://www.elegantthemes.com/documentation/bloom/flyin/`
