### ISSUE TITLE
Cudzysłowy uwstecznione ukośnikiem w selektorach atrybutów?

### ISSUE THREAD

**Issue by gwarser** [PolishFiltersTeam/PolishAnnoyanceFilters#1212]
Przykładowo PPB.txt linia 35

`aboutyou.pl##[class*=\"styles__footerContainer\"] > div:nth-of-type(2)`

W sumie jest tego chyba 35 filtrów w tej jednej liście, ale w innych listach też to jest.

**Comment by blocker999** [comment]
@gwarser Dzięki, poprawimy nie dziś to jutro

**Comment by gwarser** [comment]
Jeszcze wam tu podrzucę

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/4a8d282c708d3e2779be15f22cda7641791b7465/PPB.txt#L4487

`$images,` -> `$image,`


https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/4a8d282c708d3e2779be15f22cda7641791b7465/PPB.txt#L1116

`myloview.pl##.subskrypcja, #.ui-widget-overlay` -> `myloview.pl##.subskrypcja, .ui-widget-overlay` ?

**Comment by krystian3w** [comment]
Dzięki za literówki, te będzie prościej naprawić.

**Comment by krystian3w** [comment]
Gdzieś są jeszcze lub źle ręcznie poprawiłem z pomocą Notepad++?

**Comment by krystian3w** [comment]
oj będzie trochę tego: ` url(\"`

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/b979e0ea90eade5a98e2514d188505f58a6afa1f/PPB.txt#L3328

Chyba lepiej zostawię już to pod regex i sed itd.

**Comment by gwarser** [comment]
> oj będzie trochę tego: ` url(\"` ... `linen.png\")`

Ten chyba jest OK, bo to drugi cudzysłów wewnątrz innego.

**Comment by krystian3w** [comment]
Aż sprawdzę czy coś wycina.

**Comment by krystian3w** [comment]
Aż bym go przepiął pod filtry divów "fixed" bez klas i ID.

**Comment by krystian3w** [comment]
`##.cookie-alert-content`

**Comment by krystian3w** [comment]
Może na taki czas przerobić.

**Comment by hawkeye116477** [comment]
Ja tam obstawiałbym, że to nie wina skryptu, tylko ktoś coś się pomylił.

**Comment by krystian3w** [comment]
Ale aż z 16?

**Comment by hawkeye116477** [comment]
Raczej to nie reduntat checker ani skrypt, ale @blocker999 coś tam używa i mu to przestawia, bo ja już raz widziałem to w commitcie w tym nieposortowanym pliku przez skrypt. Tylko ciekawe co to jest.

**Comment by krystian3w** [comment]
Mnie najbardziej boli dodawanie komunikatów trudnych do listy pop-up-ów prostych, jak doda i ucieknie nam ten fakt to potem będzie bajzel aż do zgłoszenia zbłąkanego użytkownika ABP/Adblock Plus.

**Comment by krystian3w** [comment]
> Tylko ciekawe co to jest.

Może jakiś kulawy edytor tekstu i nawet nie jest on świadomy trybu pracy edytora.

**Comment by hawkeye116477** [comment]
A ztymi ukośnikami to jeszcze nic, ten edytor pozamieniał reguły miejscami i teraz są niektóre nie do tej strony co trzeba.

**Comment by krystian3w** [comment]
"masłowski" miks:

![obraz](https://user-images.githubusercontent.com/35370833/50050176-183a3980-00f4-11e9-98c1-40576146753e.png)

![obraz](https://user-images.githubusercontent.com/35370833/50050179-225c3800-00f4-11e9-8af3-9fc96917250f.png)

**Comment by hawkeye116477** [comment]
Jakby co, to polecam VS Code, a do tego `https://marketplace.visualstudio.com/items?itemName=adguard.adblock#overview` i `https://marketplace.visualstudio.com/items?itemName=ybaumes.highlight-trailing-white-spaces`. Trochę wolniej się uruchamia, bo jest na Electronie, szybszy jest Sublime, ale mi jakoś VS Code bardziej przypadł do gustu :smile:.
