### ISSUE TITLE
oponyalbert.pl

### ISSUE THREAD

**Issue by garrgamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1220]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się itp.)

![ss_181](https://user-images.githubusercontent.com/45873234/50047878-b57a7b00-00be-11e9-953b-ff5317908b13.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 2 modułów:
- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 2 modułach.

**Comment by hawkeye116477** [comment]
Stosują tą samą technikę, co #1154 i #1128, także musimy odblokować.
A ty @blocker999 trochę ostrożniej z colorboxami, bo one często coś innego też psują, najlepiej zawsze obserwować czy jest jakaś galeria/produkty z podglądem zdjęć w popupie :smile:

**Comment by blocker999** [comment]
@hawkeye116477 Sorry moja niewiedza zawsze można coś usunąć ale będe pamiętał na przyszłość

**Comment by krystian3w** [comment]
I tak z 30 zablokowaliśmy kiedyś i pewnie dopiero od 3 dni wiemy o tak dziwnym bugu.

**Comment by hawkeye116477** [comment]
@krystian3w No tak niekoniecznie, o colorboxie, że potrafi przy okazji coś psuć, to już sporo wcześniej wiedzieliśmy, no przynajmniej ja, blocker nie jest tak doświadczony, to mógł nie wiedzieć, no chyba, że chodzi o ten bug z **-abp-has**. Dlatego też zawsze staram się obejrzeć co się da, do czego mam podejrzenia, że może się coś popsuć :smile:.
