### ISSUE TITLE
astromagia.pl

### ISSUE THREAD

**Issue by garrgamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1228]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [x] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się itp.) błąd - część komunikatu wycięta a część nie
![ss_192](https://user-images.githubusercontent.com/45873234/50047934-15bdec80-00c0-11e9-8893-ad43d533c557.png)

po wyłączeniu modułu Polskie Filtry Elementów Irytujących - Newslettery:
![ss_193](https://user-images.githubusercontent.com/45873234/50047939-28d0bc80-00c0-11e9-876b-336365b45d13.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 2 modułów:
- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 2 modułach.

**Comment by krystian3w** [comment]
No to dociąłem, jak będzie więcej bugów, to się pomyśli nad przebudową generyków, by były skuteczne i szybkie.
