### ISSUE TITLE
jordanki.torun.pl/pl/

### ISSUE THREAD

**Issue by garrgamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1233]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [x] Błąd
- [] Pytanie
- [] Ulepszenie

---

\- wycięty komunikat, ale jest tło/cień
\- dodatkowo komunikat jest wycięty nie przez tę listę przez którą być powinien

![ss_264](https://user-images.githubusercontent.com/45873234/50113795-45493200-0243-11e9-8263-1fe0f092ed23.png)

po wyłączeniu modułu Polskie Filtry Elementów Irytujących - Newslettery wyskakuje popup:

![ss_265](https://user-images.githubusercontent.com/45873234/50113822-55611180-0243-11e9-8d8c-bce014a2e2f1.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 2 modułów:
- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 2 modułach.

**Comment by krystian3w** [comment]
protip:

`\-` i już nie wypunktuje.
