### ISSUE TITLE
bolix.pl [2]

### ISSUE THREAD

**Issue by garrgamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1236]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [x] Błąd
- [] Pytanie
- [] Ulepszenie

Reopen #1204 bo dalej to jest zarówno na Firefoxie jak i na Operze.

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 2 modułów:
- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 2 modułach.

**Comment by krystian3w** [comment]
@blocker999  zmieniłeś już edytor tekstu? 

A tak to pewnie po losowym ID / klasie zablokowane i już się zmieniło.

**Comment by krystian3w** [comment]
`pushpushgo.com###ebook-popup?` fałszywy alarm.

**Comment by hawkeye116477** [comment]
@krystian3w To akurat ja dodałem => `https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/62180a4e34d81541dbdcf598ac7346045a8b414e#diff-89ffbf43b368507d29148da7dae11294`, teraz tego nie widzę, ale oni jakiś ebook reklamują, więc zapewne wtedy to się pojawiało :smile:

**Comment by krystian3w** [comment]
Najważniejsze by nie zmieszał się filtr z innym.
