### ISSUE TITLE
uap.edu.pl [2]

### ISSUE THREAD

**Issue by garrgamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1237]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [ ] Błąd
- [] Pytanie
- [] Ulepszenie

Reopen #1208 bo dalej to jest zarówno na Firefoxie jak i na Operze.

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 2 modułów:
- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 2 modułach.

**Comment by hawkeye116477** [comment]
No to powiedziałbym, że nie błąd, tylko po prostu ktoś nie zrobił to co miał zrobić...

**Comment by garrgamel** [comment]
- 1_ etykieta jest `Błąd` a nie `Błąd w filtrach`
- 2_ nigdzie nie twierdzę, że to błąd w filtrach
- 3_ poza nie wiem czy brak filtra zalicza się do błędu w filtrach czy nie
- 4_ nie ma etykiety `Nienaprawione` lub `Niezrobione` jeśli taka się pojawi, wtedy chętnie będę z niej korzystał
- 5_ a skoro zgłoszenie zamknięte + zatwierdzone, a problem dalej jest, bo ktoś zapomniał albo zamknął i zatwierdził nie to zgłoszenie, które trzeba, to też błąd, chociaż nie w filtrach.
- 6_ poza tym nie sprawdzam bebechów każdego nienaprawionego zgłoszenia, żeby się dowiedzieć dlaczego nie działa, czy wskutek złego filtra czy z braku filtra w ogóle, czy z pomylenia zgłoszenia  z inymm, patrzę tylko wizualnie czy naprawione czy nie. Jeśli widzę zgłoszenie zamknięte i zatwierdzone (co oznacza, że naprawione), a w praktyce nie jest naprawione, to błąd i tyle, jeśli byłoby tak, że ktoś nie zrobił co miał zrobić, to powinno być otwarte + rozpoczęto.
