### ISSUE TITLE
balladine.com [2]

### ISSUE THREAD

**Issue by garrgamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1238]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [ ] Błąd
- [] Pytanie
- [] Ulepszenie

Reopen #1189 bo dalej to jest zarówno na Firefoxie jak i na Operze.

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 2 modułów:
- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 2 modułach.

**Comment by hawkeye116477** [comment]
Ja tam nic nie widzę, no chyba, że to pojawi się dopiero za godzinę :smile:.

**Comment by hawkeye116477** [comment]
Ale `balladine.com##.popupTloNewslatter` to już działa...

**Comment by garrgamel** [comment]
Tu mi się coś pochrzaniło, nie zauważyłem i myślałem że zgłaszane i nieusunięte

<details not-open>
<summary> było to:</summary>

![ss379](https://user-images.githubusercontent.com/45873234/50170443-32406b80-02f0-11e9-8949-844180fcf9a6.png)

</details>
<br>

- ale tak teraz spojrzałem do https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1189 i zauważyłem, że tam był zgłaszany inny komunikat, który jest poprawnie usunięty
- poza tym ten komunikat o którym myślałem też jest już usuwany przez moduł Polskie Filtry Elementów Irytujących - Inne Widżety

Więc jest gitara i wszystko gra, zamykam.
