### ISSUE TITLE
cieplikpodrozuje.pl/pl/

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1247]
![opera zdjecie_2018-12-19_111259_cieplikpodrozuje pl](https://user-images.githubusercontent.com/36385327/50214159-d8878200-037f-11e9-85e2-4b9c3bf5a620.png)

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by hawkeye116477** [comment]
Ach ten Fanboy, scrolla zablokował...

**Comment by krystian3w** [comment]
Jak to jest coś z tych:

```
##div[data-cookie]
##div[data-cookiebar]
##div[data-nconvert-cookie]
```

To z tego chyba się już nie wygrzebią.

**Comment by hawkeye116477** [comment]
@krystian3w Nie, inna reguła jest problemem => `##.fb-page`.

**Comment by krystian3w** [comment]
Jak masz siły to możesz zgłosić by sobie naprawili, ja nie mam okienka nawet po wyłączeniu EI jakby sobie do IP przypisywali, że widziałem.

**Comment by krystian3w** [comment]
Zgłoszone, niech się bawią. Myślałem nad dodaniem `#@#.fb-page` do wyjątków, może się przydać dla użytkowników AdBlock / ABP by szybciej namierzyli POP-UP i zamykacz.
