### ISSUE TITLE
trans.info

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1248]
https://trans.info/pl/jak-budowa-autostrad-zmniejszyla-bezrobocie-w-niemczech-117707
![opera zdjecie_2018-12-19_115814_trans info](https://user-images.githubusercontent.com/36385327/50216289-a1b46a80-0385-11e9-84fa-4b763aad2944.png)

### Typ elementu/problemu
- [X] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [ ] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by hawkeye116477** [comment]
To akurat jest newsletter :stuck_out_tongue:
