### ISSUE TITLE
kupbilecik.pl

### ISSUE THREAD

**Issue by garrgamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1252]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [x] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się itp.) + push 2in1 - stąd 2 etykiety bo nie wiedziałem, czy dać jedną, a jeśli tak to którą, czy dwie, chociaż o ile dobrze pamiętam to gdzieś ktoś pisał, że jeśli tło to popup:

![ss_270](https://user-images.githubusercontent.com/45873234/50309461-352d8e80-049f-11e9-9fc8-5e6066ded7af.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 3 modułów:
- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 3 modułach.

**Comment by hawkeye116477** [comment]
No tak w zasadzie, to można dodać połowę tu, a połowę tam, ale myślę, że nie ma co się rozdrabiać i jednak lepiej cały dodać do popupów :smile:.
