### ISSUE TITLE
yoursclothing.pl

### ISSUE THREAD

**Issue by garrgamel** [PolishFiltersTeam/PolishAnnoyanceFilters#1255]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [x] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się itp.) oraz push

![ss_273](https://user-images.githubusercontent.com/45873234/50309566-8b9acd00-049f-11e9-9278-55e5f5064ced.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 3 modułów:
- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 3 modułach.

**Comment by hawkeye116477** [comment]
Jeżeli chodzi o push, to mam nadzieję, że to niczego nie popsuje => `yoursclothing.pl##+js(abort-on-property-read.js, Notification.requestPermission)`, a przynajmniej dla niezalogowanych nic nie psuje, ale po zalogowaniu może być różnie. Ewentualnie jeszcze może być => `yoursclothing.pl##+js(set-constant.js, Notification.requestPermission, noopFunc)` :smile:.
