### ISSUE TITLE
Uwaga

### ISSUE THREAD

**Issue by booleek** [PolishFiltersTeam/PolishAnnoyanceFilters#1308]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [x] Pytanie
- [] Ulepszenie

Radzę uważać i szybko zapisywać wszystkie moje zgłoszenia bo pedofile z administracji githuba (albo ich durne boty) banują konta z nienacka bez powodu, a potem ignorują i nie odpisują na mejle, pomimo, że nic złego nie robię i nie jestem robotem, taki ban powoduje, że człowiek jest wymazywany gumką jakby nigdy nie istniał, nie ważne czy siedzisz tu 10 dni czy 10 miesięcy czy 10 lat, dostajesz bana i wszystkie zgłoszenia, commity, komentarze, repozytoria oraz konto (profil)....znikają, jesteś jak woda, która wyparowuje... zaraz te konto może też polecieć i znowu szalg trafi wszystkie zgłoszenia. Być może również tak, że ktoś życzliwy donosi, te geje rozwalają nam robotę.

**Comment by hawkeye116477** [comment]
Te :banana: to takie nagrody za wzorowe zachowanie. Kiedyś dawali rózgi, a teraz :banana: :smile:

**Comment by booleek** [comment]
Akurat chodziło mi o konto garrgamel, które nic złego nie zrobiło, a tylko dużo pomagało, skoro jesteś taki mądry to może wyjaśnisz co te konto zrobiło, że dostało bana.

Druga ciekawa rzecz skoro rozmawiamy o uczciwości i zachowaniu to jest taka dlaczego, kiedy ja kiedyś zgłaszałem jednego typa do administracji githuba, bo ten typ bluzgał wielokrotnie w wielu komentarzach, to nic mu nie zrobili, a jego bluzgi dalej wiszą? Dlaczego nie dostał nagrody za "wzorowe zachowanie"?

Rozumiem, że to takie "wzorowe zachowanie" administracji i tego typa który bluzgał, że tylko wybrani dostają nagrody, a przydupasy i znajomki nie.

**Comment by hawkeye116477** [comment]
@booleek Dobra, dobra, już nie rób z siebie takiej ofiary. Tym poprzednim kontem, o którym wspomniałeś akurat nie widziałem byś coś niegrzecznego wypisywał, przynajmniej na tym repo, nie wiem jak na innych, ale w twoim przypadku jakoś nie wierzę, byś dostał nagrodę bez powodu. Omijasz bany poprzez tworzenie nowych kont przez proxy czy czego ty tam używasz, a ja w Audit Logu widzę, że wraz z nowym kontem wchodzisz z innego kraju. Zapewne za to też są jakieś nagrody.
Jak dostajesz karę, to powinieneś czekać na jej zakończenie, a nie próbować jak by tu ją ominąć.

**Comment by booleek** [comment]
> hawkeye116477 : booleek Dobra, dobra, już nie rób z siebie takiej ofiary.

Nie robię z siebie ofiary, raczej ty robisz ze mnie kata, konto garrgamel nic nie zrobiło, a dostało bana, na mejle github nie odpisuje.

> hawkeye116477 : Tym poprzednim kontem, o którym wspomniałeś akurat nie widziałem byś coś niegrzecznego wypisywał, przynajmniej na tym repo, nie wiem jak na innych, ale w twoim przypadku jakoś nie wierzę, byś dostał nagrodę bez powodu.

No właśnie nic nie zrobiłem złego, kompletnie nic, byłem jak aniołek, i tak przez jakiś czas po prostu robiłem tylko zgłoszenia tutaj i było wszystko ok, przez ileś dni, a tu nagle ban z duupy.

> hawkeye116477 : Jak dostajesz karę, to powinieneś czekać na jej zakończenie, a nie próbować jak by tu ją ominąć.

Ty nie bądź taki mądry już ci pisałem, bo jakoś lubisz pisać tylko o mnie, a dlaczego milczysz jak grobowiec w kwestii typa, który bluzgał i którego zgłaszałem i nie dostał bana? Dlaczego nie napiszesz czegoś w stylu: no to fakt, administracja github leci w kulki, skoro zgłaszałeś typa który bluzgał, a oni mu nic nie zrobili, a ciebie blokują non stop. Czy uważasz to za sprawiedliwość i wzorowe zachowanie administracji gdy 2 coś zrobi a tylko jeden jest karany? Skoro tamten typ nie dostał bana to ja też mam nie dostawać, tym bardziej, że na nowym nikcu byłem jak aniołek i na niego nie zasługiwałem.

Tylko nie zamykaj zaraz wątku, bo ja ci nie ubliżam i normalnie dyskustuję, a znam twoje i twojego kolegi po fachu metody.

**Comment by booleek** [comment]
Po co w ogóle ta dyskusja, nie dam się tobie sprowokować, zamykam, ale oczywiscie jeśli chcesz kontynuować.
