### ISSUE TITLE
vivrehome.pl

### ISSUE THREAD

**Issue by gaargulec** [PolishFiltersTeam/PolishAnnoyanceFilters#1322]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas itp.)

![ss_329](https://user-images.githubusercontent.com/45939728/50377041-6e3c3f00-0616-11e9-9edc-acfe1c01ba9c.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 3 modułów:
- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 3 modułach.

**Comment by hawkeye116477** [comment]
Cwanie zrobili, jak schowam to, to i rejestracja się zepsuje.

**Comment by gwarser** [comment]
Na starcie jest tak:

                            <h2 class="title js-title-for-onload">Witaj</h2>
                            <h2 class="title js-title-default is-hidden">Utwórz konto</h2>

po kliku tak

                            <h2 class="title js-title-for-onload is-hidden">Witaj</h2>
                            <h2 class="title js-title-default">Utwórz konto</h2>


To powinno działać w uBO dev, ale coś nie bangla

    www.vivrehome.pl###modals>.js-popup-register:has(.js-title-for-onload:not(.is-hidden))


Ma działać 30 sekund, no i ukrywa jak się za szybko kliknie:

    www.vivrehome.pl##+js(overlay-buster.js)

**Comment by hawkeye116477** [comment]
Czyli tak raczej słabo. Opcja z busterem raczej odpada, bo kto będzie czekał, żeby móc się zarejestrować. W AG ta pierwsza reguła też nie działa.
A więc, poczekamy na @F4z, może on będzie miał lepszy pomysł.

**Comment by krystian3w** [comment]
Jak nie wymyślą nic skryptowego to będzie podobnie jak z `e-forma` lub wycinamy tym co nie mogą uaktualnić uBO do nowszej stabilnej i dodatkowo jeszcze jakiś bug z atrybutami jest.

**Comment by krystian3w** [comment]
`vivrehome.pl##.js-popup-register:not(has-text(Utwórz konto))`

Niby działa.

**Comment by hawkeye116477** [comment]
@krystian3w Niby jak, jak oba mają tekst „Utwórz konto" :stuck_out_tongue:

**Comment by krystian3w** [comment]
Nie patrzyłem na guzik (`<button>`)..., ale nawet doprecyzowanie h2 nie działa.

**Comment by gwarser** [comment]
uBO zapamiętuje tego noda z `:has()` i potem tylko sprawdza czy został usunięty, ale nie patrzy czy selektor dalej pasuje (zmiany class albo id).

Próbowałem ze scriptletami, ale ciężko mi się to debuguje bo mi cały komp zamula jak coś tam mieli w debugerze :( To co próbowałem to nie działało (okolice `openPopupRegister`...) Jak by się dało ciastka ustawiać (`newsletter-modal-closed`)...

**Comment by hawkeye116477** [comment]
:cookie: może pingwin ustawić, a i @F4z może do AG dodać.

**Comment by hawkeye116477** [comment]
To u was działa => `vivrehome.pl##.js-popup-register:has(.js-title-default.is-hidden:watch-attrs(class))`? Bo sprawdzałem na najnowszym uBO Dev i chyba nie działa,.
To znowu jako tako działa => `vivrehome.pl##.js-popup-register:watch-attrs(class):has(.js-title-default.is-hidden)`, tyle, że muszę kliknąć na logowanie, by rejestracja się odblokowała.

**Comment by krystian3w** [comment]
U mnie wcale, coś poszło chyba nie tak jak testowałem gdy `watch-attrs` jest w `:has()`.

Trzeba by się dopytać czy Raymond dał tylko propozycje, która jeszcze nie działa, bo niedoprogramował...

**Comment by gwarser** [comment]
U mnie 1 działa. Nightly 1.17.7b2

**Comment by krystian3w** [comment]
Sprawdź na innej wersji językowej dla pewności.

```
vivre.ro
vivre.hr
vivre.hu
vivre.cz
vivre.gr
vivrehome.sk
vivre.si
```

w Operze 57 z uBO Dev chromowatym nie działa mi klikanie w "rejestruj".

**Comment by krystian3w** [comment]
Sprawdzę jeszcze nowojorskie przepisy czy się przypadkiem coś więcej nie popsuło.

**Comment by gwarser** [comment]
? `vivrehome.pl##.js-popup-register:not([style]):watch-attrs(style):has(.js-title-default.is-hidden:watch-attrs(class))`

Coś w skrypcie zmienili i nie zmienia `.is-hidden` tak jak wcześniej. Za to dodaje atrybut `style`.

**Comment by krystian3w** [comment]
OK i z atrybutem style działa?

**Comment by hawkeye116477** [comment]
A ja tam widzę, że jednak zmienia **.is-hidden**.

**Comment by krystian3w** [comment]
A mi działa to z style lub chamsko robią ciasteczko po usunięciu.

**Comment by gwarser** [comment]
> A ja tam widzę, że jednak zmienia **.is-hidden**.

Ale nie w tym samy momencie. Czasami zostaje.

> OK i z atrybutem style działa?

U mnie działa, ale warto sprawdzić, bo u mnie nie zawsze czyszczenie ciastek zaskakuje.

**Comment by hawkeye116477** [comment]
A mi nie działa i tak robią ciasteczko po usunięciu.

**Comment by krystian3w** [comment]
To pewnie u mnie działa ciastko a animacje nie wiem skąd są wyciąłem ostatnio:

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/407ca5d5f4de3af4309c61f7debe701a394db61d/PAF_pop-ups.txt#L456

**Comment by hawkeye116477** [comment]
Wyłączyłem i włączyłem uBO i o dziwo nagle zaskoczyło, dziwne, czasem tak jest, że coś nie chce działać i muszę wyłączyć go i włączyć :smile:.

**Comment by krystian3w** [comment]
Mi **element picker** zazwyczaj mi się naprawia na odświeżenie strony, a **logger** by widzieć coś z danej strony od ponownego uruchomienia firefox/opery (jeszcze nie próbowałem wyłączać samego rozszerzenia by sprawdzić czy się odbuguje.

**Comment by krystian3w** [comment]
A tak wracając, jak teraz mieli by zawsze dopisywany atrybut style, to nie idzie tego podobnie jak z #1324 czasem?

**Comment by hawkeye116477** [comment]
Rejestracja nie działa za pierwszym razem.

**Comment by krystian3w** [comment]
Ja bym powiedział że teraz działa nawet:

```
vivrehome.pl##.js-popup-register:not([style]):watch-attrs(style)
```

Ale może lepiej sprawdzać i to h2.

**Comment by hawkeye116477** [comment]
A więc, został uBO Edge, Safari i Nano. Do Safari to jakoś wątpię, że nadejdzie ten update, a w prypadku Edge zawiesili chyba pracę, bo i tak zaraz przechodzi na Chromium. Do Nano :penguin: może kiedyś doda te :cookie: , na razie coś niezdecydowany, chce robić nową listę, ale nie wiem w jakim celu skoro jest już Nano Annoyance :smile:.

**Comment by krystian3w** [comment]
Jeszcze też jest `AdNauseam` i niby planują na kiedyś uaktualnienie do kodu bazującego na uBO 1.18+.

**Comment by hawkeye116477** [comment]
@krystian3w `AdNauseam` niby nie wspieramy :smile:.

**Comment by hawkeye116477** [comment]
Jeszcze jest Avast Adblocker czy jakoś tak, z tym, że on jest tylko w pakiecie z Avast Safe Browser i coś tam chyba nie działa subskrypcja dodatkowych list  :smile:

**Comment by krystian3w** [comment]
Działa podwójnie w nim są jakoś dwa uBlock Origin i raczej dalej w wersji 1.14.23

**Comment by hawkeye116477** [comment]
@krystian3w No niby podwójnie, ale w ustawieniach nie widać w ogóle tych list zasubskrybowanych samodzielnie albo ja nie ogarnąłem tego interfejsu.

**Comment by krystian3w** [comment]
Oni tam sieczkę zrobili z interfejsu.

Jedynie nie pamiętam czy to przeglądarka nadpisywała czy taki dodali CSS stylizujący na ustawienia Chromium.

**Comment by hawkeye116477** [comment]
@krystian3w Offtopic proponuję lepiej pisać na naszym czacie drużynowym. Ale skoro już zacząłeś, to tak, można zrobić. Trzeba będzie chyba po prostu zrobić „pułapkę" z sieciowych.  Jak chcesz to się tym zajmij.

**Comment by krystian3w** [comment]
W najnowszym Avast widzę, że już zablokowali opcje subskrypcji. Więc ten idzie na listę oficjalnie niewpieranych przez podejście twórców forka.

**Comment by krystian3w** [comment]
"Avast Adblock" / "Avast Anti-Tracking" są wciąż w za starej wersji.

**Comment by krystian3w** [comment]
Dla odważnych z AdGuard AdBlocker 3.0.X:

https://pastebin.com/raw/UGjzRwQ9/

**Comment by krystian3w** [comment]
Kolejny klon uBO: https://www.adaware.com/pl/ad-block

**Comment by hawkeye116477** [comment]
Trochę po polsku, trochę po angielsku i krzaki zamiast polskich znaków, widać, że profesjonalna strona... Rok temu ten wynalazek aktualizowali.

**Comment by krystian3w** [comment]
Ktoś robił czelendż z filtrami procuduralnymi w AdGuard 3.X?

Niby ogarnęli i ich demo obsługują - `https://ameshkov.github.io/web/watchattr.html`

**Comment by krystian3w** [comment]
Z tego co patrzyłem jednak poszli na tworzenie ciastek w AdGuard.

**Comment by krystian3w** [comment]
Chyba znów coś pokombinowali lub żadna składnia niekompatybilna dla portu NaB 1.0.0.123 z AMO.

**Comment by krystian3w** [comment]
A już widzę, już nagle nie ma przycisku rejestracji a "subskrypcja".

Teraz pytanie czy wycinamy przycisk subskrypcji z komunikatem lub dalej zabawa by wracał po kliknięciu w "subskrybuj".

**Comment by krystian3w** [comment]
Jednak nie działa, jakby już w kodzie nie było niczego do `watch-attr`?

**Comment by hawkeye116477** [comment]
Chyba coś zmienili, w ogóle ten popup ma co innego napisane.

**Comment by krystian3w** [comment]
Ciastko też nowe:     `modal-subscribe-closed-daily:true`

stare: `#%#document.cookie = "newsletter-modal-closed=true";`

**Comment by hawkeye116477** [comment]
@krystian3w Nowy sposób => `vivrehome.pl##+js(set-constant.js, appShell.guest, false)`, nie wiem tylko czy czegoś nie sknoci, ale chyba to jest do sprawdzania czy jesteśmy gośćmi (niezalogowani) :smile:

**Comment by krystian3w** [comment]
Chyba zrobili zmianę całkowitą wyglądu:

- nowe logo
- nowy wygląd strony
- niby więcej reklamują "produktów"
