### ISSUE TITLE
newslettery colorbox

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters#1324]
### Typ elementu/problemu:

- [x] Wyskakujące okienko (popup)

### Adresy:

```diff
+annalotan.pl
-arms.com.pl
+e-forma.pl
@@ homeoapteka.pl @@
+meblezagrosze.pl
+oponyalbert.pl
-spex.pl
+zegarkiabc.pl
+zegarkizpasja.pl
```

Przykładowe źródło reszty:

`http://www.sellsmart.pl/realizacje,28.html`

### Błędy rozpatrywane w innych dodatkach:

* https://issues.adblockplus.org/ticket/7170 - w 2019 o ile nie zostanie uznane za mało istotny błąd.
* https://help.getadblock.com/support/tickets/59223 - zamknięty z winy podania filtrów na obejście, trzeba spróbować ponownie i inaczej niż poprzednio.

Przykłady blokowania:

* `##^#newsletter_colorbox`
   `$$#newsletter_colorbox`

* `###cboxOverlay:not([style="opacity: 0.9; visibility: visible; display: block; cursor: pointer;"])`
  `###cboxOverlay:not([style="opacity: 0.9; visibility: visible; display: block; cursor: pointer;"]) ~ #colorbox`

* `###colorbox:not(:has(.cboxPhoto))`
  `###cboxOverlay`

**Comment by garrgamel** [comment]
e-forma.pl https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1128 
homeoapteka.pl https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1154
oponyalbert.pl https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1220
meblezagrosze.pl https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1215

**Comment by krystian3w** [comment]
Wróciły :+1:

**Comment by krystian3w** [comment]
`###colorbox:not(:has(.cboxPhoto))`

przestał mi się podobać, ma buga przy otwieraniu galerii za pierwszym otwarciem i w sumie też ciężko to naprawiać kilkoma poleceniami CSS.

**Comment by hawkeye116477** [comment]
@krystian3w Ale ta nowa reguła to słaby pomysł, bo w starym uBO psuje galerię.

**Comment by krystian3w** [comment]
W sensie że:

`###cboxOverlay:not([style="opacity: 0.9; visibility: visible; display: block; cursor: pointer;"]) ~ #colorbox`

wycina za dużo?

Jak tak to Opera i Chrome obejdą się smakiem aż do popularności wydania poprawionego stabilnego uBO.

Ta alternatywa nie może być skoro w AdGuardzie za drugim razem wcale nie ma ładowania grafiki.

**Comment by hawkeye116477** [comment]
@krystian3w Przecież można dla AG i uBO dać oddzielne.

**Comment by krystian3w** [comment]
@krystian3w  ja nie umiem by nie wchłoną AG obu.

**Comment by hawkeye116477** [comment]
@krystian3w Masz przecież pliki popupy_uBO i popupy_AG porobione :stuck_out_tongue:

**Comment by krystian3w** [comment]
W AdGuard  2.10.11 `###colorbox:has(#newsletter_colorbox)` działa poprawnie.


Jak stare uBO zaczytają mimo dyrektyw listę AG do uBO?

**Comment by hawkeye116477** [comment]
@krystian3w W AG to nie działa poprawnie, bo za pierwszym czy tam drugim razem będzie ok, ale potem już galeria nie chce się ponownie otwierać.

**Comment by krystian3w** [comment]
`http://arms.com.pl` jednak ma newsletter.

**Comment by hawkeye116477** [comment]
@krystian3w Ten arms.com.pl wygląda mi na fake'owy sklep, nie mają https i jak chce się dowiedzieć info o sklepie to wywala że zbyt wiele przekierowań.

**Comment by hawkeye116477** [comment]
@krystian3w Nie wiem czy ten `arms.com.pl` to by nie dodać do KADa, nie mają `https`, a na dole jak klikam info o sklepie to wywala błąd, że zbyt wiele przekierowań. Regulamin to chyba przepisali od jakiegoś innego `Regulamin określa zasady świadczenia usług sprzedaży za pośrednictwem strony internetowej sklepu internetowego działającego pod domeną: www.sklep.pl. `. Mail podświetlany jest inny niż napisany (`kontakt@dosklepu.pl` is BAD).

**Comment by hawkeye116477** [comment]
A ta reguła nadal w uBO nie działa poprawnie => `###cboxOverlay:not([style="opacity: 0.9; visibility: visible; display: block; cursor: pointer;"]) ~ #colorbox`

**Comment by krystian3w** [comment]
Czyli zostawia cień pod galerią?

**Comment by hawkeye116477** [comment]
@krystian3w Nic nie zostawia, nie działa powiększanie zdjęć w Nano.

**Comment by krystian3w** [comment]
Mi chodziło czy na uBO znika cień pod galerią.

**Comment by hawkeye116477** [comment]
@krystian3w Nie znika, jest ok, więc niby można byłoby to zamienić, ale dla Nano musiałaby być nadal tamta reguła z not has.

**Comment by krystian3w** [comment]
Spex się przebranżowiło czy jakoś tak...

**Comment by krystian3w** [comment]
@hawkeye116477 Firefox chyba zaczął mieć podobny problem co kiedyś AG, filtr not has coś robił mimo że html filtering unieszkodliwiło.

**Comment by hawkeye116477** [comment]
`homeoapteka.pl` - do sprawdzenia, jak dla mnie podejrzana

**Comment by hawkeye116477** [comment]
Najwyraźniej chyba zaczęło się psuć, ta opcja z `:not(:has` czasem powoduje problem, że wyświetla miniaturę, ale na szczęście można użyć `remove`. Jedynie problem jest, że uBO legacy tego nie obsługuje, ale tej kombinacji `:not(:has` też nie. Ma nawet problemy ze skryptletami, jak wpisze się pełną nazwę, ale bez `js`, to olewa, ale o dziwo działa skrócona i bez js...

**Comment by krystian3w** [comment]
Niby porzucono legacy na rzecz 1.20.0 i zalecenia modernizacji używanego oprogramowania.

**Comment by hawkeye116477** [comment]
@krystian3w Justoff przejął dowodzenie => https://github.com/gorhill/uBlock-for-firefox-legacy

**Comment by krystian3w** [comment]
@hawkeye116477 może proceduralny CSS będzie dobry i coś awaryjnie starszego dla uBO legacy (lub miks z HTML Filteringiem).

```css
*#$##cboxOverlay:has( + #colorbox:has(#newsletter_colorbox)) { visibility: hidden !important; }
*#$##colorbox:has(#newsletter_colorbox) {visibility: hidden !important; }
```

**Comment by hawkeye116477** [comment]
A o co konkretnie chodzi? Coś nie działa? Bo jakto się mówi, to już było dawno i nieprawda....

**Comment by krystian3w** [comment]
No niby w "lipcu" znowu dodałeś `arms.com.pl` do złej listy:

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/f9572cb52664d87c18a48fa44af72ea9fe6e9004/PPB/popupy.txt#L54-L55 (efekt poprawiania po blockerze). I jak testuje to najnowsze ABP nawet olewa te filtry (lub to uszkodzenie w profilu przeglądarki).

I takie filtry działają średnio dla [uBO 1.30+](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/milestone/3)

A `visibility: hidden` wyjątkowo nawet nie robi glitchy że podgląd czasem jest za mały lub pusty (nawet do 11 razy mogę otworzyć galerię bez odświeżania oferty).

**Comment by hawkeye116477** [comment]
No fakt, sprawdziłem ponownie i czasem podgląd robi się za mały. Twoja poprawka wydaje się ok. Tak więc trzeba będzie po prostu dodać poprawkę dla nowego, a dla legacy starą wersję.

**Comment by krystian3w** [comment]
Jeszcze zrobiłem test i musimy chyba w AG czekać na naprawy "Unhide nodes" aka watch-attr:

`https://github.com/AdguardTeam/ExtendedCss/issues/122`
`https://github.com/ameshkov/web/pull/2`

**Comment by krystian3w** [comment]
#2956
