### ISSUE TITLE
claudia.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1326]
### Typ elementu
scrollujący filmik
### Link bezpośredni 
`https://www.claudia.pl/swiateczne-ozdoby-z-szyszek`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox 56.0
**Bloker:** Nano Adblocker 1.0.0.81
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
Wystarczy tylko `claudia.pl##.miniplayer` :smile:.
