### ISSUE TITLE
eholiday.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1333]
https://www.eholiday.pl/noclegi-nt9230.html
![opera zdjecie_2019-01-04_094303_www eholiday pl](https://user-images.githubusercontent.com/36385327/50679769-2c8f9900-1005-11e9-95fc-2c84d24ba1ac.png)

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [ ] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
@xMaap  znowu misclick i nie to zaznaczone?

**Comment by krystian3w** [comment]
`eholiday.pl##.box-promofixed`
