### ISSUE TITLE
strefakodera.pl

### ISSUE THREAD

**Issue by garrgul** [PolishFiltersTeam/PolishAnnoyanceFilters#1336]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas itp.),
dodatkowo nie działa przycisk zamknij "X" , więc nie da się zamknąć komunikatu, nawet po wyłączeniu adblockera, więc to chyba u nich, ale pewności nie mam bo nie zagłębiałęm się i nie analizowałem tego

![ss_009](https://user-images.githubusercontent.com/46375428/50733916-69d76080-1196-11e9-8bb9-a4732a97e897.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 3 modułów:

    Newslettery (bez wyskakujących okienek)
    Wyskakujące Okienka
    Powiadomienia Web Push

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 3 modułach.

**Comment by hawkeye116477** [comment]
@MajkiIT Poprawka na przycisk zamknięcia:
`@@||cdn.dtxngr.com/init.js$script,domain=strefakodera.pl`

**Comment by krystian3w** [comment]
A majkiIT dodał poprawkę?

**Comment by hawkeye116477** [comment]
Tak
