### ISSUE TITLE
instagram.com

### ISSUE THREAD

**Issue by gwarser** [PolishFiltersTeam/PolishAnnoyanceFilters#1337]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [x] Błąd
- [] Pytanie
- [] Ulepszenie

### Moja konfiguracja
**Przeglądarka internetowa:** Nightly, Chromium 71

**System operacyjny:** Manjaro

**Bloker:** uBO 1.17.7b1, 1.17.4

**Używane filtry:**
1. https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB.txt

### Link bezpośredni (opcjonalny)
https://www.instagram.com/smarkacz.pl/

### Inne ważne informacje mogące mieć znaczenie (opcjonalne):
jak się coś wklepie w wyszukiwarkę na górze strony (`asdf`) poczeka na dymek z wynikami i odsunie kursor to cały top robi się biały. W Chromium chyba trzeba odświeżyć stronę.

Błędny filtr:

    instagram.com##body > span#react-root > section > nav > div > div > div[class]:has(.coreSpriteDismissLarge)

Właściwie to:

    instagram.com#?#body > span#react-root > section > nav > div > div > div[class]:-abp-has(.coreSpriteDismissLarge)

**Comment by hawkeye116477** [comment]
To akurat najwyraźniej jest coś z części :cookie:, nieładnie @krystian3w :stuck_out_tongue:

**Comment by krystian3w** [comment]
Mnie tam pasowało, najważniejsze z 2 miesiące temu było odblokować rejestracje na stronie www, bo filtry szukające w p "cookies" wycinały za dużo.

**Comment by krystian3w** [comment]
Jak coś u mnie da się zreprodukować to robiąc cofanie w historii przeglądanego instagrama.

**Comment by krystian3w** [comment]
@gwarser  / @hawkeye116477  pasek cookies znów dodali lub się u mnie odblokował:

![image](https://user-images.githubusercontent.com/35370833/51471179-47d50500-1d76-11e9-916e-fd46e784bfb3.png) |
--- |

**Comment by krystian3w** [comment]
Najlepiej poprosiłbym o testy:

`instagram.com##.lOPC8`

**Comment by hawkeye116477** [comment]
U mnie tego nie ma nawet po wyłączeniu Nano, ale ja nie zalogowany.

**Comment by krystian3w** [comment]
Ja mam na wylogowanym.
