### ISSUE TITLE
pinka.pl

### ISSUE THREAD

**Issue by garrgul** [PolishFiltersTeam/PolishAnnoyanceFilters#1341]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [ ] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas itp., przy okazji powiązane - błąd u Fanboya https://github.com/ryanbr/fanboy-adblock/issues/880)

![ss_021](https://user-images.githubusercontent.com/46375428/50983304-81e51200-14ff-11e9-84ef-1c9b3efea560.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 3 modułów:

    Newslettery (bez wyskakujących okienek)
    Wyskakujące Okienka
    Powiadomienia Web Push

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 3 modułach.

**Comment by krystian3w** [comment]
`###colorbox, #cboxOverlay` chyba bezpieczny do wycięcia, bez sprawdzania co w sobie ma na poziomie uBO 1.17.6/1.18.0+ lub AdGuard.
