### ISSUE TITLE
modea.pl

### ISSUE THREAD

**Issue by garrgul** [PolishFiltersTeam/PolishAnnoyanceFilters#1343]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

2 x popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas itp.,)

![ss_030](https://user-images.githubusercontent.com/46375428/50985930-c7a4d900-1505-11e9-8a20-a6380dc77be5.png)

![ss_031](https://user-images.githubusercontent.com/46375428/50986036-0d61a180-1506-11e9-9d3f-714906625995.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 3 modułów:

    Newslettery (bez wyskakujących okienek)
    Wyskakujące Okienka
    Powiadomienia Web Push

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 3 modułach.

**Comment by krystian3w** [comment]
`###CoverPop-cover.splash`
