### ISSUE TITLE
modea.pl (2)

### ISSUE THREAD

**Issue by garrgul** [PolishFiltersTeam/PolishAnnoyanceFilters#1344]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [x] Błąd
- [] Pytanie
- [] Ulepszenie

Reopen https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1343 - bo brak przewijania

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 3 modułów:

    Newslettery (bez wyskakujących okienek)
    Wyskakujące Okienka
    Powiadomienia Web Push

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 3 modułach.

**Comment by hawkeye116477** [comment]
@krystian3w Nie ładnie, a można było wyciąć sieciowymi :stuck_out_tongue:

**Comment by krystian3w** [comment]
Pierwszy się normalnie przewijał, drugi dociąłem jak wyskoczył, na Operze działał CSS, nie sądziłem by nie działał w Firefox, a sieciowo ma wadę jak ktoś już przeglądał stronę kiedyś aż nie zresetuje pamięci podręcznej.
