### ISSUE TITLE
aasapolska.pl

### ISSUE THREAD

**Issue by garrgul** [PolishFiltersTeam/PolishAnnoyanceFilters#1347]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

2 x popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas itp.)

1

![ss_035](https://user-images.githubusercontent.com/46375428/51084474-6d389200-172a-11e9-9e18-417c0be8656f.png) | `###leave-page-modal`
---- | ----

2

![ss_037](https://user-images.githubusercontent.com/46375428/51084482-922d0500-172a-11e9-92b4-a3cd4fc6b211.png) | `\|\|aasapolska.pl/scripts/popups.js` :question: 
---- | ----

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 3 modułów:

    Newslettery (bez wyskakujących okienek)
    Wyskakujące Okienka
    Powiadomienia Web Push

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 3 modułach.

**Comment by krystian3w** [comment]
`###leave-page-modal` - i mam przewijanie, nie wiem czy się da sieciowo.

**Comment by krystian3w** [comment]
Drugiego nie mam jak używam całe EI i może błąd z Firefox.

**Comment by krystian3w** [comment]
Jak dla mnie to starcza jeden filtr kosmetyczny, a ten plik wycina tylko jeden z dwóch pop-upów.
