### ISSUE TITLE
strefakodera.pl (2)

### ISSUE THREAD

**Issue by garrgul** [PolishFiltersTeam/PolishAnnoyanceFilters#1352]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

Reopen https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1336 bo dalej to jest.

**Comment by hawkeye116477** [comment]
@krystian3w Masz to? Bo ja nie.

**Comment by krystian3w** [comment]
Nie mam, a jak podglądam co zablokowało to jakiś inny ten krzyżyk - taki czarny w białym kole, a tamten kwadratowy na szarym tle?

**Comment by krystian3w** [comment]
Musi mieć inne ID niż: `###PopupSignupForm_0`

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/e278de34229a42401c788d14396451c7eab2dc6f/PPB/popupy.txt#L373

Ja mam taką wersje i blokuje poprawnie.

**Comment by garrgul** [comment]
Jak mi wyskoczy znowu to sprawdzę i podam nazwę ID.

**Comment by hawkeye116477** [comment]
Może `||downloads.mailchimp.com/js/signup-forms/popup/unique-methods/embed.js$domain=strefakodera.pl`.

**Comment by krystian3w** [comment]
Ja nie mam obu, a blokowanie tego skryptu ubija ten wyskakujący:

`||downloads.mailchimp.com/js/signup-forms/popup/unique-methods/2.0/popup.js`

teraz ocenić co który robi.

**Comment by garrgul** [comment]
Wyskoczyło mi znowu: `###PopupSignupForm_1`, a w filtrach dodane jest tylko` ###PopupSignupForm_0`:

<details not-open>
<summary>screenshoot</summary>

![ss_078](https://user-images.githubusercontent.com/46375428/51243865-f0a0f000-1983-11e9-81df-8cef8d624cf9.png)

</details>
<br>

![ss444](https://user-images.githubusercontent.com/46375428/51243892-02829300-1984-11e9-909c-caac09e83502.png)

**Comment by krystian3w** [comment]
Jak złapiesz jakąś 2/3 czy nie wiadomo co to chyba zmieni się na blokowanie

`/popup/unique-methods/embed.js` lub  `/popup/unique-methods/2.0/popup.js`

**Comment by hawkeye116477** [comment]
Ciekawe czy też na tych pozostałych stronach nie zrobili takiego samego numeru. Może by trzeba je ponownie sprawdzić, ewentualnie zamienić na sieciową.

**Comment by krystian3w** [comment]
`silesiasem.pl` - nie mają elementu żadnego 
`psycholog-pisze.pl` - nie kombinują
`oakywood.pl` - nie kombinują
`uap.edu.pl` - nie kombinują
