### ISSUE TITLE
blizejprzedszkola.pl

### ISSUE THREAD

**Issue by poompon** [PolishFiltersTeam/PolishAnnoyanceFilters#1359]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (~~newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas~~ itp.)

![ss_084](https://user-images.githubusercontent.com/45519946/51280935-48217900-19e1-11e9-9d75-d406bd73fe28.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 3 modułów:

Newslettery (bez wyskakujących okienek)
Wyskakujące Okienka
Powiadomienia Web Push

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 3 modułach.

**Comment by krystian3w** [comment]
Otwarte jakby się nadawało na listę reklamową a nie EI, bo jakaś reklama wewnętrzna.

**Comment by hawkeye116477** [comment]
Zewnętrzna
