### ISSUE TITLE
kegel-aj.com

### ISSUE THREAD

**Issue by poompon** [PolishFiltersTeam/PolishAnnoyanceFilters#1360]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas itp.)
podobny losowy przypadek jak tu https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1352, czyli może nie pojawić się za pierwszym razem

![ss_085](https://user-images.githubusercontent.com/45519946/51281014-8028bc00-19e1-11e9-8e52-89ea363d02d3.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 3 modułów:

Newslettery (bez wyskakujących okienek)
Wyskakujące Okienka
Powiadomienia Web Push

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 3 modułach.

**Comment by krystian3w** [comment]
Daj znać czy trzeba przerabiać teraz filtr:

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/b34fdfedde6d46ddc3ef54f8f1d9ae72c7c9892f/PPB/popupy.txt#L179

Bo może różnie stylują element.
