### ISSUE TITLE
EasyPrivacy / uBO Privacy

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters#1365]
### Typ elementu/problemu
- [X] Pytanie

### Link bezpośredni (opcjonalny)

[`https://www.travelplanet.pl/`](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.travelplanet.pl%2F%60)
[`https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/906`](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fgithub.com%2FPolishFiltersTeam%2FPolishAnnoyanceFilters%2Fissues%2F906)

### Inne ważne informacje mogące mieć znaczenie (opcjonalne):

Czy blokować elementy EI jak ktoś uważa że nie musi używać tych list, czyli na przykładzie `travelplanet.pl` efekty po użyciu:

```
@@||www.googletagmanager.com/gtm.js$script,domain=www.travelplanet.pl
@@||www.google-analytics.com/analytics.js$script,domain=www.travelplanet.pl
```

czyli mam teraz widget/pop-up kontaktowy (pośpiesznie zmieniony).

**Comment by hawkeye116477** [comment]
@krystian3w Raczej tak
