### ISSUE TITLE
nbsklep.pl

### ISSUE THREAD

**Issue by poompon** [PolishFiltersTeam/PolishAnnoyanceFilters#1367]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas/nagabywanie itp.)

![ss_087](https://user-images.githubusercontent.com/45519946/51326897-608ca480-1a70-11e9-95b4-c3876a2997d3.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 3 modułów:

Newslettery (bez wyskakujących okienek)
Wyskakujące Okienka
Powiadomienia Web Push

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 3 modułach.

**Comment by krystian3w** [comment]
Pop-up nie chce wskoczyć.

**Comment by krystian3w** [comment]
A w stopce resztka po newsletterze, którego też nie można otworzyć, chyba JS próbują generować pop-up

**Comment by hawkeye116477** [comment]
Ale pusha wyłapałem :smile:.

**Comment by krystian3w** [comment]
No jest.

**Comment by krystian3w** [comment]
`||newbalance.api.useinsider.com/views/push/js/sdk/insider-push-native-sdk.js$script,domain=nbsklep.pl`
