### ISSUE TITLE
auto50.pl [livecall.io]

### ISSUE THREAD

**Issue by poompon** [PolishFiltersTeam/PolishAnnoyanceFilters#1369]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas/nagabywanie itp.)

![ss_089](https://user-images.githubusercontent.com/45519946/51345200-b1b18e00-1a9a-11e9-8eec-b496e3795d8e.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam tylko 3 modułów:

Newslettery (bez wyskakujących okienek)
Wyskakujące Okienka
Powiadomienia Web Push

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 3 modułach.

**Comment by krystian3w** [comment]
`https://nerdydata.com/search?query=assets.livecall.io`
`https://publicwww.com/websites/assets.livecall.io/2`

Jak ktoś chce może zrobić generyki

**Comment by krystian3w** [comment]
`Livecall.io` nie podoba się blokada sieciowa, zobaczymy czy odpiszą że pozwalają w swoim pliku przemycać dowolny JavaScript.

**Comment by krystian3w** [comment]
Będzie obecnie wyciekać jak gdzieś używają generichide pod anty-adblock (sam raczej nie wyłapałem by z 12 domen go miało).
