### ISSUE TITLE
www.dobreprogramy.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1385]
### Typ elementu
~~strzałka~~
### Link bezpośredni 
`https://www.dobreprogramy.pl/chrome-android-historia-nawigacja-gesty,News,99859.html`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Opera 58.0.3135.47
**Bloker:** uBlock Origin 1.17.0
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
`###phContent_divArticle > .desktop-flex > #sidebar > .block.sticky:style(position: static !important;)`
