### ISSUE TITLE
bulldogjob.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1387]
https://bulldogjob.pl/articles/1058-dlaczego-mam-placic-za-scrum-mastera
![opera zdjecie_2019-01-25_012413_bulldogjob pl](https://user-images.githubusercontent.com/36385327/51717155-06777a80-2040-11e9-8f75-3f236ef4ae0d.png)

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [x] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by hawkeye116477** [comment]
@krystian3w A to nie do newsletterów?
