### ISSUE TITLE
nowyrp.pl

### ISSUE THREAD

**Issue by poompon** [PolishFiltersTeam/PolishAnnoyanceFilters#1396]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas/nagabywanie itp.)
nie jestem pewien czy do się powinno zaliczać do popupów / widżetów czy Widżety Kontaktowe/Informacji Zwrotnej, więc ewentualnie etykieta do poprawy, (sprawdzałem też przy włączonych modułach Inne Widżety​ i Widżety Kontaktowe/Informacji Zwrotnej i dalej to jest):

![ss_064](https://user-images.githubusercontent.com/45519946/51787323-a3d1cc00-2170-11e9-9628-160ffd29e59a.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam 5 modułów:

- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push
- AdGuard Popups
- AdGuard Push-notifications

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 5 modułach.

**Comment by hawkeye116477** [comment]
@MajkiIT Została dla ciebie reklama „Gotowe mieszkania".

**Comment by blocker999** [comment]
@hawkeye116477 Scroll do odblokowania

**Comment by hawkeye116477** [comment]
@blocker999 Już ciebie sprawdzałem i odblokowałem z 15 minut temu :smile:.
