### ISSUE TITLE
polskacanada.com

### ISSUE THREAD

**Issue by poompon** [PolishFiltersTeam/PolishAnnoyanceFilters#1398]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [x] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas/nagabywanie itp.)

![ss_067](https://user-images.githubusercontent.com/45519946/51787373-4ab66800-2171-11e9-8b29-cf903c83a210.png)

po włączeniu modułu Polskie Filtry Elementów Irytujących Newslettery - powstaję błąd - popup jest wycięty, ale zostaje tło, a w ogóle to powinno być zdaje się wycianane przez listę Popupów

![ss_066](https://user-images.githubusercontent.com/45519946/51787368-42f6c380-2171-11e9-8e39-6defaf48301a.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam 5 modułów:

- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push
- AdGuard Popups
- AdGuard Push-notifications

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 5 modułach.

**Comment by krystian3w** [comment]
`AdGuard Popups`, `AdGuard Push-notifications`  - to skąd

**Comment by krystian3w** [comment]
Jak nie wyskakuje w rogu zapraszamy to wystarczy zmiana miejsca filtrów.

**Comment by poompon** [comment]
> krystian3w : AdGuard Popups, AdGuard Push-notifications - to skąd

 Z modułów AdGuard:
https://github.com/AdguardTeam/AdguardFilters/tree/master/AnnoyancesFilter/sections

https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/sections/popups.txt
https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/sections/push-notifications.txt
