### ISSUE TITLE
kormoran-rowy.pl [2]

### ISSUE THREAD

**Issue by poompon** [PolishFiltersTeam/PolishAnnoyanceFilters#1399]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas/nagabywanie itp.)

![ss_077](https://user-images.githubusercontent.com/45519946/51804006-a3fac600-225b-11e9-993c-a990e98772ed.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam 5 modułów:

- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push
- AdGuard Popups
- AdGuard Push-notifications

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 5 modułach.

**Comment by hawkeye116477** [comment]
Tamtego już nie widzę, za to jest pop-up LiveCall.

**Comment by krystian3w** [comment]
U mnie już działa ` d(y|e)fuzer`.

**Comment by hawkeye116477** [comment]
@krystian3w Ale masz na myśli <img src="https://user-images.githubusercontent.com/45519946/51787401-af71c280-2171-11e9-9c03-aad5b913c173.png">? U mnie samo to znikało po jakimś czasie, ale jak dodałem regułę i wyczyściłem dane, to już się nie pojawiało.

**Comment by krystian3w** [comment]
Tak miałem te owoce na myśli, ręczne uaktualnienie listy już ich mi nie ładuje.

**Comment by krystian3w** [comment]
I dociąłem ten `callpage.io` sieciowo w pop-upach.

**Comment by poompon** [comment]
> hawkeye116477 : Tamtego już nie widzę, za to jest pop-up LiveCall.

Racja, pomyłka z mojej strony, chodziło mi właśnie o ten popup, a nie o tamten pierwszy, poprawiłęm pierwszy komentarz i dałem zrzut ekranu.

**Comment by krystian3w** [comment]
To za 9 minut będzie wycięty jak @circleCi nie zastrakuje.

**Comment by hawkeye116477** [comment]
@krystian3w Dopiero o 19:00, w configu godziny są podane w strefie UTC, czyli w Polsce zawsze będzie godzina do przodu :smile:

**Comment by krystian3w** [comment]
Aha, to jeszcze potestuje rozwiązanie pod AdGuard.

**Comment by hawkeye116477** [comment]
@krystian3w A te rozwiązanie w ogóle działa? Ja zdaje się testowałem kosmetyczne i zaraz po jakiejś chwili ten pop-up wracał, dlatego dodałem rozwiązanie skryptowe.

**Comment by krystian3w** [comment]
Najbardziej obawiam się odblokowania przewijania - `hidden !important;`.

Jak go nie odblokuje w Chromowatych to zostaje skrypt, bo po co coś co wytnie właściwy pop-up jak nie ma przewijania przez 30 sekund.

**Comment by krystian3w** [comment]
Na razie szkoda, że `:has()` działa za wolno - sekundowe  miganie, a przewijanie mam (jedynie zostaje redukcja zbędnych filtrów po teście z Firefox, by i  w nim było).

Ale na to pomóc może tylko przeklinanie czy używają często / aktywnie fancybox.

**Comment by hawkeye116477** [comment]
Ah, już wiem o co chodzi, w Nano Vivaldi kosmetyczna nie działa, bo nie ma userCSS. W przypadku reszty natomiast widać tylko wczytywanie.

**Comment by krystian3w** [comment]
To by można zaryzykować rezygnacje z has.
