### ISSUE TITLE
masterproject.pl

### ISSUE THREAD

**Issue by poompon** [PolishFiltersTeam/PolishAnnoyanceFilters#1405]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [x] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

Problem 1: popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas/nagabywanie itp.)

![ss_085](https://user-images.githubusercontent.com/45519946/51804418-ebd01c00-2260-11e9-8070-9b563374bf3e.png)

Problem 2: to tak przy okazji odrazu (chociaż wiem, że się nie kwalifikuje tutaj, ale może ktoś to zgłosi przy okazji na repo AdGuard albo zawoła F4Z), błąd - po włączeniu modułów ciasteczkowych jak tu: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1398#issuecomment-457843891, zawartość strony się nie ładuje:

![ss_083](https://user-images.githubusercontent.com/45519946/51804435-2e91f400-2261-11e9-9933-95a15e59d362.png)

po wyłączeniu modułu "cookies_general.txt"  strona ładuje się normalnie:

![ss_084](https://user-images.githubusercontent.com/45519946/51804442-42d5f100-2261-11e9-8051-7520ccdeada6.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam 5 modułów:

- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push
- AdGuard Popups
- AdGuard Push-notifications

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 5 modułach.

**Comment by krystian3w** [comment]
@adamwr napraw `cookies_general.txt`

**Comment by krystian3w** [comment]
@poompon  a dla ciebie raczej bezpieczniejsze było by używanie całego AdGuard Annoyance, by się nie natknąć na regułę wyłączoną komentarzem:

`!platform ()`

takiego czegoś nie naprawią.

**Comment by krystian3w** [comment]
Mnie to na Firefox po odświeżeniu znika i nie mam żadnego filtru pod to konkretnego a widzę w debugowaniu z loggera elementów dom.

**Comment by poompon** [comment]
> poompon: 
> 
> > krystian3w:
> > @poompon sprawdź czy dalej masz Pop-up i widget kontaktowy po użyciu:
> > ```
> > @@||masterproject.pl/js/jquery.cookiebar.js$script
> > ```
> 
> Tak, dalej mam.

Hmm chyba coś źle sprawdziłem, bo nie miałem włączonego modułu Widżety Kontaktowe/Informacji Zwrotnej​, w ogóle od teraz będę go miał na stałe włączonego, po włączeniu tego modułu jest git i nic już nie ma.
