### ISSUE TITLE
vwpoznan.pl + vwuzytkowepoznan.pl

### ISSUE THREAD

**Issue by poompon** [PolishFiltersTeam/PolishAnnoyanceFilters#1407]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [x] Inny element
- [] Błąd
- [x] Pytanie
- [] Ulepszenie

wewnętrzna reklama scrollująca w osobnym okienko chociaż tła nie ma więc do wyskakująceych okienek  się nie zalicza raczej, ale nie jestem pewien czy to może się zalicza do jakiś innych elementów irytujących bo w końcu ta reklama wewn. jest w osobnym okienku i jakby w formie widżetu bo wyjeżdza i wjeżdza do krawędzi (lewo <==> prawo) + scrolluje z przewijaniem (góra <==> dół).

vwpoznan.pl
![ss_089](https://user-images.githubusercontent.com/45519946/51807232-ca812700-2284-11e9-8048-6e65b750ca44.png)

vwuzytkowepoznan.pl
![ss_090](https://user-images.githubusercontent.com/45519946/51807383-665f6280-2286-11e9-82fd-60208e294016.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam 5 modułów:

- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push
- Polskie Filtry Elementów Irytujących - Widżety Kontaktowe/Informacji Zwrotnej
- AdGuard Popups
- AdGuard Push-notifications

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 5 modułach.

**Comment by poompon** [comment]
zaznaczyłem "inny element" a przypisuje "widżet", to chyba trzeba skorygować.

**Comment by krystian3w** [comment]
Bo inny element był "widgetem".

**Comment by krystian3w** [comment]
Mechanizm zgłoszeniowy przeprogramowany, tu nic innego nie widzę.

---

Jakby ktoś wypatrzył jakieś inne irytujące elementy to pisać śmiało.
