### ISSUE TITLE
wellsamed.pl

### ISSUE THREAD

**Issue by poompon** [PolishFiltersTeam/PolishAnnoyanceFilters#1408]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (reklama, chyba wewn.) 

![ss_091](https://user-images.githubusercontent.com/45519946/51807452-40868d80-2287-11e9-9277-6c721b3acf89.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam 5 modułów:

- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push
- Polskie Filtry Elementów Irytujących - Widżety Kontaktowe/Informacji Zwrotnej
- AdGuard Popups
- AdGuard Push-notifications

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 5 modułach.

**Comment by krystian3w** [comment]
Jakby ktoś wypatrzył jakieś inne irytujące elementy to pisać śmiało.
