### ISSUE TITLE
planeta-budowlana.pl

### ISSUE THREAD

**Issue by poompon** [PolishFiltersTeam/PolishAnnoyanceFilters#1409]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (reklama wewn. typu karuzela :+1:) 

<ul>

1 |
--- |
![ss_092](https://user-images.githubusercontent.com/45519946/51807534-492b9380-2288-11e9-8751-8e998c0b92fd.png) |

<details> <summary> zrzuty ekranu </summary><br>

2 |
--- |
![ss_093](https://user-images.githubusercontent.com/45519946/51807535-492b9380-2288-11e9-999d-b00e1d0e09d7.png) |

3 |
--- |
![ss_094](https://user-images.githubusercontent.com/45519946/51807536-49c42a00-2288-11e9-8259-05921886a4ce.png) |

4 |
--- |
![ss_095](https://user-images.githubusercontent.com/45519946/51807537-49c42a00-2288-11e9-8c9e-10fb92190024.png) |

5 |
--- |
![ss_096](https://user-images.githubusercontent.com/45519946/51807538-49c42a00-2288-11e9-93d2-ef71ea584903.png) |

6 |
--- |
![ss_097](https://user-images.githubusercontent.com/45519946/51807539-4a5cc080-2288-11e9-9907-c2adc3255cb8.png) |

</details><br>
</ul>

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam 5 modułów:

- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push
- Polskie Filtry Elementów Irytujących - Widżety Kontaktowe/Informacji Zwrotnej
- AdGuard Popups
- AdGuard Push-notifications

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 5 modułach.

**Comment by krystian3w** [comment]
@poompon teraz tylko wyrównuje do prawej, a pomysł z chowaniem tylko pozostałych lepszy! :+1:

**Comment by krystian3w** [comment]
Jakby ktoś wypatrzył jakieś inne irytujące elementy to pisać śmiało.

**Comment by hawkeye116477** [comment]
@krystian3w On już nie odpisze, :banana: dostał, bo był bardzo niegrzeczny.
