### ISSUE TITLE
wysokienapiecie.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1418]
Po jakimś czasie na stronie nie da się w nic kliknąć. Podejrzewam, że coś ma tutaj związek z zablokowanym popup.

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [x] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
`##.modal` ale umiem odtworzyć po kliknięciu w link "Newsletter.
