### ISSUE TITLE
sklep.grupamagnum.eu

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1419]
### Typ elementu
push
### Link bezpośredni 
`https://sklep.grupamagnum.eu`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Opera 58.0.3135.47
**Bloker:** uBlock Origin 1.18.2
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Push.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
@krystian3w No, nakombinowali, każdy skrypt importuje kolejny :smiley:
Ale chyba to styknie => `grupamagnum.eu##+js(abort-on-property-read.js, Notification.requestPermission)`.

**Comment by krystian3w** [comment]
Niby logowanie Google działa, dociąć można newsletter:

```
##.leftcol > #box_custom81 > center  > iframe[src^="https://media-grupamagnum.ipresso.pl"]
```

A farmerem nie jestem więc raczej nic tam nie kupię.
