### ISSUE TITLE
pl.globalvoices.org

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1421]
![opera zdjecie_2019-02-02_044632_pl globalvoices org](https://user-images.githubusercontent.com/36385327/52159510-a8810d80-26a5-11e9-88e7-f32b45e858fe.png)

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by hawkeye116477** [comment]
O 15:00 będzie aktualizacja.
