### ISSUE TITLE
ozonee.pl

### ISSUE THREAD

**Issue by pomidoor** [PolishFiltersTeam/PolishAnnoyanceFilters#1430]
### Typ elementu/problemu
- [x] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas/nagabywanie itp. (widżet)

![anim 001](https://user-images.githubusercontent.com/44265754/52296809-8c1ff200-297f-11e9-8f37-f4786e171331.gif)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam 6 modułów:

- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push
- Polskie Filtry Elementów Irytujących - Widżety Kontaktowe/Informacji Zwrotnej
- AdGuard Popups
- AdGuard Push-notifications

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 6 modułach.

**Comment by krystian3w** [comment]
Na moje to już to coś wycina.

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/df06181d969056e637dfc9504282b959c932a229/PPB/widgety.txt#L329

**Comment by krystian3w** [comment]
To chyba jakiś bug z 2017?

**Comment by krystian3w** [comment]
@hawkeye116477  / @blocker999  ja to `#tws_i_3` przeniosłem do filtrów `newslettery_nie_popupy.txt` jak coś.
