### ISSUE TITLE
modyfikatory tytułów stron - "wróć do" / "wróć na"

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters#1431]
### Typ elementu/problemu

- [x] Pytanie
- [x] Ulepszenie

### Inne ważne informacje mogące mieć znaczenie (opcjonalne):

Takie coś namierzamy w skryptach strony czy olać np.:

`https://www.picodi.com/pl/`
`https://bludshop.com`

Jak dla mnie problem to w ogóle namierzyć jakby każdy robił własnym kodem JavaScript.

**Comment by hawkeye116477** [comment]
Sam nie wiem, ja to zwykle olewałem. A co @blocker999 o tym sądzi?

**Comment by blocker999** [comment]
@hawkeye116477 poco taka ingerencja ?

**Comment by krystian3w** [comment]
Trochę może ludzi denerwuje z 5 takich samych zakładek a niby w każdej coś innego a oni podmieniają na "wróć...".

**Comment by krystian3w** [comment]
Za dużo roboty i trzeba sprawdzać czy połowa strony nie padła.
