### ISSUE TITLE
bogulandia.pl

### ISSUE THREAD

**Issue by pomidoor** [PolishFiltersTeam/PolishAnnoyanceFilters#1432]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas/nagabywanie itp.)

![ss_001](https://user-images.githubusercontent.com/44265754/52399755-68fb5c80-2abd-11e9-907c-a9a1ad565fb2.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam 6 modułów:

- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push
- Polskie Filtry Elementów Irytujących - Widżety Kontaktowe/Informacji Zwrotnej
- AdGuard Popups
- AdGuard Push-notifications

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 6 modułach.

**Comment by krystian3w** [comment]
Mnie z całym EI bez AdGuard na razie nie wyskakuje.

**Comment by krystian3w** [comment]
Umiem złapać na:

https://www.bogulandia.pl/newsletter.php?msg=mailing_maileregerror&mail=Podaj+sw%C3%B3j+adres+e-mail&name=

`bogulandia.pl###tws_i_1`
