### ISSUE TITLE
finanse.wp.pl

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters#1433]
Też wam miga domek "dodaj wp"  na stronę startową:

![ezgif com-crop](https://user-images.githubusercontent.com/35370833/52539958-5d8d8700-2d84-11e9-9f39-c9c1305672a7.gif) |
--- |

https://finanse.wp.pl/pomysl-na-biznes-kawiarnia-dla-influencerow-6347893885458049v

![ezgif com-crop 1](https://user-images.githubusercontent.com/35370833/52540184-03da8c00-2d87-11e9-950c-8e8962799f98.gif) |
--- |

**Comment by krystian3w** [comment]
```css
wp.pl##div[class][data-reactid] > div[class=""][data-reactid] > div[class][style][data-reactid] > div[data-st-area="Header"] > div > button[title="Ustaw WP jako stronę startową"]
wp.pl##div[class][data-reactid] > div[class=""][data-reactid] > div[class][style][data-reactid] > div[data-st-area="Header"] > div > button[title="Ustaw WP jako stronę startową"] ~ div
```

**Comment by krystian3w** [comment]
@gwarser zerkniesz co buguje sprawdzanie wielu parametrów CSS?

```
##div[class^="_"]:matches-css(position: relative):matches-css(display: inline-block):matches-css(vertical-align: -11px)
```

**Comment by gwarser** [comment]
Czasami znika `display: inline-block`

**Comment by gwarser** [comment]
`div[class^="_"]` to nie jest zbyt wydajne, bo `matches-css` musi sprawdzić prawie 100 elementów. Może `.header>div[class^="_"]`?

**Comment by krystian3w** [comment]
I na 3 będzie lepiej?

**Comment by krystian3w** [comment]
@hawkeye116477  jak zawęzimy do szukania 3 elementów to można wywalić wykrywanie wyświetlania linowego?

```
wp.pl,~www.wp.pl##div.header > div[class^="_"]:matches-css(position: relative):matches-css(vertical-align: -11px)
```

Chyba, że to innego autora reguła.

**Comment by hawkeye116477** [comment]
`Chyba, że to innego autora reguła.`
Nie, to moje :smile:. A nie wiem, posprawdzaj, potestuj czy jest ok, ważne aby nic nie psuło i było wydajne :smile:.

**Comment by krystian3w** [comment]
Jak dla mnie to oni próbują negować teraz `display: none` i może zluzowanie nodów w ubo 1.18+ daje o tym znać. 

Jak nie ucieknie button ani ustaw to też bym sprawdził jak wolno ukrywa ABP/AdBlock.

**Comment by gwarser** [comment]
> Czasami znika `display: inline-block`

No bo przecież ukrywanie polega na ustawieniu `display: none`, a uBO przy filtrach proceduralnych patrzy na zmiany tylko jak nody wewnątrz są dodawane/usuwane, więc pewnie wp coś zmienia w tym drzewku i dlatego miga.

**Comment by krystian3w** [comment]
Jak coś to miganie idzie też odtworzyć na reście podobnych subdomen WP.

**Comment by krystian3w** [comment]
ABP tego nie łapie jak coś, filtrem:

```
wp.pl,~www.wp.pl#?#div.header > div[class^="_"]:-abp-has(button[title^="Ustaw"])
```

**Comment by krystian3w** [comment]
Ale AdBlock już obiema łapie nawet szybko.

**Comment by krystian3w** [comment]
Teraz się na chama otwiera z poprawkami AdamaWr na Anty-adblock...

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/63802478-019ae200-c913-11e9-9159-6614b122feab.png) |
--- |

```
https://wiadomosci.wp.pl/mateusz-morawiecki-o-aferze-w-resorcie-ziobro-zapowiedzial-ze-wylaczy-sie-z-tej-sprawy-6418132302161537a
```

**Comment by hawkeye116477** [comment]
@krystian3w Ja nie mam.

**Comment by krystian3w** [comment]
Mi wraca po 10 sekundach i się nagle otwiera.

**Comment by hawkeye116477** [comment]
@krystian3w Nie miga, ale jakby co to mam Ryzena :smile:.

**Comment by krystian3w** [comment]
Chyba overlay-buster robi z kodu sieczkę:

![obraz](https://user-images.githubusercontent.com/35370833/63803278-d74a2400-c914-11e9-93cd-b30356e05083.png)

**Comment by hawkeye116477** [comment]
@krystian3w Nie sprawdzałem z busterem, zresztą i tak ta reguła nadaje się do kosza.

**Comment by krystian3w** [comment]
Może na samym CSS przejdzie? ABP i tak nie dawało rady, AdBlock cudem wycinał komunikat.

**Comment by hawkeye116477** [comment]
@krystian3w Ja tego ze stroną startową w ogóle nie mam, nawet po wyłączeniu uBO.

**Comment by krystian3w** [comment]
W Firefox nie działa ten ichniejszy dodatek na podmianę "about:home" / "about:newtab"... ale crap...

**Comment by krystian3w** [comment]
Ciekawe gdzie jeszcze zmienią layout i czy w końcu wyrównają by FX i Chrome miało na money ten sam.
