### ISSUE TITLE
szybkanauka.pro

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1435]
https://szybkanauka.pro/nauka-jezykow-obcych-a-mozg/
![opera zdjecie_2019-02-12_170252_szybkanauka pro](https://user-images.githubusercontent.com/36385327/52649179-1c15ec80-2ee8-11e9-9461-675c19d405ab.png)

### Typ elementu/problemu
- [x] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Nie mam, wygląda na pop-up...

**Comment by krystian3w** [comment]
Jak coś dziwaczny pasek cookies wycięty, potem zrobi się lepszy filtr.

Dwie sekcje social też dociąłem.

**Comment by hawkeye116477** [comment]
@krystian3w A ja mam, przy pierwszej wizycie scrolluje na samą górę, gdzie jest ten newsletter, po jakimś czasie sam znika. Po za tym, jeszcze są normalne newslettery, jeśli tak można je nazwać, też o tym kursie. Także wszystkie 3 do wycięcia :smile:.

**Comment by krystian3w** [comment]
Ja wyciąłem tylko ten tęczowy przydługim filtrem.

I potem jeszcze wyłapałem 3 sekcje cookies i czy to się nie nadaje na kad:

`https://szybkanaukapro.pl/akcelerator-jezykowy/`

puste, certyfikat zły, i niby ta baba to reklamowała.

**Comment by krystian3w** [comment]
`#?##tve_editor:-abp-has(input)`

Ale trzeba zobaczyć jak to działa przy przewijaniu w górę z tym niebieskim...

**Comment by krystian3w** [comment]
Trzeba by testować czy CSS jest potrzebny i dla Nano Adblockera koniecznie skrypt, bo liniowy CSS:


```html
<body style="margin-top: 603px !important;">
```

**Comment by hawkeye116477** [comment]
No, Vivaldi ostrzega, do KADa chyba trzeba będzie dodać :smile:.

**Comment by hawkeye116477** [comment]
@krystian3w U mnie po czasie puste się wysuwa :smiley:.

**Comment by xMaap** [comment]
Ja się nie przyglądałem tej stronie jak mi to się wyświetliło to od razu tutaj dostałem. Jak szybkanaukapro.pl jest powiązany z tym szybkanauka.pro to chyba jedno i drugie bym dodał do KAD.

**Comment by krystian3w** [comment]
A wysuwa się już puste?

**Comment by hawkeye116477** [comment]
`||szybkanauka.pro/wp-content/plugins/thrive-leads/js/frontend.min.js
`

**Comment by krystian3w** [comment]
I likwiduje wszystkie 3 i nawet może pasek cookies?

**Comment by hawkeye116477** [comment]
@krystian3w Tak, nawet pasek :cookie: znika.

**Comment by krystian3w** [comment]
To może być czy bawimy się w `:-abp-has`/`contains(...)` i dodatkowo CSS/skrypt na te największe?

**Comment by krystian3w** [comment]
> A jest też niby poprawna => `https://szybkanauka.pro/akcelerator-jezykowy/`, coś tu śmierdzi.

Może z pl przeszła na pro i nie stać jej było wydawać do 100 złotych na 2 domeny...

**Comment by krystian3w** [comment]
uBO jak dla mnie daje radę z `:-abp-has(...)` nawet w trybie incognito i `:-abp-contains(...)` dla cookies.

**Comment by hawkeye116477** [comment]
`https://webcache.googleusercontent.com/search?q=cache:4pybH8TvyVkJ:https://performancemedia.pl/czy-google-kocha-marki-i-dlaczego-infografiki-sa-niebezpieczne/+&cd=15&hl=pl&ct=clnk&gl=pl` 
Z tego wynika, że gość miał 2 strony i niby ta druga była dedykowana użytkownikom Google...
