### ISSUE TITLE
OleOle! dwa SkrOle!

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters#1436]
![obraz](https://user-images.githubusercontent.com/35370833/52675069-d9730500-2f25-11e9-9cd8-381dd5a99baf.png) |
--- |

**Comment by krystian3w** [comment]
Teraz mam czasem poziomy niepotrzebnie.

**Comment by krystian3w** [comment]
@hawkeye116477 dodawać tam `.remodal-is-locked` lub `html.remodal-is-locked`? Czy róże są tam pop-upy że lepiej bez klas?

**Comment by hawkeye116477** [comment]
@krystian3w Chyba to drugie będzie lepsze.
