### ISSUE TITLE
polska-ie.com

### ISSUE THREAD

**Issue by pomidoor** [PolishFiltersTeam/PolishAnnoyanceFilters#1439]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas/nagabywanie itp.)

![ss_010](https://user-images.githubusercontent.com/44265754/52900211-74543380-31f3-11e9-8854-cf8a715cc3ed.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam 6 modułów:

- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push
- Polskie Filtry Elementów Irytujących - Widżety Kontaktowe/Informacji Zwrotnej
- AdGuard Popups
- AdGuard Push-notifications

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 6 modułach.

**Comment by krystian3w** [comment]
@MajkiIT  / @olegwukr: dla was anty adblock:

![obraz](https://user-images.githubusercontent.com/35370833/52911374-5219ee80-32a3-11e9-81ec-ed8000e9e3eb.png) |
--- |

**Comment by krystian3w** [comment]
Mnie ten właściwy pop-up zgłoszenia za szybko ucieka by go wyciąć kosmetycznie.

**Comment by pomidoor** [comment]
krystian3w czy mogę ci jakoś pomóc, napisz mi co mam zrobić.

**Comment by krystian3w** [comment]
Najlepiej zamrozić go lub znaleźć w jakimś pliku js  / zrządaniu xhr?

**Comment by pomidoor** [comment]
Nie da rady, te kosmetyki co dodałeś działają,

**Comment by krystian3w** [comment]
To około 19 będzie wycinany w uBO / suplementach.

**Comment by krystian3w** [comment]
Co do anty-adblock to nie mam na to wpływu a też nie mam ochoty np. na kilka razy zgłaszać jak będzie umykać naprawa tego.
