### ISSUE TITLE
monikahonory.pl

### ISSUE THREAD

**Issue by pomidoor** [PolishFiltersTeam/PolishAnnoyanceFilters#1445]
### Typ elementu/problemu
- [x] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

newsletter na dole

![ss572](https://user-images.githubusercontent.com/44265754/52914229-3247f200-32c6-11e9-948b-b064443665af.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam 6 modułów:

- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push
- Polskie Filtry Elementów Irytujących - Widżety Kontaktowe/Informacji Zwrotnej
- AdGuard Popups
- AdGuard Push-notifications

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 6 modułach.

**Comment by krystian3w** [comment]
Co ci blokuje taki popup:

![obraz](https://user-images.githubusercontent.com/35370833/52914395-ed24bf80-32c7-11e9-9e25-2505564e9f1d.png) |
--- |

**Comment by pomidoor** [comment]
> krystian3w: Co ci blokuje taki popup:

Fanboy's Social Blocking List.

**Comment by krystian3w** [comment]
To znowu mi wyciekł...

**Comment by pomidoor** [comment]
Edytowałem komentarz, pewnie w momencie gdy odpisywałeś... poprawiłem na Fanboy's Cookie List.

**Comment by krystian3w** [comment]
OK `##[div=data-no-convert-cookies] troubles...

**Comment by pomidoor** [comment]
Nom, ten ich globalny, dużo wyłapuje.

**Comment by krystian3w** [comment]
To jak coś minimalizuję, na Fanboya nic nie wpłynie jak sam nie robi jakiś testów czym ten generyk zastąpić...
