### ISSUE TITLE
atat.pl

### ISSUE THREAD

**Issue by pomidoor** [PolishFiltersTeam/PolishAnnoyanceFilters#1453]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas/nagabywanie itp.)
nie jestem pewien czy to kwalifikuje się na ten tracker czy do wewnętrznych

![ss_032](https://user-images.githubusercontent.com/44265754/53013667-9f829100-3446-11e9-8393-127f010e2d54.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam 6 modułów:

- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push
- Polskie Filtry Elementów Irytujących - Widżety Kontaktowe/Informacji Zwrotnej
- AdGuard Popups
- AdGuard Push-notifications

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 6 modułach.

**Comment by hawkeye116477** [comment]
A to ciekawe, bo ja tam nic nie mam, no chyba, że @krystian3w już to dodał i zapomniał oznaczyć.

**Comment by krystian3w** [comment]
Ja też nie mam, trzeba by się przerzucić na moduły i niezalecaną opcje subskrypcji AdGuarda.

**Comment by krystian3w** [comment]
Albo mam np.: `https://www.oswietlenie-atat.pl/`

![obraz](https://user-images.githubusercontent.com/35370833/53053730-7859ad00-34a2-11e9-8ebb-e0377507fc3b.png) |
--- |

**Comment by krystian3w** [comment]
Dodatkowo jakby RODO blokowało przewijanie, widać po 3 miesiącach dodali blokowanie przewijania...

**Comment by pomidoor** [comment]
Na pełnych EI to ja też tego nie mam (na atat.pl), ale na moich modułach to jest (mówię o sytuacji sprzed powyższych commitów), przyczyna jest taka, że filtr, który to wycina (`atat.pl###exitpopup, #exitpopup_bg`) leży z nieznanych mi przyczyn w sekcji/module "Inne widżety", którego nie używam, zamiast w "Wyskakujące Okienka", którego używam, a przecież to jest popup i nazywa się `exitpopup` więc pytanie dlaczego jest w sekcji "Inne widżety", chyba przez pomyłkę, bo jak widać po powyższych commitach teraz nowe filtry poszły już do sekcji "Wyskakujące Okienka", a skoro tak to ten filtr `atat.pl###exitpopup, #exitpopup_bg` to zdaje się można w takim razie usunąć z "Inne widżety" bo dalej tam siedzi.

**Comment by hawkeye116477** [comment]
Ok, zrobione, aktualizacja będzie o 15 :smile:.
