### ISSUE TITLE
Poszatkowane filtry

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters#1463]
* `https://filters.adtidy.org/extension/android-content-blocker/filters/237.txt`

* `https://filters.adtidy.org/ios/filters/237.txt`

Jak zrobiłem porównanie z filtrami dla np. Firefox:

`https://filters.adtidy.org/extension/firefox/filters/237.txt`

to serwer sobie wyrwał połowicznie filtry na np. pop-upy i usunął naprawy przewijania / usunięcia rozmazania / przezroczystości.

Tak na wypadek jakby gdzieś się coś przyblokowało z ograniczeń technologicznych.

---

Nie badałem na ile pop-upy wyskakują na Androidzie ani tym bardziej na iOS :iphone: z ograniczeniami technologicznymi.

**Comment by hawkeye116477** [comment]
No to trzeba będzie dołożyć warunek `!+ NOT_PLATFORM(ext_safari, ext_android_cb, ios)` do całego supplementu.

**Comment by krystian3w** [comment]
Tylko uważaj na uBO, bo nagle przy dwóch zmiażdżonych warunkach będzie ten drugi ignorować - nagle zniknie sens np. `popupy-userCSS.txt`.

**Comment by hawkeye116477** [comment]
A no to faktycznie może być problem. Niby można jeszcze dodać `!+ NOT_PLATFORM(ext_safari, ext_android_cb, ios)`, ale pewnie to w tym przypadku nie przejdzie. A inaczej też raczej to nie rozwiążemy, no chyba, że gorhill naprawi zagnieżdżone warunki albo ameshkov zrobi tak, by ten ich kompilator sam dodawał dyrektywy, żeby includowane listy nie działały w ACB.

**Comment by krystian3w** [comment]
Coś przeczuwam że by wymusili na nas ukrywanie CSS-em pop-upa zamiast filtrem ABP.

**Comment by hawkeye116477** [comment]
No tak też można, ale ja tam myślę raczej, że może trzeba napisać do gorhilla, by ogarnął zagnieżdżone warunki, bo AG to naprawił, to teraz chyba kolej na uBO :smile:. 
No jeszcze ewentualnie moglibyśmy zrezygnować z oddzielnych reguł, ale raczej to nie wchodzi w grę, bo o ile specjalne dla FF można byłoby usunąć, to znowu dla Nano muszą zostać.

**Comment by krystian3w** [comment]
Ale to też nic w sumie nie da, bo nagle się walnie w przestarzałych wersjach uBO, może jednak trzeba by to pchać w AdGuard, może powinni dodać wykrywanie że CB / iOS nie mają html filteringu czy np. userCSS?

**Comment by hawkeye116477** [comment]
Stare nie wspieramy. 
`może powinni dodać wykrywanie że CB / iOS nie mają html filteringu czy np. userCSS?`
Raczej to nic nie da, bo są też normalne reguły przecież. Musieliby raczej zrobić tak, by dokładać warunek, by includowana lista nie była dla AG CB/iOS/Safari.

**Comment by krystian3w** [comment]
Safari 1.X "extension" używa listy iOS, a dopiero 2.x/3.x to:

`https://filters.adtidy.org/extension/filters/safari/237.txt` :question:

**Comment by hawkeye116477** [comment]
@krystian3w Nie wiem, nie posiadam Maca ani iPhona. Jestem zwolennikiem Androida i mam Xiaomi :smile:.

**Comment by krystian3w** [comment]
```diff
!
! Otagowane linki wewnętrzne w artykułach
!
!
! Popupy
+!
+!
! Popupy - specjalne instrukcje
```

Chyba ten pierwszy if działa.

**Comment by hawkeye116477** [comment]
@krystian3w Tego nie możemy dodać `!#if (!adguard_ext_android_cb && !adguard_ext_safari && !adguard_app_ios)`, bo wtedy problem jest w uBO, że resztę warunków olewa.

**Comment by krystian3w** [comment]
przecież usunąłem jakieś 10 minut później.

**Comment by hawkeye116477** [comment]
@krystian3w A skąd, zostało, nie trafiło do GH, więc ja usunąłem 20 minut temu :smile:

**Comment by krystian3w** [comment]
A dziwne, sprawdzałem na vivrehome i potem juz nie wycinało popupu...

**Comment by krystian3w** [comment]
Problem niby naprawiony: https://github.com/gorhill/uBlock/commit/de41c1bf533d7a58400ea91f8361620912375bb1

**Comment by krystian3w** [comment]
na razie łagodne poprawki w plikach pod AdGuard 
* https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/49eddaf6d754df1a2a2755b0381f27112cda0970 + https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/6fb8c2b6d6799389035ac6c8ed25bcb6172e12b3
* https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/65de878df36e3d9449c71ae6c4cafeed451d4770

**Comment by krystian3w** [comment]
Jakby to naprawiać tylko w template to raczej tylko tak na razie:

```
!#if !adguard_ext_android_cb 
!#if !adguard_ext_safari 
!#if !adguard_app_ios

! filter for modern uBlock Origin and AdGuard Adblocker / AdGuard APP (macOS, Windows, Android).
! "modern" - support `:style()` filters.

!#endif
!#endif
!#endif
```

Nie wiem czy Gorhill doda wersje skróconą do nawiasu.
