### ISSUE TITLE
justjoin.it

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1464]
![opera zdjecie_2019-02-20_103043_justjoin it](https://user-images.githubusercontent.com/36385327/53081242-b84c7e80-34fa-11e9-8fee-7a3b5048a88c.png)

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [ ] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by hawkeye116477** [comment]
Dodane, aktualizacja będzie o 15.
