### ISSUE TITLE
cieplikpodrozuje.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1465]
![opera zdjecie_2019-02-23_130931_cieplikpodrozuje pl](https://user-images.githubusercontent.com/36385327/53286285-690d8480-376c-11e9-9c74-880516eb77d3.png)

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
:ice_cream:  :snowflake:  :snowman: :snowman_with_snow: :snowboarder:

**Comment by krystian3w** [comment]
Zniknie po 19.
