### ISSUE TITLE
jakdojade.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1531]
![opera zdjecie_2019-03-07_120122_jakdojade pl](https://user-images.githubusercontent.com/36385327/53952351-cb517800-40d0-11e9-8f3c-a8dbeba980c2.png)

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by hawkeye116477** [comment]
@krystian3w Jest ok, zamykamy :smile:
