### ISSUE TITLE
teraz-wilanow.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1532]
http://teraz-wilanow.pl/stanislawa-celinska-koncert-koled-i-pastoralek/
![opera zdjecie_2019-03-08_094603_teraz-wilanow pl](https://user-images.githubusercontent.com/36385327/54017671-02826080-4187-11e9-8751-8779b725b786.png)

### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [ ] Widżet kontaktowy/informacji zwrotnej
- [] Wyskakujące okienko (popup)
- [x] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Od kiedy to wigdget kontaktowy?
