### ISSUE TITLE
dobre-driny.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1536]
### Typ elementu
popup
### Link bezpośredni 
`http://www.dobre-driny.pl/Suzie-Taylor,235.html`
### Moja konfiguracja 
**System operacyjny:** Linux
**Przeglądarka internetowa:** Google Chrome 71
**Bloker:** Nano Adblocker 1.0.0.89
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
`qwww.dobre-driny.pl#@##newsletter:not(.modal)`

**Comment by krystian3w** [comment]
`dobre-driny.pl###newsletter > *`
