### ISSUE TITLE
zaradnyfinansowo.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1537]
https://zaradnyfinansowo.pl/co-to-jest-indywidualne-konto-emerytalne/
![Opera Zdjęcie_2019-03-12_221139_zaradnyfinansowo pl](https://user-images.githubusercontent.com/36385327/54236484-e9293d80-4513-11e9-964d-14a48558f16a.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Inny element (np. `następny artykuł`)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
`||zaradnyfinansowo.pl/wp-content/cache/min/1/wp-content/plugins/wp-subscribe-pro/assets/js/magnificpopup-*.js$script,first-party`

**Comment by krystian3w** [comment]
Niby ładnie pop-up ubija ale może ubiłem zły plik i kolejny się nie wykonuje...

**Comment by krystian3w** [comment]
@hawkeye116477  chyba usunęli ten plik po 3 miesiącach?
