### ISSUE TITLE
Plik wyjątków niedopoprogramowany

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters#1538]
### Typ elementu
błąd

### Dodatkowe informacje mogące mieć znaczenie

skrypt nie widzi zmian w tym pliku i trzeba na siłę poprawić jakiś inny by wysłać i zrobiło się RTM.

**Comment by hawkeye116477** [comment]
To raczej trzeba tutaj poprawić => `https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/master/scripts/VICHS_auto.sh`, a tak właściwie dopisać.

**Comment by krystian3w** [comment]
W sensie że jako osobny if lub doczepić się do każdego jako kolejny warunek?

**Comment by hawkeye116477** [comment]
@krystian3w Doczepić do każdego. Tak jak zrobiłeś, raczej powinno być ok :smile:
