### ISSUE TITLE
xyz.xyz

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1539]
### Typ elementu
popup
### Link bezpośredni 
`https://xyz.xyz`
### Moja konfiguracja 
**System operacyjny:** Linux
**Przeglądarka internetowa:** Google Chrome 73.0
**Bloker:** Adblock Plus 3
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
test.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
I jak on to podwójnie zamyka :rofl:
