### ISSUE TITLE
tokfm.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1542]
### Typ elementu
scrollujący filmik
### Link bezpośredni 
`http://www.tokfm.pl/Tokfm/7,130517,23739904,rodo-sparalizuje-wybory-samorzadowe-ministerstwo-cyfryzacji.html`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Vivaldi 2.3.1440.60
**Bloker:** Nano Adblocker 1.0.0.92
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
@adamwr / @f4z doblokujecie to w AdGuardzie?

**Comment by AdamWr** [comment]
Tak, ale prawdopodobnie jutro.
Swoją drogą, wydaje mi się, że na stronie `gazeta.pl` zmienił się odtwarzacz/używają różnych odtwarzaczy(?) i ta reguła może już nie działać, ale możliwe, że się mylę.
Na przykład tutaj:
http://wiadomosci.gazeta.pl/wiadomosci/7,114883,24548342,episkopat-przedstawil-raport-dot-pedofilii-w-kosciele-382.html

Reguła z `ONTVshowMiniature` powinna działać:
`##+js(set-constant.js, ONTVshowMiniature, noopFunc)`

Dzięki za "zawołanie".

**Comment by krystian3w** [comment]
Mnie działa jeszcze ta stara, wideo się nie odtwarza na starcie to i nie ma przewijania.
