### ISSUE TITLE
retailnet.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1543]
![Opera Zdjęcie_2019-03-16_020355_retailnet pl](https://user-images.githubusercontent.com/36385327/54468714-cc993980-478f-11e9-8f4e-7f461568a5bd.png)

### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Inny element (np. `następny artykuł`)
- [ ] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Strasznie duże, to na moim monitorze, może do pop-upów?

**Comment by hawkeye116477** [comment]
Trochę duże, ale jest z boku i nie ma kurtyny, więc chyba jednak do widgetów.

**Comment by xMaap** [comment]
@krystian3w @hawkeye116477 
![Opera Zdjęcie_2019-03-16_235726_retailnet pl](https://user-images.githubusercontent.com/36385327/54482662-653ec080-4847-11e9-8ab4-ae35cdcae42f.png)

**Comment by krystian3w** [comment]
`##.elementor-popup-modal.dialog-widget`
