### ISSUE TITLE
polomarket.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1544]
![Zrzut ekranu z 2019-03-16 02-05-53](https://user-images.githubusercontent.com/36385327/54468738-141fc580-4790-11e9-8d0e-68fa6384f8fe.png)

### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Inny element (np. `następny artykuł`)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [x] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
@majkiIT, to wycina klasa `##.advert`

więc na swojej liście powinieneś dodać: `###layer_box`

Chyba, że uznajemy to @hawkeye116477 jako reklamę wewnętrzną, bo promują nowe wydanie swojej gazetki.

**Comment by hawkeye116477** [comment]
@krystian3w No raczej to wewnętrzna reklama.
