### ISSUE TITLE
delikatesy.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1546]
![Zrzut ekranu z 2019-03-17 02-22-38](https://user-images.githubusercontent.com/36385327/54483890-cec8ca00-485b-11e9-9706-4e5aaffbea4a.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [ ] Powiadomienie push
- [] Scrollujący filmik
- [] Inny element (np. `następny artykuł`)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Push nie ma, to geolokalizacja, tego nie ubijamy, niby Polskie prawo zabrania 🤣.

Nie wiem czy ktokolwiek ubija, nawet listy do ochrony prywatności się nie kwapią.

**Comment by krystian3w** [comment]
@hawkeye116477  co myślisz o blokowaniu pop-upa po odrzuceniu zgody na geolokalizacje, wyskakuje taki brzydki systemowy "nie udało nam się ustalić twojej lokalizacji", jak nie rozwala mapki to może da się go wyeliminować, na tyle chyba będzie bezpiecznie.

**Comment by hawkeye116477** [comment]
@krystian3w Czy ja wiem, może lepiej zostawić.
