### ISSUE TITLE
intermarche.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1547]
![Zrzut ekranu z 2019-03-17 02-25-33](https://user-images.githubusercontent.com/36385327/54483902-fae44b00-485b-11e9-81c5-44a0bed855c3.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [ ] Powiadomienie push
- [] Scrollujący filmik
- [] Inny element (np. `następny artykuł`)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Nie umiem wyciąć by youtube nie zaczęło ryczeć, trzeba by sięgnąć po skrypt lub sieciowo ubić pop-upy.

**Comment by krystian3w** [comment]
Wyciąłem pop-up w Firefox html filteringem a reszta potrzebuje skryptu lub sieciówki.

**Comment by krystian3w** [comment]
Podsumowując, trzeba by znaleźć jakąś lepszą metodę i push okazał się jak dla mnie geolokalizacją - nie zablokujemy tego.

**Comment by xMaap** [comment]
To można już zamknąć?

**Comment by krystian3w** [comment]
No myślę, że mogę zamknąć, nikt raczej nie wymyśli czegoś lepszego a to przynajmniej działa w Adblock Plus / AdBlock i raczej tylko jedno wideo odtwarza - trzeba by go może w artykule poszukać jak napisali jakiś.
