### ISSUE TITLE
autokult.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1549]
Ale nie potrafię powiedzieć kiedy to się pojawia
![Opera Zdjęcie_2019-03-20_225213_autokult pl](https://user-images.githubusercontent.com/36385327/54721717-fe7d1800-4b62-11e9-9cb4-ca2421021a6a.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
A mam, po wyciu i powrocie przykładowo.

**Comment by xMaap** [comment]
@krystian3w 
![Opera Zdjęcie_2019-03-21_134806_autokult pl](https://user-images.githubusercontent.com/36385327/54753018-4726e680-4be0-11e9-9398-bd8c259fcbdd.png)

**Comment by krystian3w** [comment]
Za jakieś 48 minut będzie wycinane (plus wymuszenie aktualizacji w Nano), chyba że zmienili ID.
