### ISSUE TITLE
planeta.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1550]
### Typ elementu
newsletter,inny element
### Link bezpośredni 
`https://www.planeta.pl/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 73
**Bloker:** uBlock Origin 1.18.8
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
czerwony dzwonek

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Jak dla mnie to nie ma newslettera, inny element do szukania z lupą?

**Comment by krystian3w** [comment]
Za 17 minut powinno być blokowane.
