### ISSUE TITLE
reddit.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1551]
### Typ elementu
push
### Link bezpośredni 
`https://www.reddit.com/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 66.0.1
**Bloker:** Nano Adblocker 1.0.0.97
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
Częściowo pomoże => `reddit.com##+js(abort-on-property-read.js, Notification.requestPermission)`, tzn. zostanie kurtyna.

**Comment by krystian3w** [comment]
A kurtynę w popupach?
