### ISSUE TITLE
invimed.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1552]
![Opera Zdjęcie_2019-03-24_010846_purellafood pl](https://user-images.githubusercontent.com/36385327/54873186-823c3c00-4dd1-11e9-972f-78e793a0d9a1.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by hawkeye116477** [comment]
Nic tam nie widzę, a na pewno to ta strona czy jednak pomyłka?

**Comment by xMaap** [comment]
@hawkeye116477 Tak pomyłka chodziło o http://purellafood.pl

**Comment by krystian3w** [comment]
to około jedenastej już powinien być wycinany po aktualizacji filtrów.
