### ISSUE TITLE
polskieradio.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1558]
![Opera Zdjęcie_2019-03-27_013912_www polskieradio pl](https://user-images.githubusercontent.com/36385327/55042309-32f44680-5031-11e9-86bd-dd5549860ba1.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Zniknie za jakieś 41 minut z aktualizacją.
