### ISSUE TITLE
tanienurkowanie.pl

### ISSUE THREAD

**Issue by pomidoor** [PolishFiltersTeam/PolishAnnoyanceFilters#1561]
### Typ elementu/problemu
- [] Newsletter (nie popup)
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Powiadomienie push
- [] Scrollujący filmik
- [] Strzałka
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Wyskakujące okienko (popup)
- [] Inny element
- [] Błąd
- [] Pytanie
- [] Ulepszenie

2 x popup

 1_ popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas/nagabywanie itp.) 
![ss_010](https://user-images.githubusercontent.com/44265754/55221634-342c9b80-520a-11e9-8a5e-914221b2b6a4.png)

 2_ popup (newsletter/subskrybcja/zapisz się/polub nas/dołącz do nas/nagabywanie itp.) 
![ss_009](https://user-images.githubusercontent.com/44265754/55221572-0ba4a180-520a-11e9-9c69-26d640338dd9.png)

(Póki co zgłaszam tylko takie elementy, więc jeśli na stronie znajdą się jeszcze jakieś inne elementy do zgłoszenia, to niech inni się nimi zajmują, ja się innymi elementami na razie nie zajmuję.), używam 7 modułów:

- Newslettery (bez wyskakujących okienek)
- Wyskakujące Okienka
- Powiadomienia Web Push
- Polskie Filtry Elementów Irytujących - Widżety Kontaktowe/Informacji Zwrotnej
- Polskie Filtry Elementów Irytujących - Inne Widżety
- AdGuard Popups
- AdGuard Push-notifications

więc jeśli czasem zdarzy się, że coś u kogoś się nie pojawia bo ma włączone inne moduły lub całą listę EI to niech spróbuje tylko na tych 7 modułach.

**Comment by krystian3w** [comment]
to drugie raczej nie łapie się u nas na pop-up, AdGuard nawet te wysuwane obecnie ukrywa jako pop-py.

**Comment by krystian3w** [comment]
Popup jakby blokowało:

```
||forms2.fcc-online.pl/public/static/js/sitecall.js
```

?
