### ISSUE TITLE
new.reddit.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1562]
### Typ elementu
błąd
### Link bezpośredni 
`https://www.reddit.com/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 68.0a1 
**Bloker:** uBlock Origin 1.18.13.0
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
Jest tego więcej ale wyłączając wszystkie pozostałe kombinacje tylko "Filtry Elementów Irytujących" powoduje problemy
### Dodatkowe informacje mogące mieć znaczenie
Po włączeniu filtra "Polskie Filtry Elementów Irytujących" brakuje możliwości sortowania komentarzy "TOP"
Jeżeli sortowanie "TOP" jest akurat aktywne to cały combobox "ucieka" w nieprawidłowe miejsce na stronie przy próbie rozwinięcia go.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by kulmegil** [comment]
Problem dotyczy przygotowywanego wciąż nowego layout'u storny: new.reddit.com

Przykładowy link:
https://new.reddit.com/r/Polska/comments/8d49wm/

Nie tylko sortowanie komentarzy jest zepsute ale linków także:
![Reddit - broken links sorting](https://user-images.githubusercontent.com/570575/55439459-f1b9e480-55a4-11e9-85ce-b145678dea8b.png)

**Comment by krystian3w** [comment]
Dasz radę zrobić analizę jaki filtr psuje, bo może filtr na push jest zbyt agresywny?

**Comment by krystian3w** [comment]
Dobra mam winnego, trzeba inny filtr na przycisk "przewiń do góry" 😉

**Comment by krystian3w** [comment]
Za jakieś 45 minut powinna być poprawka filtrów.

**Comment by krystian3w** [comment]
3 minuty!
