### ISSUE TITLE
pep.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1563]
![Opera Zdjęcie_2019-04-03_070641_www pep pl](https://user-images.githubusercontent.com/36385327/55454173-1cc12a00-55df-11e9-97d6-d8f20f4002a2.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
koło 20 powinno zniknąć, jak nie to dopiero około 24 (zmiana czasu opóźniła nam wszystko o godzinę...).
