### ISSUE TITLE
lancerto.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1564]
![Opera Zdjęcie_2019-04-03_071901_www lancerto com](https://user-images.githubusercontent.com/36385327/55454619-d240ad00-55e0-11e9-9a31-2463a7ba647b.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
koło 20 powinno zniknąć, jak nie to dopiero około 24 (zmiana czasu opóźniła nam wszystko o godzinę...).
