### ISSUE TITLE
parkiet.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1565]
https://www.parkiet.com/Portfel-fundamentalny/304039941-Efektowne-stopy-zwrotu-mozliwe-dzieki-malym-i-srednim-spolkom.html
![Opera Zdjęcie_2019-04-04_003650_www parkiet com](https://user-images.githubusercontent.com/36385327/55517754-c18c4780-5671-11e9-95c9-6e1915e66985.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Nie umiem odtworzyć.

**Comment by krystian3w** [comment]
Aktualizacja około 20.
