### ISSUE TITLE
mamopracuj.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1569]
![Opera Zdjęcie_2019-04-05_184210_mamopracuj pl](https://user-images.githubusercontent.com/36385327/55643156-bb61ac80-57d2-11e9-8915-fc1e4bbc9a61.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Aktualizacja za około 43 minuty lub jutro o 12 - @hawkeye116477  co niby teraz codziennie bumpuje pierwszą aktualizacje jak nikt nic nie edytował?

**Comment by hawkeye116477** [comment]
@krystian3w Generalnie jeżeli jest godzina 12 polskiego czasu, to on wtedy patrzy na to co było 15 godzin 58 minut temu, w przeciwnym wypadku 3 godziny 58 minut temu. Pewnie te 15,58 to trochę za dużo, także do poprawy. Wcześniej nie było o 12 aktualizacji, dlatego było ok.
