### ISSUE TITLE
haps.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1572]
http://haps.pl/Haps/7,167251,24623838,sernik-z-brzoskwiniami-klasyczne-ciasto-na-swieta-i-rodzinne.html
![Opera Zdjęcie_2019-04-07_173803_haps pl](https://user-images.githubusercontent.com/36385327/55685946-edeae100-595b-11e9-9f48-c5b12c692367.png)

### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [x] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
aktualizacja około 22.

**Comment by hawkeye116477** [comment]
A raczej o północy.
