### ISSUE TITLE
opencard.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1577]
![Opera Zdjęcie_2019-04-13_040701_www opencard pl](https://user-images.githubusercontent.com/36385327/56073294-ab813400-5da1-11e9-8935-f2dcc924e48a.png)

### Typ elementu/problemu
- [X] Wyskakujące okienko (popup)
- [ ] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
ma zaciemnienie tła więc pop-up

**Comment by krystian3w** [comment]
Jak ktoś złapie wersje z zrzutu @xMaap  to niech sprawdzi czy to też jest `###trialModal`.

**Comment by krystian3w** [comment]
Bo mnie wskoczył pop-up z newsletterem na E-MAIL a nie o karcie upominkowej.

**Comment by hawkeye116477** [comment]
@krystian3w U mnie na PC też wyskakuje ten z mailem, ale na smartfonie już z telefonem i tak, to to samo.
