### ISSUE TITLE
korzystneit.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1578]
### Typ elementu
inny element
### Link bezpośredni 
`https://korzystneit.pl/`
### Moja konfiguracja 
**System operacyjny:** Linux
**Przeglądarka internetowa:** Google Chrome 74
**Bloker:** Adblock Plus 3.5
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
masa przewijających się śmieci

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
Aktualizacja będzie o 16:00.
