### ISSUE TITLE
glejak.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1579]
https://glejak.com/nowa-terapia-optune-novocure-glejak/
![Opera Zdjęcie_2019-04-13_223030_glejak com](https://user-images.githubusercontent.com/36385327/56084967-c6a08200-5e3b-11e9-8003-122373780291.png)

### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [x] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
`glejak.com###upprev_box`

**Comment by krystian3w** [comment]
Zniknie po 24 🕛 jak uaktualnisz filtry, lub za jakieś 2 dni jak uBO zaktualizuje filtry odgórnie.
