### ISSUE TITLE
www.eobuwie.com.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1580]
### Typ elementu
push
### Link bezpośredni 
`https://www.eobuwie.com.pl/?utm_source=Onet&utm_medium=Mailing&utm_content=20190412_shopping_men&utm_campaign=Mailing`
### Moja konfiguracja 
**System operacyjny:** Mac
**Przeglądarka internetowa:** Safari 12
**Bloker:** uBlock Origin 1.14
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
push.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
Dodane. O 16:00 będzie aktualizacja :smile:
