### ISSUE TITLE
o2.pl

### ISSUE THREAD

**Issue by Barticf** [PolishFiltersTeam/PolishAnnoyanceFilters#1587]
### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [X] Błąd
- [] Pytanie
- [] Ulepszenie

### Moja konfiguracja
**Przeglądarka internetowa:**
Firefox

**System operacyjny:**
Win 7
**Bloker:**
uBlock
Nanodefender

**Używane filtry:**
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących

### Link bezpośredni (opcjonalny)
https://www.o2.pl/artykul/szejk-nie-chce-placic-za-leczenie-dziecka-zalega--mln-dolarow-6370327510697601a

### Zrzut ekranu (opcjonalny)
![Przechwytywanie](https://user-images.githubusercontent.com/32641928/56130804-33279800-5f86-11e9-8061-cde29b5ee3af.PNG)

### Inne ważne informacje mogące mieć znaczenie (opcjonalne):
Biała strona po wejściu

**Comment by hawkeye116477** [comment]
`@@||o2.pl/static/1.js`

**Comment by Barticf** [comment]
@hawkeye116477 pomogło, dzięki

**Comment by krystian3w** [comment]
To koło 20 można będzie pobrać listę z usuniętym filtrem sieciowym i można wtedy rozważyć dodany ręczny wyjątek.
