### ISSUE TITLE
wzielonej.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1589]
### Typ elementu
scrollujący filmik
### Link bezpośredni 
`https://www.wzielonej.pl/informacje/zielona-gora/nieznane-twarze-zielonej-gory-nowa-ksiazka-o-miescie/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 60.0
**Bloker:** Nano Adblocker 1.0.0.103
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
```
##html.js.cssanimations body#tie-body.post-template-default.single.single-post.postid-129721.single-format-standard.wrapper-has-shadow.block-head-4.magazine1.is-lazyload.is-desktop.is-header-layout-3.has-header-ad.has-header-below-ad.sidebar-right.has-sidebar.post-layout-3.wide-title-narrow-media.is-video-format.has-mobile-share.post-has-toggle.hide_breaking_news div.background-overlay div#tie-container.site.tie-container div#tie-wrapper div#content.site-content.container div.tie-row.main-content-row div.main-content.tie-col-md-8.tie-col-xs-12 article#the-post.container-wrapper.post-content.tie-video div#the-sticky-video.featured-area.video-is-sticky div.featured-area-inner div.tie-fluid-width-video-wrapper div.wp-video div#mep_0.mejs-container.wp-video-shortcode.mejs-video div.mejs-inner div.mejs-layers div.mejs-overlay.mejs-layer.mejs-overlay-play
```

kto poprawi...

**Comment by krystian3w** [comment]
Naprawione CSS-em.
