### ISSUE TITLE
www.jelenia-gora.policja.gov.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1590]
![Opera Zdjęcie_2019-04-17_185251_www jelenia-gora policja gov pl](https://user-images.githubusercontent.com/36385327/56306124-0a4c0200-6142-11e9-920d-d03a94759b54.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Y żałobę mają.

**Comment by krystian3w** [comment]
Poprawka o 24.
