### ISSUE TITLE
codziszjemnasniadanie.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1591]
![Opera Zdjęcie_2019-04-17_192302_codziszjemnasniadanie pl](https://user-images.githubusercontent.com/36385327/56307949-58fb9b00-6146-11e9-9f61-9e95241d6f11.png)

### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [x] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Może tylko do sociala, bo niby follow.

**Comment by hawkeye116477** [comment]
@krystian3w Tak, tylko do sociala
