### ISSUE TITLE
party.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1595]
### Typ elementu
scrollujący filmik
### Link bezpośredni 
`https://party.pl/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 60.0
**Bloker:** Nano Adblocker 1.0.0.103
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Filmik jest w prawym dolnym rogu, na stronie głównej.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Wycięło gdzie lub formularz kulawy. Niby możemy wrócić do starszych filtrów z dyfuzerem.

**Comment by krystian3w** [comment]
@adamWr / @gwarser macie może po roku pomysły?

**Comment by gwarser** [comment]
Jak kogoś bardzo wkurza na głównej, to `||party.pl/|$csp=media-src 'none'`, ale w ogóle nie da się wtedy odtworzyć - trzeba wejść w artykuł.

**Comment by krystian3w** [comment]
A no to już trochę myk z CSS i wycinaniem szarego tłs pod video bezpieczniejszy.
