### ISSUE TITLE
psy-pies.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1596]
https://psy-pies.com/artykul/affenpinscher-pinczer-malpi,112.html
![Zrzut ekranu z 2019-04-25 00-15-37](https://user-images.githubusercontent.com/36385327/56697637-8076d880-66ef-11e9-8411-8213c1bc38ad.png)

### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [x] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Lewe zostawiam, prawe zniknie po 24 🕛  jak zaktualizujesz filtry.
