### ISSUE TITLE
www.bdl.lasy.gov.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1600]
### Typ elementu
popup
### Link bezpośredni 
`https://www.bdl.lasy.gov.pl/portal/mapy`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 74
**Bloker:** uBlock Origin 1.18.16
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
4.Oficjalne polskie filtry przeciwko alertom o Adblocku
### Dodatkowe informacje mogące mieć znaczenie
Akceptacja regulaminu

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
znowu przeszło walidacje z pustym linkiem, może opcjonalnie pole do zaznaczania "nie chcę podawać gdzie wyskakakuje".

**Comment by krystian3w** [comment]
Niby akceptacja nic ważnego nie blokuje.

**Comment by hawkeye116477** [comment]
@krystian3w Bo zrzut ekranu jest opcjonalny.

**Comment by hawkeye116477** [comment]
@krystian3w Na link bezpośredni nie ma walidacji, on jest opcjonalny, bo nie zawsze jest potrzebny, czasem wystarczy ten w tytule.

**Comment by krystian3w** [comment]
Dzięki 😎
