### ISSUE TITLE
Interia.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1606]
### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [x] Scrollujący filmik
- [x] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [x] Błąd
- [] Pytanie
- [] Ulepszenie

Po scrollowaniu strony film znika
```
https://motoryzacja.interia.pl/samochody-nowe/testy/news-volkswagen-arteon-2-0-tdi-cos-wiecej-niz-design,nId,2914439
https://swiatseriali.interia.pl/newsy/seriale/na-wspolnej-385/news-na-wspolnej-zona-smolnego-umiera,nId,2982876
https://muzyka.interia.pl/wiadomosci/news-mario-szaban-wraca-posluchaj-singla-wyprowadzam-sie-z-siebie,nId,2983269
https://nt.interia.pl/technauka/news-amerykanski-turysta-wpadl-do-wulkanu-i-przezyl,nId,2979310
```
![Zrzut ekranu z 2019-05-12 19-20-41](https://user-images.githubusercontent.com/36385327/57585649-3c574680-74eb-11e9-863d-554ef729531c.png)

A tutaj scrolluje film i inne:
```
https://film.interia.pl/raporty/raport-taniec-z-gwiazdami-9/wideo/video,vId,2690814
```

![Zrzut ekranu z 2019-05-12 19-21-09](https://user-images.githubusercontent.com/36385327/57585664-67419a80-74eb-11e9-8cf7-ae0de87bf560.png)

<details> <summary> zobacz również  na "swiatkobiety.pl" - zablokowane </summary>

`http://rodzina.swiatkobiety.pl/psychologia/news-jak-dziecko-zmienia-mezczyzne,nId,2320488`
![Zrzut ekranu z 2019-05-12 19-23-03](https://user-images.githubusercontent.com/36385327/57585675-90622b00-74eb-11e9-9b42-6709d2b823c2.png)

</details>

**Comment by krystian3w** [comment]
To chyba wina braku userCSS, niestety nikt nie umiał napisać skryptu blokującego to wideo, więc skopiowałem CSS z AdGuard lub taki działający tylko z uBlock Origin.

**Comment by krystian3w** [comment]
`film.interia.pl` i `nt.interia.pl` tu niestety skrypt raczej nie pozwala na detekcje `active` / `inactive`.

**Comment by krystian3w** [comment]
AdGuardowy CSS podzielony na dwa pliki, po 24 zobaczymy czy dobrze powpisywałem w szablon i skrypt generujące nowsze listy.

Dalej nie mam pomysłu na `film.interia.pl` i `nt.interia.pl` - chyba tylko skryptowe.

**Comment by krystian3w** [comment]
@xMaap  na:
 `https://nt.interia.pl/technauka/news-amerykanski-turysta-wpadl-do-wulkanu-i-przezyl,nId,2979310`

 masz tylko uszkodzony film (niby po aktualizacji się "odbuguje") i tylko tyle?

---


W Nano Adblocker ten film będzie trochę migać paskiem odtwarzania w prawym rogu, jak by się ograniczyć do rozwiązań z samym CSSS.

**Comment by xMaap** [comment]
@krystian3w U mnie nic nie miga w rogu. Jak wracam do filmu to przez chwilę nie widać obrazu, ale szybko się pojawia.
Jeszcze mam jakiś pasek.
![Zrzut ekranu z 2019-05-13 02-41-50](https://user-images.githubusercontent.com/36385327/57590000-d2f62880-7528-11e9-9885-77726dc2c1fc.png)

**Comment by krystian3w** [comment]
No to jest właśnie ten pasek, kij wie jak go ukryć dodatkowym CSS-em (jak nie macham w prawym rogu to znika i już nie wskakuje.

**Comment by krystian3w** [comment]
Jak taki efekt nie odpowiada to zostaje najwyżej wycofanie filtrów (nie widzę szansy na cud, że będzie filtr skryptowy - chociaż plik z bazą playera łatwo dostępny) dla przeglądarek bez userCSS, widać AdGuard jakoś inaczej myśli i mu brak userCSS nie przeszkadza lub nie było to testowane.

**Comment by xMaap** [comment]
No to niech tak już zostanie.

**Comment by krystian3w** [comment]
Jak coś zostawiam otwarte aż do pomysłu jak AdamWr połączy `embeded-video-player` z nowszym `video body`.

**Comment by krystian3w** [comment]
No to AdamWr dodał jako kolejne filtry pod samą Interię i niby player nawet pomimo fajnych CSS-ów umie wygenerować się w rogu jak powinien być pełnoekranowy i to na przykładzie tego wideo z Gimperem.
