### ISSUE TITLE
ekstrastats.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1608]
http://ekstrastats.pl/31611/35-kolejka-2018-19-podsumowanie-spotkan/

Włączony filtr
![Zrzut ekranu z 2019-05-14 06-19-50](https://user-images.githubusercontent.com/36385327/57670655-8554eb00-7610-11e9-9ff5-3a538ea52266.png)
Wyłączony filtr
![Zrzut ekranu z 2019-05-14 06-20-18](https://user-images.githubusercontent.com/36385327/57670663-8d148f80-7610-11e9-900e-d713f7b327ba.png)

### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [x] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Błąd w zasysanych filtrach cookies - więc i poprawka może czekać jeszcze z 4 dni jak @hawkeye116477 zajęty
