### ISSUE TITLE
swojadroga.onet.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1611]
https://swojadroga.onet.pl/miasto-nie-spi-miasto-zyje
![Screenshot_20190522_115425](https://user-images.githubusercontent.com/36385327/58165618-6990bb00-7c88-11e9-9523-4fab7b6e7308.png)

### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [x] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
`swojadroga.onet.pl##div[class="player-mvp-wrap js-player-mvp-wrap active"]`
