### ISSUE TITLE
zaradnyfinansowo.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1612]
https://zaradnyfinansowo.pl/karta-przedplacona/
![Screenshot_20190524_190438](https://user-images.githubusercontent.com/36385327/58344745-d35ebf80-7e56-11e9-96c0-91d9e27a85d6.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Po 24 🕛  lub za dwa dni jak uBO sam ręcznie uzna że musi pobrać nowszy plik.
