### ISSUE TITLE
pl.geofumadas.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1615]
![Screenshot_20190528_164424](https://user-images.githubusercontent.com/36385327/58487491-f2679500-8167-11e9-90d4-aaa577650746.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Mam jakiś inny...

**Comment by krystian3w** [comment]
Borze, dwa się nałożyły i nie wiem który zablokował przewijanie...
