### ISSUE TITLE
wp.pl / onet.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1621]
```
https://sportowefakty.wp.pl/pilka-nozna/824673/sergio-ramos-zadluzyl-sie-przez-nieudana-inwestycje-dlatego-chce-odejsc-do-chin
https://wiadomosci.wp.pl/szokujace-porownanie-janusza-korwin-mikkego-kwasniewski-kaczynski-i-tusk-jak-hitler-6386486765725313a
https://kobieta.wp.pl/jak-wybrac-truskawki-na-ten-szczegol-musisz-zwracac-uwage-6385906337642113a
https://gwiazdy.wp.pl/tymon-tymanski-zdradzal-zone-o-wszystkim-dowiedziala-sie-z-tabloidu-6386458351748737a
https://film.wp.pl/rafal-zawierucha-ma-23-rodzenstwa-balem-sie-o-swoja-przestrzen-6385187033212545a
https://facet.wp.pl/za-kolegow-oddalby-zycie-ale-to-nie-przyjazn-tak-zostal-wyszkolony-6227428999571585a
```
![Screenshot_20190530_142922](https://user-images.githubusercontent.com/36385327/58632972-7005df00-82e7-11e9-9315-940fb56721b2.png)

<del>A tutaj ukrywa filmy po zjechaniu na dół strony

```
https://finanse.wp.pl/sezon-nad-zatoka-gdanska-rozpocznie-sie-z-opoznieniem-za-to-plaze-beda-szersze-6385831776364673a
https://opinie.wp.pl/warzecha-to-moze-byc-koniec-grzegorza-schetyny-opinia-6385456910182529a
https://wiadomosci.wp.pl/totalna-zmiana-w-pogodzie-rozleje-sie-poludniowo-wschodni-zar-6386459228371073a
```
</del>

### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [x] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [ ] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Niby kolejne po interii zbugowane z braku userCSS albo WP ataktuje w skryptowe rozwiązanie na ich dziadostwo.

**Comment by krystian3w** [comment]
`wp.pl#@#+js(set-constant.js, WP.gdpr.init, noopFunc)` @MajkiIT  trzeba to jednak wywalić a nie dopisywać kolejne domeny - wtedy wideo nie ucieka.

**Comment by krystian3w** [comment]
@hawkeye116477  nie umiem odtworzyć tych przewijanych wideo z Chrome 74 i Nano Adblocker, jakby Opera dostawała jeszcze inny kod.

**Comment by xMaap** [comment]
Pominę temat i zapytam czy można coś z tym coś zrobić? Nie wiem jakieś automatyczne przekierowanie do artykułu. Dotyczy to się Onetu i WP.
![Screenshot_20190530_193100](https://user-images.githubusercontent.com/36385327/58651500-c6881300-8311-11e9-8d0e-4c4ef4ee5c5b.png)

**Comment by krystian3w** [comment]
Ja myślę, że nie w uBO (możesz próbować szczęścia z AdGuard i może za 3 miesiące wymyślą autorski skrypt blokujący to...)- chyba że mam pytać czy norweskie portale coś takiego mają i czy `Danielon` da radę to ogarnąć w redirector.

**Comment by hawkeye116477** [comment]
Jeśli chodzi o filmik to niby jest już na liście, ale w przypadku Nano, to nie działa.

**Comment by hawkeye116477** [comment]
@krystian3w Bo to jest już na liście, tylko, że w Nano to nie działa przez brak userCSS.

**Comment by krystian3w** [comment]
A czemu w chrome nie było problemu, A/B testy?

**Comment by krystian3w** [comment]
To nie lepsze może:

`finanse.wp.pl###Player0.floating:style(visibility: hidden !important;)`

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/4c9ebe175d51dff72bca569fb71e60f6d6fde2c3/PPB/uBO_AG/scroll_film_suplement.txt#L2

chyba, że zasłania coś mimo że niewidoczne i unset  lepiej wywala poza klikalny obszar?

**Comment by hawkeye116477** [comment]
`A czemu w chrome nie było problemu`
Jak nie jak tak... Vivaldi z Nano.
No niby tak też można :smile:
