### ISSUE TITLE
niezlasztuka.net

### ISSUE THREAD

**Issue by hawkeye116477** [PolishFiltersTeam/PolishAnnoyanceFilters#1622]
### Typ elementu/problemu
- [x] Newsletter (nie popup)

### Inne ważne informacje mogące mieć znaczenie (opcjonalne):
Z prawej strony newsletter po czasie wyskakuje. Kiedyś chyba pomagało => `niezlasztuka.net##+js(setTimeout-defuser.js, i(), 99000)`, a teraz już niestety nie.
@F4z Zerkniesz?

**Comment by AdamWr** [comment]
Mógłbyś sprawdzić, czy działa jeśli zamienisz `99000` na `35000`?

`niezlasztuka.net##+js(setTimeout-defuser.js, i(), 35000)`

**Comment by hawkeye116477** [comment]
@AdamWr Działa, dzięki :smile:
