### ISSUE TITLE
bigbrother.tvn.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1623]
https://bigbrother.tvn.pl/big-brother-naj,3659,n/big-brother-tvn-7-iza-maczka-odpadla-z-programu-video,292444.html
![Screenshot_20190603_033632](https://user-images.githubusercontent.com/36385327/58770782-34059f00-85b1-11e9-9141-b9a3bf58fb48.png)

### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [x] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
`##.videoPlayerFloatEnabled.videoPlayerFloat.videoPlayer`

**Comment by krystian3w** [comment]
Inny element to taki mały element wyskakujący w rogu zachęcający do oglądania na player tego :shit:.
