### ISSUE TITLE
megazoologiczny.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1624]
![Screenshot_20190604_040619](https://user-images.githubusercontent.com/36385327/58846087-3da90880-867e-11e9-965b-3f3672d87fed.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
`megazoologiczny.pl###tws_i_100000`
