### ISSUE TITLE
rynek-rolny.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1626]
https://www.rynek-rolny.pl/artykul/prawidlowa-uprawa-ziemniakow-jadalnych-w-polsce.html
![Screenshot_20190605_165915](https://user-images.githubusercontent.com/36385327/58966856-56670a80-87b3-11e9-9e72-1fc5ecf3f778.png)

### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [x] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
aktualizacja około 20.
