### ISSUE TITLE
kobieta.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1632]
https://www.kobieta.pl/artykul/sex-stories-wszystko-co-musisz-wiedziec-o-seksie-w-ciazy
https://www.claudia.pl/15-pomyslow-na-meble-z-palet
![Screenshot_20190609_104402](https://user-images.githubusercontent.com/36385327/59156942-9b38bd00-8aa3-11e9-89fb-a51ff643b4c6.png)

### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [x] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
@adamwr sprawdź sobie potem czy AdGuard Annoyance jakoś blokuje ten player na `kobieta.pl` i `claudia.pl`.
