### ISSUE TITLE
bankier.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1633]
`https://www.bankier.pl/wiadomosc/Cyfrowy-Polsat-zwiekszy-udzial-w-Premium-Mobile-do-25-proc-w-zamian-za-a2mobile-7619643.html`
![Screenshot_20190609_125711](https://user-images.githubusercontent.com/36385327/59158137-32a70b80-8ab6-11e9-86cb-744ac2abfa03.png)

### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [x] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Przebudowali sobie player:

```
##.onnetworkplayercontainer.miniature > .alwplayer
```

**Comment by krystian3w** [comment]
OK, to będzie blokowane nowym filtrem i skryptem od @adamwr.
