### ISSUE TITLE
medipartner.pl

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters#1634]
`http://www.medipartner.pl/oferta/medycyna-pracy/`

### Typ elementu/problemu
- [X] Widżet kontaktowy/informacji zwrotnej

---

Czy to się nadaje do wycinania:

 > ![obraz](https://user-images.githubusercontent.com/35370833/59159984-49a72700-8ad1-11e9-84c2-fe237e64e4af.png)

PS. ich RWD  kuleje i pola do wypełniania znikają na telefonach lub jak za bardzo zmniejszymy okno przeglądarki. 

Jakiś specjalista stwierdził, że ukryje każde `<p>` i nawet nie przetestował że ukrył przy okazji pola na `Imię`, `Nazwisko`, `Telefon`, `e-mail`.

> ![obraz](https://user-images.githubusercontent.com/35370833/59160142-106fb680-8ad3-11e9-9967-b8e13b54bf8d.png) |
> --- |
>
> 🤣

**Comment by hawkeye116477** [comment]
Raczej nie nadaje się. Wycinamy raczej latające, jak siedzi na miejscu to może zostać.

**Comment by krystian3w** [comment]
To zobaczymy czy na mail odpiszą, po miesiącu najwyżej się aktywuje suplement dla uBO / AdGuard.

**Comment by blocker999** [comment]
Ja bym zostawił

**Comment by hawkeye116477** [comment]
Naprawione, dodałem poprawkę dla uBO :smile:.
