### ISSUE TITLE
weathermap.netatmo.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1635]
![Screenshot_20190616_145704](https://user-images.githubusercontent.com/36385327/59564458-5b477c00-9047-11e9-8e02-6e97fbd8ca7a.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
@hawkeye116477 dołącz do społeczności "netatmo.com" to już pop-up czy za mały i do widgetów.

---

To ten nad tym samouczkiem.

**Comment by hawkeye116477** [comment]
@krystian3w Widżet
