### ISSUE TITLE
##.hejhej.hey-outer

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters#1637]
```
http://siecportali.pl/realizacje
```

Pop-up pożegnalny na jakiś ~75 stronach, na razie wycięty na dwóch i może cudem jakoś sieciowo na `.pl`

**Comment by hawkeye116477** [comment]
Nie da się sieciowo, bo to jest inline. Trzeba więc po prostu dopisać resztę tak jak ostatnio to robiłem :smile:.

**Comment by krystian3w** [comment]
Może pl kosmetyczne bezpieczne?

**Comment by hawkeye116477** [comment]
@krystian3w Ale już jest.

**Comment by krystian3w** [comment]
Znaczy w jakiej postaci? ja dopisałem dwie "egzotyczne domeny".

**Comment by hawkeye116477** [comment]
@krystian3w W widgetach było, już poprawiłem.
