### ISSUE TITLE
parenting.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1638]
https://parenting.pl/kiedy-podroz-w-ciazy-jest-niebezpieczna
![Screenshot_20190623_210914](https://user-images.githubusercontent.com/36385327/59980837-7132df00-95fb-11e9-82ad-a6c335f3b36d.png)

### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [x] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Będzie wycinane za jakieś 40 min po aktualizacji i jak Nano pobierze nowsze filtry
