### ISSUE TITLE
mgprojekt.com.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1639]
https://www.mgprojekt.com.pl/blog/ile-trwa-budowa-domu/
![Screenshot_20190624_123540](https://user-images.githubusercontent.com/36385327/60012634-bd723380-967c-11e9-9cc0-1e1ad45b85fe.png)
![Screenshot_20190624_123617](https://user-images.githubusercontent.com/36385327/60012659-cf53d680-967c-11e9-800d-1e850c65d9d4.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Drugi kiedy wyskakuje?

**Comment by krystian3w** [comment]
Takie coś na razie tylko przyczepiłem na sztywno do góry:

![obraz](https://user-images.githubusercontent.com/35370833/60050872-fab4e080-96d1-11e9-8662-f2ad03bf8115.png) |
--- |
