### ISSUE TITLE
kulturaliberalna.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1642]
### Typ elementu
popup
### Link bezpośredni 
`https://kulturaliberalna.pl/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 75.0.3770.100
**Bloker:** uBlock Origin 1.20.0
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Newsletter

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
`kulturaliberalna.pl##.bottom-bar` @KonoromiHimaries  - dotacje, pasek u dołu.

**Comment by hawkeye116477** [comment]
@krystian3w Ale on wymaga EI.

**Comment by krystian3w** [comment]
No to czy u nas zrobimy blokadę do stopki / nagłówka Po update Wew.

**Comment by krystian3w** [comment]
Np. można ustatycznić by zostało w nagłówku / stopce a wew. dotną kompletnie.

**Comment by hawkeye116477** [comment]
@krystian3w Nie, chowamy.
