### ISSUE TITLE
uzywki.expert

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1646]
![Screenshot_20190707_183712](https://user-images.githubusercontent.com/36385327/60771318-8ffaa080-a0e6-11e9-95a1-808c20035721.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Wycięty.

**Comment by krystian3w** [comment]
Mały Newsletter to chyba też mieli w lewej kolumnie.
