### ISSUE TITLE
prywatnoscwsieci.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1654]
https://prywatnoscwsieci.pl/najlepszy-vpn/

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Ja tego pop-upa nie widzę, chyba że taki filtr:

`*$popup,domain=prywatnoscwsieci.pl`

**Comment by hawkeye116477** [comment]
@krystian3w Powinien się pojawić po czasie, ale może być problem, bo jest coś takiego `html.om-position-popup body { overflow: hidden!important; }`.

**Comment by krystian3w** [comment]
No to do testowania, skopiowałem na żywca z CSS klasy, najwyżej się potem podzieli pod AdGuardy i Nano Adblockery.

**Comment by hawkeye116477** [comment]
@krystian3w To nie przejdzie, bo jest już hidden na important.

**Comment by krystian3w** [comment]
No to nie przechodzi tylko z Nano Adblocker lub Chromowatymi, w Firefox niby ładnie się to aktywuje i przewijanie jest.

**Comment by hawkeye116477** [comment]
@krystian3w Poprawione `https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/cf1ced3e610a1740eb6acb673f9892ecf9969193`.

**Comment by krystian3w** [comment]
Znaczy że takie ruszy w NaB?

**Comment by hawkeye116477** [comment]
@krystian3w Tak, tam i wszędzie ruszy.
