### ISSUE TITLE
parkmania.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1657]
![Screenshot_20190713_003314](https://user-images.githubusercontent.com/36385327/61161827-00019000-a506-11e9-8960-5b8e95494b72.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
`###bio_ep`

w uBO Annoyances?

**Comment by krystian3w** [comment]
Unieszkodliwione na dwa sposoby, przynajmniej uBO/NaB nigdy nie będzie miał problemu z przewijaniem, w tym pluginie odblokowany czasem nie jest.
