### ISSUE TITLE
wei.org.pl

### ISSUE THREAD

**Issue by niwelator** [PolishFiltersTeam/PolishAnnoyanceFilters#1661]
### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [x] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

### Link bezpośredni (opcjonalny)
https://wei.org.pl

### Zrzut ekranu (opcjonalny)
![wei](https://user-images.githubusercontent.com/52965407/61592041-11b1fa00-abce-11e9-904a-9aa8d1798d3e.jpg)

**Comment by krystian3w** [comment]
Po 24 powinny zniknąć po wymuszeniu aktualizacji filtrów ręcznie.
