### ISSUE TITLE
telewizja-cyfrowa.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1664]
### Typ elementu
newsletter
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox 56.2.12
**Bloker:** Nano Adblocker 1.0.0.103
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
" Dołącz do 15000+ osób otrzymujących nasz newsletter. Nie przegapisz żadnej ważnej wiadomości. " ( po prawo )

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Nie można wyciąć, na sztywno z tymi grafikami a nie widzę sensu ukrywania tego po przez:


```
telewizja-cyfrowa.com###text-2 > .textwidget > p:nth-of-type(1):after:style(color: #FFF; background: #FFF; content: ""; width: 350px; height: 60px; position: absolute; margin-top: -60px)
```

Czy nawet po prostu zrobić by tekst tam był przezroczysty:

```
telewizja-cyfrowa.com###text-2 > .textwidget > p:nth-of-type(1):style(color: #FFF0;)
```

**Comment by hawkeye116477** [comment]
Można rozmiar czcionki ustawić na 0 :smile:

**Comment by krystian3w** [comment]
Lipa jak jakiś inny wstawią, regex dodasz by wyszukiwał tekst, br i koniec "P".

**Comment by krystian3w** [comment]
Dla AdGuarda możesz dodać. Ale on głupieje jakby używać peseudo elementu "`::before`" / "`::after`".

**Comment by hawkeye116477** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/382

**Comment by krystian3w** [comment]
W kodzie nawet jest ukryte "not yet".

**Comment by krystian3w** [comment]
`1.29.3b10`:

* `###text-2 > .textwidget > p:nth-of-type(1):-abp-contains(/[\w\W]{337}/):contains(/Dołącz do 15000\+ osób otrzymujących nasz newsletter\. Nie przegapisz żadnej ważnej wiadomości\./):style(font-size: 0 !important;)`

* `###text-2 > .textwidget > p:nth-of-type(1):has-text(/.{337}/):contains(/Dołącz do 15000\+ osób otrzymujących nasz newsletter\. Nie przegapisz żadnej ważnej wiadomości\./):style(font-size: 0 !important;)`

Już widzę problem z twardymi spacjami, więc pewnie dawno padło w AdGuard jak działało i nie popsuł tego schowek przy kopiowaniu.
