### ISSUE TITLE
WP

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1666]
```
https://ksiazki.wp.pl/poznala-dziewczynki-wydane-za-maz-zadne-dziecko-nie-zasluguje-na-taki-los-6403210065020545a
https://www.money.pl/gospodarka/nowy-rzad-wielkiej-brytanii-sajid-javid-ministrem-finansow-6406128818628225a.html
```
![Zrzut ekranu z 2019-07-25 06-16-49](https://user-images.githubusercontent.com/36385327/61845534-fe3fb100-aea3-11e9-8cd0-ae9518ba1e94.png)
![Zrzut ekranu z 2019-07-25 06-17-25](https://user-images.githubusercontent.com/36385327/61845535-fe3fb100-aea3-11e9-9737-208169716a00.png)

### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [x] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Chromium Only?

**Comment by krystian3w** [comment]
@blocker999  czy uBO u ciebie w Vivalidi ukrywa to dopiero z filtrem:

```
money.pl,wp.pl###Player0.floating:style(visibility: hidden !important;)
```

bo Chrome z uBO go nie wymaga.

**Comment by blocker999** [comment]
Na vivaldim z samym uBO są filmiki a po dodani powyższej reguły znikają.

**Comment by krystian3w** [comment]
To jutro będzie ukrywać w problematycznych momentach gry userCSS nie pomaga.
