### ISSUE TITLE
independenttrader.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1670]
### Typ elementu
inny element
### Link bezpośredni 
`https://independenttrader.pl`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 75
**Bloker:** uBlock Origin 1.21.6
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
"`Dostęp do kursu inteligentny inwestor`"

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
`###limited-account`

**Comment by krystian3w** [comment]
No niby nie newsletter
