### ISSUE TITLE
shoplet.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1686]
### Typ elementu
popup
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox 56.2.12
**Bloker:** Nano Adblocker 1.0.0.103
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
@hawkeye116477 ten skryptlet działa lepiej od CSS-a?

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/ae9ce7e095cd28f28411b24201efe8cf55be9220/PPB/uBO_AG/popupy_suplement.txt#L318
