### ISSUE TITLE
begio.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1688]
`https://begio.pl/niespodziewany-gosc-na-treningu-bayernu-monachium/
`
### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [x] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
@hawkeye116477  "zobacz również" w prawej kolumnie w EI, z racji że reklmują przez google swoje artykuły (`dubleclick`)?

**Comment by hawkeye116477** [comment]
@krystian3w Raczej chyba do odblokowania, generalnie podobne elementy ukrywaliśmy, ale bocznych nie.
