### ISSUE TITLE
goldenmark.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1692]
`https://goldenmark.com/pl/mysaver/cena-zlota-w-pln-najwyzsza-w-historii/
`![Zrzut ekranu z 2019-08-21 22-47-17](https://user-images.githubusercontent.com/36385327/63467385-a75ad680-c465-11e9-851a-68ded5ebc656.png)
### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [x] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Jutro w wydaniu 2 dziennej wersji
