### ISSUE TITLE
extradom.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1693]
![Zrzut ekranu z 2019-08-26 16-18-27](https://user-images.githubusercontent.com/36385327/63697417-27de5600-c81d-11e9-99aa-21015f12646b.png)

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
Newsletter w stopce

**Comment by krystian3w** [comment]
Pop-up oddzielony od ikonki, tak chyba lepiej aktualizacja po 20.
