### ISSUE TITLE
#totop psuje body...

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters#1694]
### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [X] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [X] Błąd
- [] Pytanie
- [] Ulepszenie

### Link bezpośredni (opcjonalny)

`https://www.auto50.pl/`

**Comment by hawkeye116477** [comment]
@krystian3w Co się pytasz, dodaj `:not(body)` i tyle :stuck_out_tongue:

**Comment by krystian3w** [comment]
@hawkeye116477 jakieś inne zabezpieczyć odgórnie?

**Comment by hawkeye116477** [comment]
@krystian3w Jeszcze możesz `not(html)` :smile:
