### ISSUE TITLE
parkiet.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1697]
### Typ elementu
scrollujący filmik,inny element
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox 56.2.14
**Bloker:** Nano Adblocker 1.0.0.125
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
RP nie ma podobnie, czy jak to im leciało?

**Comment by hawkeye116477** [comment]
Gremi Media.

**Comment by krystian3w** [comment]
Co powiesz na takie coś:

```
##div[class*="-tv_"][style*="position"][style*="fixed"]
```

Więcej cech wspólnych nie mają...

**Comment by hawkeye116477** [comment]
@krystian3w Ale po co? Tak jest dobrze :stuck_out_tongue:

**Comment by krystian3w** [comment]
Zrobiłbym pod najwyżej dwie domeny, reszta zatrzymała się na wyglądzie z poprzedniego 10 lecia.

**Comment by hawkeye116477** [comment]
@krystian3w Ale o co, o co chodzi? Bo tamta reguła sam mówiłeś, że przecież odpada...

**Comment by krystian3w** [comment]
No myślałem, że jakoś lepiej się zmienia dynamicznie ten tag style, ale widać na parkiecie wideo za wysoko, rp to ma jakieś zdjęcie chyba w nagłówku i strona daje radę rozpoznać że przewinięta wystarczająco wysoko.
