### ISSUE TITLE
rzetelnafirma.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1702]
### Typ elementu
popup
### Link bezpośredni 
`https://rzetelnafirma.pl/`

<h3>Screenshots</h3>
<details>
  <summary>Screenshot 1</summary>
<p><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/a20ebba7bd17d8a4a0ceb74fc282bd42e0b03f69/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f436c4d4a4139392e706e67"><img src="https://camo.githubusercontent.com/a20ebba7bd17d8a4a0ceb74fc282bd42e0b03f69/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f436c4d4a4139392e706e67" alt="Screenshot 1" data-canonical-src="https://reports-img.adguard.com/ClMJA99.png" style="max-width:100%;"></a></p>
</details>
<details>
  <summary>Screenshot 2</summary>
<p><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/29c0fa16222b9f7e8eadd167c3b66a8bbbdb1ee5/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f6e7366475173542e706e67"><img src="https://camo.githubusercontent.com/29c0fa16222b9f7e8eadd167c3b66a8bbbdb1ee5/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f6e7366475173542e706e67" alt="Screenshot 2" data-canonical-src="https://reports-img.adguard.com/nsfGQsT.png" style="max-width:100%;"></a></p>
</details>

### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 76.0.3809.100
**Bloker:** Nano Adblocker 1.0.0.126
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Tylko skryptem, musi się usunąć node z "YouTube", bo inaczej psuje odtwarzacz w pop-upie...

**Comment by hawkeye116477** [comment]
YouTube padł?

**Comment by krystian3w** [comment]
Nie padł, użyli jednej technologii do pop-upów (2 pop-up "call to You") i ten spod:

![obraz](https://user-images.githubusercontent.com/35370833/65819428-d4489900-e21c-11e9-97ee-e59afba0196b.png)

Wszystkie w tym samym elemencie, jak tylko ukryjemy "oddzwonimy" CSS-em to nie zamkniejsz nigdy więcej wideo spod:

![obraz](https://user-images.githubusercontent.com/35370833/65819428-d4489900-e21c-11e9-97ee-e59afba0196b.png)

**Comment by hawkeye116477** [comment]
Mi chodzi o to, że strona YT padła.

**Comment by krystian3w** [comment]
Całe YouTube padło to sprawdź jutro?

**Comment by krystian3w** [comment]
Mnie wideo leci, a skryptowo zalecam, bo CSS nie robi dobrze ukrycia.

![obraz](https://user-images.githubusercontent.com/35370833/65819481-55079500-e21d-11e9-933b-cda43d1fc830.png)

**Comment by hawkeye116477** [comment]
Te popupy mają różny iframe, więc może jednak coś z tam z hasem się da pokombinować.
Ah, to chyba znowu mój ISP nawala, zmieniłem DNS i poszło, dziwne...

**Comment by hawkeye116477** [comment]
Chyba jednak lipa, po jakimś czasie coś się psuje i jak przycisk się klika, to wyskakuje mały filmik i nie można go zamknąć.

**Comment by krystian3w** [comment]
No właśnie dlatego CSS nie może być musi być skrypt:

- na przerywanie wykrywania że kursor wyjechał poza stronę i...

- jakiś defuser na to by po minucie nie aktywował się drugi pop-up.

**Comment by krystian3w** [comment]
Najgorzej jak AdGuard zamknie lub zrobi Adam skryptem niekompatyblinym z:

>  [📖  AdguardTeam/Scriptlets](https://github.com/AdguardTeam/Scriptlets)

**Comment by krystian3w** [comment]
Dodatkowo na Firefox męczą powiadomieniem push dzisiaj.

**Comment by hawkeye116477** [comment]
@krystian3w Może `rzetelnafirma.pl##+js(setTimeout-defuser, setPopup)`?

**Comment by krystian3w** [comment]
Potestuję.
