### ISSUE TITLE
rossmann.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1704]
### Typ elementu
popup
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox 56.2.14
**Bloker:** Nano Adblocker 1.0.0.125
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Trzeba tak wyciąć by nie psuło jak kiedyś pop-upa jak przy wysyłce dodali pop-up bo jakaś akcja "kosmetykowa".

**Comment by krystian3w** [comment]
```
rossmann.pl#?#.modal:-abp-has(> div > div > a > img[src*="/GalleryImages/PopupCMS/"])
rossmann.pl#?#.modal:-abp-has(> div > div > a > img[src*="/GalleryImages/PopupCMS/"]) ~ .modal-backdrop
```

?

**Comment by krystian3w** [comment]
A dalej blokują przewijanie to nie może być `abp...`.

**Comment by krystian3w** [comment]
Test róbcie tu:

[`https://www.rossmann.pl/Produkt/Wody-toaletowe/Nike-Blush-woda-toaletowa-dla-kobiet-Premium-Edition-100-ml,284611,8515`](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=q=https%3A%2F%2Fwww.rossmann.pl%2FProdukt%2FWody-toaletowe%2FNike-Blush-woda-toaletowa-dla-kobiet-Premium-Edition-100-ml%2C284611%2C8515)

Nie ma prawa zniknąć taki pop-up:

![obraz](https://user-images.githubusercontent.com/35370833/65819309-14a71780-e21b-11e9-80fc-54b5159c9c5a.png) |
--- |

 spod przycisku:

![obraz](https://user-images.githubusercontent.com/35370833/65819312-24bef700-e21b-11e9-8fa0-2c695da677c7.png) |
--- |

**Comment by hawkeye116477** [comment]
Raczej jest ok.
