### ISSUE TITLE
neonet.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1708]
### Typ elementu
strzałka
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox 56.2.14
**Bloker:** Nano Adblocker 1.0.0.125
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
`##div[class^="scrollTopArrow-wrapper"]` 

@blocker999:

http://www.kurshtml.edu.pl/css/selektor_atrybutu_o_wartosci_rozpoczynajacej_sie_od,atrybuty.html
http://www.kurshtml.edu.pl/css/selektor_atrybutu_zawierajacego_okreslony_tekst,atrybuty.html
http://www.kurshtml.edu.pl/css/selektor_atrybutu_o_wartosci_konczacej_sie_na,atrybuty.html

to nie gryzie a jest łatwe do opanowania...
