### ISSUE TITLE
audio.com.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1710]
`https://audio.com.pl`

![2019-10-01 06 37 42 czasnawnetrze pl 12e2472208ee](https://user-images.githubusercontent.com/36385327/65934503-053fee00-e416-11e9-8b85-88250694b2c0.png) | ![2019-10-01 06 38 38 audio com pl f5abd5305d5c](https://user-images.githubusercontent.com/36385327/65934530-256fad00-e416-11e9-987e-5c59c33633f0.png)
--- | ---

 
`https://audio.com.pl/testy/stereo/gramofony/3107-clearaudio-innovation-basic`

![obraz](https://user-images.githubusercontent.com/35370833/65945873-2b28bb00-e435-11e9-9a5a-97a065ea5223.png) | ---------------------------------------------------------
--- | ---

### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [x] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [x] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Comment by krystian3w** [comment]
@xMaap to ten sam pop-up, nie jakiś inny element.
