### ISSUE TITLE
Blokowanie reCaptcha v3

### ISSUE THREAD

**Issue by krychu90** [PolishFiltersTeam/PolishAnnoyanceFilters#1713]
## Typ elementu/problemu
- [ ] Wyskakujące okienko (popup)
- [ ] Newsletter (nie popup)
- [ ] Powiadomienie push (nie „zgoda na geolokalizację”)
- [ ] Scrollujący filmik
- [ ] Inny element (np. widget „następny artykuł”)
- [ ] Widżet kontaktowy/informacji zwrotnej
- [ ] Strzałka
- [ ] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [x] Błąd
- [ ] Pytanie
- [ ] Ulepszenie

### Moja konfiguracja
**Przeglądarka internetowa:**
Firefox 69/70

**System operacyjny:**
Windows 10

**Bloker:**
uBlock Origin

**Używane filtry:**
1. Polskie Filtry Elementów Irytujących

### Zrzut ekranu (opcjonalny)
![obraz](https://user-images.githubusercontent.com/11661487/67373843-9a02bb00-f580-11e9-9319-d83c37b15264.png)

### Inne ważne informacje mogące mieć znaczenie (opcjonalne):
Filtr ten blokuje skrypt Google reCaptcha v3 przez co nie da się wysłać formularzy korzystających z niego. Pływające logo recaptchy widoczne na screenie powyżej w ogóle się nie pojawia, po wyłączeniu filtra recaptcha działa poprawnie.

**Comment by hawkeye116477** [comment]
Jakiś przykładowy link do strony?

**Comment by krychu90** [comment]
https://fotoportal.poznan.pl/uzytkownik/rejestracja

**Comment by hawkeye116477** [comment]
Tak w zasadzie to lista nie blokuje skryptu, jedynie ustawia nieprzezroczystość ikony na 0.

Dodaj i sprawdź czy pomogło:
```
pl#@#.grecaptcha-badge:style(opacity: 0 !important;)
pl##.grecaptcha-badge:style(visibility: hidden !important;)
```

**Comment by krychu90** [comment]
Faktycznie recaptcha mimo niewidoczności zachowuje swoją funkcjonalność.

**Comment by hawkeye116477** [comment]
@krystian3w Opacity psuje Captchę.
