### ISSUE TITLE
YouTube: pasek "Więcej filmów"

### ISSUE THREAD

**Issue by klocus** [PolishFiltersTeam/PolishAnnoyanceFilters#1718]
### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [x] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

**Używane filtry:**
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących

### Więcej informacji:
Upierdliwe okienko "Więcej filmów", które pojawia się przy zapauzowaniu filmu.

### Filtr:
```
www.youtube.com##.ytp-pause-overlay
```

### Zrzut ekranu (opcjonalny)
![Więcej filmów](https://www.wykop.pl/cdn/c3397993/link_06nVTKjGRtHYu4y2Cb5GYAAaOKayKKOw,w300h223.jpg)

**Comment by krystian3w** [comment]
chyba działa dobrze: `https://naekranie.pl/recenzje/czarodziejki-sezon-2,-odcinek-1-i-2-recenzja`
