### ISSUE TITLE
transfery.info

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1733]
### Typ elementu
scrollujący filmik
### Link bezpośredni 
`https://transfery.info/aktualnosci/klopp-zirytowal-sie-pytaniem-o-halanda-jestes-jak-polscy-dziennikarze/131416`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Opera a.k.a Chromium: 78.0.3904.108
**Bloker:** uBlock Origin 1.23.0
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
`Opera Wersja 1.0.1 Chromium: 78.0.3904.108`
To jakaś edycja limitowana musi być, bo nie widziałem jeszcze takiego cuda :smiley:

**Comment by krystian3w** [comment]
"gazeta.pl"
