### ISSUE TITLE
benchmark.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1735]
### Typ elementu
inny element
### Link bezpośredni 
`http://www.benchmark.pl/aktualnosci/plundervolt-luka-bezpieczenstwa-w-procesorach-intel-czy-jestes-za.html`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Brave 1.1.20
**Bloker:** uBlock Origin 1.23.0
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Zmieszane z RSS więc zasubskrybuj listę z projektu: https://github.com/PolishFiltersTeam/PolishAntiAnnoyingSpecialSupplement/
