### ISSUE TITLE
plejada.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1740]
### Typ elementu
scrollujący filmik
### Link bezpośredni 
`https://plejada.pl/newsy/don-vasyl-sprzedaje-dom-aby-splacic-dlugi-jak-mieszkala-gwiazda-zdjecia/z343ek2?utm_source=plejada.pl_viasg_plejada&utm_medium=referal&utm_campaign=leo_automatic&srcc=ucs&utm_v=2`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Brave 1.1.21
**Bloker:** uBlock Origin 1.23.0
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Mnie nic nie lata...

---

Na ślepo mogę jedynie dopisać do:

`##.player-floating, .player-move-up`
`##div[class="mainVideo toFix fixedVideo"]`
`##.active.player-float-wrap > .player-float-container`

---

`##+js(set-constant.js, FloatingVideoPlayer, noopFunc)`
`##+js(set-constant.js, floatingPlayer, noopFunc)`

**Comment by krystian3w** [comment]
Na razie musi wystarczyć.
