### ISSUE TITLE
oleole.pl / euro.com.pl

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishAnnoyanceFilters#1755]
### Za dużo blokuje:

tzn. nie ma "`porównywania`" na głównej i jest ok, ale problem zaczyna się gdy dodamy coś do porównywarki a tej nie widać, wystarczy to odblokować. tak by nie było tego na głównej albo unieruchomić by nie przewijało się.

### To samo tu: 

`https://www.euro.com.pl`

**Comment by krystian3w** [comment]
U mnie jest widoczne?

### Euro:

![obraz](https://user-images.githubusercontent.com/35370833/72221743-b994f880-355d-11ea-9e45-4612f1e50e95.png)

Na OleOle nie widzę ale to może efekt #1436?

**Comment by krystian3w** [comment]
To tak:

- w ABP na głównej ukryte
   - w uBO / AG przypięte do stopki na głównej
- W działach / na produkcie będzie się przewijać

I pop-upy trzeba przebudować na bardziej proceduralne filtry by nie wchodziły w interakcje z pop-upem porównywarki.
