### ISSUE TITLE
niedziela.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1756]
`https://www.niedziela.pl/artykul/48555/Swiety-Hilary-z-Poitiers`
![Screenshot_2020-01-13 Święty Hilary z Poitiers](https://user-images.githubusercontent.com/36385327/72298798-6b681e00-365f-11ea-8fbc-dd87093b61d3.png)

**Comment by xMaap** [comment]
`https://www.niedziela.pl/artykul/48391/Ukrainski-samolot-pasazerski-rozbil-sie-w`
![Screenshot_2020-01-13 Ukraiński samolot pasażerski rozbił się w Iranie](https://user-images.githubusercontent.com/36385327/72299021-f6491880-365f-11ea-88df-646ef9662500.jpg)

**Comment by krystian3w** [comment]
Playera nie umiem uchwycić...

**Comment by xMaap** [comment]
To chyba można zamknąć.

**Comment by krystian3w** [comment]
Jak dzisiaj nie wyłapię to zamkniemy.
