### ISSUE TITLE
dziennik.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1780]
```
https://sport.dziennik.pl/pilka-nozna/ligi-zagraniczne/artykuly/6447868,liga-niemiecka-gol-piatka-z-rzutu-karnego-remis-herthy-w-duesseldorfie.html
https://wiadomosci.dziennik.pl/
https://auto.dziennik.pl/
https://technologia.dziennik.pl/
https://film.dziennik.pl/
https://muzyka.dziennik.pl/
https://rozrywka.dziennik.pl/
https://zdrowie.dziennik.pl/
https://podroze.dziennik.pl/
https://kultura.dziennik.pl/
https://edukacja.dziennik.pl/
https://kobieta.dziennik.pl/
```

![obraz](https://user-images.githubusercontent.com/35370833/75604560-3e21e300-5ada-11ea-8522-535ebcf6040e.png) |
--- |

**Comment by krystian3w** [comment]
@hawkeye116477 jak on dał tag, bug w skrypcie?

**Comment by krystian3w** [comment]
@xMaap to nie jest inny element a film, nie było czytać 10 minut artykuł...

**Comment by krystian3w** [comment]
@gwarser da się zrobić by element picker wykrywał niestnienie nodów na podstawie klas?

Muszę wycinać filtr by sprawdzić czy nie tyka on nieruchomego wielkiego playera.

**Comment by gwarser** [comment]
Nie rozumiem. Pokazuje przecież 0 jak nic nie znajdzie.

**Comment by krystian3w** [comment]
Przewiń w dół, złap player filtrem, wróć by się schował i uchwyt nie puszcza aż nie opróżnię textarea z filtru.

`##.video.widget > .videoScroll`

**Comment by gwarser** [comment]
Aaaa! Ale to tylko Picker.

Picker "przykleja się" do elementu a nie "selektora". Trzeba by do `highlightElements` podawać selektor zamiast elementu, i potem czuwać jakimś `MutationObserver` czy się coś nie zmienia. 

W tym wypadku może to jest źle, ale jak byś chciał zaznaczyć np. element który się przesuwa na stronie, to by ramka cały czas znikała, bo się np top/left cały czas zmieniał.
