### ISSUE TITLE
mediaexpert.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1783]
### Typ elementu
popup,inny element
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Vivaldi 2.0.1309.42
**Bloker:** AdGuard 3.3.8
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
dwie podstrony:
```
https://www.mediaexpert.pl/sport-i-rekreacja/skutery
https://sklepy.mediaexpert.pl/blonie_powstancow
```

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Nie wiem jaki inny element, lewej wyszukiwarki nie ruszamy, to raczej dla "Polskie reklamy wewnętrzne".
