### ISSUE TITLE
kurierzamojski.pl

### ISSUE THREAD

**Issue by gwarser** [PolishFiltersTeam/PolishAnnoyanceFilters#1811]
### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [x] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [x] Pytanie
- [] Ulepszenie

### Moja konfiguracja
**Przeglądarka internetowa:** Firefox Nightly / Chrome 80

**System operacyjny:** Manjaro KDE

**Bloker:** uBO dev / stable

**Używane filtry:**
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
2. POL: Oficjalne polskie filtry przeciwko alertom o Adblocku​​​​​
2. Polskie Filtry Elementów Irytujących​​​​​
2. Polskie Filtry Społecznościowe

### Link bezpośredni (opcjonalny)
`https://www.kurierzamojski.pl/zbiorka-pieniedzy-dla-szpitala-papieskiego-na-stronie-zrzutka-pl/`

### Zrzut ekranu (opcjonalny)
![image](https://user-images.githubusercontent.com/886325/77650694-266c3c00-6f6c-11ea-99a6-25a5bf7ffca5.png)

### Inne ważne informacje mogące mieć znaczenie (opcjonalne):
Można coś zrobić z tym podwójnym nagłówkiem? Bez adblocka na pierwszej "stronie" są reklamy, na drugiej ten wielki obrazek i dopiero na trzeciej artykuł. Nasze filtry blokują banery ale trochę pustego miejsca zostaje.

No i widzę przyciski społecznościowe nie są usunięte, ale to chyba nie tutaj?

**Comment by krystian3w** [comment]
> No i widzę przyciski społecznościowe nie są usunięte, ale to chyba nie tutaj?

Ze headera, stopki i nad artykułem social wycina fanboy, zostaje dociąć nagłówek w stopce.
Jak bardzo chcesz, mogę przywrócić e-mail i print (fanboy raczej to olewa).

Jak błąd generuje AdGuard Social Media to zgłaszaj na dev "cookies / social";  tamta lista inaczej podchodzi do blokowania - "`telepolis`".

**Comment by gwarser** [comment]
> Ze headera, stopki i nad artykułem social wycina fanboy,

Racja. Tutaj mi chodzi tylko o ten wielki obrazek na górze. Żeby nie trzeba było przewijać by zobaczyć artykuł.

**Comment by krystian3w** [comment]
Kto chce dalej ukrywać nagłówek - niech użyje:

```
##.td-full-screen-header-image .td-post-template-6 .td-post-header:style(width: 220px !important;)
```
