### ISSUE TITLE
mateuszrus.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#1822]
![Screenshot_2020-04-07 Mateusz Rus - Programowanie z pasją Blog z pasji na temat algorytmów i matematyki](https://user-images.githubusercontent.com/36385327/78646765-d66d6d80-78b9-11ea-9434-71975ed7c153.png)

**Comment by krystian3w** [comment]
takie duże i z zaciemnieniem to już pop-up.
