### ISSUE TITLE
swiatkwiatow.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1823]
### Typ elementu
popup,inny element
### Link bezpośredni 
`https://www.swiatkwiatow.pl/poradnik-ogrodniczy/ozdoby-wielkanocne-id581.html`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 80.0.3987.158
**Bloker:** AdGuard 3.3.8
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

widżet (w prawym dolnym rogu)

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
proszę się nauczyć pisać poprawnie nawiasy, słowa wolniej.

**Comment by krystian3w** [comment]
Pop-upa nie widzę.
