### ISSUE TITLE
florini.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1850]
### Typ elementu
popup
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 81.0.4044.132
**Bloker:** AdGuard 3.3.8
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

`https://www.florini.pl/budleja-dawida-black-knight-div-classlat-buddleja-davidii-div-p1307`

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
@hawkeye116477 chyba powrót #1324, tu fancybox do pop-upa jak i galerii.
