### ISSUE TITLE
m.leroymerlin.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1858]
### Typ elementu
push
### Link bezpośredni 
`https://m.leroymerlin.pl/elektrycznosc/baterie-ladowarki-latarki/baterie-cr2032,a1085,t20.html`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 81.0.4044.132
**Bloker:** AdGuard 3.3.8
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Nie potrafię bezpiecznie dezaktywować, trzeba by analizować ich makaronowe spaghetti 🍝  JS.

**Comment by hawkeye116477** [comment]
@krystian3w Zapraszam do testów :smile:
