### ISSUE TITLE
ding.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1862]
### Typ elementu
push
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 81.0.4044.132
**Bloker:** AdGuard 3.3.8
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
To może nie być push, a ich system w HTML+JS.

**Comment by hawkeye116477** [comment]
Powiedziałbym, że robota jeszcze nie skończona. Z prawej otwiera się „modal" z informacją, że jak chcesz powiadomienia, to rejestracja wymagana.

**Comment by krystian3w** [comment]
Wtedy trzeba sięgnąć po `matches-css` i wykrywać może niezalogowanych?
