### ISSUE TITLE
nokia.com

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#1870]
### Typ elementu
push
### Link bezpośredni 
`https://www.nokia.com/phones/pl_pl`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 81.0.4044.132
**Bloker:** AdGuard 3.3.8
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
@krystian3w Najwyraźniej AG już zaczął konwerterować skryptlety i dopuszczają je dla naszej listy.

Ale to z Nano u nich nie trybi => https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_237_PolishAnnoyance/diff.txt#L1104 i :penguin: napisał, że może to w przyszłości usunąć, więc trzeba chyba będzie to zamienić na `:remove() `

**Comment by hawkeye116477** [comment]
U nas bezpośrednio aktualizacja listy będzie o 16:00, w przypadku AG prawdopodobnie będzie pół godziny później.

**Comment by krystian3w** [comment]
AG też zamyka z prośbą uaktualnienia po 3 godzinach.
