### ISSUE TITLE
angielski-przedszkole.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1877]
![capture_002_01-06-2020_13-58-01](https://user-images.githubusercontent.com/63287518/83407587-53781780-a411-11ea-8eb5-36279687f995.gif)

PS. dawno mnie tu nie było, więc już kompletnie nie pamiętam, do jakiej kategori to sie zalicza:
- Newslettery (nie pop-upy)
- Widżety kontaktowe/informacji zwrotnej
- Wyskakujące okienka

Jak coś to niech ktoś poprawi.

<details not-open>
<summary>Moje listy:</summary>

```
Polskie Filtry Elementów Irytujących - Inne Elementy
Polskie Filtry Elementów Irytujących - Newslettery
Polskie Filtry Elementów Irytujących - Powiadomienia Web Push
Polskie Filtry Elementów Irytujących - Widżety Kontaktowe/Informacji Zwrotnej
Polskie Filtry Elementów Irytujących - Wyskakujące Okienka
https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/sections/popups.txt
https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/sections/push-notifications.txt
```

</details>

**Comment by krystian3w** [comment]
W rogu, małe, bez tła, więc do newsletterów.

> Zapisz się na newsletter i otrzymaj od nas bezpłatny poradnik  :)

**Comment by krystian3w** [comment]
A `widżet kontaktowy/feedback` to praktycznie same czaty i system sugestii i zgłaszania bugów ze stroną.

**Comment by gargul2** [comment]
A popup socialowy to gdzie zgłaszać, bo kiedyś chyba tutaj się zgłaszało jako popup ,a potem na repo POL listy jako social.

**Comment by hawkeye116477** [comment]
@gargul2 W zasadzie możesz i tutaj, jeśli masz też więcej elementów, ale generalnie popupy socialowe dodajemy najpierw do Sociala, w EI potem CI tylko pobiera popupy z Sociala.

Tak więc najlepiej na https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/issues albo do Dyrektora Majkela :smile:

**Comment by gargul2** [comment]
OK, dzięki wam obydwu za wyjaśnienie.
