### ISSUE TITLE
mojaszkola.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1878]
Z modułem Polskie Filtry Elementów Irytujących - Inne Elementy:
![capture_011_03-06-2020_12-17-37](https://user-images.githubusercontent.com/63287518/83625686-a201ef00-a594-11ea-907d-44163ca2ca4d.gif)

Bez modułu Polskie Filtry Elementów Irytujących - Inne Elementy:
![capture_010_03-06-2020_12-17-21](https://user-images.githubusercontent.com/63287518/83625733-b80faf80-a594-11ea-88f6-fc543c3c4089.gif)

**Comment by hawkeye116477** [comment]
Z mojej analizy przy pomocy publicwww wynika, że element o tej klasie to głównie zazwyczaj widget FB, który zresztą już jest ukrywany w bezpieczniejszy sposób przez Polską listę Social. W EI też raczej jedynie z Sociala dodajemy popupy, więc usuniemy tę niebezpieczną regułę z tego modułu.

**Comment by gargul2** [comment]
"W EI też raczej jedynie z Sociala dodajemy popupy," a co to jest jak nie popup?
Nie używam (póki co) filtrów Social, to już nie wiem, którą listę włączyć żeby tego popupa nie było.
