### ISSUE TITLE
fantoma.pl + lachlach.pl + epiekarnia.com + abcsurf.pl + kokonhome.pl + biomak.eu + sklep-kajkosz.pl + goshico.com + justmeble.pl + center-camp.pl + akcesoriabaristy.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1882]
Te same popupy, największa różnica to kolor górnej belki..na każdej ze stron jest inny hmm

**Dodane:** tak myślałem, kiedy skończy im się paleta kolorów, i w końcu się doczekałem, przed chwilą znalezione goshico.com ma belkę czarną tak jak epiekarnia.com, podobnie jak później znalezione akcesoriabaristy.pl

**Dodane 2:** jednak pomimo, że wszystkie 3 belki są czarne dla nieuzbrojonego oka, to po zbadaniu próbnikiem jest to nieco inny odcień czarnego w obytrzu belkach #333333 epiekarnia.com vs goshico.com #040202 vs akcesoriabaristy.pl #020202

fatnoma.pl
![capture_020_03-06-2020_12-46-58](https://user-images.githubusercontent.com/63287518/83628191-6406ca00-a598-11ea-894b-3849d5ab2106.gif)

lachlach.pl
![capture_021_03-06-2020_12-48-04](https://user-images.githubusercontent.com/63287518/83628316-91ec0e80-a598-11ea-9552-c93c34e68efe.gif)

epiekarnia.com
![capture_029_03-06-2020_13-21-23](https://user-images.githubusercontent.com/63287518/83631052-2b1d2400-a59d-11ea-9d7c-24143a8dc9a2.gif)

abcsurf.pl
![capture_034_03-06-2020_16-16-22](https://user-images.githubusercontent.com/63287518/83647853-aab6ed00-a5b5-11ea-8606-e6b09cee7aac.gif)

kokonhome.pl
![capture_066_05-06-2020_09-05-39](https://user-images.githubusercontent.com/63287518/83847056-e2d04400-a70b-11ea-8ed9-34b3ec19c6d5.gif)

biomak.eu
![capture_074_05-06-2020_09-36-35](https://user-images.githubusercontent.com/63287518/83849738-275dde80-a710-11ea-9f4e-5d117c6822b1.gif)

sklep-kajkosz.pl
![capture_075_05-06-2020_09-37-39](https://user-images.githubusercontent.com/63287518/83849804-40668f80-a710-11ea-8839-b2e1ba3570fa.gif)

goshico.com
![capture_079_05-06-2020_09-54-15](https://user-images.githubusercontent.com/63287518/83851377-91778300-a712-11ea-9965-b4586ecb4e66.gif)

justmeble.pl
![capture_086_05-06-2020_10-06-15](https://user-images.githubusercontent.com/63287518/83852544-3fcff800-a714-11ea-9b6b-b83a202757c6.gif)

center-camp.pl
![capture_101_05-06-2020_17-25-51](https://user-images.githubusercontent.com/63287518/83894490-a7586880-a751-11ea-97f4-3da1c9f572a1.gif)

akcesoriabaristy.pl
![capture_106_05-06-2020_17-41-58](https://user-images.githubusercontent.com/63287518/83896220-13d46700-a754-11ea-9a82-08680496c8f2.gif)

**Comment by krystian3w** [comment]
W ten pop-up mogą wepchać wszystko, generyk pod `pl,com` wymagał by powolnego `abp-has`.

**Comment by hawkeye116477** [comment]
@krystian3w A ktoś tu mówił coś o generyku? Musiałem i tak do kurtyny dodać `-abp-has`, bo inaczej podgląd produktów jest nie elegancko, bez kurtyny :smiley:
