### ISSUE TITLE
kobietyipodryw.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1887]
![capture_027_03-06-2020_13-19-31](https://user-images.githubusercontent.com/63287518/83630906-e5605b80-a59c-11ea-97a7-b78a08eece81.gif)

**Comment by krystian3w** [comment]
W tle umie lecieć YouTube a Firefox nie blokuje tego domyślnie, nawet nie wykrywa że trzeba by stronie dać ucisk na audio/video.

**Comment by gargul2** [comment]
> W tle umie lecieć YouTube a Firefox nie blokuje tego domyślnie, nawet nie wykrywa że trzeba by stronie dać ucisk na audio/video.

Też już jakiś czasm temu zauważyłem, że ta funkcja wyciszająca filmy wbudowana w Firefoxa jest ułomna i dosyć często nie wycisza jakiegoś filmiku (nawet na stronach https)
