### ISSUE TITLE
tvkrosno.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1890]
![capture_031_03-06-2020_15-26-33](https://user-images.githubusercontent.com/63287518/83642113-b652e580-a5ae-11ea-8e11-941051c33112.gif)

**Comment by krystian3w** [comment]
@MajkiIT:

```
tvkrosno.pl#@##top-reklama
```

wycina za dużo.

**Comment by krystian3w** [comment]
A pop-upa brak.

**Comment by krystian3w** [comment]
@hawkeye116477 Polskie EI super mocno zaleca `Fanboy Social` czy dodajemy to:

```
/plugins/easy-facebook-likebox/*
```

PL social tego nie wymaga a już jakiś generyk mamy dla leniuszków.

**Comment by MajkiIT** [comment]
@krystian3w Dzięki

**Comment by hawkeye116477** [comment]
@krystian3w Raczej nie zaleca.
