### ISSUE TITLE
perfumylane.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1892]
![capture_033_03-06-2020_16-15-40](https://user-images.githubusercontent.com/63287518/83647709-7e02d580-a5b5-11ea-9c6d-dda953f5280d.gif)

**Comment by hawkeye116477** [comment]
Coż, tak w zasadzie, to informacja o dostępności produktów bardzo pożądanych, szczególnie teraz. Niby każdy może kliknąć na produkt i też jest informacja, ale z drugiej strony jak jest pop-up, to mniej fatygi.
