### ISSUE TITLE
vw-sklep.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1901]
![capture_049_03-06-2020_18-05-53](https://user-images.githubusercontent.com/63287518/83660279-ead19c00-a5c4-11ea-9c4a-01dec351c83c.gif)

**Comment by krystian3w** [comment]
Może funkcjonalny, trzeba sprawdzić czy nie uszkodzi się górna wyszukiwarka.

**Comment by hawkeye116477** [comment]
No raczej odpada, jak nie wybierzesz dealera to górna wyszukiwarka się psuje.

**Comment by krystian3w** [comment]
Ja myślę, że tym można zweryfikować czy można pojechać do salonu i osobiście odebrać / kupić bez używania funkcji "zapytaj o produkt" lub koszykiem.

Dodatkowo bez wyboru to na etapie `order` mają awarię wyboru dealera (kod wyglądający jak z początku ery internetu - goły tekst i JS się wywala - gargul naprawi pro bono `VW` kod to zablokujemy).

**Comment by krystian3w** [comment]
Dodatkowo inne pop-upy tracą ostylowanie i treść mają uszkodzoną:

> `Produkt pomyślnie dodany do <a href=\"%s\">schowka</a>`

widać link html a nie powinno tak być.
