### ISSUE TITLE
sudafed.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1903]
![capture_051_03-06-2020_18-07-46](https://user-images.githubusercontent.com/63287518/83660472-2a988380-a5c5-11ea-9f97-694a0129e01b.gif)

**Comment by krystian3w** [comment]
Muzyka leci sama?  Jak tak, to pewnie pod stare Firefox i pewnie Chrome trzeba filtr stopujący (skrypt / html filtering / `remove()` lub `nano-remove-...` / filtr sieciowy dla elementów `media` lub `object`).

**Comment by gargul2** [comment]
> Muzyka leci sama?

Nie.
