### ISSUE TITLE
westwingnow.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1907]
![capture_055_03-06-2020_18-10-32](https://user-images.githubusercontent.com/63287518/83660809-8fec7480-a5c5-11ea-8ec9-7512405e4bc9.gif)

**Comment by hawkeye116477** [comment]
Tutaj w zasadzie może być problem, bo wydaje się, że jeśli zablokuję pop-up, to newsletter statyczny też się zepsuje, bo jest wywoływany jako pop-up. A może jednak da się inaczej, nie wiem, pomyślimy.
