### ISSUE TITLE
bgzoptima.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1911]
![capture_059_03-06-2020_18-15-33](https://user-images.githubusercontent.com/63287518/83661352-44869600-a5c6-11ea-8727-082aaf7159bd.gif)

**Comment by hawkeye116477** [comment]
No to mamy problem, po naciśnięciu przycisku jest taki sam pop-up, trzeba byłoby jakoś to rozdzielić. Może @krystian3w coś poradzi?

**Comment by krystian3w** [comment]
Mnie nie wyskakuje, muszę najpierw naprawić Firefox z opcji odśwież profil, nie mogę przeglądać np. epic store.

**Comment by hawkeye116477** [comment]
@krystian3w Do poprawy, po kliknięciu `zostaw numer` nic się nie dzieje.

**Comment by krystian3w** [comment]
Ja mam utrudnione debugowanie tego, raz na 15 min wskakuje a uBO jak mam filtr wklejony to przy oczku nie pokazuje mi nigdy "6" (zakładam że 5 to jest bez filtra na pop-up).
