### ISSUE TITLE
myob.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1912]
![capture_060_03-06-2020_18-16-27](https://user-images.githubusercontent.com/63287518/83661404-6253fb00-a5c6-11ea-8a79-ddba747dc1ec.gif)

**Comment by krystian3w** [comment]
Jak dla mnie niestety informacyjny, jak zacznie być samą reklamą udogodnień / bonusów to wtedy tak.

**Comment by gargul2** [comment]
No to się doczekałeś - mówisz i masz:

![capture_084_14-06-2020_11-28-07](https://user-images.githubusercontent.com/63287518/84589880-23c60800-ae32-11ea-94ea-cf71b0606db4.gif)

**Comment by krystian3w** [comment]
Byznesmen?

**Comment by krystian3w** [comment]
Odrzucone, bo mogą odkomentować wersję z informacją.

Zatwierdzone, bo raczej nie zrobią, że wersja informacyjna będzie zasłaniać reklamę.

**Comment by gargul2** [comment]
Teraz to strona popsuta - nie działają przyciski `JESTEM NASTOLATKĄ` i `JESTEM KOBIETĄ` przez co nie da się wejść dalej na stronę, przyczyna - został przycisk `X` zamknięcie okna razem z jakąś niewidzialną warstwą:

![capture_001_14-06-2020_19-06-34](https://user-images.githubusercontent.com/63287518/84599420-34966e00-ae72-11ea-8572-ca5add89e769.gif)
