### ISSUE TITLE
tomkas.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1916]
![capture_064_03-06-2020_18-25-25](https://user-images.githubusercontent.com/63287518/83662345-a5fb3480-a5c7-11ea-9571-24df33575fd0.gif)

**Comment by gargul2** [comment]
Mam dosyć, tego jest za dużo,  dodałem `*##+js(overlay-buster.js)` , akurat nie działa na to, ale na niektóre inne tak.

**Comment by gargul2** [comment]
Mam dosyć, tego jest za dużo, nie na jedną osobę, tu trzeba drużyny albo plutonu żeby to wszystko wyłapać

**Comment by krystian3w** [comment]
Pop-upów informacyjnych nie blokujemy. Jak są blokowane generykiem to możemy odblokować.

**Comment by gargul2** [comment]
A bo ja wiem co wy blokujecie, a czego nie, to chyba tylko święty mikołaj wie, wszystkiego się dowiaduję w komentarzach, tak jak i [tu](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1877). Zróbcie po ludzku jakąś rozpiskę co blokujecie a czego nie, żeby było jasne i klarowne (nie mylić z masłem klarowanym), i własnie dlatego, że nie wiadomo co blokujecie a co nie, to zgłaszam wszystko jak leci, i to już wasza sprawa czy to sobie zakwalifikujecie czy nie, poza tym mam w dupie czy to popup informacyjny czy nie, jak mi jakieś gówno wyskakuje na cały ekran bez mojej zgody i blokuje całą stronę to dla mnie jest to element drażniący, którego chcę się pozbyć więc to zgłaszam, a czy to zakwalifikujecie czy nie to wasza sprawa, cokolwiek chcą przekazać nie muszą tego ładować w popupa. Chyba dodam sobie `*##+js(overlay-buster.js)` ale i tak wszystkiego nie wytnie.

**Comment by hawkeye116477** [comment]
Na twoją prośbę dodane => https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/master/CONTRIBUTING.md

`co ty taki zdziwiony`

Raczej chodziło o to, że nie wiem o co ci chodzi, przecież tu nie pracujesz, więc nie musisz na siłę wynajdywać rzeczy do zgłoszenia. A napisałeś tak jak by to była pretensja, że za dużo roboty ci daliśmy... :rofl: 

PS: @gargul2 nie odchodź z roboty, damy ci podwyżkę :smiley:

**Comment by gargul2** [comment]
> Na twoją prośbę dodane

OK, a tak w ogóle to powinno było być dodane bez niczyjej prośby i to już na samym początku gdy powstała lista EI, ale jak to głosi przysłowie "lepiej późno niż wcale" ewentualnie można zmodyfikować: "lepiej na prośbę niż wcale"

A wogóle to zdaje się o ile dobrze pamiętam, że nie usuwacie też np. statycznych komunikatów rodo/ciasteczkowych, więc trzeba by utworzyć tak samo CONTRIBUTING także dla https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev i umieścić tam tę informację.

> A napisałeś tak jak by to była pretensja, że za dużo roboty ci daliśmy... smiley

To że tak odczytałeś, to nie znaczy że tak napisałem, widocznie coś ci się ubzdurało, generalnie to nie miałem pretensji ani żali, a raczej zasygnalizowałem i wyraziłem swoje zmęczenie i że dużo tego jest na jedną osobę, jeśli już miałbym mieć jakieś żale to co najwyżej do samego faktu, że aż tyle tych popupów, ale na pewno nie do was, zwłaszcza skoro jak napisałeś "przecież tu nie pracuję, więc nie muszę na siłę wynajdywać rzeczy do zgłoszenia" to dlaczego miałbym mieć do was pretensje i żale..., miałem je dopiero w następnym komentarzu odnośnie tego żeby wyraźnie napisać co jest blokowane a co nie jest. A tu dla przykładu podobna sytuacja, z winą gdzieś po środku: https://github.com/easylistpolish/easylistpolish/issues/463.

**Comment by hawkeye116477** [comment]
@krystian3w Robota dla ciebie :smile:

**Comment by gargul2** [comment]
Najpierw robią z siebie i z innych głupków, informując dopiero po fakcie, że popupów informacyjnych nie blokują, potem ktoś się do mnie czepia że miałem pretensje o coś , kiedy nie miałem, ciekawe co mnie tu jeszcze spotka.

**Comment by gargul2** [comment]
Dla przykładu to co w popupach wyżej można umieścić w banerze, więc czy musza walić to do popupów?:

https://iglaki24.pl/
![capture_076_05-06-2020_09-40-19](https://user-images.githubusercontent.com/63287518/83850079-a9e69e00-a710-11ea-98ad-26c8a56a82c5.gif)

**Comment by hawkeye116477** [comment]
`ledwo przyszedłem a już się zaczyna. Haha. Dorzucę wam popupów żebyście mieli co przeżuwać`

No widać, zaczyna się, nie można nic skrytykować ani zwrócić uwagę, bo od razu wielki problem, mimo, iż nie było bardzo agresywnych komunikatów... Trochę zabrzmiało, jak by te dorzucenie pop-upów to po złośliwości, ale pewnie znowu się mylę i ponownie będzie esej o tym...

**Comment by gargul2** [comment]
> nie można nic skrytykować ani zwrócić uwagę, bo od razu wielki problem

Nie zauważyłem żeby ktoś mi zwracał uwagę czy mnie krytykował, tylko wkurzają odrzucone zgłoszenia, bo nie wiadomo co się kwalifikuje a co nie, a często trudno odróżnić.

> ale pewnie znowu się mylę

Nie no co ty, przecież zawsze nasz rację...:smiley: 

Z tym dorzuceniem popupów, to raczej forma przekamarzania / kary (na żarty), bo wiesz... najpierw chciałem zażądać kary chłosty - 20 uderzeń z końskiego bicza, ale pomyślałem - nie będę takim barbarzyńcą... hehe a w ogóle gdybym był złośliwy to napisałbym, że doszukiwanie się w czyichś komentarzach samych złośliwości to... też złośliwość. 

> i ponownie będzie esej o tym...

 ...rzekł [niemota](https://pl.wikipedia.org/wiki/Niemota) albo [Spartanin](https://pl.wikipedia.org/wiki/Lakonizm) :smiley: 

A zostawiając utarczki, i wracając do tematu, nie dostałem odpowiedzi na pytanie odnośnie popupów o które wyżej pytałem, bo zgłupiałem które z nich zgłaszać, a które nie.

**Comment by hawkeye116477** [comment]
`Z tym dorzuceniem popupów, to raczej forma przekamarzania / kary (na żarty)`

Mhmm, niezbyt wyglądało na żart, ale post jednak zamazałeś, więc mogę sobie pomyśleć, że było inaczej.


`nie dostałem odpowiedzi na pytanie odnośnie popupów o które wyżej pytałem`
Spokojnie, wrócimy do pana za jakiś czas, w tej chwili jesteśmy zajęci... Zresztą @krystian3w odpowie :smile:

**Comment by gargul2** [comment]
Zamazałem, żebyś nie czuł się urażony, a także po to żeby skrócić wypowiedź z "eseju" których ponoć też nie lubisz do [wypowiedzi lakonicznej](https://pl.wikipedia.org/wiki/Wypowied%C5%BA_lakoniczna), która cię usatysfakcjonuje, ale jak chcesz to możemy przyjąć twoją wersję każdego mojego komentarza i uczynku.... :smiley:

**Comment by krystian3w** [comment]
Slider `iglaka` się nie liczy, `bntrade` nie ma faktycznego pop-upa (lubisz fiolet w tle, twój problem).

Na`azun` to pop-up jest reklamą, to w rogu raczej nie ma nawet własnego tła (o wirusie).

**Comment by gargul2** [comment]
> Slider `iglaka` się nie liczy, `bntrade` nie ma faktycznego pop-upa (lubisz fiolet w tle, twój problem).

Wiem, akurat w tym komentarzu nie pytałem, jedynie pokazywałem, że komunikaty z wcześniejszego komentarza można umieścić gdzieś indziej niż w natrętnym popupie - to miał być argument na blokowanie wszelkich takich popupów jak z wcześniejszego komentarza, bo nie ma potrzeby pchania takich komunikatów w popup. Dlatego wydzieliłem to do osobnego komentarza zamiast doklejać screenshooty do poprzedniego, ale jak widać, owe wydzielenie nie odniosło zamierzonego skutku.

> Na `azun` to pop-up jest reklamą, 

Ok, i rozumiem jednakowoż, że muszę wydedukować sobie, że tak samo jak na pozostałych screenshootach są to wszystko reklamy wewnętrzne / auto-promocja które nie są blokowane na POL repo, ale czy to od razu oznacza, że nie są też blokowane na EI?, skoro oprócz tego, że są reklamą wewnętrzną, to przecież są też popupem, więc jako popup i reklama wewnętrzna wg. CONTRIBUTING kwalifikują się do zablokowania na EI, no chyba, że CONTRIBUTING do poprawki:
`reklam zewnętrznych` ==> `reklam` albo ==> `reklam wewnętrznych i zewnętrznych`

> to w rogu raczej nie ma nawet własnego tła (o wirusie).

Wiem, chodziło mi tylko o ten duży popup / na środku, czego nie zasygnalizowałem, więc nie szkodzi że odpowiedziałeś, moje przegapienie.

**Comment by hawkeye116477** [comment]
Reklamy wewnętrzne/autopromocje jak najbardziej ukrywamy.

**Comment by gargul2** [comment]
No też tak właśnie myślałem, a komentarz krystiana odebrałem jakby w nim wyliczał to co się nie kwalifikuje, podając powody (no iglak akurat nie miał powodu podanego):

> Slider `iglaka` się nie liczy

Czyli nie kwalifikuje się

> `bntrade` nie ma faktycznego pop-upa (lubisz fiolet w tle, twój problem).

Czyli też nie kwalifikuje się, bo: `nie ma faktycznego pop-upa (lubisz fiolet w tle, twój problem).`

> Na `azun` to pop-up jest reklamą, 

Czyli znowu nie kwalifikuje się, bo: `to pop-up jest reklamą, `

> to w rogu raczej nie ma nawet własnego tła (o wirusie).

Czyli niekwalifikuje się bo: `raczej nie ma nawet własnego tła (o wirusie).`

To teraz nie wiem, czy to krystian pomylił się, że azun / reklam wewnętrznych nie blokujemy, a może źle się wyraził / sformułował kontekst komentarza, czy może to ja źle odczytałem kontekst komentarza? hawkeye a ty jak odczytałeś jego komentarz i to o `azun`?  W każym bądź razie najważniejsze, że już wyjaśnione, że popupy z reklam wewn. / autopromocją się kwalifikują do zablokowania.

**Comment by hawkeye116477** [comment]
`hawkeye to pewnie nigdy lektury w życiu nie przeczytał tylko same streszczenia`

Czytałem lektury, ale generalnie nie lubię za dużo czytać. Tyle tylko, że to nie lekcja języka polskiego, tutaj pisze się raczej, krótko i na temat, ale też, że by wszyscy skumali o co chodzi :smile:

> 
> Slider iglaka się nie liczy
> 
> Czyli nie kwalifikuje się

Jakby było w pop-upie, to wtedy chowamy. Natomiast w takiej formie slidera jest akceptowalne, ale Konoromi lubi takie ukrywać.


> To teraz nie wiem, czy to krystian pomylił się, że azun / reklam wewnętrznych nie blokujemy, a może źle się wyraził / sformułował kontekst komentarza

Raczej @krystian3w źle się wyraził, czasem sam nie mogę zrozumieć co miał na myśli.

**Comment by gargul2** [comment]
> Czytałem lektury, ale generalnie nie lubię za dużo czytać.

To tak jak ja.

> Tyle tylko, że to nie lekcja języka polskiego, tutaj pisze się raczej, krótko i na temat, ale też, że by wszyscy skumali o co chodzi 

Stary ale zrozum, myślisz, że ja chcę pisać "eseje"? Nie, ale często jestem zmuszony pisać bo za pomocą samych fraszek i miniatur, które tak lubisz, to się nie idzie dogadać, czego przykładem jest ten wątek pełny nieporozumień i wszystko trzeba szczegółowo omawiać i dopytywać się żeby zrozumieć kontekst, a to wymaga niestety rozpisania się, ty byś chciał króko, zwięźle i żeby wszystko było w tym zawarte, to tak jakbyś chciał zjeść ciastko i mieć ciastko, a tak się nie zawsze da.

> Tyle tylko, że to nie lekcja języka polskiego,

No właśnie, doceniam samokrytykę, więc fajnie byłoby gdybyś nie wchodził w rolę polonisty i nie narzucał innym jaką długość mają mieć czyjeś komentarze... zwłaszcza, że tobie nikt tego nie narzuca, no i obyś zaraz nie zaczął wytykać błędów ortograficznych, bo to nie dyktando, hahaha

> tutaj pisze się raczej, krótko i na temat, ale też, że by wszyscy skumali o co chodzi smile

krystian [napisał ](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1916#issuecomment-639811830) krótko a i tak był problem z rozszyforwaniem kontekstu `azzun,` co sam przyznałeś, hahaha

hawkeye może ty pomyliłeś github z czatem? o ile wiem to na czacie pisze się komentarze o takiej długości jakie ty piszesz, hahaha, a gtihub jest raczej dla inteligentnych ludzi, którzy mają w głowie coś więcej, a ludzie, którzy mają w głowie coś więcej, zazwyczaj piszą więcej, hahaha chociaż czasem trafiają się krowy, które dużo muczą a mało mleka dają, hahaha

> > Slider iglaka się nie liczy
> > Czyli nie kwalifikuje się
> 
> Jakby było w pop-upie, to wtedy chowamy. Natomiast w takiej formie slidera jest akceptowalne, ale Konoromi lubi takie ukrywać.

Z `iglakiem` i `bntrade` to nie było pytanie, tylko stwierdzenie, co już krystianowi tłumaczyłem [na początku tego komentarza](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1916#issuecomment-639988059), bo źle odczytał kontekst, więc nie wiem po co komentujesz tak jak on. Z `Czyli nie kwalifikuje się` to też nie pytanie, a jedynie stwierdzenie, przedstawiłem jak odczytałem jego komentarz.

> Raczej @krystian3w źle się wyraził, czasem sam nie mogę zrozumieć co miał na myśli.

Hehe, bo on pisze pismem dla inteligentnych, nie dla byle głupków, dlatego dopuściłem możliwość, że z tym `azzun` to nie on się pomylił, tylko ja czegoś nie rozszyfrowałem, hmm może założył że napisanie, że to reklama to wystarczy, i samemu trzeba sobie wydedukowac, że skoro "reklama" nie jest odrzucona przez CONTRIBUTING to kwalifikuje się do zablokowania, tylko ja poległem na tym, czy samo słowo "reklama" oznacza reklamę wewnętrzną czy zewnętrzną czy dowolną z nich? + fakt, że wszystko inne co wymienione w jego komentarzu nie kwalifikuje się, więc pomyślałem, że kontekst komentarza jest taki, że wszystko wymienione w komentarzu nie kwalifikuje się, wiec `azzun` też nie.  Bo to tak jak z serem albo samochodem, jak ktoś powie samo "ser" / 
"samochoód", to chodzi mu o jaki ser? o żołty? biały? topiony? i o jaki samochód? osobowy? ciężarowy? wyścigowy? a może o dowolny z nich, więc samo słowo "ser" / "samochód" czy "reklama" to raczej określenie rodzaju produktu, ale nie jego konkretnej odmiany, hahahaha

hawkey może ty lepiej tego "eseju" nie czytaj, bo za wysokie progi? Prędzej na czacie znajdziesz kolegów, któzy piszą po jednym zdaniu hahahaha

**Comment by hawkeye116477** [comment]
Dobra, dobra, czasem potrafisz rozwlekać, niczym Polsat z Wydarzeniami, zresztą chyba ktoś inny miał już podobne uwagi co do twoich wypowiedzi :smiley:

**Comment by gargul2** [comment]
Github to też nie czat żeby dukać po jednym zdaniu, ani nie rozmowa przez komórkę żeby pisać sms-ami.

Jak przerzutka na czat ci nie pasuje, to jak chcesz mieć krótko i zwięźle to może sobie kup kobyłę i trzymaj ją na uwięzi krótko i zwięźle...ale nie człowieka, zwierzęta nia mówią, więc nie będziesz musiał kobyły wysłuchiwać, a jak będziesz jechał dorożką w zaprzęgu albo na koniu to nawet 1 zdania nie będziesz musiał mówić, bo wystarczy 1 słowo: `wio` albo `prrr`, myslę, że będziesz bardzo zadowolony, ewentualnie jak nie stać cię na konia to możesz muchę złapać i trzymać w słoiku, a jak podczas karmienia wyleci ci ona ze słoika, i zacznie natrętnie latać, to co najwyżej ją odgonisz mówiąc `sio`. Krócej i zwięźlej się nie da, więc myślę, że ze zwierzętami ci będzie lepiej, one nie mówią w ogóle, a ty nie będziesz musiał też dużo, ewentualnie możesz zamieszkać w Zoo albo w dżungli, tudzież w lesie w chatce na kurzej stopie, nie będziesz musiał wysłuchiwać żadnych długich wypowiedzi, co najwyżej śpiew ptaków, pohukiwania sowy, krakanie gawronów, albo okazjonalne piski czy ryki dziczyzny leśnej, a jeśli nawet to ci nie pasuje, to możesz kupić do domu akwarium z rybkami, tylko wtedy pompka może buczeć...

A w ogóle inteligentni ludzie piszą więcej bo mają w głowie coś więcej niż tylko sznurek, który trzyma uszy żeby nie odpadły....

:smiley:

**Comment by hawkeye116477** [comment]
`Github to też nie czat żeby dukać po jednym zdaniu, ani nie rozmowa przez komórkę żeby pisać sms-ami.`
`Krócej i zwięźlej się nie da`

Widzę, nie lubisz przyznawać, że może ktoś inny jednak miał rację. Ja tam myślę, że czasem jednak dałoby się krócej, ale najwyraźniej nie dasz się przekonać. Albo po prostu może lubisz dużo mówić, plotkować i dlatego tak przekonujesz.

**Comment by gargul2** [comment]
> Widzę, nie lubisz przyznawać, że może ktoś inny jednak miał rację. 

To raczej ja mógłbym napisać to w twoją stronę... a co do mnie, to nie mam problemu w przyznawaniu komuś racji, jeśli rzeczywiście ją ma i sensownie ją uzasadni argumentami, a nie za wszelką cenę próbuje chyba nawet całemu światu udowodnić, że każdy post dłuższy od twojego jest zły, no nie wiem to może lepiej byłoby gdybyś założył jakiś wątek na głównym repo githuba pod tytułem "wszyscy na githubie powinni pisać krótkie komentarze" albo "ograniczenie długości komentarza do iluś tam linijek" tudzież "krótsze komentarze są lepsze od dłuższych"  i byś w takim wątku tam wszystkich przekonywał.

> A tam myślę, że czasami jednak dałoby się krócej, ale najwyraźniej nie dasz się przekonać.

Pisałem we wcześniejszym komentarzu, że gdzie się da to staram się, ale nie zawsze się da, bo trudno odnieść się do tylu różnych kwestii i napisać o tylu różnych szczegółach w paru krótkich zdaniach.

> Albo po prostu może lubisz dużo mówić, plotkować 

Lubię komuś dokładnie wyjaśnić żeby nie było niedomówień, źle odebranego kontekstu, nieporozumień, czasem tylko lubię poswaworzyć, jak to kulfon z długim czerwonym nochalem drapiący po uszach pozytywnych januszy internetu

> i dlatego tak przekonujesz do swoich racji.

Nie potrzebuję nic nikomu na siłę udowadniać, ale też nie pozwolę żeby ktoś mi coś na siłę udowadniał.

> Cóż, trudno, ja cię nie zmienię ani ty raczej mnie też nie.

Ale mnie to nie mieszaj w te twoje zmienianie, bo ja nie próbuję nikogo zmienić, póki co to ty ciągle próbujesz zmienić moje komentarze na krótsze, a ja jedynie się z tym nie zgadzam, ale nigdzie ci nie każę pisać dłuższych komentarzy takich jak ja, bo ja nikomu nic nie narzucam, bo wg. mnie każdy sam decyduje o swoich komentarzach i nie wiem w ogóle jak można aż tak mocno komuś coś narzucać, rozumiem, że mam też chodzić w krókich spodenakch, słuchać krótkich piosenek i oglądać krótkie filmów, krótko robić kupę, wybacz ale lubię się czasem porządnie powoli i na spokojnie wysrać bez pośpiechu...

**Comment by hawkeye116477** [comment]
> To raczej ja mógłbym napisać to w twoją stronę

Jesteś przewidywalny, spodziewałem się, że tak napiszesz.

> każdy post dłuższy od twojego jest zły

To już lekko nadinterpretowane, mówiłem, że nieco zbyt długi, co nie oznacza też, że ma być nie dłuższy niż mój.


A zresztą, moglibyśmy tu gadać długie godziny, ale cóż, chyba nie ma co kontynuować dalej tematu.

**Comment by gargul2** [comment]
> Jesteś przewidywalny, spodziewałem się, że tak napiszesz.

Może po prostu lubisz zarzucać komuś coś co jest tak naprawdę twoją przywarą, czyli odwracać kota ogonem, więc pozostaje mi to tylko odkręcić spowrotem...

> A zresztą, moglibyśmy tu gadać długie godziny, ale cóż, chyba nie ma co kontynuować dalej tematu.

Tak jak już napisałem, skoro tak bardzo starasz się przekonać kogoś do krótkich komentarzy, to chyba marnotrawstwem czasu i wysiłku jest przekonywanie do tego tylko jednej osoby (mnie), powtarzam propozycję, żebyś założył wątek na głownym repo githuba i przekonał całę rzesze (setki może tysiące osób) żeby zaczęli pisać krókie komentarze, a może nawet wymusisz na administracji githuba żeby wprowadzili limit długości komentarza, skoro jesteś tak mocno przekonany o swojej racji to dlaczego nie spróbujesz? My z krystianem byśmy jakiś dobry popcorn z sererm kupili, żeby śledzić dyskusję.

:smiley:
