### ISSUE TITLE
tova.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1930]
![capture_087_05-06-2020_10-19-09](https://user-images.githubusercontent.com/63287518/83853749-05675a80-a716-11ea-8a90-4ee8a8114ac5.gif)

**Comment by krystian3w** [comment]
`##.popmake-overlay.pum-overlay.pum` trzeba by chyba kolejny raz przejrzeć co jeszcze się da w html-filteringu.

Może i `:remove()` coś da?

**Comment by hawkeye116477** [comment]
To skoro nie trzeba scrolla odblokować, to nie lepiej to przenieść do reguł dla ABP?

**Comment by krystian3w** [comment]
Ale prawy margines? Tego ich JS do bycia KULL nie nadpisuje, niby nie lubisz jak wycinanie robi margines i go nie korygujemy.

**Comment by hawkeye116477** [comment]
Ah, no tak, ale można też inaczej :smile:

**Comment by krystian3w** [comment]
Czyli ABP z marginesem a uBO / AG kortekta?
