### ISSUE TITLE
marchewkowepole.com

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1931]
![capture_088_05-06-2020_16-36-04](https://user-images.githubusercontent.com/63287518/83888876-b7207e80-a74a-11ea-8738-3dbec2998809.gif)

**Comment by krystian3w** [comment]
Chyba trzeba zostawić do poniedziałku, jak nie umieją zrobić pola wyboru "odbiór"/dostawa".

**Comment by krystian3w** [comment]
W sumie do wycięcia, jest podział "odbiorę osobiście o", jak ktoś poda że obierze po minucie to jego problem jak danie robią 30 min w okolicy września 2020.
