### ISSUE TITLE
duzekubki.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1942]
![capture_102_05-06-2020_17-28-22](https://user-images.githubusercontent.com/63287518/83894754-06b67880-a752-11ea-88b5-f740fbcb9b77.gif)

**Comment by hawkeye116477** [comment]
Fajne kubki mają => https://duzekubki.pl/p/u-mnie-dziala/ :smiley:

**Comment by gargul2** [comment]
:rofl:
