### ISSUE TITLE
bedziepieklo.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1950]
![capture_111_05-06-2020_18-07-33](https://user-images.githubusercontent.com/63287518/83898662-82ff8a80-a757-11ea-987c-017514367a88.gif)

**Comment by hawkeye116477** [comment]
Co, nie lubisz grilla?

**Comment by krystian3w** [comment]
Już piecze.

**Comment by krystian3w** [comment]
Nic innego nie widzę, skryptu jak uAssets na anty-adblock w sowie chyba nie robimy (chociaż teraz to wycinają plik JS)?
