### ISSUE TITLE
azzun.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1952]
Wydzielone z https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1916#issuecomment-639289036

![](https://user-images.githubusercontent.com/63287518/83848815-b4079d00-a70e-11ea-9e9c-442bcf2d2cbd.gif)

**Comment by krystian3w** [comment]
Lewe nie, prawe tak.

**Comment by krystian3w** [comment]
Do dezaktywacji:

`azzun.pl##.scrollbar-track`, bo CSS nie wystarcza. Coś jak kiedyś autostrada a4.

```
azzun.pl###scroll-container:style(overflow: auto !important;)
azzun.pl##.scrollbar-track
azzun.pl##+js(...)
```

**Comment by hawkeye116477** [comment]
Wystarcza:
```
azzun.pl##.scrollbar-track
azzun.pl###scroll-container:style(overflow: auto !important; width: auto !important; height: auto !important;)
```
