### ISSUE TITLE
fundacjajoannyradziwill.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1963]
Nagabywanie do zapisania się i wyłudzanie danych pod przykrywką akceptacji rodo,  może da się powycinać te napisy i pola nagabywujące i wyłudzające emaijl itp. i zostawić samą akceptację rodo

![capture_121_06-06-2020_17-59-23](https://user-images.githubusercontent.com/63287518/83948794-27e59a80-a820-11ea-8187-ef376d58302f.gif)

**Comment by hawkeye116477** [comment]
`zostawić samą akceptację rodo`

Zgoda jest w formularzu do newslettera, więc raczej to nie do Filtrów Ciasteczkowych. Nie wiem, co by zrobił @krystian3w, ale ja raczej całość bym wyciął.

**Comment by krystian3w** [comment]
fresh mail nie oferuje plugina na paski i pop-upy rodo.
