### ISSUE TITLE
bestcentrum.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1965]
https://bestcentrum.pl/strona/index.php?prmtr=

![capture_124_06-06-2020_18-13-55](https://user-images.githubusercontent.com/63287518/83948993-865f4880-a821-11ea-94c5-1759d19628c8.gif)

**Comment by krystian3w** [comment]
Jak dla mnie reklama, a w kodzie strony trudny do znalezienia wybór "lekcji pokazowych (darmowych?)"?

**Comment by hawkeye116477** [comment]
W zasadzie to nic się nie dzieje po kliknięciu na to.
