### ISSUE TITLE
cmp.med.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1972]
Deklaracja POZ w CMP kwalifikuje się?

![capture_132_07-06-2020_12-03-48](https://user-images.githubusercontent.com/63287518/83965870-0b487180-a8b7-11ea-97c2-af98d5afb2e6.gif)

**Comment by krystian3w** [comment]
Ja bym zostawił, może ktoś musi na przyszłość zmienić placówkę już teraz a nie chce wydawać 50 złotych prywatnie na tele leczenie.
