### ISSUE TITLE
aliholik.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1973]
Niby covid, ale nie informacyjne raczej natrętna reklama

![capture_133_07-06-2020_12-12-24](https://user-images.githubusercontent.com/63287518/83966039-2cf62880-a8b8-11ea-880f-148a859fc902.gif)

**Comment by hawkeye116477** [comment]
Masa przekierowań z tego idzie i nawet już nie ma tej aukcji.
