### ISSUE TITLE
myjki.com

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1974]
Podobnie jak w https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1973, niby COVID ale raczej wykorzystywanie COVID do nagabywania, aniżeli jakaś informacja o COVID.

![capture_134_07-06-2020_12-16-50](https://user-images.githubusercontent.com/63287518/83966153-cb828980-a8b8-11ea-9446-5458869168df.gif)

**Comment by hawkeye116477** [comment]
Jeszcze jest też ten nie lubiany szczególnie przez @krystian3w modyfikator tytułów. Niby można z niego, że tak powiem zrezygnować (`myjki.com##+js(addEventListener-defuser, blur)`), ale wtedy formularze się trochę popsują.

**Comment by hawkeye116477** [comment]
W tym problem, że to nie jest pop-up, tylko element slidera.
