### ISSUE TITLE
splacepark.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#1995]
![capture_159_07-06-2020_13-48-42](https://user-images.githubusercontent.com/63287518/83967902-9f213a00-a8c5-11ea-8a48-cf1c843340d9.gif)

**Comment by blocker999** [comment]
help scroll

**Comment by krystian3w** [comment]
@blocker999  przy problematycznych z scrollem to najwyżej jako komentarz dodaj, tak by nie trzeba przenosić po fakcie do suplementów.
