### ISSUE TITLE
klinika.krakow.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2010]
![capture_186_07-06-2020_18-50-16](https://user-images.githubusercontent.com/63287518/83974734-bffe8500-a8ef-11ea-877d-1c9d30b610ed.gif)

**Comment by blocker999** [comment]
@hawkeye116477  informacyjny ?

**Comment by hawkeye116477** [comment]
Tak, raczej chyba zostawimy.
