### ISSUE TITLE
arteodevelopment.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2016]
Widżet kontaktowy w okienku:

![capture_195_08-06-2020_15-17-27](https://user-images.githubusercontent.com/63287518/84034865-34423280-a99b-11ea-9fc0-5c2c50184596.gif)

**Comment by hawkeye116477** [comment]
@krystian3w A jak ktoś będzie chciał skorzystać z przycisku? Blokada okienka psuje przycisk.
