### ISSUE TITLE
niezalezna.pl + gazetapolska.pl + naszeblogi.pl + panstwo.net

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2018]
![capture_200_08-06-2020_16-04-56](https://user-images.githubusercontent.com/63287518/84039637-d402bf00-a9a1-11ea-9a5c-6bff95c7d948.gif)

![capture_203_08-06-2020_16-35-18](https://user-images.githubusercontent.com/63287518/84043021-162dff80-a9a6-11ea-94c1-50fc6279d833.gif)

![capture_205_08-06-2020_16-40-52](https://user-images.githubusercontent.com/63287518/84043677-e7fcef80-a9a6-11ea-8976-2b0c2d859bfd.gif)

![capture_206_08-06-2020_16-43-31](https://user-images.githubusercontent.com/63287518/84043953-38744d00-a9a7-11ea-94e1-a55a56393e51.gif)

![capture_207_08-06-2020_16-43-33](https://user-images.githubusercontent.com/63287518/84043960-3a3e1080-a9a7-11ea-8fa8-b285c5e2bedb.gif)

**Comment by hawkeye116477** [comment]
Same najciekawsze strony...
