### ISSUE TITLE
bgzoptima.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2021]
![capture_204_08-06-2020_16-38-20](https://user-images.githubusercontent.com/63287518/84043372-7c1a8700-a9a6-11ea-8341-bdb5cddc2908.gif)

**Comment by hawkeye116477** [comment]
Czy ja wiem, takiego nielota może lepiej zostawić.

**Comment by krystian3w** [comment]
No artystę z tym przewijaniem to poniosło.
