### ISSUE TITLE
gpcodziennie.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2022]
![capture_208_08-06-2020_16-45-01](https://user-images.githubusercontent.com/63287518/84044109-6bb6dc00-a9a7-11ea-9cae-834eb11149b9.gif)

**Comment by hawkeye116477** [comment]
@MajkiIT Na górze jest resztka po reklamie.

**Comment by krystian3w** [comment]
Dalej to jest teraz resztką reklamową?

**Comment by krystian3w** [comment]
Duplicate of #2219

**Comment by gargul2** [comment]
> Duplicate of #2219

Wyjaśnienie: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2135#issuecomment-650110575
