### ISSUE TITLE
nbi.com.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2027]
https://github.com/MajkiIT/polish-ads-filter/issues/16496

Już się pogubiłem, czy ta reklama zewnętrzna w okienku kwalifikuje się do filtrów reklamowych (jako reklama zewnętrzna, których EI niby nie blokuje) czy do filtrów irytujących (jako wyskakujące okienko), a może kwalifikuje się na obydwie listy.

**Comment by hawkeye116477** [comment]
Jak sam powiedziałeś, jest to reklama zewnętrzna, a więc do Majkela.

**Comment by gargul2** [comment]
> bo u niego to różnie bywa...

Dokładnie, tak jak np. [wczoraj](https://github.com/MajkiIT/polish-ads-filter/issues/16483#issuecomment-640424641), hahaha

**Comment by krystian3w** [comment]
W sumie jest źle; nie widać poprawki, by lista reklamowa/anty-adblockowa odblokowała to, a pewnie nie 100% ma aktywne w tle polskie EI (ktoś zostanie na lodzie z czarnym tłem).

**Comment by hawkeye116477** [comment]
No właśnie, @MajkiIT dlaczego zamknąłeś zgłoszenie https://github.com/MajkiIT/polish-ads-filter/issues/16496 bez jakiejkolwiek poprawki? Jeżeli nie chcesz tego elementu wycinać, może kiedyś przez pomyłkę dodane, to powinieneś usunąć tę regułę, a nie zostawiać bez zmian, popsute...

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/commit/38c7817b3dc36b8ba36fc96e8f314a45729443fb
