### ISSUE TITLE
belvederehotel.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2033]
![capture_222_09-06-2020_10-29-36](https://user-images.githubusercontent.com/63287518/84124967-314b4e80-aa3c-11ea-974b-51a3eaeb0cf8.gif)

**Comment by hawkeye116477** [comment]
Tutaj trochę przekombinowałem => `belvederehotel.pl##.fancybox-overlay-fixed:not(:has(.fancybox-nav)):watch-attr(class)` i problem w tym, że AdGuard tego nie obsłuży. Może ktoś ma lepszy pomysł?

**Comment by krystian3w** [comment]
Jak dla mnie AdGuard umie, tylko w Vivaldim niby bugi robi wbudowanych obrońca prywatności przy pomocy EasyList/EasyPrivacy.

**Comment by hawkeye116477** [comment]
@krystian3w A skąd, wyłączyłem wszystkie listy i nadal jest błąd na `http://www.belvederehotel.pl/dla-rodziny/o-nas`, za drugim razem się uaktywnia.

**Comment by krystian3w** [comment]
Najlepiej nie wchodzić bezpośrednio w dział, na moje zostaje skrypt przerywający pop-up (ciastek nie pieką) lub html-filtering jak voucher widać w html i nie robią myków z xhtml lub znakami w ISO-XXXX-X.

**Comment by AdamWr** [comment]
>nadal jest błąd na `http://www.belvederehotel.pl/dla-rodziny/o-nas`, za drugim razem się uaktywnia, szczególnie jak się szybko klika raz za razem (miniaturka się pokazuje jedynie)

Zgaduję, że problem polega na tym, że przez pewien czas ten popup jest ukryty, a szerokość i wysokość tego obrazka jest ustawiana na "auto". Jak się zmieni rozmiar okna przeglądarki, to rozmiar obrazka wraca do "normalnej" wielkości.

**Comment by hawkeye116477** [comment]
Tak czy siak, skryptlet działa perfekcyjnie, więc sprawa rozwiązana.
