### ISSUE TITLE
containex.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2037]
http://www.containex.pl/pl popup + widżet kontaktowy

![capture_226_09-06-2020_11-10-19](https://user-images.githubusercontent.com/63287518/84129135-dae10e80-aa41-11ea-9a9a-c45685dd0561.gif)

**Comment by gargul2** [comment]
> popup + widżet kontaktowy

Właśnie, jak dodać 2 etykiety?

**Comment by hawkeye116477** [comment]
> Właśnie, jak dodać 2 etykiety do jednego zgłoszenia?

Generalnie niby można np.  tak `labels=duplikat,social`, ale podejrzewam, że to raczej działa tylko jeżeli masz odpowiednie uprawnienia. W innym przypadku działają tylko szablony

W przypadku EI albo Sociala, po prostu wybierz szablon `Inne sprawy` i tam możesz zaznaczyć parę pól, by dodać kilka etykiet. Majkel nie ma bota etykietującego, więc u niego taki myk nie przejdzie.

**Comment by gargul2** [comment]
> `Inne sprawy (np. zbiorcze zgłoszenie paru różnych elementów)` 

hahaha a no rzeczywiście, widziałem to ze 20 razy, a i tak o tym zapomniałem, kulfon - jak ty czytasz! hahaha ! Ale w sumie może dlatego, że jest poza ekranem i na samym dole, więc jakoś umknęło.
