### ISSUE TITLE
apartamentyzdrowie.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2040]
![capture_229_09-06-2020_16-06-18](https://user-images.githubusercontent.com/63287518/84157677-4db2af80-aa6b-11ea-9965-e1607830877d.gif)

**Comment by hawkeye116477** [comment]
Hakerzy się chyba bawią...

**Comment by krystian3w** [comment]
Ja bym wyciął, może do kilku dni naprawią SSL lub usunął formularze ze strony.
