### ISSUE TITLE
innergo.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2052]
Info o zdalnej pracy nie wiem czy w kontekście covid czy po prostu spam, zadecydujcie sami.

![capture_004_10-06-2020_14-44-22](https://user-images.githubusercontent.com/63287518/84269112-0e4a9880-ab29-11ea-931a-7d9bc9441172.gif)

**Comment by krystian3w** [comment]
Jak dla mnie to w tym wypadku ich reklama.
