### ISSUE TITLE
topplant.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2058]
![capture_011_10-06-2020_17-09-17](https://user-images.githubusercontent.com/63287518/84285010-38a65100-ab3d-11ea-8b39-2a99d2cadabe.gif)

**Comment by hawkeye116477** [comment]
No to ładnie, z listą Fanboya wygląda to niezbyt elegancko, pop-up załadowany jest do połowy.

@krystian3w Co z tym robimy, zgłaszamy, że by dodał wyjątek czy co?

**Comment by krystian3w** [comment]
Zgłoszone, może odblokują ramkę, dla uBO i wspieranych AG ja bym przywrócił blokowanie, klika KiB mniej ładowania.

**Comment by hawkeye116477** [comment]
@krystian3w `https://developers.facebook.com/docs/plugins/page-plugin/`
Może być zbyt ogólne jak na sam pop-up.
