### ISSUE TITLE
ipbilawa.com.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2061]
![capture_015_10-06-2020_20-30-17](https://user-images.githubusercontent.com/63287518/84304856-70bb8d00-ab59-11ea-91ff-2f90f761708a.gif)

**Comment by hawkeye116477** [comment]
Informacja się zmieniła już, w tym wypadku chyba jednak to zostawimy.

**Comment by krystian3w** [comment]
Ja mam identyczny, jak dla mnie to już reklama.

**Comment by gargul2** [comment]
Dla celów archiwalnych żeby było wiadomo, że zawartość popupa się zmienia, teraz faktycznie informacyjny zamiast reklamy:

![capture_077_13-06-2020_17-46-55](https://user-images.githubusercontent.com/63287518/84572983-03e50480-ad9e-11ea-8180-51cd65ed831a.gif)
