### ISSUE TITLE
solidsecurity.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2069]
Zdecydujcie sami czy to w kontekście ubezpieczenia przeciwko COVID...(czy mają możliwość ubezpieczenia na wypadek śmierci na skutek choroby np. COVID) a może to raczej ogólnie czyli spam:

![capture_022_11-06-2020_10-39-26](https://user-images.githubusercontent.com/63287518/84364041-df3b3200-abcf-11ea-9c4f-d4ed3aa0d553.gif)

**Comment by hawkeye116477** [comment]
To jest autoreklama.
