### ISSUE TITLE
depilacja.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2071]
Nielot, podobne do https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2021#issuecomment-640685692, tamten nielot odrzucony, ale nie napisane czy wszystkie nieloty  są odrzucane czy tylko niektóre.

![capture_024_11-06-2020_10-45-49](https://user-images.githubusercontent.com/63287518/84364692-b7989980-abd0-11ea-87b6-04f466a60949.gif)

**Comment by krystian3w** [comment]
Wszystkie nie latające, zostają nawet niektóre widgety:
  `[id^="mc4wp_form_widget"].widget_mc4wp_form_widget`
