### ISSUE TITLE
um.jaslo.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2073]
Ankieta ponoć się kwalifikuje: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/159#issue-261615002 : `! usunięcie popupa z ankietą`, chyba, że coś się zmieniło w tym zakresie, ale czy każda ankieta?  Czy ankieta informacyjna kwalifikuje się jako informacyjny?

![capture_026_11-06-2020_11-00-46](https://user-images.githubusercontent.com/63287518/84366245-da2bb200-abd2-11ea-8789-28c48e64fe80.gif)

**Comment by krystian3w** [comment]
Bez headera - ten tu: https://github.com/KonoromiHimaries/PolishSubFilters
