### ISSUE TITLE
prettyone.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2077]
### Typ elementu/problemu
- [X] Wyskakujące okienko (popup)
- [] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Błąd
- [] Pytanie
- [] Ulepszenie

![capture_031_11-06-2020_11-53-45](https://user-images.githubusercontent.com/63287518/84371622-3b0ab880-abda-11ea-8ea7-6d6a6a6dbf66.gif)

**Comment by gargul2** [comment]
Gdzie ten robot, dlaczego nie poprawił etykiety.

**Comment by gargul2** [comment]
O jednak jest w końcu hehe, dodał `popup` ale Push mi nie usunął, hawkeye trzeba uzupełnić forumulrz o etykiete `Push` ?

**Comment by hawkeye116477** [comment]
@gargul2 Przecież jest, 3 od góry :stuck_out_tongue:

**Comment by gargul2** [comment]
Ooo znowu się pojawił robot i w końcu usunął `push` , ale znowu dopiero jak kulfon zaczął kręcić nochalem hahaha, ten robot to chyba był sterowany z tylnego fotela przez hawkeye  :rofl:

**Comment by gargul2** [comment]
To ja przeoczyłem ten `push` OMG.

**Comment by gargul2** [comment]
I znowu lecą w kulki, a gdzie to ogłoszenie testowe co hawkeye testował robota etykietującego przec chwilą? Wyparowało z issue trackera czy gdzie ono jest. jaja, i pewnie znowu kulfon głupek bo nie widzi tego zgłoszenia.

**Comment by gargul2** [comment]
Kulfon [jak ty czytasz](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2037#issuecomment-641205421)!  hahaha

**Comment by hawkeye116477** [comment]
@gargul2 Jeżeli chodzi o opóźnienia, to najwyraźniej są jakieś problemy po stronie hostingu bota => https://status.glitch.com/.
