### ISSUE TITLE
bitner.com.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2080]
![capture_036_11-06-2020_12-54-35](https://user-images.githubusercontent.com/63287518/84377346-bcfedf80-abe2-11ea-9212-96cd440a9e96.gif)

**Comment by hawkeye116477** [comment]
Hehe, IDCAC wycina tego pop-upa.

Oni sobie w skrypcie ciacho robią i używają go do wyświetlania tego okienka i być może czegoś innego jeszcze.

**Comment by hawkeye116477** [comment]
@kiboke I didn't see great self-advertisement with IDCAC, so can you add exclusion => 
`@@||bitner.com.pl/plugins/cookiebar/jquery.cookiebar.js`?

**Comment by gargul2** [comment]
Dalej jest overlay / tło / cień jak na screenshocie.

**Comment by hawkeye116477** [comment]
Najwyraźniej, IDCAC też schował te tło.

**Comment by kiboke** [comment]
I don't see any problem with this website.
