### ISSUE TITLE
fajerwerki.shop.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2087]
![capture_044_11-06-2020_13-37-48](https://user-images.githubusercontent.com/63287518/84381088-c3905580-abe8-11ea-85c6-ae050e5c1868.gif)

**Comment by hawkeye116477** [comment]
Już 🎆 kupujesz? Przecież do Nowego Roku jeszcze kupa czasu...
