### ISSUE TITLE
projektowanie-wnetrz-online.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2094]
![capture_052_11-06-2020_18-29-06](https://user-images.githubusercontent.com/63287518/84414010-ade35600-ac11-11ea-8fd0-4dadbaee2359.gif)

![capture_053_11-06-2020_18-29-09](https://user-images.githubusercontent.com/63287518/84414017-af148300-ac11-11ea-88ef-30466b31bf77.gif)

**Comment by hawkeye116477** [comment]
@gargul2 Wszystkie typy nie muszą być koniecznie wypisane, ale niestety serwer ma lagi i chyba już tak od paru dni jest => https://status.glitch.com/ i coś nie mogą naprawić, ale ja też nie płacę, korzystam za friko, więc nie mogę zbyt wiele wymagać... Tak czy siak, przepraszamy za problemy techniczne.

**Comment by gargul2** [comment]
Spoko, gitara gra, jakoś damy radę.

**Comment by krystian3w** [comment]
Lewa kolumna to może w PASS jak nie zabije to wydajności strony.

**Comment by krystian3w** [comment]
Trzeba poziom wyżej chwycić feedback...
