### ISSUE TITLE
zygzaksnow.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2098]
![capture_058_11-06-2020_18-55-30](https://user-images.githubusercontent.com/63287518/84417106-6e1e6d80-ac15-11ea-9893-3a7064be075f.gif)

**Comment by hawkeye116477** [comment]
To jest info po RODO, ale jest już ono ukrywane w liście Ciasteczkowej.

**Comment by gargul2** [comment]
> ale i też ten pop-up nawet z modułem samym nie jest pusty.

Tylko na chromowatych, bo na Firefoxie JEST pusty.

**Comment by hawkeye116477** [comment]
> Tylko na chromowatych nie jest pusty, bo na Firefoxie jest pusty.

@gargul2 No to chyba coś u ciebie nie trybi, coś musiałeś majsterkować, bo sprawdziłem i jest tak samo jak na chromowatych, ba nawet z włączoną ochroną przed oczami ciekawskich...

**Comment by gargul2** [comment]
> coś musiałeś majsterkować,

Świeży goły nie tknięty profil utworzony po twoim komentarzu, ciekawe co mogłem zmajsterkować nie dotykając niczego poza przyciskiem utworzenia i uruchomienia nowego profilu:

![capture_072_13-06-2020_16-54-03](https://user-images.githubusercontent.com/63287518/84571869-8b2e7a00-ad96-11ea-9499-c2427f061181.gif)

**Comment by gargul2** [comment]
Jakaś nawiedzona strona - na innym profilu Firefox, na którym nigdy wcześniej też się nie pojawił, teraz się nagle zaczął pojawiać:

![capture_075_13-06-2020_16-59-53](https://user-images.githubusercontent.com/63287518/84571988-6555a500-ad97-11ea-862b-5f99207dab01.gif)

**Comment by gargul2** [comment]
Na jeszcze innym (3) profilu jak nigdy się nie pojawiał, dalej się nie pojawia.

**Comment by hawkeye116477** [comment]
No to albo dają ci inną wersję strony albo to naprawdę jakieś problemy po twojej stronie (może net szwankuje?) albo szwankuja ochrona przed ciekawskimi...

**Comment by gargul2** [comment]
> albo to naprawdę jakieś problemy po twojej stronie (może net szwankuje?) albo szwankuje ochrona przed ciekawskimi albo po prostu strona ma błąd, co czasem się objawia...

Gówno prawda.

> A to też nie jest WP, więc przypadek z inną wersją strony dla innych raczej odpada.

> No to albo dają ci inną wersję strony 

To się zdecyduj w końcu, tak czy inaczej, niezależnie od tego czy się w końcu zdecydujesz, czy nie, faktycznie dają inną wersję, a dokładniej, przy wchodzeniu na `https://zygzaksnow.pl/`:
- raz wchodzi na `https://zygzaksnow.pl/pl/` gdzie jest treść komunikatu, 
- a innym razem przekierowuje na `https://zygzaksnow.pl/en/` gdzie nie ma treści komunikatu - jest puste



Wniosek: pieprzona strona bawi się w ciuciu

**Comment by hawkeye116477** [comment]
> To się zdecyduj w końcu,

Niestety moja magiczna kula się popsuła, więc nie mogę przedstawić jednoznacznej odpowiedzi. Ale spokojnie zawiozłem do speca, za parę godzin naprawi, to wtedy lepiej odpowiem :stuck_out_tongue:

**Comment by gargul2** [comment]
A z ciekawości zapytam, żeby rozwiać wszelkie wątpliwości - czy masz na `https://zygzaksnow.pl/en/` treść komunikatu?

**Comment by hawkeye116477** [comment]
@gargul2 No tutaj, faktycznie nie ma i tak samo jest bez adblockera, więc to raczej sprawa dla webmastera.

**Comment by gargul2** [comment]
To że jest puste bez adblockera to wiedziałem już, zanim to zgłoszenie założyłem, dlatego nie dałem etykiety `błąd`, bo by sugerowała mylnie że to błąd w filtrach.

**Comment by hawkeye116477** [comment]
@gargul2 To tak na przyszłość powiem, pustych nie usuwamy. A może to tak specjalnie, by wytknąć, że nie napisane, że pustych nie usuwamy :stuck_out_tongue:

**Comment by gargul2** [comment]
> A może to tak specjalnie zgłoszone, by wytknąć,

Na pewno nie specjalnie - że pustych nie usuwacie nie wiedziałem.

> że nienapisane, że pustych nie usuwamy 

A to prawda, nigdzie nie mieliście napisane, a po tym zgłoszeniu uzupełniliście w CONTRIBUTING, więc to zgłoszenie jednak na coś się przydało.

> To tak na przyszłość powiem

To w takim ja też coś powiem przy okazji, a raczej zapytam, i zrobiłbym to w [bardziej odpowiednim wątku](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1916#issuecomment-639988059) ale zablokowałeś (domyslam się, że to ty): dlaczego w [CONTRIBUTING](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/master/CONTRIBUTING.md) nie zostało dodane jedno z [proponowanych przeze mnie wpisów](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1916#issuecomment-639988059):

> - komunikatów o pełnoletniości

Ktoś zapomniał?

**Comment by hawkeye116477** [comment]
`A to prawda, nigdzie nie mieliście napisane, a po tym zgłoszeniu uzupełniliście w CONTRIBUTING, więc to zgłoszenie jednak na coś się przydało, pomimo, że jak wyżej - nie było to pierwotnym celem zgłoszenia.`

No może i się przydało, choć ja bym powiedział, że to oczywiste, że takich nie usuwamy, bo skoro mamy pewne wyjątki co do pop-upów, no to znaczy, że w ciemno nie usuwamy. Dlatego też stwierdziłem, że ty tak pewnie też uważasz i specjalnie to zgłosiłeś, żeby potem mieć pretensje...

`dlaczego w CONTRIBUTING nie zostało dodane jedno z proponowanych przeze mnie wpisów:`

A to już pytanie do @krystian3w, on wtedy dodawał informacje dot. pop-upów. Tak czy siak, zaktualizowałem już.

**Comment by gargul2** [comment]
> choć ja bym powiedział, że to oczywiste (...)

Co oczywiste dla was, to nie znaczy że od razu dla wszystkich, bo wy siedzicie tu długi czas i na co dzień zajmujecie się zgłoszeniami, to wam jest o wiele łatwiej coś sklasyfikować. 

> Dlatego też stwierdziłem, że ty tak pewnie też uważasz i specjalnie to zgłosiłeś, żeby potem mieć pretensje, bo z tobą to różnie bywa...

Nie medytowałem zbytnio nad tym popupem, widziałem pusty bezużyteczny i przeszkadzający popup to go zgłosiłem, może nie wszystko przyszło mi do głowy, może nie byłem pewny, to wolałem zgłosić, łatwo też się pogubić w dużej ilości różnych elementów, i coś może się wydawać tak, a nie inaczej, no ale przecież ty zawsze wiesz lepiej, że to po złości itp, bo masz swoją szklaną kulę i swoje teorie..hahaha

> bo z tobą to różnie bywa...

Na pewno nie tak jak z tobą - twoją szklaną kulą i teoriami, wg. których wszystko robię po złości...

> Wątek zablokował zarząd spółki, ponieważ był już tam lekki bałagan i uznali sprawę za rozwiązaną

A może raczej dlatego bo komuś skończyły się argumenty na swoje teorie hahaha

Jasne, właśnie widać jak bardzo rozwiązaną, że aż piszemy w 2-gim wątku...najśmieszniejsze będzie, jak zaraz znowu zostanie zablokowany również i ten wątek, i wtedy trzeba będzie w 3-cim kontynuować...tam były dwa wątki: jeden dotyczący zgłoszeń i drugi personalny między nami, i to że ten personalny został rozwiązany, to nie znaczy, że ten dotyczący zgłoszeń też, dowodem tego jest, że musze się dopytywać o zgłoszenia w kolejnym wątku. hahaha

**Comment by hawkeye116477** [comment]
> Na pewno nie tak jak z tobą - twoją szklaną kulą i teoriami, wg. których wszystko robię po złości...hahaha i nie tak jak z zarządem i jego zamykaniem wątków.

Bo wiem, że czasem lubisz czepiać się szczegółów, a bywa tak też, że jak my coś źle zrobimy, to ty też zaraz mówisz, że pewnie celowo tak zrobiliśmy :stuck_out_tongue: 

> no ale przecież ty zawsze wiesz lepiej, że to po złości itp, bo masz swoją szklaną kulę i swoje teorie..hahaha

Nie napisałem, że na 100% tak jest. Jak sam powiedziałeś, jednak nie, to ok, ja tego nie kwestionuję.

**Comment by gargul2** [comment]
> Wiem, że czasem lubisz czepiać się szczegółów i potem zaraz mówisz, że pewnie celowo tak zrobiliśmy 

Pisałeś o bałaganie, ale już nie o tym, że sam do niego doprowadziłeś swoją jałową dyskusją o moich "esejach", gdzie ja tylko odpierałem twoje zarzuty, więc o bałagan miej do siebie pretensje, a mi zamknąłeś wątek w którym chciałem dyskutować o kwestiach technicznych, przez co muszę teraz te same kwestie techniczne poruszać w innych wątkach, czyli w tym wątku, i tu znowu robisz to samo, znowu robisz bałagan, czepiając się mnie swoimi zarzutami wyssanami z palca, które ja tylko odpieram, a za chwilę "zarząd" znowu zamknie wątek z tego samego powodu - "bałagan", i będę musiał w 3-cim wątku kontynuować kwestie techniczne.

> Wiem, że czasem lubisz czepiać się szczegółów

Raczej to ty lubisz się czepiać się moich komentarzy np. z [poprzedniego wątku](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1916#issuecomment-639988059), doszukując się w nich złośliwości albo zarzucając, że są za długie ("eseje"), a a kolei w tym wątku, że problem z pustym komunikatem leży po mojej stronie, a następnie, że zgłoszenie założyłem celowo, żeby komuś coś wytknąć. A potem na koniec odwracasz kota ogonem, że to niby ja się lubię czepiać, a ty nie (bo o twoim własnym czepianiu jakoś dziwnym przypadkiem nie wspominasz nic).

> Nie napisałem, że na 100% tak jest. Jak sam powiedziałeś, jednak nie, to ok, ja tego nie kwestionuję.

Już nie baw się w procenty, wystarczy, że odpowiednio mocno to akcentowałeś.

hahaha

**Comment by hawkeye116477** [comment]
> A potem na koniec odwracasz kota ogonem, że to niby ja się lubię czepiać, a ty nie (bo o twoim własnym czepianiu jakoś dziwnym przypadkiem nie wspominasz nic).

Tak jak mówiłem, wiem jaki ty czasem bywasz, dlatego stąd też moje uwagi, ale widać nie dogadamy się, więc więcej już nie mam nic do dodania.

**Comment by gargul2** [comment]
To może lepiej w osobnym / wydzielonym wątku pt. "utarczki z kulfonem" :smiley: , bo te twoje uwagi doprowadzają do personalnych dyskusji a następnie do zamknięcia wątku, w którym także są kwestie techniczne.
