### ISSUE TITLE
centrum-kaszuby.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2110]
Po kliknięciu na reklamę z https://github.com/MajkiIT/polish-ads-filter/issues/16512 przekierowało mnie na `centrum-kaszuby.pl` na których przywitało mnie urocze wyskakuące okienko, informacyjne czy reklama?

![capture_081_13-06-2020_19-15-31](https://user-images.githubusercontent.com/63287518/84575058-d2bf0100-adaa-11ea-8cc4-689c4a32dfcb.gif)

**Comment by krystian3w** [comment]
reklama

**Comment by krystian3w** [comment]
`http://centrum-kaszuby.pl/galeria/170/walentynki-fotobudka.html` - galerię mają na tym samym co pop-up.

**Comment by krystian3w** [comment]
Pop-up niby tylko na głównej.

**Comment by hawkeye116477** [comment]
@krystian3w A dla mnie co tu do roboty? Mógłbym wprawdzie zamienić to na skryptową, ale skoro da się zachować kompatybilność z ABP i nie ma odczuwalnych spowolnień/migotań, to chyba nie opłaca się :smile:
