### ISSUE TITLE
biuroprasowe.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2112]
2 x newsletter zarówno na głównej jak i w artykułach

http://www.biuroprasowe.pl/artykuly/695/sportowe-emocje-na-platformie-player-w-czerwcu

### 1
![capture_020_17-06-2020_10-56-21](https://user-images.githubusercontent.com/63287518/84878003-88c76b00-b089-11ea-9ee0-3345668e5a76.png)

### 2
![capture_021_17-06-2020_10-56-42](https://user-images.githubusercontent.com/63287518/84878012-89f89800-b089-11ea-954d-89e076ff9dff.png)

**Comment by krystian3w** [comment]
Pierwsze jest jakoś źle zrobione, zachęcenie do rejestracji konta na `whitepress`...

**Comment by gargul2** [comment]
Raczej drugie... jest literówka: zbędne `w` w domenie,  przez co newsletter nr 2 nie ukryty.

**Comment by krystian3w** [comment]
3 też złe, żaden blocker nie pozwala na globalne obciążanie sieci z `:contains()` / `:has()` - trzeba pogrzebać w ustawieniach lub używać:

* kilka tysięcy TLD

* bugów w bardzo starym uBO:
   `pl,#?#b:contains(...)` (legacy ma już to załatane)

* zapisu z gwiazdką dla uBO "webext" (`shadow dom`):
   `*#?#b:contains()`
