### ISSUE TITLE
imgw.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2114]
![2020-06-17 20 16 06 meteo imgw pl 3bbc682c0fe5](https://user-images.githubusercontent.com/36385327/84934360-81c74980-b0d7-11ea-98e9-182079d3b635.png)

**Comment by gargul2** [comment]
U mnie to trochę inaczej wygląda, albo się komunikat zmienił:

![capture_011_17-06-2020_21-21-13](https://user-images.githubusercontent.com/63287518/84940783-a07e0e00-b0e0-11ea-9d98-ecd0e87f4371.png)

**Comment by krystian3w** [comment]
A to wina @hawkeye116477  uprościł zgłoszenie.

**Comment by hawkeye116477** [comment]
Zgadza się, bo element tak samo się nazywa w obu przypadkach.
