### ISSUE TITLE
info-przetargi.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2117]
Widżet kontaktowy w popupie, kwalifikacja jako popup ma pierwszeństwo:

![capture_020_18-06-2020_20-18-04](https://user-images.githubusercontent.com/63287518/85057294-dedb0200-b1a0-11ea-9f92-4df5e358b1b6.png)

**Comment by krystian3w** [comment]
A co z tą ich melodią...
