### ISSUE TITLE
angelius.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2119]
Jeszcze informacyjny czy może już  nagabywanie?

![capture_030_19-06-2020_12-44-16](https://user-images.githubusercontent.com/63287518/85124824-d7603b00-b22a-11ea-9c11-602b98dcad39.png)

**Comment by krystian3w** [comment]
Jak dla mnie reklama i dopisanie numeru to za mało.
