### ISSUE TITLE
portalpogrzebowy.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2120]
![capture_032_19-06-2020_12-49-44](https://user-images.githubusercontent.com/63287518/85125142-63726280-b22b-11ea-8607-fc7c8ef5c9b0.png)

**Comment by krystian3w** [comment]
trzeba by poczekać z zamknięciem aż nagle uzupełnią się produkty lub lista rekomendowanych zakładów (mogą mieć galerię fancybox).

**Comment by krystian3w** [comment]
Strona chyba sama będzie potrzebować pewnie swoich usług, w przeszłości dla produktów i zakładów nie używano fancybox.
