### ISSUE TITLE
dodaj-strone.com.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2121]
![capture_036_19-06-2020_12-57-21](https://user-images.githubusercontent.com/63287518/85125753-7e91a200-b22c-11ea-9f63-624f69973458.png)

**Comment by krystian3w** [comment]
Jak ktoś chce to może dodać sprawdzanie czy tło ma być ukryte, bo są niby 4 tła dla 1 popupa.

`#popupframe_bg` ...
