### ISSUE TITLE
sofine.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2122]
![capture_044_19-06-2020_17-23-05](https://user-images.githubusercontent.com/63287518/85149509-acd5a880-b251-11ea-9e14-83bf02b9eeb4.png)

**Comment by krystian3w** [comment]
Z problemów jakie już widzę, to nie działa wtedy:

![obraz](https://user-images.githubusercontent.com/35370833/85150268-9da32a80-b252-11ea-8261-e76571de7b7d.png) |
-- |

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/85151339-f45d3400-b253-11ea-96be-96cf9d79ec6b.png)

Pod tę sekcję podpięli też pop-up (ten sam).

---

Jakby użyć `:remove()` to się otworzy podstrona:

`https://sofine.pl/kontakt.html` ale bez formularza, bo nie mają.

`watch-attr` raczej nie pomoże

skrypt musi być bardzo łagodny jak ten z `niezlasztuka.net` #1622

**Comment by gargul2** [comment]
`sofine.pl##+js(no-setInterval-if, popcount, 1000)`

**Comment by gargul2** [comment]
Zawsze do tej pory używaliście długich skryptów, dlatego podawałem długie, a teraz widzę przerzutka na krókie:  (https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/1dda40e82bb3fca7463247341d8557ab3c48ef4f) no to w takim razie będę podawał krótkie.

A można zapytać dlaczego wcześniej były długie? Myślałem, że dla zgodności z uBO Legacy.

**Comment by krystian3w** [comment]
Po jakieś nowości z obsługą wielu `if-ów` stwierdziliśmy że zaczniemy iść z duchem czasu i zostały ciachnięte potem `.js` - powiązane z premierą uBO `v1.20.X`.

A niedawno najkrótsze nazwy weszły w życie po tym jak AG już nie ma z nimi problemu (jak ktoś nie aktualizuje dodatku i sobie na siłę wkleja do filtrów własnych `składnię uBO` to jego problem...) i niby okazały się kompatybilne z nim jak ktoś nie stwierdził, że uBO legacy to umarło z "`1.13.8`" (a dalej aktualizuje wersje 1.16.X).
