### ISSUE TITLE
busko.net.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2126]
w Artykułach np. http://busko.net.pl/nowy-lek-dla-chorych-z-covid-19-w-wojewodzkim-szpitalu-zespolonym-w-kielcach,,1,14,14,1,30755,n.html

![Nagrywaj_2020_06_22_16_06_10_211](https://user-images.githubusercontent.com/63287518/85296899-58753780-b4a2-11ea-83c9-32b8b65391d0.gif)

![capture_072_22-06-2020_16-04-12](https://user-images.githubusercontent.com/63287518/85296705-164bf600-b4a2-11ea-8f9d-58aa9e1a7c42.png)

**Comment by krystian3w** [comment]
Dział kultura blokuje dezaktywację tarczy Firefox - 🤣 😛.

http://busko.net.pl/_kultura.php
