### ISSUE TITLE
kolobrzeg.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2128]
![capture_109_22-06-2020_17-24-03](https://user-images.githubusercontent.com/63287518/85305376-44830300-b4ad-11ea-9894-7fda2cebce01.png)

**Comment by gargul2** [comment]
Znowu wyskoczyło jakieś nowe okienko:

![capture_005_03-08-2020_13-09-08](https://user-images.githubusercontent.com/63287518/89176829-8b731680-d58a-11ea-9154-47e72d77ca1b.gif)

**Comment by gargul2** [comment]
Czasem pojawia się takie:

![capture_003_16-09-2020_11-48-56](https://user-images.githubusercontent.com/63287518/93321556-97e9c080-f812-11ea-94ad-beab1ff08fdc.gif)

**Comment by krystian3w** [comment]
Oba napędzane tym samym silnikiem/frameworkiem.
