### ISSUE TITLE
bilkom.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2129]
![2020-06-22 20 44 19 bilkom pl 413af480649d](https://user-images.githubusercontent.com/36385327/85323908-3347ef80-b4c9-11ea-96ff-23bccd5b87f2.png)

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2814
