### ISSUE TITLE
otoboleslawiec.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2130]
### Typ elementu
popup
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 83.0.4103.109
**Bloker:** uBlock Origin 1.27.10
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by gargul2** [comment]
Niezależnie od tego czy to się zakwalifikuje czy nie, uzupełniam o screenshoot, (jako, że zgłaszający tego nie zrobił):

![capture_112_23-06-2020_12-34-44](https://user-images.githubusercontent.com/63287518/85394010-389b4d80-b54e-11ea-87ed-062d287cb28e.png)

**Comment by krystian3w** [comment]
Bo w formularzu jest napisane że link i screen jest opcjonalny, a to jest chyba zgłoszenie @blocker999  o prenumeratach.

Ale mu chyba chodziło, że zaczęły mu wadzić te w prawych lub lewych wąskich **kolumnach**.

**Comment by gargul2** [comment]
> Bo w formularzu jest napisane że link i screen jest opcjonalny, 

Jak bym nie wiedział... to raczej ty nie umiesz czytać ze zrozumieniem, bo czy ja gdzieś pisałem, że jest obowiązkowy? Po prostu sam od siebie uzupełniłem, tak jak robię to zawsze w swoich zgłoszeniach, a nie dlatego że trzeba, bo wiem, że nie trzeba, ale lepiej widzieć co jest zgłaszane.
