### ISSUE TITLE
zegarkiipasja.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2132]
![capture_157_23-06-2020_18-21-55](https://user-images.githubusercontent.com/63287518/85429070-74e6a200-b57e-11ea-9661-76e06ac6326a.png)

**Comment by krystian3w** [comment]
@hawkeye116477 ta e-gazeta w headerze się łapie?

Jak tak to trzeba by uruchomić suplement i użyć najlepiej `remove()` / html filteringu i zobaczyć czy się nie buguje  mikro slider

**Comment by hawkeye116477** [comment]
Tam informacja się czasem zmienia, więc może lepiej im to darować.

**Comment by krystian3w** [comment]
Nie chodzi mi o przełączanie się sliderów jako zmianę, a ciachnięcie pierwszego slajdu gdy ma tekst lub link o e-gazecie:
*  `:has()`/`:has-text()` 
* lub `[tag-content="..."]`.
