### ISSUE TITLE
inzynier-medyczny.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2135]
![capture_159_23-06-2020_18-26-23](https://user-images.githubusercontent.com/63287518/85429476-1110a900-b57f-11ea-8188-fe8e7b9adae1.png)

**Comment by blocker999** [comment]
#2214

**Comment by gargul2** [comment]
Spodziewałem się, że mogą się jakieś duplikaty trafić, ale wpadłem w trans / ciąg robienia zgłoszeń, i wolałem więcej zgłosić, niż tracić czas na sprawdzanie czy zgłoszenie już istnieje, i niejako - brzydko się przyznając - przerzuciłem wyłapanie ewentualnych duplikatów na wasze barki, piszę to żeby ktoś nie pomyślał, że głupek nie patrzy co robi i zakłada duplikaty.

**Comment by krystian3w** [comment]
Duplicate of #2214
