### ISSUE TITLE
skladaniekomputera.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2141]
![Nagrywaj_2020_06_23_18_36_38_203](https://user-images.githubusercontent.com/63287518/85430548-8b8df880-b580-11ea-8cec-3042891832ce.gif)

**Comment by blocker999** [comment]
![zk](https://user-images.githubusercontent.com/23176832/86510148-82f1b980-bded-11ea-8d40-88439e4a64af.png)

**Comment by krystian3w** [comment]
Pop-up w popupach @blocker999 

nie wygląda to na wykrycie anty-adblock

**Comment by krystian3w** [comment]
Ja wyciekającej strzałki nie widzę.
