### ISSUE TITLE
glokalna.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2161]
### Typ elementu
popup
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 83.0.4103.109
**Bloker:** uBlock Origin 1.27.10
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by gargul2** [comment]
![capture_178_24-06-2020_17-53-29](https://user-images.githubusercontent.com/63287518/85589163-a1182680-b643-11ea-8094-0e10a2319e9d.png)
