### ISSUE TITLE
prgok.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2173]
Informacyjny (w kontekście COVID / godziny otwarcia), czy zwykły spam reklamowy i nagabywanie (czy odwiedziłeś już nasz PSZOK)? A może 2w1, co wtedy - kwalifikuje się czy nie?

![capture_183_25-06-2020_08-48-32](https://user-images.githubusercontent.com/63287518/85669965-b1221b80-b6c0-11ea-9f80-220d8a5ea848.png)

**Comment by krystian3w** [comment]
Obecnie inny:

![obraz](https://user-images.githubusercontent.com/35370833/88822391-14bdce00-d1c4-11ea-9c98-56ce0d088e92.png) |
--- |

Ja bym zostawił, bo może ktoś nie wie, że mailem nie można.

**Comment by gargul4** [comment]
No dobra ale mogłeś odpowiedzieć tak na przyszłość, w razie jakby się znowu taki trafił.
