### ISSUE TITLE
Prenumeraty

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2180]
### Typ elementu/problemu
- [x] Pytanie
- [x] Prenumerata
- [x] prenumerata

Niejasne to wszystko, 

z jednej strony niby chodzi o `prenumeratę`:
- etykieta jest `prenumerata` 
- nazwa zgłoszenia:  "Bloki z `prenumeratami`"
- opis w liście filtrów: ! Description: Filtry ukrywające i blokujące bloki z reklamą `prenumerat.`
- [CONTRIBUTING](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/master/CONTRIBUTING.md) nic nie wspomina o nieblokowaniu `prenumerat`

a z drugiej o `e-prenumeratę`:
- opis etykiety: "reklama `e-wydania` gazety"
- opis zgłoszenia: "Block with `e-newspapper` subscription"
- tytuł w liście filtrów: "! Title: Polskie Filtry Elementów Irytujących - `e-wydania` gazet"

Dodatkowo są dwie listy do prenumerat:

- https://raw.githubusercontent.com/KonoromiHimaries/PolishSubFilters/master/internal-filters/paid-subscriptions/prenumeraty.txt
- https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_e_newspaper.txt

Więc które (prenumeraty, e-prenumeraty, płatne, niepłatne) gdzie?

Pytam prowizorycznie i zapobiegawczo bo zaraz mądraliński krystian3w w moich zgłoszeniach zacznie mi wytykać, że nie o takie prenumeraty chodzi, tylko o inne itp. więc się zdecydujcie, w końcu i doprowadźcie ten wasz pomieszany opis do kupy, bo zgodnie z prawem, niejasności rozstrzyga się na korzyść klienta i pozwę was do sądu, wygram sprawę i to wy wyjdziecie na głupków, a nie ja. 

I jak widać przy okazji nie działa etykieta / formularz zbiorczy nie został uzpełniony o etykietę `prenumerata`, i tym razem hawkeye nie napisze: 

> https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2077#issuecomment-642547244 : > @gargul2 Przecież jest, 3 od góry :stuck_out_tongue:

 bo tym razem to nie gargul wyjdzie na głupka i to ja się z was teraz śmieję.

Z powyższych powodów póki co zgłaszam wszystkie prenumeraty  (prenumeraty, e-prenumeraty, płatne, niepłatne, o smaku pomarańczowym czy truskawkowym, w ptaszki czy w słoneczka) jak leci i sami sobie decydujcie czy się kwalifikuje czy nie, z resztą i tak się nie połapię która to jaka.

**Comment by gargul2** [comment]
Przenoszę do https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2181

**Comment by krystian3w** [comment]
Wątek zaktualizowany, muszisz na razie kopiować wersje "long", może później uprości się do wykrywania:

- [ ] tytuł
- [ ] prenumerata

**Comment by hawkeye116477** [comment]
Jest opis dłuższy, by wszyscy skumali o co chodzi. 

PS: Planujemy jeszcze wydłużyć opis strzałki do `Przycisk z narysowaną strzałką mający funkcję szybkiego przeskoczenia do góry` :rofl:
