### ISSUE TITLE
Prenumeraty

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2181]
### Typ elementu/problemu
- [x] Pytanie

Test - skoro [w zgłoszeniu zbiorczym](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2180) nie działa / nie ma etykiety prenumerata, to najpierw stworzę zgłoszenie typu prenumerata, co nada zgłoszeniu etykietę `Prenumerata`, a potem edytuję komentarz i dodam - `[x] Pytanie`.

Jak widać: powiodło się, więc wklejam tu poprzednie zgłoszenie:

### Typ elementu/problemu
- [x] Pytanie
- [x] Prenumerata
- [x] prenumerata

Niejasne to wszystko, 

z jednej strony niby chodzi o `prenumeratę`:
- etykieta jest `prenumerata` 
- nazwa zgłoszenia:  "Bloki z `prenumeratami`"
- opis w liście filtrów: ! Description: Filtry ukrywające i blokujące bloki z reklamą `prenumerat.`
- [CONTRIBUTING](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/master/CONTRIBUTING.md) nic nie wspomina o nieblokowaniu `prenumerat`

a z drugiej o `e-prenumeratę`:
- opis etykiety: "reklama `e-wydania` gazety"
- opis zgłoszenia: "Block with `e-newspapper` subscription"
- tytuł w liście filtrów: "! Title: Polskie Filtry Elementów Irytujących - `e-wydania` gazet"

Dodatkowo są dwie listy do prenumerat:

- https://raw.githubusercontent.com/KonoromiHimaries/PolishSubFilters/master/internal-filters/paid-subscriptions/prenumeraty.txt
- https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_e_newspaper.txt

Więc które (prenumeraty, e-prenumeraty, płatne, niepłatne) gdzie?

Pytam prowizorycznie i zapobiegawczo bo zaraz mądraliński krystian3w w moich zgłoszeniach zacznie mi wytykać, że nie o takie prenumeraty chodzi, tylko o inne itp. więc się zdecydujcie, w końcu i doprowadźcie ten wasz pomieszany opis do kupy, bo zgodnie z prawem, niejasności rozstrzyga się na korzyść klienta i pozwę was do sądu, wygram sprawę i to wy wyjdziecie na głupków, a nie ja. 

I jak widać przy okazji nie działa etykieta / formularz zbiorczy w  [>> poprzednim zgłoszeniu <<](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2180) nie został uzpełniony o etykietę `prenumerata`, i tym razem hawkeye nie napisze: 

> https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2077#issuecomment-642547244 : > @gargul2 Przecież jest, 3 od góry :stuck_out_tongue:

 bo tym razem to nie gargul wyjdzie na głupka i to ja się z was teraz śmieję, a tylko dzięki zastosowaniu sztuczki uzyskałem 2 etykiety w nowym zgłoszeniu.

Z powyższych powodów póki co zgłaszam wszystkie prenumeraty  (prenumeraty, e-prenumeraty, płatne, niepłatne, o smaku pomarańczowym czy truskawkowym, w ptaszki czy w słoneczka) jak leci i sami sobie decydujcie czy się kwalifikuje czy nie, z resztą i tak się nie połapię która to jaka.

**Comment by krystian3w** [comment]
Bo jeszcze trzeba uaktualnić plik bota, pliki w repo strony www.

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/master/.github/probot.js - `powrotne tytuły` też nie dodane..., czyżby tylko `hawkeye` miał prawo do blokowania bez zgłoszeń?

**Comment by krystian3w** [comment]
Jak zaczniesz zgłaszać powrotne tytuły `"Wróc do .."` / `"Wróc na..."` to najlepiej z gotowym filtrem `xhr` / `+js()` który najmniej upośledza stronę.

**Comment by hawkeye116477** [comment]
> bo tym razem to nie gargul wyjdzie na głupka i to ja się z was teraz śmieję


A skąd wiesz, że wyszła stabilna wersja prenumerat? Może tylko testujemy i dlatego też nie ma dodanych etykiet do formularza... A tak w ogóle, to ale śmieszne...

PS: Jak tam w twoim państwie, jaka pogoda, nadal są trzęsienia ziemi?

**Comment by krystian3w** [comment]
Wie jak śledzi commity lub z #2180

**Comment by krystian3w** [comment]
Co do ograniczeń to bym wrzucił że nie wycinamy statycznych linków bez grafik z nawigacji i na podstronie z takiego menu ukrywamy tylko wersje banerową (np. na szerokość całej lub szerszej kolumny, blok w wąskiej kolumnie - bo to można uznać za np. zapętlenie).

**Comment by gargul2** [comment]
> A skąd wiesz, że wyszła stabilna wersja prenumerat?

Ale odwrócił kota ogonem, i zwala winę... a gdzie jakieś info, że testowa? Pewnie samemu ze szklanej kuli trzeba sobie wywróżyć. Skoro:
- brak etykiety `test` w zgłoszeniu krystiana
- w samej liście nie ma info, że to testowa wersja
- jest również możliwość utworzenia zgłoszenia z prenumeratą i etykietą "prenumerata"
- widzę również, że ktoś już takie zgłoszenie utworzył, 

To też robię zgłoszenie i tyle.

> Może tylko testujemy i dlatego też nie ma dodanych etykiet do formularza... 

Morze to jest szerokie i głębokie

>  tak w ogóle to, ale śmieszne...

Śmieszne to jak w menu jest nowe danie, a gdy klient zamawia to słyszy, że nie dostanie bo to tylko testowe danie dla pracowników sklepu, albo gdy restauracja zamknięta, a brak kartki "nieczynne", a klienci "całują" klamkę.

Przy okazji, pisałem również wcześniej, że przydałoby się stworzyć CONTRIBUTING dla repo cookies/social, i wykluczyć 
- komunikaty statyczne cookies
- elementy społecznościowe wymagane do zalogowania (np. logowanie prez Facebook)

**Comment by hawkeye116477** [comment]
> Ale odwrócił kota ogonem, i zwala winę... a gdzie jakieś info, że testowa?

Nie ma modułu na liście na stronie PAF, więc można byłoby uznać, że testy. A nawet gdyby, to też nie musisz zawsze takim ostrym tonem, przecież nie płacisz za listę. Wiem, że zaraz pewnie powiesz, że to tylko takie żarty. Tak więc powiem, że raczej nikt się nie śmieje z tych twoich słabych sucharów....


> Śmieszne to jak w menu jest nowe danie, a gdy klient zamawia to słyszy, że nie dostanie bo to tylko testowe danie 

Ale wspaniałe porównanie...

**Comment by gargul2** [comment]
> Nie ma modułu na liście na stronie PAF, więc można byłoby uznać, że testy. 

A można by również uznać, że ktoś jeszcze nie uzupełnił albo zapomniał. Pozatym, nie każdy wie, że przeprowadzacie tu jakieś nieoznakowane testy, bo nigdzie nie ma takiego infa, a owe testy nie różnią się od normalnych zgłoszeń. Rozumiem zatem, że twoja filozofia, to filozofia szklanej kuli i do myślania się (skoro drzwi od restauracji nie są otwarte, to pewnie jest nieczynna...bo przecież we wszystkich restauracjach drzwi są zawsze otwarte...)

> nie musisz zawsze takim ostrym tonem

Nie piszę ostrym tonem, ja jestem zupełnie spokojny, i się nie złoszczę czy coś, czy w którymś komentarzu używałem wykrzykników albo wyzwisk? To już nie rozumiem, po czym oceniasz, moje komentarze, że są ostre, nie są przecież posypane ostrą papryczką chili...chodzi mi tylko o to, że wskutek braku informacji i filozofii szklanej kuli, to zawsze ja wychodzę na głupka, który czegoś nie wie bo się czegoś nie domyślił itp. i gdybym tego zgłoszenia nie założył to w którymś zgłoszniu z prenumeratą bym usłyszał od kogoś docinek, że przecież wy takich czy takich prenumerat nie blokujecie, to może w końcu czas wam pokazać, że to wasza filozofia s zklanej kuli jest głupia, śmieszna i wprowadzająca w błąd i robiąca zamieszanie.

**Comment by hawkeye116477** [comment]
>  na pierwszy rzut oka wychodzi, że nie jesteś w Polsce, ale z kolei w Polsce nie ma trzęsień ziemii, ok czyli chodzi o to, że ja nie mieszkam w Polsce, ale przecież mieszkam, no więc jak podumam i rozszyfruję to odpowiem

Dobra, dobra już nie udawaj, wiem, że jesteś w Chile...

**Comment by gargul2** [comment]
Acha ostra papryczka chili pochodzi z Chile, i dlatego uznałeś moje komentarze za ostre bo posypane ostrą papryczką chili, żart-zagadka dobry, nie zaprzeczam. No dobra to ja se robięzbyty, ale ak na serio wychodzi na to, że próbujesz wyśledzić skąś moje IP? :smiley:

**Comment by gargul2** [comment]
Strzelam, że na którymś screenshocie w jakimś zgłoszeniu, coś pokazało skąd jesten.

**Comment by hawkeye116477** [comment]
`No dobra to ja se robię zbyty, ale ak na serio wychodzi na to, że próbujesz wyśledzić skądś moje IP? Strzelam, że na którymś screenshocie, strona wyświetliła skąd odwiedzam stronę.`

Pudło, po prostu pewna firma z Redmond dała mi twoje namiary.

**Comment by gargul2** [comment]
I pewnie dała tak sama z siebie... 
- albo masz jakieś znajomośc
- albo zwyczajnie zapytałeś i ci podali choć nie powinni
- albo github jakoś gdzieś wyświetla pochodzenie użytkownika, nie prowadzę repo więc nie wiem jak to wygląda ze strony admina...no kiedyś na jakimś gargulu prowadziłem mini-repo z ciasteczkami razem z krystianem, ale repo jest już zarchiwizowane, hasła nie mam już do tamtego konta, a i wtedy nie przyglądałem się czy panel administracyjny gdzieś pokazuje lokalizację użytkownika

**Comment by hawkeye116477** [comment]
> albo masz jakieś znajomości

Tak, mój wujek zna prezesa GitHuba i powiedział, że obserwują ciebie.

**Comment by gargul2** [comment]
Po tym  jak okazało się, że [>> prezes Youtube jest kuzynką Morawieckiego <<](https://www.polsatnews.pl/wiadomosc/2020-01-22/premier-spotkal-sie-z-prezes-youtube-to-moja-daleka-kuzynka/), i zaraz po tym spotkaniu jednemu ze znanych polskich youtuberów, Youtube zablokowało bezpodstawnie film na youtube na temat PISu, to już mnie nic nie zdziwi.

**Comment by hawkeye116477** [comment]
No to teraz już wiesz, że lepiej być grzecznym i nas nie wkurzać.

**Comment by gargul2** [comment]
hahaha ale troll, znowu odwrócił kota ogonem, a sam mnie zaczepia... hawkeye dla czego jesteś taki niegrzeczny i ciągle nas wkurzasz hahaha.

Przecież to ty mnie ciągle zaczepiasz / robisz wycieczki personalne w moją stronę i sam się nakręcasz..., bo co bym nie napisał, to w każdym moim normalnym komentarzu widzisz coś złego i zarzuczasz: a to że niby napisałem coś złośliwie, a to że niby napisałem ostrym tonem, a to że niby miałem pretensje i żale, a kabaret to był jak się uczepiłeś moich długich komentarzy "esejów", teraz z kolei próbujesz wmówić całemu światu, że jestem niegrzeczny i was wkurzam, mów za siebie, a nie za wszystkich, każdy ma swój własny język i jak będzie chciał coś napisać to zrobi to sam, ale wolisz sobie tworzyć sztuczne poparcie, którego ci brakuje, żeby wydawało się jakby kilka osób coś mi zarzucało, a nie ty jeden, ale to ciągle ty sam się nakręcasz, zbaczasz z tematu i szuaksz zaczepki, lepiej się zachowuj i nie troluj tyle, bo rózgę dostaniesz hahaha

**Comment by gargul2** [comment]
Ty ale bez kitu, żeby znać kraj użytkownika githuba, to ten użytkownik musi mieć podany kraj w swoim profilu, a ja nie mam i nie miałem nigdy podanego.

Więc tylko sam użytkownik githuba i administracja gtihuba znają IP i kraj użytkownika, (bo żeby znać kraj, trzeba znać IP), jak widać ktoś z administracji najwyraźniej z dupy strzelił jak zwykła prostytutka i rozpowszechnia wrażliwe dane, chytrze, bo nie podali IP a tylko kraj, dzięki czemu nie narazili się na złamanie RODO, bo jak wiadomo IP zalicza się do danych osobowych, sam kraj zdaje się już nie.

**Comment by hawkeye116477** [comment]
> hahaha ale troll, znowu odwrócił kota ogonem, a sam mnie zaczepia

Ale to przecież tylko takie żarty, no co ty na żartach się nie znasz....

**Comment by gargul2** [comment]
Znam, przecież nie spinam się, bo:
- też żartem zakończyłem swój komentarz "gargul2: bo rózgę dostaniesz za te wycieczki personalne hahaha"
- w całym komentarzu się wielokrotnie śmiałem ("hahaha")

Więc teraz ja zapytam czy okulary masz sprawne...
A to że, przy okazji oprócz śmiechów, napisałem też coś na serio, to dlatego, bo ja mogę się znać na żartach, a ktoś inny niekoniecznie i jeszcze uwierzy, więc wolałem sprostować co nieco na wszelki wypadek.

**Comment by hawkeye116477** [comment]
> co wynika po części z uzależnienia

A, słyszałem ostatnio jest to co raz popularniejsze, WHO określa to schorzenie jako raportoza. Jego objawem jest m.in. to, że dana osoba cały czas szuka czegoś do zgłaszania i czuje, że musi to robić i nawet skarży się, że ma sporo roboty, mimo, że nikt jej nic nie kazał i nie otrzymuje za to żadnego wynagrodzenia. Na szczęście już od jakiegoś czasu są dostępne metody leczenia tego. Najskuteczniejszy ze sposobów jest niestety bardzo kosztowny, więc pewnie trzeba by zrobić jakąś zbiórkę na `siepomaga.pl` lub gdzieś indziej. Jednakże jest też tańszy nieco mniej skuteczny sposób, otóż trzeba takiej osobie załatwić dwutygodniowy urlop od GitHuba/GitLaba/BitBucketa i zaproponować inne metody spędzania wolnego czasu, np. granie w darmowe gry od Epic Games (Civilization VI, Darksiders, Borderlands The Handsome Collection, GTA V), ewentualnie płatny Wiedźmin 3 GOTY albo oglądanie telewizji linearnej lub VOD. A jeżeli to nie pomoże i zacznie szukać błędów w grach albo oprogramowaniu telewizora, to należy wtedy przeciąć jego kabelek od Internetu, a telewizor wyrzucić za okno. A potem dać mu w prezencie skakankę, niech skacze. A jeżeli to nie pomoże i zacznie szukać błędów w konstrukcji skakanki, to wtedy należy zakupić taki lek:
<img src="https://www.eksperymentalnie.com/wp-content/uploads/2014/02/ma%C5%9B%C4%87.jpg">
i niech sobie codziennie smaruje przez 2 tygodnie. A jeżeli to nie pomoże, to wtedy niestety pozostaje tylko bardzo kosztowne leczenie.

**Comment by gargul2** [comment]
Raportoza - niech będzie, świetna nazwa, pasuje mi hehe, teraz zastanawiam się jak nazwać twoje schorzenie opisane w https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2181#issuecomment-650149472, już wiem - czepioza / troloza, a leczenie zapewne podobne do tego, które przed chwilą opisałeś w przypadku raportozy. Może nawet spotkamy się gdzieś na wspólnym urlopie odwykowym.

Tylko mała uwaga co do:

> hawkeye116477 : a czasem nawet skarży się, że dają jej sporo roboty, mimo, że nikt jej nic nie kazał i nie otrzymuje za to żadnego wynagrodzenia.

Powtarzasz swoje błędne zarzuty z naszej wcześniejszej dyskusji, w której już ci wyjaśniłem, że wcale tak nie było: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1916#issuecomment-638854774, to chyba do twojej czepiozy / trolozy dodać trzeba także sklerozę, chyba, że dalej tkwisz w swojej ułudzie i sądzisz, że miałem jakieś pretensje, że mi dają za dużo roboty, wtedy należy dodać imaginozę. 

:smiley:

**Comment by hawkeye116477** [comment]
> czepioza / troloza

Niestety zaraziłem się od ciebie.

**Comment by gargul2** [comment]
Tylko ci się tak wydaje wskutek imaginozy...:smiley:

**Comment by hawkeye116477** [comment]
Nie martw się, czytałem między wierszami. Chciałeś po prostu przez to powiedzieć „szefie, normalnie wariuję już od tego wszystkiego, więc poproszę o 2 tygodnie urlopu". A ja na to odpowiem, że świetny z ciebie pracownik, wyrabiasz nawet nadgodziny i ciągle mi przypominasz jak dobrym jestem szefem, więc dam ci nawet dodatkowe 2 tygodnie :smile:.

**Comment by gargul4** [comment]
> https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2181#issuecomment-649506907 :
> 
> - albo github jakoś gdzieś wyświetla pochodzenie użytkownika, a może jest do tego jakiś specjalny nieoficjalny skrypt.

Haha i to był strzał w 10, zobacz co znalazłem w starych rupieciach: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1308#issuecomment-449579273
