### ISSUE TITLE
ksm.org.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2182]
Prenumerata w popupie: dałem 2 etykiety elementowe, bo kwestia czy to się kwalifikuje jako `popup` czy `prenumerata`, z dotychczasowej praktyki, jeśli `widżet kontaktowy/feedback` jest w `popupie` to kwalifikuje się jako `pupup`, czy tak samo jest w przypadku `prenumerat` w `popupie`?

![capture_194_25-06-2020_12-52-11](https://user-images.githubusercontent.com/63287518/85706774-d45dc280-b6e2-11ea-9156-19e3a4e2fb05.png)

**Comment by krystian3w** [comment]
@hawkeye116477 jest za tym by takie wycinać w pop-upach, czyli trzeba dla lepszej obrony 2 moduły.

---

I w sumie 1 filtr pewnie też do przeniesienia za użycie w kampanii słowa `newsletter`.
