### ISSUE TITLE
o-m.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2186]
![capture_201_25-06-2020_14-01-49](https://user-images.githubusercontent.com/63287518/85716169-7c2bbe00-b6ec-11ea-9fc7-f364c6940a82.png)

**Comment by krystian3w** [comment]
Trzeba by robić podgląd czy nie zmieniają układu, jak zmieniają to trzeba przepisać na `-abp-has` / `-abp-contains`.
