### ISSUE TITLE
rewasz.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2194]
![capture_212_25-06-2020_14-33-29](https://user-images.githubusercontent.com/63287518/85720593-de86bd80-b6f0-11ea-8c11-83fb4b750826.png)

**Comment by blocker999** [comment]
@gargul2 co tu blokować ?

**Comment by hawkeye116477** [comment]
Chyba chodzi o ten link w menu.

**Comment by blocker999** [comment]
@hawkeye116477 a jak o banner z książkami, to które blokować ?

**Comment by hawkeye116477** [comment]
Banner z książkami to oferty promocyjne ala gazetka, więc raczej nie. W ogóle nie wiem czy ten sam link lepiej nie darować, bo zbyt wielkie to to nie jest...

**Comment by krystian3w** [comment]
Jak tu wycofujemy to i inne bannery social / newsletter, jak się da wyciąć `:remove()` lub `html filteringiem` i nie głupieje JS to będzie ok - jak głupieje to zostaje CSS i `pointer-events: none`.

**Comment by krystian3w** [comment]
W sumie to lepiej rozbudować https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/9257bd1b023b4b57f838f27a625b6d8819750047:

- że nie wycinamy linków pozbawionych graficznej oprawy
- serwisów sprzedających tylko e-gazety lub książki (i że elementy gazetowe mają tam zadanie funkcjonalne)
- paywalli, bo za raz pewnie wyjdzie, że wyborczą mamy jakoś odblokować a tam chyba nawet popularne dodatki anti-paywall zowadą.

**Comment by krystian3w** [comment]
I jeszcze kwestia reklamy gazetek promocyjnych np. na Interii:

```
www.interia.pl###promocyjni
www.interia.pl###page > section > .promo-container
```

może być skojarzenie z e-bookiem.

**Comment by gargul2** [comment]
> blocker999 : @gargul2 co tu blokować?
> blocker999 : @hawkeye116477 a jak o banner z książkami, to które blokować?

Tak, chodziło mi o właśnie o ten baner z książkami, po prostu jakaś gazetka i napis "wydanie XIX" to zaleciało jakąś promocją...zwłaszcza, że tak dużo jest tych wszystkich elementów irytujących, że człowiek głupieje od tego, więc na wszelki wypadek wolałem zgłosić na zapas zgodnie z rzymską zasadą:

> lepiej zgłosić i żeby zostało odrzucone, niż nie zgłosić czegoś co powinno być zgłoszone

a zasada ta w oryginalnym brzmieniu wzięta z pewnego filmu, gdy kobieta A mówi do kobiety B na statku pełnym facetów:

> kobieta A: po co ci te kondony?
> kobieta B: wiesz - tak na wszelki wypadek - bo lepiej mieć i nie potrzebować / nie użyć, niż potrzebować, a nie mieć

Ale jeśli ten baner się nie kwalifikuje to ok, mi to 'ganc egal'.
