### ISSUE TITLE
poradnikhodowcy.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2199]
![capture_218_25-06-2020_14-42-32](https://user-images.githubusercontent.com/63287518/85721985-26f2ab00-b6f2-11ea-919d-3f67bae1fad2.png)
![capture_219_25-06-2020_14-42-43](https://user-images.githubusercontent.com/63287518/85721992-2823d800-b6f2-11ea-922d-08aa7ff965e5.png)

**Comment by blocker999** [comment]
@hawkeye116477 tego chyba nie, co tu blokować ?

**Comment by krystian3w** [comment]
Mati by wyciął obrazek pewnie, jeden filtr widziałem, że wyciął grafikę a opis wtrącony do każdego newsa zostawił.

**Comment by gargul2** [comment]
A oprócz obrazka np. to nie?

![85721985-26f2ab00-b6f2-11ea-919d-3f67bae1fad2](https://user-images.githubusercontent.com/63287518/85856986-46a0d680-b7b9-11ea-87f4-783aa728230a.png)

Argumentacja: wyżej o góry po prawej jest już przycisk PRENUMERATA z informacjami.

**Comment by hawkeye116477** [comment]
To co mówi gargulec jest do schowania.
