### ISSUE TITLE
prenumerata.ruch.com.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2203]
### Typ elementu/problemu
- [x] Reklama prenumeraty/e-wydania gazety
- [x] Pytanie

Kolejne pytanie czy moduł prenumerata blokuje całe dedykowane strony? Np. `||prenumerata.ruch.com.pl^$all` albo to  https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2236

![capture_224_25-06-2020_14-51-56](https://user-images.githubusercontent.com/63287518/85723354-708fc580-b6f3-11ea-82c6-9b0e4217bfb0.png)

**Comment by blocker999** [comment]
Ja bym tego nieblokował a tylko odnośniki do tych stron ale @hawkeye116477 decyduje

**Comment by krystian3w** [comment]
Ja bym tak mocno nie blokował, jeszcze zrobią pozew za ograniczanie dostępu 10 milionom użytkowników `PPB.txt`
