### ISSUE TITLE
fzz.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2207]
![capture_230_25-06-2020_14-59-47](https://user-images.githubusercontent.com/63287518/85724462-85208d80-b6f4-11ea-9419-3d316fc5e264.png)

**Comment by gargul2** [comment]
Jak w https://github.com/MajkiIT/polish-ads-filter/issues/16538#issuecomment-645414245:
`elementor-element-4c4d26d3` to ciąg losowych znaków alfanumerycznych, filtr raczej do poprawki.
@hawkeye116477 @krystian3w @blocker999

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/b476fc0e241946c46e8bf0dfb9c7e5175a01bc4a/PAF_e_newspaper.txt#L33

**Comment by krystian3w** [comment]
Ja nie widzę w tym wady, `elementor` to zło i używanie tam długich ścieżek by sprawdzać do 10 elementów jest katorgą...

Jak filtr padł to można pomyśleć nad aktualizacją - nie chcesz tych ID to przy elementor proponuj ładną ścieżkę CSS z sprawdzaniem do około 10 elementów - sprawdzanie z 500 już było krytykowane na `WP.pl`.
