### ISSUE TITLE
dziennikelblaski.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2213]
http://dziennikelblaski.pl/653611,quotZamknietequot-otwarcie-Zulawskich-Zabytkow.html

![capture_237_25-06-2020_15-08-45](https://user-images.githubusercontent.com/63287518/85725866-d2e9c580-b6f5-11ea-9f72-b1681f1d4b00.png)

**Comment by krystian3w** [comment]
@blocker999 ten filtr jest zły:

`##div.p:nth-of-type(5)`, zobacz sobie na długich artykułach.

**Comment by krystian3w** [comment]
Z posiadanych zrobiłem już: `##.highlight:-abp-has(.box-ewydanie)`

Niestety prenumeraty mogą wymagać nauki `-abp-has` i `-abp-contains`.
