### ISSUE TITLE
gpcodziennie.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2219]
![capture_244_25-06-2020_15-31-52](https://user-images.githubusercontent.com/63287518/85729327-01b56b00-b6f9-11ea-90ac-556322dbe141.png)

**Comment by krystian3w** [comment]
@blocker999  a ten link graficzny z headera? - https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2022

**Comment by krystian3w** [comment]
Dodatkowo numeryczne psują stronę, musimy użyć `:has()` / `contains()` @hawkeye116477
