### ISSUE TITLE
e-hotelarz.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2221]
### 1
![capture_247_25-06-2020_15-35-55](https://user-images.githubusercontent.com/63287518/85730267-d1220100-b6f9-11ea-9f8b-c961dab39ca2.png)

### 2
![capture_249_25-06-2020_15-36-11](https://user-images.githubusercontent.com/63287518/85730295-d5e6b500-b6f9-11ea-9866-f515b3ca23e2.png)

**Comment by blocker999** [comment]
help
