### ISSUE TITLE
czary.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2233]
![capture_264_25-06-2020_15-59-48](https://user-images.githubusercontent.com/63287518/85733988-f2d0b780-b6fc-11ea-94ad-0ff3f381fe13.png)

**Comment by blocker999** [comment]
Po pierwsze to chyba nie prenumerta
Po drugie jest to wtopione w tło

help

**Comment by hawkeye116477** [comment]
Nie da rady wyciąć, jedynie może można link usunąć, ale nie wiem czy się opłaca...

**Comment by krystian3w** [comment]
W sumie tła nie mają opcji zgłoszeń, chyba że jako inny element?

Niby też najmniej ich jest w filtrach - pewnie to jest powodem.

**Comment by gargul2** [comment]
> blocker999:  Po pierwsze to chyba nie prenumerta

Wyjaśnienie: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2194#issuecomment-650137425 (po prostu wolałem zgłosić, cokolwiek to jest, bo jest podejrzane, a wy jako sąd ostateczny  rozstrzygniecie czy się kwalifikuje.

**Comment by krystian3w** [comment]
To ja jeszcze pomyślę czy da się tam nanieść prostokącik `::before`.

**Comment by gargul2** [comment]
![capture_018_05-08-2020_08-22-05](https://user-images.githubusercontent.com/63287518/89378793-e0cb3700-d6f4-11ea-9b2c-51940d774a7d.gif)
