### ISSUE TITLE
zycie.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2235]
Podobne pytanie jak w https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2182

### Typ elementu/problemu
- [x] Inny element (np. widget „następny artykuł”)
- [x] Reklama prenumeraty/e-wydania gazety
- [x] Pytanie

Prenumerata w widżecie raczej kwalifikuje się jako `prenumerata` niż `widżet`, bo np. `newsletter` w `widżecie` kwalifikuje się jako `newsletter`, ale wolę się upewnić.

### 1
![capture_266_25-06-2020_16-10-33](https://user-images.githubusercontent.com/63287518/85736095-7a6af600-b6fe-11ea-9f6b-a0356158ea75.png)

### 2
![Nagrywaj_2020_06_25_16_02_58_737](https://user-images.githubusercontent.com/63287518/85735314-d8e3a480-b6fd-11ea-8eae-2eeda52c237a.gif)

**Comment by krystian3w** [comment]
Ja bym wrzucił do `e_gazety`, bo potem utonie w innych elementach i szukaj wiatru w polu.

**Comment by gargul2** [comment]
Czyli tak jak ja, to jesteśmy zgodni.
