### ISSUE TITLE
e-kiosk.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2236]
### Typ elementu/problemu
- [x] Reklama prenumeraty/e-wydania gazety
- [x] Pytanie

Kolejne pytanie czy moduł prenumerata blokuje całe dedykowane strony? Np. `||e-kiosk.pl^$all` albo to: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2203

![Screenshot_2020-06-25 e-Kiosk pl - e-wydania gazet i czasopism, e-booki, audiobooki](https://user-images.githubusercontent.com/63287518/85736794-1694fd00-b6ff-11ea-8b66-2d7cee31a3f6.jpg)

**Comment by krystian3w** [comment]
Jedynie link z grafiką do e-kiosku u innych, to nie KAD by ich banować na maksa, że strona się rozwala lub dawać ostrzenie że otwierasz e kiosk.
