### ISSUE TITLE
ktociewyleczy.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2237]
### Typ elementu/problemu
- [x] Inny element (np. widget „następny artykuł”)
- [x] Reklama prenumeraty/e-wydania gazety
- [x] Pytanie

Pytanie jak kwalifikować obiekt nr 2 , zdaje się, że jako `Inny element (np. widget „następny artykuł”)`

### 1
![capture_267_25-06-2020_16-26-13](https://user-images.githubusercontent.com/63287518/85739127-d46cbb00-b700-11ea-8cf0-709d64309df2.png)

### 2
![capture_268_25-06-2020_16-28-31](https://user-images.githubusercontent.com/63287518/85739234-e9494e80-b700-11ea-9233-7372e6959fb9.png)

**Comment by krystian3w** [comment]
Ja mam to jako pop-up, jak dla mnie fukcjonalny to go nie ruszamy, a dół z magazynami dotniemy.

**Comment by gargul2** [comment]
> Ja mam to jako pop-up

No nie bardzo, to nie wyskakuje jak popup, lecz wyjeżdza z lewej strony jak widżet, a jak się go zamknie to spowrotem wjeżdza do lewej krawędzi, być może to przegapiłeś?

**Comment by krystian3w** [comment]
Newsletter gdzieś w środku a pop-up bo jednak rozmiar (i duplikuje funkcje widgetu spod headeru), nawet twoje `i()` @hawkeye116477 jednak przeniósł do pop-upów "suplement".
