### ISSUE TITLE
telewizjarepublika.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2264]
![Schowek02](https://user-images.githubusercontent.com/63287518/85931498-1ba3a900-b8c5-11ea-902a-cd1bbb60cc64.gif)

**Comment by blocker999** [comment]
@hawkeye116477  / @krystian3w  co zz tego typu " promocją " ?

**Comment by hawkeye116477** [comment]
To są po prostu linki do innych serwisów z samą „prawdą"...
