### ISSUE TITLE
tylkotorun.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2275]
![capture_335_27-06-2020_22-41-53](https://user-images.githubusercontent.com/63287518/85931831-6de5c980-b8c7-11ea-8147-6be86f4440f1.gif)

**Comment by krystian3w** [comment]
@hawkeye116477 trzeba poprawić, niby czasem otwiera się pop-up z "carrefourem".

**Comment by krystian3w** [comment]
Jak dla mnie obecny filtr wycina 1 z 2 lub zmienili 3 na 4.
