### ISSUE TITLE
nowinykrapkowickie.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2280]
http://nowinykrapkowickie.pl/w/ruch-bedzie-faworytem

![capture_340_27-06-2020_22-46-44](https://user-images.githubusercontent.com/63287518/85931918-1d22a080-b8c8-11ea-9b47-1cf0ecf37669.gif)

**Comment by blocker999** [comment]
@krystian3w  / @hawkeye116477  Niewiem co z tym zrobić , bo teoretycznie to zachęta do prenumeraty ale z drugiej strony to info że to tylko część artykułu więc ja bym zostawił, a Wy ?

**Comment by hawkeye116477** [comment]
Raczej do zostawienia, skoro całości nie da rady przeczytać bez opłaty.
