### ISSUE TITLE
zwierciadlo.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2287]
### 1
![capture_347_27-06-2020_22-52-57](https://user-images.githubusercontent.com/63287518/85932048-1fd1c580-b8c9-11ea-83b2-8602dc8669d8.gif)

### 2
![capture_348_27-06-2020_22-53-02](https://user-images.githubusercontent.com/63287518/85932051-23fde300-b8c9-11ea-82ad-ccf8a941a35f.gif)

### 3
![capture_349_27-06-2020_22-53-07](https://user-images.githubusercontent.com/63287518/85932053-25c7a680-b8c9-11ea-86ea-47f99d10675a.gif)

**Comment by blocker999** [comment]
help

**Comment by gargul2** [comment]
Znowu są:

### 1
![capture_006_03-08-2020_13-12-57](https://user-images.githubusercontent.com/63287518/89177206-308def00-d58b-11ea-9bb9-5f70a368fbeb.gif)

### 2
![capture_007_03-08-2020_13-13-03](https://user-images.githubusercontent.com/63287518/89177216-34ba0c80-d58b-11ea-90b9-cd25dc6f5709.gif)

**Comment by gargul2** [comment]
To samo co tu: https://github.com/uBlockOrigin/uBlock-issues/issues/1238

**Comment by gargul6** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/341
