### ISSUE TITLE
histmag.org

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2294]
### Typ elementu/problemu
- [x] Inny element (np. widget „następny artykuł”)
- [x] Reklama prenumeraty/e-wydania gazety

### 1
![capture_359_27-06-2020_23-06-26](https://user-images.githubusercontent.com/63287518/85932285-f74acb00-b8ca-11ea-928e-d57e32d82b73.gif)

### 2
![Nagrywaj_2020_06_27_23_07_54_299](https://user-images.githubusercontent.com/63287518/85932300-0c275e80-b8cb-11ea-9115-cd26db7271db.gif)

**Comment by krystian3w** [comment]
Newsletter jak na innym zgłoszeniu co otwiera / zachęca do rejestracji.
