### ISSUE TITLE
party.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2305]
![capture_372_27-06-2020_23-30-12](https://user-images.githubusercontent.com/63287518/85932651-31699c00-b8ce-11ea-972e-154f46862a27.gif)

**Comment by blocker999** [comment]
Co z tym zrobić, bo teraz jest smartfon w tym miejscu ?

**Comment by hawkeye116477** [comment]
Olać.
