### ISSUE TITLE
dziennikbaltycki.pl + dzienniklodzki.pl + dziennikpolski24.pl + dziennikzachodni.pl + echodnia.eu + expressbydgoski.pl + expressilustrowany.pl + gazetakrakowska.pl + gazetalubuska.pl + gazetawroclawska.pl + gloswielkopolski.pl + gp24.pl + gs24.pl + kurierlubelski.pl + nowiny24.pl + nowosci.com.pl + nto.pl + polskatimes.pl + poranny.pl + to.com.pl + wspolczesna.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2307]
![capture_361_27-06-2020_23-10-40](https://user-images.githubusercontent.com/63287518/85932337-835cf280-b8cb-11ea-8aea-ee56692e6431.gif)

**Comment by krystian3w** [comment]
Mam nadzieje, że nie wskoczy do bocznego, bo będzie trzeba przeszukiwać z 249 elementów za prenumeratą by nie zostawał placeholder - nie wiem na ile tu:

 `a[title="Podczas wakacji nie musisz rozstawać się ze swoją gazetą"]:upward(1)`

 pomaga...

**Comment by gargul2** [comment]
Znalazłem prostsze i zgodne z ABP: 
`domeny##[data-event-params^="url=%2Fzabierz-swoja-gazete-na-wakacje-prenumeruj-przez-kwartal-w-nizszej-cenie"]`

**Comment by krystian3w** [comment]
A ten "mniejszy" można przekonwertować: 

![obraz](https://user-images.githubusercontent.com/35370833/85947604-10479080-b94c-11ea-82dc-4e04a346d3d7.png)


Jak dla mnie to jeszcze nie `paywall`.

**Comment by krystian3w** [comment]
przy czym nie "ufam":

`<div class="atomsPromotionsLink component" data-event-position="atomsPromotionsLink" data-event-name="atomsPromotionsLink" data-event-type="click">`

zapisaniu tego wszystkiego w kwadratowych nawiasach.

**Comment by gargul2** [comment]
>  krystian3w : https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2307#issuecomment-650746451

Fajnie, że też znalazłeś coś co z kolei ja przegapiłem, no to się uzupełniamy.

**Comment by gargul2** [comment]
To ja też pokopałem głębiej, postanowiłę sprawdzić wersje z `plusem`, więc dodałem `plus.` do `dziennikbaltycki.pl`, następnie kliknąłem w artykuł: https://plus.dziennikbaltycki.pl/przeciez-cie-nie-zgwalcil-czyli-mroczne-sekrety-biblioteki-umk-uczelnia-reaguje-kolejny-rok/ar/c15-15042382 i oczom moim ukazał się TATA dziecka z pierwszego komentarza:

![capture_431_28-06-2020_14-43-35](https://user-images.githubusercontent.com/63287518/85947925-f149fe00-b94d-11ea-90c5-b09545baa108.gif)

**Comment by gargul5** [comment]
Np. https://gloswielkopolski.pl/poznan-spoldzielnie-mieszkaniowe-bez-wsparcia-rzadu-i-samorzadu-nikt-nie-odpowiada-na-nasze-pisma-i-prosby/ar/c1-14956622

![capture_046_19-09-2020_13-02-11](https://user-images.githubusercontent.com/71551039/93665657-7722a480-fa78-11ea-9912-7cb3967de84d.gif)
