### ISSUE TITLE
mesco.com.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2308]
![Nagrywaj_2020_06_28_09_28_24_120](https://user-images.githubusercontent.com/63287518/85941203-c1850100-b921-11ea-80a7-07d6e963d4bc.gif)

**Comment by blocker999** [comment]
Macie to ?

**Comment by krystian3w** [comment]
Nie.

**Comment by krystian3w** [comment]
Pewnie trzeba w poniedziałek około 10 rano sprawdzać.

**Comment by hawkeye116477** [comment]
Też nie mam, raczej obstawiam, że pewnie przedawnione.

**Comment by krystian3w** [comment]
Bzdura w kodzie dalej ładują `bazo.io`:

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +4 |  |  | mesco.com.pl | 3 | css | `https://wp.bazo.io/bazo_plugins/popups_hotfixes.css` |
| +3 |  |  | mesco.com.pl | 3 | xhr | `https://c.bazo.io/` |
| +3 |  |  | mesco.com.pl | 3 | xhr | `https://c.bazo.io/` |
| +2 |  |  | mesco.com.pl | 3 | script | `https://c.bazo.io/t.min.js` |

**Comment by blocker999** [comment]
niema a ja czekam i czekam, co dalej ?

**Comment by hawkeye116477** [comment]
@krystian3w Już coś dodał. Można zamykać?
