### ISSUE TITLE
dochodzeniewierzytelnosci.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2312]
W artykułach np
https://www.dochodzeniewierzytelnosci.pl/2020/06/02/sady-rozpoczely-dzialalnosc-ale-trzeba-uwazac/

![Nagrywaj_2020_06_28_10_03_39_677](https://user-images.githubusercontent.com/63287518/85941997-bda7ad80-b926-11ea-99d4-ec87cec5344b.gif)

**Comment by blocker999** [comment]
![blog](https://user-images.githubusercontent.com/23176832/86510407-9dc52d80-bdef-11ea-80dd-4d1fbb912b3f.png)

**Comment by krystian3w** [comment]
`dochodzeniewierzytelnosci.pl###spu-4304, #spu-bg-4304` w https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/edit/master/sections/adblock_social_list/popupy.txt
