### ISSUE TITLE
kropkatv.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2325]
![capture_404_28-06-2020_13-02-49](https://user-images.githubusercontent.com/63287518/85945669-ae812980-b93f-11ea-9da3-c1caaa37c042.gif)

**Comment by krystian3w** [comment]
Wtedy traci sens zakładka i trzeba by przekierować na kontakt lub konkursy.

**Comment by hawkeye116477** [comment]
To jest strona tej gazety i tam nic więcej nie ma, więc raczej odpada
