### ISSUE TITLE
krir.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2332]
![Nagrywaj_2020_06_28_13_32_56_517](https://user-images.githubusercontent.com/63287518/85946324-eee2a680-b943-11ea-9707-914025e8eef8.gif)

**Comment by blocker999** [comment]
Macie to ?

**Comment by krystian3w** [comment]
Nie mam, sieciowo wycięte lub nieaktywne w soboty (czas mogą sprawdzać z API z serwera).
