### ISSUE TITLE
niepokalanow.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2333]
Nie wiem czy "działalność wydawnicza" się kwalifikuje czy nie, to najwyżej mnie oświecicie i zostanę świętym.

![capture_418_28-06-2020_13-35-36](https://user-images.githubusercontent.com/63287518/85946385-4bde5c80-b944-11ea-82aa-edd15ba891e6.gif)

**Comment by blocker999** [comment]
@gargul2 Niemam nic do działalności wydawniczej ale do promowania już tak, w skrócie od wyboru książek masz księgarnie a nik na siłe nie powinien Cie zmuszać do czytania.
