### ISSUE TITLE
opolshe.ru

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2336]
Domena ruska, ale strona po polsku, chociaż komunikat po rosyjsku...

![capture_420_28-06-2020_13-47-06](https://user-images.githubusercontent.com/63287518/85946620-e55a3e00-b945-11ea-89f5-dfe395845ab2.gif)

**Comment by krystian3w** [comment]
Bo ktoś podkrada treść iframe.
