### ISSUE TITLE
urzadzamy.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2340]
### 1
![capture_425_28-06-2020_14-00-09](https://user-images.githubusercontent.com/63287518/85946888-ca88c900-b947-11ea-96fc-f76683f57064.gif)

2### 
![capture_426_28-06-2020_14-00-13](https://user-images.githubusercontent.com/63287518/85946890-cd83b980-b947-11ea-9b58-61c91bd16f2e.gif)

**Comment by blocker999** [comment]
Nie mam tego, co dalej ?

**Comment by hawkeye116477** [comment]
Gargulec już raczej nie odpisze, bo szef mu dał wolne :rofl: 

Za to ja odpowiem, że najwyraźniej zmienili wygląd strony i już tego nie ma.
