### ISSUE TITLE
polsatnews.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2342]
https://www.polsatnews.pl/wiadomosc/2020-06-30/unia-otwiera-granice-zewnetrzne-ale-nie-dla-wszystkich-znamy-liste-panstw/

![2020-06-30 22 16 07 www polsatnews pl 7c82644268c4](https://user-images.githubusercontent.com/36385327/86172978-7fc1a980-bb1f-11ea-8aeb-dac096eef0cf.png)

**Comment by hawkeye116477** [comment]
W zasadzie to już chyba kiedyś było

@krystian3w Wiesz coś, pamiętasz może o tej sprawie, co się wtedy stało z regułami na to?

**Comment by krystian3w** [comment]
Za bardzo nie wiem, pewnie się zestarzały i trzeba zaktualizować.

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/644

**Comment by krystian3w** [comment]
Mam, coś za mocno blokował `aopr`: https://github.com/MajkiIT/polish-ads-filter/issues/13261

**Comment by krystian3w** [comment]
W maju 2018 usnunąłeś, bo coś się psuło lub nagle wycofali player: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/f36006407773d032808dfda4f32ff217337fbbe7

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/643 https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/644

**Comment by hawkeye116477** [comment]
Pewnie raczej coś się psuło.
