### ISSUE TITLE
crolove.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2349]
https://crolove.pl/park-przyrody-papuk-jankovac-mountain-park/
![2020-07-18 11 49 05 crolove pl 1cf8e9d1cd01](https://user-images.githubusercontent.com/36385327/87849983-0088ef80-c8ed-11ea-9239-d05226663d25.png)

**Comment by krystian3w** [comment]
Znowu nie widzisz newslettera w stopce:

![obraz](https://user-images.githubusercontent.com/35370833/87853445-58821f00-c90a-11ea-8d6e-7b5193d1e62e.png)
