### ISSUE TITLE
heyah.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2354]
![2020-07-26 18 33 32 www heyah pl fda9b0be7620](https://user-images.githubusercontent.com/36385327/88484423-afbd6a80-cf6e-11ea-847e-7cd401fae5d2.png)

**Comment by krystian3w** [comment]
@hawkeye116477 to nie ma zamykacza? Oceń przed pierwszym podbiciem wersji czy warto.
