### ISSUE TITLE
interia.pl

### ISSUE THREAD

**Issue by gargul3** [PolishFiltersTeam/PolishAnnoyanceFilters#2355]
![capture_019_28-07-2020_12-28-39](https://user-images.githubusercontent.com/67320782/88654627-e958b780-d0cd-11ea-944c-3568d505921b.gif)

**Comment by krystian3w** [comment]
@hawkeye116477  stwierdził, że gazetki "hiper"-marketów niby się nie łapią, czyli trzeba jeszcze dokładniej to opisać w contributing.md
