### ISSUE TITLE
castorama.pl

### ISSUE THREAD

**Issue by gargul3** [PolishFiltersTeam/PolishAnnoyanceFilters#2356]
![capture_021_28-07-2020_12-30-05](https://user-images.githubusercontent.com/67320782/88654791-245aeb00-d0ce-11ea-93ee-ffafef885ed5.gif)

**Comment by blocker999** [comment]
Macie to ?

**Comment by hawkeye116477** [comment]
To jest newsletter i jest już ukrywany.

**Comment by gargul2** [comment]
Dalej to jest.

**Comment by krystian3w** [comment]
Tego nie ma, jest nowe ruchome, a tak lubisz gify wklejać.

**Comment by krystian3w** [comment]
`pl##.block-subscribe` - jak masz inną klasę to spakuj stronę "beta" do archiwum zip.

**Comment by gargul2** [comment]
> `pl##.block-subscribe`

Jak podasz mi nr wiersza gdzie ten filtr jest w module Newslettery to stawiam ci piwo :smiley: ...

> Tego nie ma,

Doskonale wiecie, że używam modułów, kiedyś już były podobne sytuacje, że zgłaszałem coś co wyskakiwało na modułach, a nie wyskakiwało na pełnych EI lub odwrotnie. No i jeśli w tym przypadku znowu testowałeś na całych EI,  to nie dziwne, że nie ma, bo sprawdziłem i rzeczywiście nie ma, a teraz czary mary: wyłącz całe EI i załącz sam moduł:
`Polskie Filtry Elementów Irytujących - Newslettery `, tadaaaa, znowu się pojawia. Więc poszukałem, pogrzebałem w commitach i teraz wyjmę ci królika z kapelusza: od prawie roku (jutro mija równo rocznica więc możemy wznieść toast szampanem) nie ma w module Newslettery filtrów ogólnych bo hawkeye je przenióśł do [>> OSOBNEJ LISTY <<](https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB/newslettery_ogolne.txt):

- https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/1b5840f99b251fcfee42f3263fb5662896a198a4#comments

- https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/25ec0ec87cda05c7ca67d4872c2773ebc7d737ea?branch=25ec0ec87cda05c7ca67d4872c2773ebc7d737ea&diff=split#diff-179cb84eb4ff06cb45a4dd112ca6d4e5L742

i do dziś jej nie zainlcudował w module Newslettery:

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/737e9b968f441f40aac162b3076239a6f350e7c4/PAF_newsletters.txt#L1575-L1581

więc:

```
- Houston, mamy problem!
- Jaki?
- Uwaliło "ogólne newslettery" w module Newslettery! Od ponad roku!
- O jasna cholera...to dlatego gargulowi wyskakują pryszcze (newslettery) na stronach...gdyby nie gargul to być może brakowałoby ogólnych w module Newslettery przez następnych 10 lat... ;)
```

>  jest nowe ruchome, a tak lubisz gify wklejać.

Te nowe mam ukryte przez swoje dodatkowe filtry (informowałem, że używam dodatkowych list), jak widać przydają się jako uzupełnienie dla EI, mniej syfu do zgłaszania.

**Comment by krystian3w** [comment]
Ja bym im nie ufał jak masz samo `##.pull-right` może ktoś tym wyrównuje jakiś tekst do prawej w artykułach i nagle fragmenty zniknął.

**Comment by hawkeye116477** [comment]
> Doskonale wiecie, że używam modułów

Cóż, zawsze można zapomnieć.

> do dziś jej nie zainlcudował w module Newslettery

Fakt, to był mój błąd, pomyliłem nazwę pliku. 

> gdyby nie gargul to być może brakowałoby ogólnych w module Newslettery przez następnych 10 lat

No skoro nikt inny nie zgłaszał, to być może tylko ty korzystasz z modułów albo inni lubią newslettery. Tak czy siak do twoich słów idealnie pasuje pewien wiersz:

> Samochwała w kącie stała. I wciąż tak opowiadała: „Zdolna jestem niesłychanie,. Najpiękniejsze mam ubranie

**Comment by gargul2** [comment]
> Cóż, zawsze można zapomnieć.
> No skoro nikt inny nie zgłaszał, to być może tylko ty korzystasz z modułów albo inni lubią newslettery. 

- wiem, ale to chyba w takim razie była zbiorowa skleroza...zgłaszane dwukrotnie, trzech chłopa i wszyscy bidoki zapomnieli
- nie ważne czy ktoś używa modułów czy całego EI, jeśli coś jest zgłaszane, zwłaszcza dwukrotnie i nie możecie zreprodukować, to normalne, że wtedy sprawdza się także w modułach, czy tu też zbiorowa skleroza, a może brak profesjonalizmu...
- poza tym tacy pewni siebie byliście jakbyście Mt. Everest zdobyli

Więc nie płacz już i nie tłumacz się tyle, że podaliście klientowi nieświeże danie w restauracji, dlatego bo nikt inny po za klientem tego dania nie zamawia, więc jego wina i dlatego bo 3 kucharzy w kuchni nie zauważyło przez 2 tygodnie, że dawało klientowi nieświeże danie przez cały rok, pomimo, że klient zgłaszał 2-krotnie, ....:smiley:

> Samochwała

Nie żebym się jakoś specjalnie przechwalał:
- na końcu jest emotka "`... ;)`" sugerująca, że to tak pół-żartem, a kulfon macha se uszami, której to emotki dziwnym przypadkiem brakuje w twoim cytacie...czyżby dlatego bo przeszkadzałaby ci ona w zamianie kontekstu pół-żartu mojej wypowiedzi na kontekst samochwalstwa...
- skoro jeden gargul wyłapał coś czego nie wyłapało 3 chłopa przez 2 tygodnie po 2 zgłoszeniach, którzy w dodatku byli pewni swego jakby zdobyli Mt. Everest, to może jednak gargul zasługuje żeby się odrobinę pochwalić, no ale ty zaraz się przyczepisz i swoimi manipulacjami zrobisz z niego chwalipiętę...

..coś na zasadzie: 
- gargul spróbuje cukierka w sklepie, to napiszesz od razu, że jest złodziejem i gangsterem, który obrabował bank...
- gargul wypije piwo albo szampana raz na "ruski rok" (np. na Sylwestra) to jest odrazu pijakiem / menelem / żulem / kloszardem

hawkeye niezły z ciebie manipulant, miłego dnia i nie przeżywaj już tyle :smiley:

**Comment by gargul2** [comment]
> Samochwała

Ta samochwała jako jedyna znalazła błąd, którego nie mogło znaleźć 3 chłopa przez 2 tygodnie pomimo 2 zgłoszeń, więc samochwała po prostu trochę chciała się pochwalić (ale tak pół żartem), więc nie płacz już tak, hahaha.

> Fakt, to był mój błąd, pomyliłem nazwę pliku.

To teraz kara chłosty - 20 uderzeń końskim biczem po dupie....hahaha
