### ISSUE TITLE
zielonyogrodek.pl

### ISSUE THREAD

**Issue by gargul3** [PolishFiltersTeam/PolishAnnoyanceFilters#2361]
### 1 na głównej:

![capture_017_28-07-2020_11-41-07](https://user-images.githubusercontent.com/67320782/88648553-62084580-d0c7-11ea-8584-d3405320ca9d.gif)

### 2 w artykułach np https://zielonyogrodek.pl/pielegnacja/uprawa-roslin/6808-jak-pielegnowac-lawende-by-kwitla-obficie

![capture_018_28-07-2020_11-42-40](https://user-images.githubusercontent.com/67320782/88648788-9bd94c00-d0c7-11ea-843c-dc5550af335c.gif)

**Comment by gargul2** [comment]
Dalej jest to co na screenshocie nr 2
