### ISSUE TITLE
gwiazdybasketu.pl

### ISSUE THREAD

**Issue by gargul3** [PolishFiltersTeam/PolishAnnoyanceFilters#2363]
![capture_016_28-07-2020_11-35-48](https://user-images.githubusercontent.com/67320782/88648173-0342cc00-d0c7-11ea-8656-98a4c94076ed.gif)

**Comment by gargul2** [comment]
Przegapiłem widżet następny artykuł w artykułach np 
http://www.gwiazdybasketu.pl/nba-obroncy-tytulu-wygladaja-mocno-lakers-przypieczetowali-pole-position/

![capture_029_05-08-2020_12-55-27](https://user-images.githubusercontent.com/63287518/89404921-0a975480-d71b-11ea-97c6-a056fa02b5c3.gif)

![Nagrywaj_2020_08_05_12_55_42_891](https://user-images.githubusercontent.com/63287518/89404927-0bc88180-d71b-11ea-893d-c00d9cbb22d1.gif)
