### ISSUE TITLE
lomilowka.pl

### ISSUE THREAD

**Issue by gargul3** [PolishFiltersTeam/PolishAnnoyanceFilters#2371]
![capture_019_28-07-2020_11-44-33](https://user-images.githubusercontent.com/67320782/88648936-c0352880-d0c7-11ea-9ff6-54674ab8eae9.gif)

**Comment by blocker999** [comment]
scroll

**Comment by krystian3w** [comment]
`##.modal-open:style(overflow: auto !important; padding-right: 0 !important;)`
