### ISSUE TITLE
merkandi.pl

### ISSUE THREAD

**Issue by gargul3** [PolishFiltersTeam/PolishAnnoyanceFilters#2374]
![capture_004_28-07-2020_10-56-52](https://user-images.githubusercontent.com/67320782/88642889-51ed6780-d0c1-11ea-8e2d-779dbf347c75.gif)

**Comment by blocker999** [comment]
scroll

**Comment by krystian3w** [comment]
`##.modal-open:style(overflow: auto !important; padding-right: 0 !important;)`
