### ISSUE TITLE
sykomat.com.pl

### ISSUE THREAD

**Issue by gargul3** [PolishFiltersTeam/PolishAnnoyanceFilters#2391]
![capture_016_28-07-2020_12-25-31](https://user-images.githubusercontent.com/67320782/88654321-8109d600-d0cd-11ea-8a11-1503a3441d3c.gif)

![Nagrywaj_2020_07_28_12_25_36_82](https://user-images.githubusercontent.com/67320782/88654395-9da60e00-d0cd-11ea-8089-f36c11eb9f3b.gif)

**Comment by gargul2** [comment]
Dalej to jest.
