### ISSUE TITLE
dobrarelacja.pl

### ISSUE THREAD

**Issue by gargul3** [PolishFiltersTeam/PolishAnnoyanceFilters#2396]
### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [x] Newsletter (nie popup)
- [] Powiadomienie push (nie „zgoda na geolokalizację”)
- [] Scrollujący filmik
- [] Inny element (np. widget „następny artykuł”)
- [] Widżet kontaktowy/informacji zwrotnej
- [] Strzałka
- [] Otagowany link wewnętrzny (niezgodny z tematem artykułu)
- [] Tło zawierające autopromocję
- [] Tytuł strony zachęcający do powrotu
- [ ] Reklama prenumeraty/e-wydania gazety
- [] Błąd
- [ ] Pytanie
- [] Ulepszenie

Dałem 2 etykiety bo to wygląda jak hybryda newslettera z prenumeratą/e-wydaniem i nie jestem pewien gdzie to się kwalifikuje

![capture_007_28-07-2020_12-16-16](https://user-images.githubusercontent.com/67320782/88653540-83b7fb80-d0cc-11ea-9332-ac161db02bad.gif)

**Comment by gargul3** [comment]
Ooo znowu bot dupy daje, nie dodał etykiet, tutaj też: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2368, albo doda z opóźnieniem, pozostaje zacisnąć kciuki i mieć nadzieję...

**Comment by krystian3w** [comment]
Kod bota podobno jest niewspierany, fajnej alternatywy by nie robić od zera bota i serwera chyba brak.

**Comment by hawkeye116477** [comment]
Alternatywa niby jest `https://github.com/riyadhalnur/issuelabeler`, ale przy pomyłce bot nic nie odznaczy i trzeba wpisywać dokładnie taki sam napis jak na etykietce. Moim zdaniem to jednak coś może też być po stronie któregoś z serwerów, jakieś lagi.

**Comment by gargul4** [comment]
Możliwe, ale ten sprint i te kilku/nasto sekundowe odstępy to były konieczne dlatego, bo gdybym zgłaszał wolniej to w maratonie mogłaby mnie wyprzedzić taka biegaczka o imieniu "blokada konta"... a chciałem pozbyć się tego syfu / badziewia / balastu zalegającego od miesiąca w zakładkach za nim nastąpi koniec świata / powygasa / zdezaktualizuje się, no i w kóncu się udało, jestem teraz zadowolony i spełniony na swojej ścieżce życia wyłożonej raportozą, co za ulga...teraz w pozycji zrelaksowanej z nachyleniem tułowia do ud, pod kątem 45 stopni, będę z podziwem was obserwował na waszej ścieżce ogarniania tego chłamu.  :smiley:

**Comment by krystian3w** [comment]
Obecnie bot ma jakieś "2 minutowe" opóźnienie.
