### ISSUE TITLE
monitor-press.com

### ISSUE THREAD

**Issue by gargul3** [PolishFiltersTeam/PolishAnnoyanceFilters#2421]
~~Strona nie jest po polsku, ale prenumerata jest~~

![capture_050_28-07-2020_15-07-30](https://user-images.githubusercontent.com/67320782/88669438-2d56b700-d0e4-11ea-88fd-6bd1146386c2.gif)

**Comment by krystian3w** [comment]
Gazeta jest dwujęzyczna.

**Comment by krystian3w** [comment]
Poza tym w innych językach nie naprawiamy zbugowanych przycisków social - by były znowu widoczne nawet jak nie mają "ukrainizacji".

**Comment by gargul4** [comment]
> Gazeta jest dwujęzyczna.

OK, w takim razie zastanawia mnie dlaczego załadowała mi się wersja ukraińska...
