### ISSUE TITLE
castorama.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2463]
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2356#issuecomment-669125090

**Comment by krystian3w** [comment]
Nie ma tego ze stopki, za to jakiś boczny "przypięty" do prawej krawędzi.

**Comment by gargul2** [comment]
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2356#issuecomment-673368394
