### ISSUE TITLE
polskaniepodlegla.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2466]
### Typ elementu/problemu
- [x] Reklama prenumeraty/e-wydania gazety
- [x] Błąd

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2364#issuecomment-669129441

**Comment by krystian3w** [comment]
Otworzyłem tamto, zmieniona etykieta.
