### ISSUE TITLE
ksiegarnia-edukacyjna.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2490]
https://github.com/MajkiIT/polish-ads-filter/issues/17000#issue-690833711

![capture_001_02-09-2020_12-50-59](https://user-images.githubusercontent.com/63287518/91972652-496cfa00-ed1b-11ea-9fe5-8cd0bba6f8f9.gif)

**Comment by krystian3w** [comment]
Jeszcze stopkę mają fatalną, trzeba było w ABP odblokować a na uBO/AG ukryć CSS-em.
