### ISSUE TITLE
aftermarket.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2492]
### 1
![capture_005_05-09-2020_17-12-48](https://user-images.githubusercontent.com/63287518/92308062-47b16980-ef9b-11ea-84cd-766b883fee56.gif)

### 2
![capture_004_05-09-2020_17-12-45](https://user-images.githubusercontent.com/63287518/92308073-5ef05700-ef9b-11ea-92d4-23097a50d5e6.gif)

### 3
![Nagrywaj_2020_09_05_17_12_32_455](https://user-images.githubusercontent.com/63287518/92308069-5009a480-ef9b-11ea-8986-38e23eff45ca.gif)

**Comment by krystian3w** [comment]
Sam się kiedykolwiek otwiera?

Jako osobny element wyskakuje tylko to a nie cały chat:

![obraz](https://user-images.githubusercontent.com/35370833/92308297-f609de80-ef9c-11ea-9f2e-b3abd67ce3b9.png) |
--- |

**Comment by gargul2** [comment]
Samo się nie otwiera, na screenach wkleiłem wersję zarówno zwiniętą (domyślną po wejściu na stronę) jak i rozwiniętą (po kliknięciu myszką), a dodatkowa animacja wyraźnie pokazuje, że rozwija się po klinięciu myszką, a nie samo. A dymek rzeczywiscie pojawia się od razu, ale tylko po 1 wejściu na stronę, zapomniałem wyczyścić ciasteczka przed zrobieniem screena / animacji.

**Comment by krystian3w** [comment]
Chyba od 3 wizyty dymek znika, ja przy drugiej dalej miałem.

**Comment by gargul2** [comment]
Okazało się, że obydwoje jesteśmy w błędzie, bo dymek jednak pojawia się automatycznie przy każdym wejściu na stronę, dopiero jego ręczne zamknięcie poprzez kliknięcie myszką na krzyżyk od dmyka dezaktywuje go na stałe, więc najwyraźniej zamknąłem dymek i zapomniałem o nim.
