### ISSUE TITLE
meczenazywo.tv

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2494]
2 x popup

### 1
![111](https://user-images.githubusercontent.com/63287518/92321878-e2f31f00-f02d-11ea-86d5-e84898a51349.gif)

### 2
![capture_007_06-09-2020_10-41-22](https://user-images.githubusercontent.com/63287518/92321881-e686a600-f02d-11ea-9700-2068b068aef4.gif)

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2495#issuecomment-687773206

@MajkiIT sts nie wydaje się być jakimś oficjalnym sponsorem `meczenazywo.tv` ani `meczelive.pl`.

**Comment by krystian3w** [comment]
Oprócz pop-upa widzę strzałkę i widżet googla o reCAPTCHA.
