### ISSUE TITLE
meczlive.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2495]
### Typ elementu/problemu
- [x] Wyskakujące okienko (popup)
- [x] Newsletter (nie popup)

2 x popup, podobne do https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2494, nie sprawdzałem  czy to bliźniacze strony (dające się naprawić tym samym filtrem), więc daję w osobnym zgłoszeniu.
1 x newsletter

### 1
![1111111](https://user-images.githubusercontent.com/63287518/92321972-b55aa580-f02e-11ea-8c46-7a06af3a7dc5.gif)

### 2
![capture_008_06-09-2020_10-48-56](https://user-images.githubusercontent.com/63287518/92321963-a542c600-f02e-11ea-9e16-bd207d1ba258.gif)

### 3 newsletter
![capture_011_06-09-2020_11-00-45](https://user-images.githubusercontent.com/63287518/92322227-4da55a00-f030-11ea-9bb6-466f7683cc4d.gif)

**Comment by krystian3w** [comment]
Ja nic nie wiem o naprawianiu pop-upów z osobnym oknem (`$popup` / `$popunder` / `nowoif.js|window.open-defuser.js`).

Możliwe, że są reklamowe i dla MajkiIT wtedy...

**Comment by gargul2** [comment]
> Możliwe, że są reklamowe

No ja też nie byłem pewien gdzie to wrzucić, więc wrzuciłem do was, ale dodatkowo w https://github.com/MajkiIT/polish-ads-filter/issues/17009 ponformowałem majkiego o tym fakcie, a on nie protestował i zamknął swoje zgłoszenie ogarniając tylko zwykłą reklamę, no chłopaki musicie się dogadać, na którą listę to się kwalifikuje :smiley:

**Comment by krystian3w** [comment]
Jak to nie ta sama domena się otwiera w okienku lub grupa np. Press Polska otwiera inny region w pop-upie (np. Lubin otwiera Łódź) to do nas nie.

Myślę, że jawny `sponsoring` tych stron przez STS/efortuna nie powoduje, że to reklama wewnętrzna.

Jak ktoś chce blokować reklamy, to musi pomyśleć o aktywacji EasyList i filtrów regionalnych.

Jak dla mnie to też nie łapie się do KAD jako "przekręt".
