### ISSUE TITLE
[Grupa ZPR Media] m.in. se.pl i murator

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2501]
https://sport.se.pl/sporty-walki/mma/fame-mma-7-gola-malczynski-aa-UxLU-hk3U-yee2.html

![capture_025_08-09-2020_09-53-10](https://user-images.githubusercontent.com/63287518/92448946-9ccac680-f1b9-11ea-85d7-31d8807f9f10.gif)

**Comment by krystian3w** [comment]
Losowy, wycięty źle w modułach lub już wyłączony.

**Comment by gargul2** [comment]
Wyłączony na pewno nie, wczoraj mi wyskoczył jeden raz, ale odświeżyłem stronę, zapominając zrobić screenshoota, i potem już cham nie chciał wyskoczyć, nawet po wyłączeniu adblockera, wyczyszczeniu ciasteczek, i odświeżaniu strony kilka razy, więc nie miałem jak go uchwycić, ale dodałem sobie stronę do zakładek, i cierpliwie czekałem do dzisiaj w razie jakby skubaniec postanowił znowu później wyskoczyć jak niemiec z bunkra i bigno! Dzisiaj znowu się pojawił, wyskakując jak Filip z konopii, więc zrobiłem screenshoota i zgłoszenie.

Po prostu skubaniec jakoś losowo się pojawia, musisz się zaczaić jak myśliwy w krzakach i go upolować. :smiley:

**Comment by gargul2** [comment]
Mam go: `https://rozrywka.grupazprmedia.net/popup_superSport_ssport_desktop`

`||rozrywka.grupazprmedia.net/popup_superSport_ssport_desktop$subdocument,domain=sport.se.pl`

(kosmetykiem trudno bo ma losowe klasy)

**Comment by krystian3w** [comment]
W sumie nie pasuje mi te tło co może jest pod iframe, więc i tak by się przydało go ujrzeć - powinno wystarczyć zapisanie strony do "zip".

**Comment by gargul2** [comment]
Racja, zostaje tło, na tło: 
`sport.se.pl##body.article-layout > div[id][class]:-abp-has(iframe[src$=popup_superSport_ssport_desktop])`

[Desktop.zip](https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/files/5194035/Desktop.zip) - (a tak w ogóle github to badziewie, nie wspiera `7zip`, jak i kolorowego tekstu)


![capture_029_09-09-2020_11-15-08](https://user-images.githubusercontent.com/63287518/92579786-ec7ac200-f28d-11ea-842f-a8a25c89dff7.gif)

**Comment by krystian3w** [comment]
Jak nie wspiera kolorowego tekstu?

```diff
@@ fiolety @@
---- czerwienie
+++ zielenie
```

```html
    <html><!-- -->
    <body><!-- -->
    <div id="kev2bglhnnucp" class="_shjrr8u">
      <div id="kev2bglhpg70r" class="_1ceeqqo">
        <div class="_hniafzj">
        <button id="kev2bglh4ovi9" class="_3xjc76y"><span class="_8x4j35">zamknij</span></button>
        <iframe class="_12ifvmu" src="https://rozrywka.grupazprmedia.net/popup_superSport_ssport_desktop" style="display: none !important;" hidden=""></iframe>
        </div>
      </div>
    </div>
    </body></html>
```

**Comment by gargul2** [comment]
> Jak nie wspiera kolorowego tekstu?

<br>
:smiley:
<br>
<br>

1) to co pokazałeś to kolorowy **kod** a nie **tekst**, widać nie umiesz rozróżnić kodu od tekstu, zwykłego tekstu nie pokolorujesz w taki sposób

2)  o kolorowaniu kodu wiem i pamiętam bo sam tego użyłem 2 miesięce temu https://github.com/MajkiIT/polish-ads-filter/issues/16763#issue-650871212

3) to co najwyżej psuedo-kolorowanie kodu / proteza, bo nie da się:
- pokolorować dowolnych słów/liter, jedynie całe wiersze
- użyć dowolnych kolorów, jest jedynie kilka narzuconych z góry, które dodatkowo w przypadku kolorowania składni html/js są wyblaknięte / wyprane i ledwo je widać, o kant dupy rozbić takie kolorowanie, wzrok dalej się męczy

Jak już pisałem github pod kilkoma względami jest po prostu niedorobionym szajsem: kolorowania tekstu brak, a kolorowanie kodu jest kalekie, można dołączyć załącznik `zip`, ale już `7zip` nie, a jak wiadomo `7zip` o wiele mocniej kompresuje, zamiast tego woleli dać durne emotki, robiąc z githuba gówno fejsbukowe dla dzieci w wieku przedszkolnym / szkolnym, żeby gimbusy i różnej maści niedorozwoje umsyłowe / pokemony mogły sobie prowokować, trolować i obklejać nimi czyjeś komentarze, teraz to jest `pokemon-hub` / `fejs-hub`, no ale jak githubem zarządza jakiś szympans / orangutan / pawian to tak niestety będzie.

**Comment by gargul2** [comment]
Do poprawki `src`, bo wyskoczyło nowe okno z nowym adresem: 
`src="https://rozrywka.grupazprmedia.net/badaniaMuzyczne_sportSe_desktop"`

Więc:
- `[src$=popup_superSport_ssport_desktop])` ==> `[src$=_desktop])`
no chyba, że kolejnym razem dadzą nowe okno z np. `_desktop5e` to wtedy ==> `[src*=_desktop])` (`$` na `*`)
- no i dodać kolejne tego typu `||grupazprmedia.net/popup_superSport_ssport$subdocument,domain=sport.se.pl`  albo jakoś scalić w jedno

![capture_033_11-09-2020_13-58-22](https://user-images.githubusercontent.com/63287518/92923307-8af65700-f437-11ea-85c8-fef9818704f0.gif)

**Comment by krystian3w** [comment]
Możliwe, że udając telefon będzie "`_mobile`"...

**Comment by krystian3w** [comment]
Mobile niby działa, wtedy jest wersja "skompresowana":

![obraz](https://user-images.githubusercontent.com/35370833/93003476-3807c700-f53f-11ea-9882-9ebef82849e9.png) |
--- |

**Comment by gargul2** [comment]
> krystian3w: 
> Możliwe, że udając telefon będzie "`_mobile`"...
> https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/9395e9e6d283415a49ea2f9a8571b1590c3fe190#diff-89ffbf43b368507d29148da7dae11294R620
> `rozrywka.grupazprmedia.net`

A zamiast `rozrywki` będzie  `budowa`:
https://budowa.grupazprmedia.net/popUp_muratorplus_mplus_pdf_desktop
https://budowa.grupazprmedia.net/popUp_muratorplus_mplus_pdf_mobile
No chyba, że to na https://www.muratorplus.pl/

A tu też chyba więcej takich stron:
https://app.grupazprmedia.net/e/er?s=1782711468&lid=52&elqTrackId=f41e549cd0f64281bed82bcc7840fcee&elq=00000000000000000000000000000000&elqaid=301&elqat=2
https://app.grupazprmedia.net/e/er?s=1782711468&lid=52&elqTrackId=f41e549cd0f64281bed82bcc7840fcee&elq=00000000000000000000000000000000&elqaid=302&elqat=2

==>

https://rodo.grupazpr.pl/#time-klauzula-marketingowa

, nowa `Grupa` na repo EI?:

![capture_001_12-09-2020_21-48-11](https://user-images.githubusercontent.com/63287518/93003758-a483c580-f541-11ea-9c6e-64c2b3375916.gif)

**Comment by krystian3w** [comment]
Ja tam widzę, że chyba dla każdego robią RWD.
