### ISSUE TITLE
[H88][R22] [cyber_Folks™] aka linuxpl/hekko

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2502]
![2020-09-11 18 41 30 cyberfolks pl bfa172c77f63](https://user-images.githubusercontent.com/36385327/92951354-7ed1c000-f45e-11ea-855f-724361f708c9.png)

**Comment by krystian3w** [comment]
@xMaap  monitoruj:

- kei.pl
- hekko.pl
- domeny.pl
- superhost.pl

**Comment by xMaap** [comment]
Powłaziłem tak gdzie można powłazić i czysto.

Jedynie to domeny.pl i superhost.pl
![2020-09-13 22 26 47 domeny pl 5e86e7ef1567](https://user-images.githubusercontent.com/36385327/93027872-407c0280-f610-11ea-96f4-92a6a627d9cb.png)
Ale ja bym tego nie ruszał.

**Comment by krystian3w** [comment]
Mnie chodzi, że do 2021 pewnie wszystkie 5 znikną i będą się otwierać z tego "cyber folks".

**Comment by xMaap** [comment]
To jeszcze warto dopisać

- ogicom.pl
- blink.pl
- certyfikatyssl.pl

Tylko oni mogą zrobić przekierowania do hekko albo domeny jak w innych przypadkach.

**Comment by krystian3w** [comment]
hekko już zlikwidowali.
