### ISSUE TITLE
diversesystem.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2512]
![2020-09-17 08 36 18 diversesystem com 627fba1a2a59](https://user-images.githubusercontent.com/36385327/93429105-e6ee2f00-f8c0-11ea-8924-4b9e34996d1e.png)

**Comment by krystian3w** [comment]
U mnie działa:

`diversesystem.com###newsletter-popup-overlay` - pewnie @blocker999  dodał i zapomniał o zgłoszeniu.
