### ISSUE TITLE
topagrar.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2525]
### Typ elementu/problemu
- [x] Scrollujący filmik
- [x] Reklama prenumeraty/e-wydania gazety

Na głównej prenumeraty + w artykułach scrollujący filmik

### 1) Na głównej prenumeraty:

**a**
![capture_005_17-09-2020_17-29-54](https://user-images.githubusercontent.com/63287518/93493007-bc759380-f90b-11ea-8728-795d2ec51804.gif)

**b**
![capture_006_17-09-2020_17-29-57](https://user-images.githubusercontent.com/63287518/93493015-bd0e2a00-f90b-11ea-8d89-09c442457a9a.gif)

### 2) W artykułach scrollujący filmik np. https://www.topagrar.pl/articles/ziemniaki/nadmiar-towaru-obniza-cene-ziemniakow/

![capture_007_17-09-2020_17-33-19](https://user-images.githubusercontent.com/63287518/93493126-dd3de900-f90b-11ea-98e1-348755f0bfad.gif)

**Comment by krystian3w** [comment]
Ten odtwarzacz jest osadzony w sidebar czy jak...?
