### ISSUE TITLE
pneumat.com.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2527]
### Typ elementu/problemu
- [x] Widżet kontaktowy/informacji zwrotnej
- [x] Błąd
- [x] Pytanie

Ten filtr na liście EI: `||secure.livechatinc.com^$third-party` nie ukrywa czatu, jedynie blokuje (nie wysuwa się) a może psuje i to błąd?

![capture_027_17-09-2020_17-49-29](https://user-images.githubusercontent.com/63287518/93495351-52aab900-f90e-11ea-9d4b-7a15e64f261a.gif)

**Comment by krystian3w** [comment]
Pewnie jakaś mutacja, że część  można osadzić w szablonie.
