### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2529]
Po wyłączeniu Polskie Filtry Elementów Irytujących działa

![2020-09-18 21 18 48 www youtube com dbe2d353acb8](https://user-images.githubusercontent.com/36385327/93636694-a7c0fa80-f9f4-11ea-8e37-6ea7fe802b68.png) |
---- |

**Comment by xMaap** [comment]
Również winne jest AdGuard Annoyances.

**Comment by hawkeye116477** [comment]
Ja mam tak tylko przez sekundę, potem jest ok.

**Comment by krystian3w** [comment]
`youtube.com#@#+js(set, ytInitialPlayerResponse.auxiliaryUi.messageRenderers.upsellDialogRenderer.isVisible, false)`

**Comment by krystian3w** [comment]
Za 10 minut się uspokoi ale znów będzie się player zatrzymywać od:

zalogowani mają się lepiej #2471

**Comment by xMaap** [comment]
@krystian3w Nowa niespodzianka od Gugla, ale chyba nie ma się ukryć tylko coś musi klikać.
`https://www.youtube.com/watch?v=LDgOFUbpy6Q
` 
![2020-10-04 09 40 50 www youtube com 7643c6cd4714](https://user-images.githubusercontent.com/36385327/95009932-de6a5800-0625-11eb-93b4-7aa894b71bff.png)

**Comment by krystian3w** [comment]
uBO nie ma klikacza, Pod komunikatem na pewno nie ma playera.

**Comment by hawkeye116477** [comment]
Za to Nano ma, więc może :penguin: coś wykombinuje :smile:.

**Comment by krystian3w** [comment]
Pewnie nie, bo to nie cookies i niby można się logować darmowym kontem.

**Comment by hawkeye116477** [comment]
`bo to nie cookies`

Lista nazywa się Nano Annoyance, a nie Nano Cookies. Spójrz na https://github.com/NanoAdblocker/NanoFilters/blob/master/NanoFiltersSource/NanoAnnoyance.txt, wynika z tego, że zajmuje się też innymi rzeczami, jak np fałszywymi ścianami logowania.
