### ISSUE TITLE
portaloswiatowy.pl

### ISSUE THREAD

**Issue by gargul6** [PolishFiltersTeam/PolishAnnoyanceFilters#2535]
by Barticf https://github.com/MajkiIT/polish-ads-filter/issues/17169#issue-707140122
(PS. nie jestem pewien czy to się kwalifikuje do "Wyskakujące okienka czy do "Powiadomienia typu webpush")

![capture_057_23-09-2020_10-33-21](https://user-images.githubusercontent.com/71756321/93987776-4304f780-fd88-11ea-84ec-dc5120c5c9a3.gif)

**Comment by krystian3w** [comment]
Duże, tło - czyli pop-upy.
