### ISSUE TITLE
pl.kronospan-express.com/pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2540]
### Typ elementu
popup
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox Classic 56.3
**Bloker:** Nano Adblocker 1.0.0.151
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Sprawdź godziny otwarcia sklepów w pobliżu
Znajdź najbliższy otwarty teraz sklep spożywczy

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Ja widzę tylko newsletter,

Godziny otwarcia i namierzanie to może być użyteczny pop-up.
