### ISSUE TITLE
national-geographic.pl

### ISSUE THREAD

**Issue by gargul23** [PolishFiltersTeam/PolishAnnoyanceFilters#2541]
https://www.national-geographic.pl/artykul/pajeczyna-jak-autobus

![capture_064_25-09-2020_09-41-34](https://user-images.githubusercontent.com/71870172/94240287-601a0180-ff13-11ea-8880-bd2ecdead698.png)

**Comment by krystian3w** [comment]
Wideo leci różne, jak masz pomysł to możesz spróbować podesłać w kulturalny sposób.

**Comment by hawkeye116477** [comment]
@krystian3w Do kogo to było? Autor zgłoszenia jest obecnie na urlopie, daj mu odpocząć :smile:

Jeżeli chodzi o filmik, to może można byłoby chociaż zatrzymać jego scrollowanie.
