### ISSUE TITLE
CMC Media (inne repo)

### ISSUE THREAD

**Issue by gargul24** [PolishFiltersTeam/PolishAnnoyanceFilters#2542]
### Typ elementu/problemu
- [x] Pytanie

Czy może ktoś temu [beep] `MajkiIT`, wytłumaczyć, że jego POL filtry PSUJĄ VIDEO na kilkudziesięciu stronach:  [LINK 1](https://github.com/MajkiIT/polish-ads-filter/issues/17140#issuecomment-695017253) + [LINK 2](https://github.com/MajkiIT/polish-ads-filter/issues/17185), ten [beep] chyba nawet się nie zorientował do tej pory, dwa razy zgłaszane, a on nie reaguje i naprawił tylko jedną domenę, zamiast naprawić wszystkie to zamyka i daje bany, a na pytania nie odpowiada, rozumiem, że jest [beep], ale żeby [beep] ludzie mieli popsute video na kilkudziesięciu stronach to nie bardzo jest fajna rzecz. @blocker999 ty niejako byłeś autorem wątku może mu przemówisz do rozsądku żeby naprawił ten błąd z video, bo ja już [beep] nie mam po prostu sił ani cierpliwości.

**Comment by krystian3w** [comment]
MajkiIT nie ma czasu by przejrzeć te 20 stron.
