### ISSUE TITLE
lento.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2549]
### Typ elementu
popup
### Link bezpośredni 
`https://www.lento.pl/elektronika/telefony-i-akcesoria/pre-paid.html` ➡️ 
`https://www.lento.pl/elektronika/telefony-i-akcesoria/pre-paid.html?page=2` (pop-up)
~~`https://www.lento.pl/elektronika/telefony-i-akcesoria/pre-paid.html?order=price:desc&page=2`~~
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox Classic 56.3
**Bloker:** Nano Adblocker 1.0.0.151
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
U mnie go nie widać.

**Comment by hawkeye116477** [comment]
Też tego nie mam.

**Comment by xMaap** [comment]
Czysto.

**Comment by krystian3w** [comment]
Umiem odtworzyć po kliknięciu w:

![obraz](https://user-images.githubusercontent.com/35370833/94607538-54746500-029c-11eb-920f-ff07fe4c8e93.png) |
--- |

Jak dla mnie to może być przydatna funkcja, skoro strona tylko newsletterem umie powiadomić o nowych aukcjach pasujących do frazy lub przeglądanego działu/kategorii.

**Comment by krystian3w** [comment]
Poprawna metoda odtworzenia:

1. czyścimy cookies dla domeny
2. wchodzimy na `https://www.lento.pl/elektronika/telefony-i-akcesoria/pre-paid.html`
3. przewijamy i klikamy w <kbd>2</kbd> "strona".
4. pop-up już atakuje
5. jak wycinamy prostym filtrem, to i sekcje po środku https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2549#issuecomment-700943696
6. jak sekcja zostaje z racji "użyteczności" (brak oznaczenia jako "newsletter" **typu** "nie pop-up"), to trzeba ubić to jakimś filtrem skryptowym, bo ja nie widzę by szło sięgnąć po [`:watch-attr()`](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjectwatch-attrarg) lub wyróżniał się czymś od tego z https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2549#issuecomment-700943696

**Comment by krystian3w** [comment]
Niby ładuje to dół strony:
```html
<html>
    <body>

    <!-- ............................................ -->

    <script>showNotify()</script>
    </body>
</html>
```
