### ISSUE TITLE
aleleki.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2552]
![2020-09-28 07 44 48 www aleleki pl 9728b58df776](https://user-images.githubusercontent.com/36385327/94394854-a2834e80-015e-11eb-9cf9-3715cdaa7fc2.png)

**Comment by krystian3w** [comment]
https://wiadomosci.radiozet.pl/Polska/Wyciek-danych-osobowych-dwoch-sklepow-internetowych-aleleki-pl-oraz-aleeko-pl
