### ISSUE TITLE
auchan.pl/pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2556]
![Screenshot_2020-10-04 Auchan Polska](https://user-images.githubusercontent.com/36385327/95005017-3045ba80-05f3-11eb-9617-a9d0707902ed.png)

**Comment by krystian3w** [comment]
@hawkeye116477  coś  w JS blokuje przewijanie jak w https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1033 / `insert.com.pl`

**Comment by krystian3w** [comment]
```css
www.auchan.pl##.v-overlay:has(~ .v-dialog__content > div > div > button ~ a > picture:only-child)
www.auchan.pl##.v-dialog__content:has(> div > div > button ~ a > picture:only-child)
```

Margaryna i Finish są nieklikalne. I niby najlepiej tylko w uBO wycinać te z linkiem, by nie stać w sprzeczności z polityką AdGuard.
