### ISSUE TITLE
meczyki.pl

### ISSUE THREAD

**Issue by hawkeye116477** [PolishFiltersTeam/PolishAnnoyanceFilters#256]
Potrzebna pomoc @F4z z powiadomieniem push.

**Comment by MajkiIT** [comment]
`https://zaufanatrzeciastrona.pl/post/7-milionow-odwiedzin-zobacz-skale-i-zasieg-kampanii-sms-premium/`

**Comment by hawkeye116477** [comment]
Jasne, można by to zablokować, tylko tu jest sporo coś tego kodu, zablokuję i pewnie coś się posypie.

**Comment by hawkeye116477** [comment]
@MajkiIT Już tak próbowałem i jeżeli to zablokuję, to program TV meczy się zepsuje.
Także tu jest potrzebna reguła script:inject().
