### ISSUE TITLE
stradivarius.com/pl/

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2560]
![Screenshot_2020-10-04 Stradivarius Polska Sezon jesień-zima 2020 Oficjalna strona internetowa](https://user-images.githubusercontent.com/36385327/95005780-82d7a480-05fc-11eb-8b61-2088a77e589d.png)

**Comment by krystian3w** [comment]
Pop-up, bo pewnie ciemny header nie jest normalnie.
