### ISSUE TITLE
infokonin.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2569]
### Typ elementu
popup
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox Classic 56.3
**Bloker:** Nano Adblocker 1.0.0.151
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by gargul03** [comment]
U krystiana3w to ostatnio jakieś zjawiska paranormalne występują, bo biedak co rusz to nie może zreprodukować, najpierw [TAM](https://github.com/AdguardTeam/AdguardFilters/issues/65244#issuecomment-707201075), teraz tutaj:

(zarówno Firefox jak i Opera):
![capture_010_14-10-2020_09-54-23](https://user-images.githubusercontent.com/72387542/95960470-10d53b80-0e04-11eb-8216-e967fba85c59.gif)

**Comment by hawkeye116477** [comment]
U mnie po jakieś chwili się pojawia, ale tylko sama kurtyna.

**Comment by hawkeye116477** [comment]
W zasadzie Waterfox Classic niby też obsługuje html filtering, ale jeżeli jest to umieszczone wewnątrz warunku, to wtedy działa tylko dla FF 57+. 

U mnie to jest i tak apropos znowu EasyList Cookies wycina nie to co trzeba...

**Comment by gargul03** [comment]
Zapomniałem, że korzystam z modułów, i nie korzystam ostatnio z list ciasteczkowych, ale też mam kurtynę po włączeniu `Polskie Filtry RODO-Ciasteczkowe`, być może pojawia się też po włączeniu innych list / rozszerzeń związanych z ciasteczkami. Tak czy inacej popup czy kurtyna coś wyskakuje.

**Comment by hawkeye116477** [comment]
> samą kurtynę po włączeniu Polskie Filtry RODO-Ciasteczkowe

U mnie tak jest jedynie z powodu EasyList Cookie.

--------------------

Tylko teraz pytanie jest, o co im chodzi z tym pop-upem, bo jak się klika to tylko się wyłącza i nic się nie dzieje...

**Comment by gargul03** [comment]
> hawkeye116477 : U mnie tak jest jedynie z powodu EasyList Cookie.

U mnie teraz też już tak jest ciągle, ale raz było tak, że była sama kurtyna, a po wyłączeniu `Polskie Filtry RODO-Ciasteczkowe` i ponownym wejściu na stronę pojawił się popup, może listy się zaktualizowały po ich wyłączeniu / włączeniu i w najnowszych `Polskie Filtry RODO-Ciasteczkowe` się to naprawiło.

**Comment by krystian3w** [comment]
Znaczy czekasz aż np. Gargul04 zgłosi do EasyList i znowu źle wytną.

Oni kilku filtrów za Chiny ludowe nie rozważają usunąć jak chodzi o np. `.spu-box` / `.spu-bg`.

**Comment by krystian3w** [comment]
@hawkeye116477 to taka głupia reklama wewnętrzna nowego logo miasta.

Niby dobrze jakby otwierała jakiś wpis "o co tam chodzi", "by szapman nie wylewał się", bo tak to nie wychodzi "spoko, nie szkodzi".

**Comment by gargul05** [comment]
> krystian3w : Nie mam, już go nie ma

U `krystian3w` jak zwykle jakieś zjawiska paranormalne i nie może biedak  zreprodukować, 
najpierw [TAM](https://github.com/AdguardTeam/AdguardFilters/issues/65244#issuecomment-708404885), a teraz tu :smiley:, a u mnie i hawkeye popup się pojawia:

![capture_010_14-10-2020_09-54-23](https://user-images.githubusercontent.com/72875495/96004262-785aad80-0e3b-11eb-984d-9667c6729ee0.gif)
