### ISSUE TITLE
mtb-xc.pl

### ISSUE THREAD

**Issue by xxcriticxx** [PolishFiltersTeam/PolishAnnoyanceFilters#257]
push push 

![capture](https://user-images.githubusercontent.com/15007183/34364544-ffa85584-ea54-11e7-9cb2-8e980ba6f7f9.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Ale to już jest w Popup Blockerze, jaką masz wersję?
Za to widzę strzałkę do zablokowania -> `mtb-xc.pl##.scroll-up`.
