### ISSUE TITLE
waze.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2612]
https://www.waze.com/pl/livemap

~~Nie można kliknąć~~ - menu nie otwiera się po kilknięciu

![Zrzut ekranu z 2020-11-01 13-20-47](https://user-images.githubusercontent.com/36385327/97802674-5b98e500-1c45-11eb-8d36-0e479dae06b5.png)

**Comment by krystian3w** [comment]
Można kliknąć/pacnąć, animuje się.
