### ISSUE TITLE
stawiszynski.org

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2614]
https://stawiszynski.org
![Przechwytywanie zawartości sieci Web_2-11-2020_8518_stawiszynski org](https://user-images.githubusercontent.com/36385327/97839372-605fa680-1ce2-11eb-9436-0796b1ef5ece.jpeg)

https://stawiszynski.org/krolestwa-wyobrazni/
![Przechwytywanie zawartości sieci Web_2-11-2020_8812_stawiszynski org](https://user-images.githubusercontent.com/36385327/97839505-9b61da00-1ce2-11eb-9ad8-653ad5acdca5.jpeg)

**Comment by krystian3w** [comment]
Ja push/web-push nie widzę, drugi pop-up to bardziej prenumerata / płatna dotacja a nie technologia powiadomień w prawym rogu ekranu o nowym artykule.

https://developer.mozilla.org/en-US/docs/Web/API/Push_API

**Comment by xMaap** [comment]
A jak scrolluj stronę stronę to nie pojawia się?

**Comment by krystian3w** [comment]
Też nie, mówisz że push jest tylko z Chrome?
