### ISSUE TITLE
aptekarzpolski.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2615]
### Typ elementu
popup,prenumerata
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 82
**Bloker:** uBlock Origin 1.30.9b6
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących (niektóre moduły, bez ciasteczek)
### Dodatkowe informacje mogące mieć znaczenie
 - 1) Jeśli chodzi o Prenumeratę to jest repoen mojego wcześniejszego zgłoszenia
- 2) A reopen dlatego bo Prenumerata znowu wyskoczyła bo w poprzednim zgłoszeniu naprawiono ją bezsensownymi losowymi filtrami, którymi nie powinno się niczego naprawiać, bo taki paździerz podziała krótko i nic dziwnego, że po chwili takie filtry przestają działać:
    ```
    aptekarzpolski.pl##.jnews_module_24236_9_5f327291370e0.jeg_alignleft.jeg_block_heading_2.jeg_block_heading
    aptekarzpolski.pl##.jnews_module_24236_10_5eff0ce4694de.jeg_alignleft.jeg_block_heading_2.jeg_block_heading
    aptekarzpolski.pl##.jnews_module_24236_10_5f32729137491.jeg_col_1o3.jeg_pagination_disable.jeg_module_hook.jeg_postblock.jeg_postblock_10
    aptekarzpolski.pl##.jnews_module_24236_11_5eff0ce469931.jeg_col_1o3.jeg_pagination_disable.jeg_module_hook.jeg_postblock.jeg_postblock_10
    ```

(by gargul)

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by blocker999** [comment]
help
