### ISSUE TITLE
elektoralna.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2626]
### Typ elementu
popup
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 82.0.3
**Bloker:** uBlock Origin 1.30.11rc0
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących (niektóre moduły, bez ciasteczek)
### Dodatkowe informacje mogące mieć znaczenie
Nie jestem pewny czy to się kwalifikuje do EI jako popup czy na POL repo jako reklama, zadecydujcie.

(by gargul)

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Myślę, że to już reklama.
