### ISSUE TITLE
autochemia.pl

### ISSUE THREAD

**Issue by Barticf** [PolishFiltersTeam/PolishAnnoyanceFilters#2628]
### Moja konfiguracja 

**Przeglądarka internetowa:** 
Firefox
**Rozszerzenia i skrypty:** 
uBlock, Nano Defender, Polska Ciasteczkowa Zgoda
**Listy filtrów:** 
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda 
3. AdGuard Annoyances
4. EasyList Cookie 
5. Fuck Fuckadblock
6. I don't care about cookies
7. Polskie Filtry Elementów Irytujących
8. Polskie Filtry Społecznościowe 
9. EasyPrivacy
10. Fanboy’s Enhanced Tracking List

### Link bezpośredni (opcjonalny) 

https://autochemia.pl/

### Zrzut ekranu (opcjonalny) 

![obraz](https://user-images.githubusercontent.com/32641928/99669440-5c1be300-2a6f-11eb-99b7-d175a49cd7d8.png)

**Comment by krystian3w** [comment]
Takie wielkie i wyśrodkowane to już pop-up.

**Comment by krystian3w** [comment]
Jutro po 15 zrób aktualizację listy i powinno zniknąć aż nie przebudują.
