### ISSUE TITLE
promocja filtrów

### ISSUE THREAD

**Issue by MajkiIT** [PolishFiltersTeam/PolishAnnoyanceFilters#263]
Chcecie promować swoje dzieło ?

**Comment by blocker999** [comment]
@MajkiIT oczywiście, tylko gdzie?

**Comment by KonoromiHimaries** [comment]
no ba, byle za darmo : p

**Comment by MajkiIT** [comment]
no najlepiej w google. Zaraz coś zbuduje.

**Comment by KonoromiHimaries** [comment]
najlepiej to napisać do ublock i adguarda.
https://github.com/AdguardTeam/AdguardFilters/issues
https://github.com/uBlockOrigin/uAssets/issues

**Comment by blocker999** [comment]
Ja jestem za ale w gre wchodzi tylko darmowe promowanie no chyba że coś skutecznego i taniego to może zaiwestuje pare groszy.

No ale co na to @hawkeye116477 ?

**Comment by MajkiIT** [comment]
@blocker999 mogę napisać u siebie artykuł i go wypozycjonować. Średnio dziennie wchodzi na stronę ok 400 osób. Dodatkowo wrzuce info na FB.

**Comment by blocker999** [comment]
@MajkiIT OK, na początek dobre i to.

@KonoromiHimaries Podsunął mi myśl, jakby dogadać się z gorhilem aby dodał tą paczke do ublocka albo pingwin do nano adblockera, co wy nato ?

**Comment by MajkiIT** [comment]
@blocker999 to zaraz coś napiszę. Warto spróbować.

**Comment by KonoromiHimaries** [comment]
zamiast listy uzupełniającej w ublocku, zamiast listy protektora w adguardzie powinni dodać.

**Comment by MajkiIT** [comment]
@blocker999 macie swoje jakieś logo lub grafikę?

**Comment by hawkeye116477** [comment]
@blocker999 Gorhill już chyba pisał, że nie doda, ale ekipa AdGuarda powiedziała, że dodadzą naszą paczkę, ale trochę później. A pingwin na początku dodał naszą paczkę, ale trochę to kiepsko wyszło, bo była domyślnie zaznaczona, więc napisałem do niego, to on usunął i powiedział, że doda znowu jak już wprowadzi jakąś tam zmianę, by nasza paczka była na liście, ale nie była domyślnie zaznaczona. A teraz zdaje się, że znowu ma nieco inne plany, ma zrobić jakiś sklep, w którym będą dostępne różne filtry.

**Comment by blocker999** [comment]
@hawkeye116477 Ok z adguardem i nano adblokiem narazie odpuśćmy, natomiast co do rozmowy teraz se przypominam że w skrócie mówił że dwie na kraj, ale jakby zamiast uzupełnienia dać naszą paczle bo i tak będzie ona zbędna no ale co nato @MajkiIT ?

**Comment by hawkeye116477** [comment]
@blocker999 Ale to wtedy gorhill tak jak i pingwin musiałby to jakoś ogarnąć, by nasza paczka nie była domyślnie zaznaczona, bo w końcu nie wszyscy chcą blokować takie elementy :smile:.

**Comment by KonoromiHimaries** [comment]
@hawkeye116477 to serio nie jest problem. wystarczy zmienić nazwę, np. z `POL-1` na `POL-01`

**Comment by hawkeye116477** [comment]
@KonoromiHimaries To nic nie zmieni raczej, nadal będzie domyślna dla Polaków, może dla starych niekoniecznie, ale dla nowych użytkowników będzie.

**Comment by KonoromiHimaries** [comment]
@hawkeye116477 no jak? przecież była by domyślnie wyłączona.
```
	},
	"POL-PPB": {
		"content": "filters",
		"group": "regions",
		"off": true,
		"title": "POL: Polskie filtry elementów irytujących",
		"lang": "pl",
		"contentURL": "https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB.txt",
		"supportURL": "https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues"
```

**Comment by blocker999** [comment]
@hawkeye116477 Pogadał byś z Gorhilem ? 

A co myślisz o najpopularniejszych adblock i adblock plus ?

**Comment by hawkeye116477** [comment]
@KonoromiHimaries Zauważ, że w innych polskich filtrach też jest off na true, a są i tak domyślnie włączone.
@blocker999 ABP to pewnie nie doda, oni nawet Oficjalnych polskich nie dodali, a ten AdBlock to nie wiem czy by chcieli czy nie. Jedynie Nano AdBlocker i AdGuard są najpewniejsi, szkoda tylko, że raczej mało użytkowników z nich korzysta.
Z gorhillem już była rozmowa, @KonoromiHimaries z nim gadał -> https://github.com/gorhill/uBlock/issues/3332. Ale to tak jak mówię, on by musiał coś wykombinować, by filtry były na liście, ale jako wyłączone.

**Comment by blocker999** [comment]
@hawkeye116477 Mi narazie info od @MajkiIT starczy, póżniej się zobaczy a jak chcesz to drąż temat u gorhila bo warto wkońcu to zaraz po adblockach najpopularniejsza wtyczka w Polsce .

**Comment by MajkiIT** [comment]
https://www.certyficate.it/polskie-filtry-elementow-irytujacych-do-adblocka/

**Comment by blocker999** [comment]
@MajkiIT Dzięki

**Comment by MajkiIT** [comment]
FYI
https://www.wykop.pl/link/4086503/polskie-filtry-elementow-irytujacych-do-adblocka/

**Comment by blocker999** [comment]
@MajkiIT Szczęśliwego nowego roku

**Comment by MajkiIT** [comment]
@blocker999 Dziękuje i Wam wszystkim również ...
