### ISSUE TITLE
papilot.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/PolishAnnoyanceFilters#264]
![2017-12-31 17_20_46-ludmila z saratowa - rosyjska kim kardashian - papilot pl](https://user-images.githubusercontent.com/5884000/34462963-1b8d5fc6-ee4f-11e7-9ad0-738468ce85c9.png)
`https://www.papilot.pl/ludzie/ludmila-z-saratowa-rosyjska-kim-kardashian,41535,1`

popup

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.22
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by hawkeye116477** [comment]
`papilot.pl###keys-info-bg`
