### ISSUE TITLE
play.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2641]
https://www.play.pl/pomoc/salony-play.html
![Zrzut ekranu z 2020-11-24 18-13-35](https://user-images.githubusercontent.com/36385327/100129048-506e5900-2e81-11eb-9918-1911db0b7b13.png)

**Comment by krystian3w** [comment]
Jak dla mnie informacyjny.

**Comment by blocker999** [comment]
jak dlamnie też informacyjny

**Comment by krystian3w** [comment]
W sumie widzę wadę, raz zamknięty wraca co odświeżenie, wtedy to jednak jest uporczywa informacja.

**Comment by blocker999** [comment]
niewiem @ hawkeye116477 niech zadecyduje

**Comment by xMaap** [comment]
@krystian3w jakiś element nie jest zablokowany.

![2020-11-27 04 43 03 www play pl bef2829758c9](https://user-images.githubusercontent.com/36385327/100408362-195b9b80-306b-11eb-8aab-5b7b134ad241.png)
