### ISSUE TITLE
kancelaria.info

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2680]
### Typ elementu
popup
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox Classic 56.3
**Bloker:** uBlock Origin 1.32.4
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
BEZPŁATNA ANALIZA UMOWY KREDYTOWEJ (KREDYTY FRANKOWE)

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Pop-up zniknął / nie ma go w Firefox Quantum / kod pop-upa ma błędy i atakuje z dużym niepowodzeniem.

**Comment by blocker999** [comment]
sorry mój błąd : https://kancelaria.info/
