### ISSUE TITLE
poboczem.pl

### ISSUE THREAD

**Issue by AroKol78** [PolishFiltersTeam/PolishAnnoyanceFilters#2682]
https://www.poboczem.pl/filmiki/video,vId,3005605,vSort,1,vTime,3
[myList](https://user-images.githubusercontent.com/70756447/102889523-1a5dce00-445b-11eb-9dfa-8919f5ae110c.PNG) +"Polskie Filtry Elementów Irytujących - Scrollujące Filmiki"

**Comment by krystian3w** [comment]
`vjs-fixedmonitor-wrapper-fixed` mi się z czymś kojarzy.

przy okazji fajny bug z zamykaniem wątków frazą `vjs-fixedmonitor-wrapper-fixed`

**Comment by AroKol78** [comment]
ok - scroll off
(za dużo grali :laughing: w NFS)
