### ISSUE TITLE
topagrar.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2700]
https://www.topagrar.pl/articles/afrykanski-pomor-swin-asf/bedzie-szczepionka-przeciwko-asf-w-pulawach-trwaja-prace-kosztowaly-juz-ponad-730-tys-zl/ |
--- |
![Zrzut ekranu z 2021-02-14 08-55-35](https://user-images.githubusercontent.com/36385327/107871490-6ac53b00-6ea2-11eb-9873-14384586e6cc.png) |

**Comment by krystian3w** [comment]
Widzę problem, że player trzeba CSS-em przenieść lub JS-em zablokować skakanie do prawego rogu.

**Comment by krystian3w** [comment]
U mnie działa tylko:

`topagrar.pl##+js(aeld, scroll, [native code])`

A CSS odpada, bo strona przenosi element w drzewie DOM...
