### ISSUE TITLE
polskacanada.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/PolishAnnoyanceFilters#271]
![2018-01-02 10_26_25-polska canada _ magazyn tworczy](https://user-images.githubusercontent.com/5884000/34479478-77fe5518-efa7-11e7-8925-d751e30fc41d.png)

widget

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by krystian3w** [comment]
dalej wyskakuje zaproszenie?
