### ISSUE TITLE
skandynawiainfo.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2729]
https://skandynawiainfo.pl/szwecja-rezygnuje-z-paliw-kopalnych-sily-zbrojne-protestuja/

![Zrzut ekranu z 2021-03-04 06-47-35](https://user-images.githubusercontent.com/36385327/109917434-a428e380-7cb5-11eb-9489-3d2953a78d23.png)

**Comment by krystian3w** [comment]
@xMaap daj znać jak strona będzie znów online:

https://dns.pl/przegladarka?domainName=skandynawiainfo.pl
https://dns.pl/whois?domainName=skandynawiainfo.pl
