### ISSUE TITLE
galeriabronowice.pl

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishAnnoyanceFilters#273]
Scroll blokuje główną

**Comment by hawkeye116477** [comment]
Tak w zasadzie z tego co ja tu widzę, to to jest popup społecznościowy i pewnie to powinno zostać przeniesione do Polskich filtrów elementów irytujących, ale z uwagi na to, że jest blokada scrolla i gorhill nie dodał #include jeszcze do wydania stabilnego, to dodam to na razie do uzupełnienia  Polskich filtrów elementów irytujących.
