### ISSUE TITLE
ms.gov.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/PolishAnnoyanceFilters#274]
![2018-01-05 18_58_04-ministerstwo sprawiedliwosci](https://user-images.githubusercontent.com/5884000/34621681-60d4ce6c-f24a-11e7-884a-556c486b56d6.png)

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.23
Nano Defender 13.16
Chrome 63.0.3239.108

**Comment by hawkeye116477** [comment]
Problem zdaje się powoduje reguła `pl###scroll-top`. Są dwa wyjścia z sytuacji można tą regułę zamienić na `pl#?#.scroll-top:-abp-has(> .fa)`, wtedy zapewne nie będzie sprawiać problemów, bo FA to firma Font Awesome i zwykle od nich biorą te strzałki, ale to wg. ABP spowoduje spowolnienie blokowania, więc po prostu damy na to wyjątek. A jeśli zdarzy się więcej takich przypadków, to wtedy najwyżej zamienimy to na regułę z `:abp-has()`.
