### ISSUE TITLE
czesci.wanicki.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2748]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox Classic 56.5
**Bloker:** uBlock Origin 1.33.2
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Już nie mają lub atakują w tygodniu.

**Comment by blocker999** [comment]
A ja mam:

![agro](https://user-images.githubusercontent.com/23176832/111130632-b9382900-8577-11eb-8368-01c2e708a194.jpg)

**Comment by krystian3w** [comment]
A to pewnie ten filtr ukryje:

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/c84485a1b84b7dbe6c39501c7ad5311d9ee1a08e/PPB/popupy.txt#L883
