### ISSUE TITLE
wrp.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2749]
### Link bezpośredni 
`https://www.wrp.pl/ochrona-zapachow-i-halasow-wsi-pir-rolnicy-sa-szykanowani-z-powodu-normalnej-pracy-rolniczej/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox Classic 56.5
**Bloker:** uBlock Origin 1.33.2
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
scrollująca okładka gazety

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Jakiś problem z dostępem do domeny, może spalili się na OVH...
