### ISSUE TITLE
unitrailer.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2757]
### Link bezpośredni 
`https://unitrailer.pl/pol_m_Czesci-do-maszyn-rolniczych-2318.html`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox Classic 56.5
**Bloker:** uBlock Origin 1.33.2
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Nie widzę tytułów powrotowych.

**Comment by blocker999** [comment]
Chodziło o popup :: 

![ut](https://user-images.githubusercontent.com/23176832/111129997-04057100-8577-11eb-91e8-f0c443820416.jpg)

**Comment by krystian3w** [comment]
To ten ukryje pewnie filtr `###dzinga`, ubocznie on chowa też widget z prawego rogu.

> https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/c84485a1b84b7dbe6c39501c7ad5311d9ee1a08e/PPB/popupy.txt#L215

Nie mam pomysłu jak zrobić by moduł pop-upów nie ukrywał tego bocznego telefoniku, bo taki pewnie będzie lekko zamulał:

`dreamtours.pl,dzinga.com,topfish.pl,unitrailer.pl,vitamoc.pl#?##dzinga:-abp-has(.widget[class*="hide])`

---

@hawkeye116477 ty wymyślałeś filtry sieciowe:

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/c84485a1b84b7dbe6c39501c7ad5311d9ee1a08e/PPB/widgety_kontaktowe_informacji_zwrotnej.txt#L604 https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/c84485a1b84b7dbe6c39501c7ad5311d9ee1a08e/PPB/popupy.txt#L847

Niby w ciągu poprzedniego tygodnia zlikwidowali domenę `accounts.dzinga.com` i przydałoby się oba przetestować i uaktualnić.
