### ISSUE TITLE
rasowear.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2764]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 86.0.1
**Bloker:** uBlock Origin 1.34.1b2
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących (niektóre moduły)

by gargul
### Dodatkowe informacje mogące mieć znaczenie
- przy okazji nie wiem czy to się kwalifikuje też: https://github.com/MajkiIT/polish-ads-filter/issues/19170

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Bon raczej zostaje, na głównej nie widać czy obsłużą i czy są kruczki by można było nie obsługiwać.

Jak znajdziesz news, że każdy "hotel" musi przyjąć bon turystyczny, to wtedy pop-up można chować.
