### ISSUE TITLE
historia.azv.pl + twojniemiecki.pl + twojfrancuski.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2769]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 86.0.1
**Bloker:** uBlock Origin 1.34.1b2
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących (niektóre moduły)

by gargul
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Pop-up zniknie jutro około `11:18` dla modułów jak nic się nie wywali.
