### ISSUE TITLE
elementstore.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2770]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox Classic 56.5
**Bloker:** uBlock Origin 1.33.2
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

```
Poczekaj chwileczkę!

icon

Zdobądź od nas
10 zł RABATU
NA PIERWSZY ZAKUP

Wpisz swój adres e-mail, a my wyślemy Ci kod, który wpiszesz w koszyku, po czym otrzymasz od nas drobny upominek :)

```

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
#1324  - trzeba podobną metodą unieszkodliwić.

**Comment by krystian3w** [comment]
```css
elementstore.pl##+js(aopw, document.title)
elementstore.pl###cboxOverlay[style*="opacity: 0.75"], #cboxOverlay[style*="opacity: 0.75"] ~ #colorbox
```

* Wada pierwszego to pewnie ubicie wszystkich zmian tytułu (łącznie z numerowaniem, że mamy np. 2 powiadomienia).
* Drugi przy szybkim otwarciu galerii obrazków "zamyka" ją, po przez podmianę przezroczystości tła z 0,9 na 0,75 (ludzie się mogą dziwić). Dodatkowo strona ma jeszcze pop-up witający, więc pewnie od około 5 odświeżenia galeria zacznie działać lepiej, bez dziwnego zamykania zdjęć.
