### ISSUE TITLE
voxfm.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2776]
To samo co tutaj #2667
![Zrzut ekranu z 2021-03-25 11-31-42](https://user-images.githubusercontent.com/36385327/112459045-b0a4d700-8d5d-11eb-8c92-5a6f90480c70.png)

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/issues/2667#issuecomment-1188256603 - tu proszę wklejać zgłoszenia błędów z filtrem.
