### ISSUE TITLE
mieszkanie.mitula.com.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2782]
### Link bezpośredni 
`https://mieszkanie.mitula.com.pl/dom-warszawa/2`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox Classic 56.5
**Bloker:** uBlock Origin 1.33.2
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
mały w boku to inny element, ze  względu na pozycje, rozmiar i brak tła.

**Comment by blocker999** [comment]
![mitula](https://user-images.githubusercontent.com/23176832/112981554-a9b20600-915b-11eb-9c5e-4c75f5d03138.png)

**Comment by krystian3w** [comment]
No to trzeba pisać by wchodzić w spis dla warszawy i u dołu wybierać listę 2.

**Comment by krystian3w** [comment]
Lewa wersja pop-upa wymaga analizy tałatajstwa w JavaScript (nie widzę zastosowania ExtendedCSS np. `:watch-attr`).

Drugi mi się nie ukazał, wtedy można by po nazwie nagłówka użyć `popup:-abp-has(h3:-abp-contains(Podobne))`
