### ISSUE TITLE
agroalex.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2785]
### Link bezpośredni 
`https://www.agroalex.pl/uklad-chlodzenia-c385/chlodnica-ursus-c-385-miedziana-st--typ-80-013-904.html`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox Classic 56.5
**Bloker:** uBlock Origin 1.33.2
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
2x ( pop - up ) :

na głównej - hej zaczekaj !

na : https://www.agroalex.pl/uklad-chlodzenia-c385/chlodnica-ursus-c-385-miedziana-st--typ-80-013-904.html   -   rabaty ...

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Oba używają wtyczki firmy `x13` pod PrestaShop.
