### ISSUE TITLE
wielen.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2786]
### Link bezpośredni 
`https://wielen.pl/aktualnosci/50987d2d1705da0d5e4de912851cd862.html`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox Classic 56.5
**Bloker:** uBlock Origin 1.33.2
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Widzę tylko widget w rogu i ten informuje, że blokuje push.

**Comment by blocker999** [comment]
Też teraz tego niemam ale jest widzet na dole ( dzwonek )

**Comment by krystian3w** [comment]
Duży wyśrodkowany push to już pop-up.
