### ISSUE TITLE
fotoblogia.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/PolishAnnoyanceFilters#279]
![2018-01-08 19_04_43-fotoblogia pl - informacje komentarze opinie](https://user-images.githubusercontent.com/5884000/34684877-e0fe6a40-f4a6-11e7-9319-b0a4113a8294.png)

popup

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.26
Nano Defender 13.17
Chrome 63.0.3239.132

**Comment by blocker999** [comment]
@KonoromiHimaries zaktualizuj filtry i sprawdź czy dalej to masz
