### ISSUE TITLE
Licencja - prośba

### ISSUE THREAD

**Issue by ClusterByte-x** [PolishFiltersTeam/PolishAnnoyanceFilters#2794]
Podobnie jak zgłoszenie w Polish Privacy Filters (https://github.com/olegwukr/polish-privacy-filters/issues/131), można byłoby zmienić na licencję, która zezwala na użycie komercyjne listy? Obecna licencja uniemożliwia zastosowanie w płatnych blokerach typu Wipr. 
> ! License: CC BY-NC-SA 4.0 (https://creativecommons.org/licenses/by-nc-sa/4.0/deed)
> ! Copyright © 2021 Polish Filters Team

@krystian3w @hawkeye116477 @MajkiIT

**Comment by krystian3w** [comment]
A to nie działa tak, że dopóki to nie jest domyślna subskrypcja, to nie zarabiają?

Niby AdGuard jest złym źródłem jak listę PPB tam dodano gdy nie posiadała "licencji" i każdy ich "prawnik" to przeoczył w PR.

**Comment by hawkeye116477** [comment]
Tyle, że my includujemy listę Ciasteczkową, a Majkel ustalił licencję `CC BY-NC-SA 4.0`, tak więc musimy stosować taką samą.

**Comment by krystian3w** [comment]
W sumie jak Oleg nie ma prawa pisać w języku ludzkim (nawet cyrylicą), to trzeba by otworzyć dyskusje w repo MajkiIT.

**Comment by MajkiIT** [comment]
@ClusterByte-x a jesteś pewny, że tak jest, że to blokuje ?

**Comment by MajkiIT** [comment]
Można dać WIPR zgodę na użytkowanie

**Comment by ClusterByte-x** [comment]
@MajkiIT - zarządzasz także poniższymi listami? Napiszę do autora w takim razie maila z propozycją dodania tych list ponownie i podam link do tego zgłoszenia tutaj.
> `Polish Anti Adblock Filters` - [link](https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/anti-adblock.txt)
> `Polish Privacy Filters` - [link](https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/adblock.txt)

**Comment by MajkiIT** [comment]
Wspomagam ... ale kopnę w kostkę właściciela.

**Comment by ClusterByte-x** [comment]
@MajkiIT - wracam ponownie z odpowiedzią. Dobrze byłoby jakbyś napisał wyraźną zgodę na pozwolenie użycia Twoich list, a także zgoda autora `Polish Anti Adblock Filters` i `Polish Privacy Filters` w tym wątku (jeśli to możliwe). Dzięki wielkie!

**Comment by krystian3w** [comment]
Zezwolenie powinno zostać dodane do `.template` czy na maila im wysłać i niech wstawią do swojej złotej gabloty?

**Comment by ClusterByte-x** [comment]
@krystian3w  - chyba najlepszym wariantem będzie wstawić pod licencją w szablonie. 
https://giorgiocalderolla.com/wipr.html - jakby były potrzebne jakieś dane.

**Comment by MajkiIT** [comment]
Co do "Polish Anti Adblock Filters i Polish Privacy Filters" nie wyraził Oleg zgody.

**Comment by krystian3w** [comment]
A można wiedzieć co to za `premission`?

**Comment by ClusterByte-x** [comment]
@MajkiIT  - dziękuję za informację. 

@krystian3w - trzeba byłoby spytać dokładnie autora Wipr. Nie mam na ten temat wiedzy, ale wiem, że lista `Official Polish Filters for AdBlock, uBlock Origin & AdGuard` była dostępna od jakiegoś czasu.

**Comment by krystian3w** [comment]
Dodatkowo raczej nie mamy macOS do reprodukcji uszkodzeń.

**Comment by MajkiIT** [comment]
@krystian3w ale chyba @xxcriticxx ma MacOS

**Comment by krystian3w** [comment]
Wątpię by priorytetowo umiał reprodukować uszkodzenia i namierzać jaki filtr działa błędnie.

**Comment by xxcriticxx** [comment]
@MajkiIT posiadam ale na macu jade na ublock origin

@ClusterByte-x co jest takiego magicznego w tych wycieraczkach?

**Comment by krystian3w** [comment]
Najpewniej ma licencje wieczystą taniej niż AdGuard gdy musimy używać **Safari**:

https://adguard.com/en/license.html

Personal<br>up to any 3 devices<br><br><br>295.83 Zł<br>+VAT, one time fee | Family<br>up to any 9 devices<br><br>~~887.5 Zł~~<br>637.22 Zł<br>+VAT, one time fee 
-- | --

Bo raczej nie każdy chce płacić 10 lub 21 zł rocznie (a mnie licencja niby z ceną skakała aż do 65 zł za rok). A AdGuardowy darmowy dodatek do Safari niby ciągle ma bugi z np. `generichide` i na onet umie walić anty-adblockiem.

**Comment by krystian3w** [comment]
> Natomiast wadą lub zaletą zależnie od spojrzenia Wipra jest brak konfiguracji

Pewnie nagle ludzie zaczną narzekać, że znikają im polskie newslettery, czaty kontaktowe a średnią radą wtedy będzie "usuń Wipr".

**Comment by ClusterByte-x** [comment]
@krystian3w - dlatego lepiej jak doda się same `Polish GDPR-Cookies Filters` do Wipr, bo one nie są takie agresywne dla przeciętnego Internauty.

**Comment by krystian3w** [comment]
Może będzie zainteresowany modułem na pop-upy?

https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PAF_pop-ups.txt

lub jakimś innym:

https://polishannoyancefilters.netlify.app/modules

**Comment by hawkeye116477** [comment]
A, czyli rozumiem, że nie można zrobić jak w innych adblockerach, czyli dodał by jako opcjonalne i ktoś by sobie zaptaszkwoał jak by chciał.

**Comment by ClusterByte-x** [comment]
@hawkeye116477 @krystian3w @MajkiIT - dodany zostanie zatem filtr ciasteczkowy i moduł wyskakujących okienek (najmniej inwazyjne dla zwykłych użytkowników). Brakuje tylko wyraźnej zgody w szablonie, chyba że wydaliście ją już autorowi na maila? Jeśli zaś chodzi o problemy, które mogłyby stworzyć te listy to będą także w AdGuardzie, bo korzystają z `Content Blocker` Apple. Na razie w AdGuardzie na Safari nie powodują żadnych problemów z tymi listami, więc i tu się ich nie spodziewam. W razie czego napewno dam znać!

**Comment by hawkeye116477** [comment]
A propos, ponoć szykują forka Safari z obsługą rozszerzeń FF i Chrome => https://github.com/el1t/uBlock-Safari/issues/158#issuecomment-809847462.
