### ISSUE TITLE
autocentrum.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2799]
### Link bezpośredni 
`https://www.autocentrum.pl/filmy/wideotesty/kia-stonic-imt-z-elektromechanicznym-sprzeglem/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 90.0.4430.72
**Bloker:** AdGuard 3.5.34
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/z1oOwOx.png)

Zgłoszenie opublikowane przez użytkownika **fxs**.

**Comment by strict-block** [comment]
@krystian3w
