### ISSUE TITLE
wykop.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2802]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 87
**Bloker:** uBlock Origin 1.34.0
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Dzieje się tak na stronie głownej Wykopu z filmami YouTube i tylko w Firefox.

![](https://i.imgur.com/wzjuzBO.png)

Zgłoszenie opublikowane przez użytkownika **ofz**.

**Comment by krystian3w** [comment]
To nie błąd, ludzie niby chcą blokowania autoodtwarzania:

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/wiki/Jak-zablokowa%C4%87-autoodtwarzanie-filmik%C3%B3w%3F

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/4d093a417b98855fadd12401bf6654cd328d225c/PPB/uBO_AG/scroll_film_suplement.txt#L26
