### ISSUE TITLE
komputerswiat.pl | auto-swiat.pl | forbes.pl | przegladsportowy.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2812]
https://www.komputerswiat.pl/artykuly/redakcyjne/polscy-matematycy-rozwiklali-majaca-kilkadziesiat-lat-tajemnice-kluczowym-momentem/8npm16d
![Zrzut ekranu z 2021-04-24 01-58-33](https://user-images.githubusercontent.com/36385327/115940091-9a934f00-a4a0-11eb-90a7-12887e740c14.png)

**Comment by krystian3w** [comment]
Nie umiem reprodukować.

**Comment by xMaap** [comment]
Po jakimś czasie wyskakuje.
Tutaj też
https://www.auto-swiat.pl/testy/testy-nowych-samochodow/peugeot-508-pse-co-potrafi-najmocniejszy-seryjny-peugeot-w-historii-test/0bhgdj3
![Zrzut ekranu z 2021-04-24 17-59-51](https://user-images.githubusercontent.com/36385327/115964907-e12b8c80-a526-11eb-94fb-d75abf729947.png)
https://www.forbes.pl/technologie/deepfake-jak-technologia-zmienia-swiat-internet-i-jakie-zagrozenia-powoduje/049fyrd
![Zrzut ekranu z 2021-04-24 18-00-35](https://user-images.githubusercontent.com/36385327/115964916-fb656a80-a526-11eb-978a-a808cbd8f748.png)

**Comment by krystian3w** [comment]
Dalej głucho i ślad o pop-upie ginie.

**Comment by xMaap** [comment]
https://www.przegladsportowy.pl/siatkowka/siatkowka-gdzie-beda-grali-reprezentanci-polski/fctnd5w?tpcc=mediaklub_GLOWNA
![Zrzut ekranu z 2021-04-25 04-04-07](https://user-images.githubusercontent.com/36385327/115977790-72c4e980-a57b-11eb-91fb-5188480c50d8.png)

**Comment by krystian3w** [comment]
Znika przewijanie (?) i czy `###tp-modal` to tylko pop-up (czy czarne tło ma własne ID jako element "obok").

**Comment by krystian3w** [comment]
@AdamWr czy dalej musimy stosować tricki na podbijanie specyficzności CSS w aplikacji dla Windows?

```css
www.przegladsportowy.pl##.tp-modal
www.przegladsportowy.pl##.tp-backdrop
www.przegladsportowy.pl##html > .tp-modal-open:style(overflow: auto !important;)
```

Bo w aplikacjach mogę poomijać `html >`

---

Jako ciekawostkę podaje to:

```
||tinypass.com^$3p,frame,important,redirect=click2load.html
*##iframe[src*="tinypass.com"][style*="height: 0"]:style(height: revert !important;)
##iframe[src*="tinypass.com"][style*="height: 0"]:style(height: revert !important;)
```

też pop-up znika.

**Comment by AdamWr** [comment]
> czy dalej musimy stosować tricki na podbijanie specyficzności CSS w aplikacji dla Windows?

Tak, w przypadku gdy styl ma atrybut `!important` wtedy konieczne jest dodanie takiej reguły żeby miała wyższy priorytet.
Na przykład `body.tp-modal-open` też powinno działać.

**Comment by krystian3w** [comment]
a jak długo będzie działać `:not(#fejk-ajdi)` (110) niby podbija mocniej od `html >` i `.body` (020).

**Comment by AdamWr** [comment]
Pewnie tak długo aż coś innego będzie miało wyższy priorytet. Na przykład styl liniowy z atrybutem `!important` powinien mieć wyższy priorytet.

**Comment by krystian3w** [comment]
OK. Wtedy  to już tylko `remove-attr` (brak innego cennego ostylowania) lub `#$?#`  (cenne ostylowanie atrybutowe).
