### ISSUE TITLE
sport.interia.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2821]
### Link bezpośredni 
`https://sport.interia.pl/raporty/raport-me-euro-2020/aktualnosci/video,vId,3094916`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox Classic 56.5
**Bloker:** uBlock Origin 1.33.2
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane przez użytkownika **blocker**.

**Comment by krystian3w** [comment]
Zaktualizować uBo do 1.35.2?

**Comment by hawkeye116477** [comment]
W Classic niby nie można zaktualizować. Trzeba odinstalować starą i zainstalować nową, bo uBO niby teraz jest dla FF 57, a Classic bazuje na 56, choć ma zmiany też z nowszych.
