### ISSUE TITLE
medianarodowe.com

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2824]
https://medianarodowe.com/2021/06/28/donald-trump-ma-dosc-big-tech-byly-prezydent-dolacza-do-alternatywy-dla-youtube/
![Zrzut ekranu z 2021-06-28 19-57-03](https://user-images.githubusercontent.com/36385327/123682271-17e59200-d84b-11eb-8791-eb1dad48347a.png)

**Comment by krystian3w** [comment]
@hawkeye116477 / @blocker999 Google news do social media czy w "inny element"?

**Comment by hawkeye116477** [comment]
To raczej chyba bardziej pasuje do PASS.

**Comment by krystian3w** [comment]
W sumie można to uznać za kontynuację RSS w nowej formie.
