### ISSUE TITLE
slaskczyta.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2826]
https://www.slaskczyta.pl/wyciszony-dziennikarz-z-niewygodnymi-pytaniami-czy-tak-powinna-wygladac-konferencja-prasowa-w-panstwie-prawa/
![Zrzut ekranu z 2021-07-04 00-59-55](https://user-images.githubusercontent.com/36385327/124368635-2a086b80-dc63-11eb-8e3d-eb19ca691786.png)

**Comment by krystian3w** [comment]
kolejny raz przegapiasz strzałkę w górę
