### ISSUE TITLE
kuchniatruckera.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2828]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox Classic 56.5
**Bloker:** uBlock Origin  1.36.2
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
Niewiem czy to bląd czy wolny internet, poprostu blokuje mi to wejście na strone, bo te " kóko " się laduje, laduje i końca niema, proszę by to sprawdzic i najlepiej usunąc.

Zgłoszenie opublikowane przez użytkownika **blocker**.

**Comment by hawkeye116477** [comment]
Raczej problem z Internetem.

**Comment by krystian3w** [comment]
Jak nie znika do sekundy to jakość połączenia (testowane na mobilnym 5G nie ze szczepionki).

**Comment by hawkeye116477** [comment]
Są problemy w Orange i Netii.

https://downdetector.pl/status/orange/
https://downdetector.pl/status/netia/

Polecam sprawdzić prędkość => http://speedtest.net/.

**Comment by krystian3w** [comment]
Chodziło mi że bazowy punkt stoi raczej na maszczie lub wieżowcu (raczej jeszcze nie mątują na każdej państwowej lampie ulicznej).
