### ISSUE TITLE
komputerswiat.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2832]
```
komputerswiat.pl
newsweek.pl
forbes.pl
auto-swiat.pl
```
![Zrzut ekranu z 2021-07-23 18-39-00](https://user-images.githubusercontent.com/36385327/126814035-6bcdfcf3-4b3a-4f5b-b569-2b388d1a4463.png)

**Comment by krystian3w** [comment]
y...
