### ISSUE TITLE
wiener.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2833]
https://www.compensa.pl/
https://www.wiener.pl/
![Zrzut ekranu z 2021-07-28 20-24-29](https://user-images.githubusercontent.com/36385327/127375928-4025988f-698d-4680-9d54-7fdedb16b74d.png)

**Comment by krystian3w** [comment]
Compensa ma ten pop-up w poddziałach przy pierwszej wizycie?

**Comment by xMaap** [comment]
Tak, ale już jest chyba tak jak powinno być.
