### ISSUE TITLE
sportowefakty.wp.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#2855]
### Link bezpośredni 
`https://sportowefakty.wp.pl/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 93.0.4577.63
**Bloker:** AdGuard 3.6.12
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
![](https://i.imgur.com/81Uxxsy.jpg)

Zgłoszenie opublikowane przez użytkownika **gzv**.

**Comment by krystian3w** [comment]
Dziwne.

**Comment by krystian3w** [comment]
```css
sportowefakty.wp.pl###randomplayer[class*="fixed"], #randomplayer[class*="fixed"] *:style(visibility: hidden !important;)
````
z racji oportunizmu jw-player trzeba ukrywać każdy element wewnątrz, inaczej umie wyciekać tło lub buttony na sekundę.
