### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#2856]
https://www.filmweb.pl/video/Zwiastun/Wcielenie+Zwiastun+nr+2-58707
![Zrzut ekranu z 2021-09-03 23-19-32](https://user-images.githubusercontent.com/36385327/132066324-b3d628ab-5d7e-4ef3-b980-d0292a873dc6.png)

**Comment by hawkeye116477** [comment]
Nie liczy się, to statyczny filmik, nie jeżdżący.

**Comment by krystian3w** [comment]
`filmweb.pl##.isPinned.videoPlayer`

@GWARSER, da się wymusić by uBO nie sortował klas "alfabetycznie"/"od końca po początek"?

**Comment by gwarser** [comment]
@krystian3w ale gdzie? Chyba raczej nie. I niby po co?

**Comment by krystian3w** [comment]
Łatwiej wtedy robić test `[class^]`  zamiast na ryzyk fizyk `[class*]`.

**Comment by gwarser** [comment]
> Łatwiej wtedy robić test `[class^]`

W źródle klasy też mogą zmieniać kolejność, więc `^` jest raczej ryzykowny.

W DOM Inspector wyglądają na nieposortowane, ale jest problem z odświeżaniem.
