### ISSUE TITLE
shopee.pl

### ISSUE THREAD

**Issue by hawkeye116477** [PolishFiltersTeam/PolishAnnoyanceFilters#2862]
Darmowa dostawa i słodkości :cookie: :chocolate_bar:

**Comment by krystian3w** [comment]
Mnie już przeszło szaleństwo na kupowanie drobnicy z "Chin", najpewniej AdamWr mnie wyprzedzi w ukryciu kupnu, cookies, banneru zalecającego instalację apki na Android / iOS.

Więc trzeba by sprawdzić czym ukryć linki do sociali.

**Comment by krystian3w** [comment]
Można sprawdzić czy zacznie znikać od poniedziałku pop-up z kuponem i na telefonie promocja aplikacji nad headerem.
