### ISSUE TITLE
www.arimr.gov.pl

### ISSUE THREAD

**Issue by Ravizz** [PolishFiltersTeam/PolishAnnoyanceFilters#288]
http://www.arimr.gov.pl/
gotowa reguła: `www.arimr.gov.pl##body > .hidden-xs`

### Co trzeba zrobić, aby pojawił się irytujący element?
1. Wejść na stronę

### Moja konfiguracja
**Przeglądarka internetowa:** 
FF 57.0.4 / O 50.0.2762.58 (PGO)
**System operacyjny:** 
Windows 7 PL SP1 U 64
**Bloker:** 
Nano Defender 13.20
uBO v1.14.25rc1
**Używane filtry:**
1. Polskie filtry elementów irytujących
2. POL: polskie filtry do Adblocka i uBlocka​​​​​
3. POL: polskie filtry do uBlocka uzupelnienie
4. Polskie filtry ciasteczkowe
5. KAD - Przekręty​
6. Adblock & uBlock polish filter - Adguard supplement
7. EasyList
8. Adblock Warning Removal List
9. Adguard Base Filters
10. uBlock filters
11. uBlock filters – Unbreak
12. Nano Defender Integration
13. NanoBase
14. NanoTimer
15. NanoWhitelist

### Zrzut ekranu
![](https://s3.dodajfote.pl/2018/01/18/arimre5070788cceb4760.png)

**Comment by hawkeye116477** [comment]
`arimr.gov.pl###kiwi_popup_layer`
