### ISSUE TITLE
subiektywnieofinansach.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/PolishAnnoyanceFilters#292]
![2018-01-26-subiektywnie o finansach _ subiektywnie o finansach - maciej samcik](https://user-images.githubusercontent.com/5884000/35421544-208b464c-0244-11e8-9858-ac8781aab7fd.png)

newsletter + popup

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.25
Chrome 64.0.3282.119

**Comment by hawkeye116477** [comment]
Newsletter łatwo zablokować, ale ten popup to już wyższa szkoła jazdy. Pomimo, że reguła na to jest, to on i tak po zescrollowaniu się pojawia, pewnie `script:inject` potrzebne, także potrzebna pomoc @F4z.
