### ISSUE TITLE
sklep.rms.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/PolishAnnoyanceFilters#294]
![2018-01-27-lindy 41961 kabel mini display port - vga - 1m cena](https://user-images.githubusercontent.com/5884000/35477037-35a84566-03bb-11e8-8d2d-fc8d10b231c1.png)
`https://sklep.rms.pl/lindy-41961-kabel-mini-display-port-vga-1m`

popup

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.27
Chrome 64.0.3282.119

**Comment by hawkeye116477** [comment]
`||sklep.rms.pl/js/rms_copy_copy/popup.js`
