### ISSUE TITLE
it-logic.pl

### ISSUE THREAD

**Issue by Ravizz** [PolishFiltersTeam/PolishAnnoyanceFilters#345]
widżet albo jakaś resztka, po barwach wygląda jak social, ale nie sprawdzałem

![capture_007_31012018_144126](https://user-images.githubusercontent.com/35421792/35626077-d755ce66-0694-11e8-9ef8-93adeb9a4704.png)

<details>
  <summary>moje ustawienia</summary>
  
```  
FF 58 &
uBO 1.14.25.101 &
ND 13.29

Adblock & uBlock polish filter - Adguard supplement​​
Adblock Warning Removal List​
Adguard’s Annoyance List​
Adguard Base Filters​
AlleBlock
EasyList​
Fanboy’s Annoyance List​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​
Fanboy’s Cookiemonster List​
Fanboy’s Social Blocking List​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt​​
I don't care about cookies​​
KAD - Przekręty
Nano Defender Integration​​
POL: polskie filtry do Adblocka i uBlocka​
POL: polskie filtry do uBlocka uzupelnienie​
Polskie filtry anty-dotacyjne​​
Polskie filtry ciasteczkowe​​
Polskie filtry elementów irytujących
Polskie filtry społecznościowe​​
Polskie filtry wewnętrzne
uBlock filters​
uBlock filters – Annoyances​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
```

</details>

**Comment by blocker999** [comment]
to sociale, tak trudno wyłączyć nano adblockera by to sprawdzić?

Takie rzeczy to Majkiego

**Comment by Ravizz** [comment]
@blocker999 teraz już wiem, że nie trudno, ale wcześniej omyłkowo wydawało mi się, że tak, bo w natłoku pracy pomieszało mi się tworzenie filtrów/ogarnianie uszkodzonych filtrów (które jest bardziej skomplikowane), ze zgłaszaniem stron, w którym rzeczywiście nie trzeba tego robić i wystarczy wyłączyć adblockera, a to wszystko dlatego, że wcześniej zgłaszałem mniej stron, bo dodatkowo do tych stron wyszukiwałem filtry oraz wyłapywałem uszkodzone filtry, a teraz jak widać bawię się w masówkę-zgłaszanie (bez grzebania w bebechach) i po prostu wyobraź sobie, że mi się jakiś trybik nie przestawił na nowy typ pracy.
