### ISSUE TITLE
[Grupa Polska Press]

### ISSUE THREAD

**Issue by Ravizz** [PolishFiltersTeam/PolishAnnoyanceFilters#382]
widżet video na stronach tej grupy: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/123, tych stron jest od h..ja, przykładowe strony:

http://www.gs24.pl/kultura/a/weekend-w-szczecinie-koncerty-filmy-i-huczna-rocznica-na-zamku-wideo,12899613/

![capture_059_01022018_200457](https://user-images.githubusercontent.com/35421792/35697732-576a1a98-078b-11e8-95e8-0358f7e979fc.png)

http://www.nowiny24.pl/bieszczady/a/w-szczawnem-w-bieszczadach-niedzwiedzica-zaatakowala-27letniego-mezczyzne-trafil-z-obrazeniami-do-szpitala,12900757/

![capture_072_01022018_205101](https://user-images.githubusercontent.com/35421792/35699874-a74cf822-0791-11e8-8f7d-77fd700ce29b.png)

<details>
  <summary>moje ustawienia</summary>

```
FF 58.0.1 & 
uBO 1.14.25rc1 & 
ND 13.29

Adblock & uBlock polish filter - Adguard supplement​​
Adblock Warning Removal List​
Adguard’s Annoyance List​
Adguard Base Filters​
AlleBlock
EasyList​
Fanboy’s Annoyance List​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​
Fanboy’s Cookiemonster List​
Fanboy’s Social Blocking List​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt​​
I don't care about cookies​​
KAD - Przekręty
Nano Defender Integration​​
POL: polskie filtry do Adblocka i uBlocka​
POL: polskie filtry do uBlocka uzupelnienie​
Polskie filtry anty-dotacyjne​​
Polskie filtry ciasteczkowe​​
Polskie filtry elementów irytujących
Polskie filtry społecznościowe​​
Polskie filtry społecznościowe - uzupełnienie do uBlocka i AdGuarda​​
Polskie filtry wewnętrzne
uBlock filters​
uBlock filters – Annoyances​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
```

</details>

**Comment by blocker999** [comment]
@hawkeye116477 co z tym robimy ?

**Comment by hawkeye116477** [comment]
Jak @Ravizz wynajdzie na to regułę, to dodamy :smile:.

**Comment by Ravizz** [comment]
@hawkeye116477: 

1)
`||s-pt.ppstatic.pl/p/js/regionalne/plywajace_wideo.js` 
! + ewentualnie:
`||s-pt.ppstatic.pl/o/js/osnowa.js`

(nie zauważyłem na pierwszy rzut oka żeby te filtry coś psuły, i wydaje się, że wszystko jest ok, ale też dokładnie tego nie sprawdzałem)

2)
! jeśli jednak 1) coś psują, to można alternatywnie kosmetykiem:
`gs24.pl###kontener-wideo.plywajacy`

**Comment by hawkeye116477** [comment]
Zdaje się, że pierwsza reguła działa ok, nie sądziłem, że da radę tak łatwo, jakoś nie spoglądałem na dziennik żądąń, sądziłem, że będzie potrzebna reguła `script:inject`, jak widać jednak obyło się bez tego.
Zaraz dodamy tą 1 pierwszą regułę :smile:.
