### ISSUE TITLE
bino.pl

### ISSUE THREAD

**Issue by Ravizz** [PolishFiltersTeam/PolishAnnoyanceFilters#430]
Zgłoszenie błędne/nieaktualne, zamykam, bo to jest już blokowane przez którąś z tych 5 list:
```
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​
uBlock filters – Annoyances
```
Niestety omyłkowo, nie wiem jakim cudem, miałem je wszystkie wyłączone.

**Comment by hawkeye116477** [comment]
Z tym, że lista Polskie filtry elementów irytujących nie wymaga do działania tych list, więc i tak to kwalifikuje się do dodania. Także zaraz to dodam.

**Comment by Ravizz** [comment]
Wiem, że kwalifikuje się wg. was, ale nie wg mnie, dlatego zamknąłem, a co wy z tym zrobicie wasza sprawa, i jednocześnie dobrze byłoby gdybyście wyjaśnili waszą filozofię, dlaczego 
"Polskie filtry elementów irytujących" nie bazują na angielskojęzycznych odpowiednikach?

Bo moja argumentacja jest prosta i skuteczna: skoro główna polska lista, czyli: 
"POL: polskie filtry do Adblocka i uBlocka" bazuje na angielskojęzycznym odpowiedniku "EasyList", analogicznie tak samo inne polskie listy powinny również bazować na angielskojęzycznych odpowiednikach, czyli "Polskie filtry elementów irytujących" powinny bazować na:
"Adguard’s Annoyance List​​​​​" i "Fanboy’s Annoyance List​", a 
"Polskie filtry społecznościowe" na "Fanboy’s Social Blocking List" (chyba, że społecznościowe bazują? Bo właśnie nie wiem).
