### ISSUE TITLE
 moneygrabbing.co.uk

### ISSUE THREAD

**Issue by Ravizz** [PolishFiltersTeam/PolishAnnoyanceFilters#474]
newsletter

![capture_212_06022018_205726](https://user-images.githubusercontent.com/35421792/35881232-7b245cfc-0b80-11e8-98cd-94101edff52c.png)

<details>
  <summary>moje ustawienia</summary>

```
FF 58.0.1 & 
uBO 1.15.4 & 
ND 13.31

Adblock & uBlock polish filter - Adguard supplement​​
Adblock Warning Removal List​
Adguard’s Annoyance List​
Adguard Base Filters​
Adguard Spyware Filters​​​​​
AlleBlock
EasyList​
EasyPrivacy​
Fanboy’s Annoyance List​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​
Fanboy’s Cookiemonster List​
Fanboy’s Enhanced Tracking List
Fanboy’s Social Blocking List​
I don't care about cookies​​
KAD - Przekręty
Nano Defender Integration​​
POL: polskie filtry do Adblocka i uBlocka​
POL: polskie filtry do uBlocka uzupelnienie​
Peter Lowe’s Ad and tracking server list
Polskie filtry anty-dotacyjne​​
Polskie filtry ciasteczkowe​​
Polskie filtry elementów irytujących
Polskie filtry społecznościowe​​
Polskie filtry społecznościowe - uzupełnienie do uBlocka i AdGuarda​​
Polskie filtry wewnętrzne
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt​​
uBlock filters​
uBlock filters – Annoyances​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
```

</details>

**Comment by hawkeye116477** [comment]
Dziwne, ja tego nie mam.Mam tylko popup i strzałkę.

**Comment by Ravizz** [comment]
Podobny przypadek co tu: https://github.com/MajkiIT/polish-ads-filter/issues/6059
Po wejściu w tryb responsywny i zmianie na 1366x768 też nie mam tego newslettera.

**Comment by hawkeye116477** [comment]
Tyle tylko, że ja właśnie mam rozdzielczość 1280x1024 i nie widzę tego newslettera. Sprawdzałem na innej i również nie ma, na tablecie tak samo nic. Może @blocker999 coś zobaczy :smile:.

**Comment by blocker999** [comment]
@Ravizz Gdzie ty widzisz tego newslletera?, bo ja sprawdzałem w różnych konfiguracjach nawet z wyłączonym nano adblockiem i nic, jedynie w artykule jest ale niewiem czy oto ci chodzi.
![eng](https://user-images.githubusercontent.com/23176832/35918698-0a5e73a2-0c13-11e8-803a-afd05c8576ba.png)

@hawkeye116477 Co robimy z tą kreską na dole co po najechaniu nanią można się zalogować no i co z tymi " artykułami powiązanymi pod artykułem?
http://www.moneygrabbing.co.uk/czy-tanie-rozmowy-do-polski-sa-mozliwe/

**Comment by blocker999** [comment]
@Ravizz A już chyba wiem chodzi ci o ten statyczny napis newslleter co jest na dole na czarnym tle?, jeśli tak to niech @hawkeye116477 zadecyduje.

**Comment by Ravizz** [comment]
@blocker999 co ty nie widzisz? Chodzi o ten zielony newsletter na dole na zrzucie ekranu w pierwszym komentarzu...
