### ISSUE TITLE
gizchina.com.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#500]
![dd9d888e-3738-49e7-91a4-c6dafcc97026](https://i.imgur.com/iwoDTGI.png)

**Comment by hawkeye116477** [comment]
```
gizchina.com.pl##.popmake
||chatbro.com/embed.js$third-party
```

**Comment by xMaap** [comment]
Jeszcze po scrollowaniu strony na dół z artykułami wyskakuje takie coś
https://gizchina.com.pl/2018/02/08/recenzja-doogee-mix-2/
![dd9d888e-3738-49e7-91a4-c6dafcc97026](https://i.imgur.com/nTmTrV5.png)
