### ISSUE TITLE
proline.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#502]
Po kilku sekundach wyskakuje 
![](https://i.imgur.com/iiJbDH7.png)

**Comment by hawkeye116477** [comment]
Powinno pomóc -> `proline.pl##div[style*="visibility: visible; display: block;"]`
Oprócz tego darmowy newsletter -> `proline.pl##td:nth-of-type(2) > .cell-round-title:nth-of-type(2)`
