### ISSUE TITLE
eksperymentalnie.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/PolishAnnoyanceFilters#508]
![2018-02-21-przepisy_ zdrowe bezglutenowe i eksperymentalne - eksperymentalnie comsitedesc](https://user-images.githubusercontent.com/5884000/36471119-a4f85c68-16ed-11e8-9b47-4baee6e96893.png)

newsletter

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.32
Nano Defender 13.35
Chrome 64.0.3282.167

</details>

**Comment by hawkeye116477** [comment]
Nadal jest problem, to coś z lewej po przewinięciu strony, samo się rozsuwa.
