### ISSUE TITLE
wiadomosci.radiozet.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#516]
### Opis zgłoszenia 
wejść na strone
### Link bezpośredni 
`http://wiadomosci.radiozet.pl/Polska/Protest-listonoszy-bedzie-rozga-dla-zarzadu.-Jestesmy-przeciazeni-musimy-pracowac-za-dwoch`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 58.0.2 ( 64 bity )
**Bloker:** Nano Adblocker 1.0.0.33
**Używane filtry:** 1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Ciasteczkowe
4. Polskie Filtry Elementów Irytujących

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
@blocker999 Ja tego nie mam.

**Comment by blocker999** [comment]
@hawkeye116477 Dziwne chodzi o te scrolujące kciuki przy artykule, może ktoś potwierdzić ?

![zet](https://user-images.githubusercontent.com/23176832/36992201-82e1425e-20aa-11e8-9438-57e18a3a876e.png)

A tu coś masz ?
https://www.antyradio.pl/Technologia/Internet/Amazon-startuje-z-wlasnym-YouTubem-8457

**Comment by hawkeye116477** [comment]
@blocker999 Nie ma scrollujący kciuków. Jest push, zaraz zbadam jak się go pozbyć :smile:.
