### ISSUE TITLE
wktoregory.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#522]
### Link bezpośredni 
`http://www.wktoregory.pl/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 65.0.3325.146
**Bloker:** Nano Adblocker 1.0.0.34
**Używane filtry:** 1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Ciasteczkowe
4. Polskie Filtry Elementów Irytujących

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by blocker999** [comment]
@hawkeye116477 ciekawe co autor miał na myśli?

**Comment by hawkeye116477** [comment]
Pewnie chodziło o strzałkę. A ja zapomniałem dodać strzałkę do formularza.
