### ISSUE TITLE
open.fm

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/PolishAnnoyanceFilters#527]
![2018-03-12-selena gomez x marshmello - wolves - 100 hits - open fm](https://user-images.githubusercontent.com/5884000/37311846-26338f90-2649-11e8-95df-c3a3d39ff28f.png)
`http://open.fm/play/64`

popup przy próbie opuszczenia strony

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.41
Chrome 65.0.3325.146

</details>

**Comment by blocker999** [comment]
@hawkeye116477 zerkniesz

**Comment by hawkeye116477** [comment]
@KonoromiHimaries Ale ja tego nie mam.

**Comment by hawkeye116477** [comment]
Takie coś powinno pomóc -> `https://userscripts-mirror.org/scripts/show/477070`, ale czy takie coś da się zrobić w Nano to na razie nie wiem.
