### ISSUE TITLE
waznygry.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/PolishAnnoyanceFilters#529]
![2018-03-13-lep s world - darmowe gry online na waznygry pl](https://user-images.githubusercontent.com/5884000/37347569-6bb9ec4c-26d2-11e8-9d2a-9c72201023da.png)
`http://waznygry.pl/leps-world-gra/`

popup

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.41
Chrome 65.0.3325.146

</details>

**Comment by blocker999** [comment]
@hawkeye116477 zerkniesz

**Comment by hawkeye116477** [comment]
Ciężko to wyłapać, na chwilę się tylko pojawia i zaraz znika.

**Comment by hawkeye116477** [comment]
`waznygry.pl##.wt-notification-container`
