### ISSUE TITLE
testingplus.me

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/PolishAnnoyanceFilters#530]
![2018-03-13-testingplus me - testowanie automatyczne - michal slezak - testowanie automatycz](https://user-images.githubusercontent.com/5884000/37348960-9e2bf58c-26d5-11e8-9e05-91f88045716c.png)

popup

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.41
Chrome 65.0.3325.146

</details>

**Comment by blocker999** [comment]
@hawkeye116477 zerkniesz
