### ISSUE TITLE
jakrobicmarketing.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/PolishAnnoyanceFilters#531]
![2018-03-13-jakrobicmarketing pl](https://user-images.githubusercontent.com/5884000/37351103-9dca3360-26da-11e8-84b8-0370c22ffdda.png)

newsletter + popup

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.41
Chrome 65.0.3325.146

</details>

**Comment by blocker999** [comment]
@KonoromiHimaries Niemam żadnego popupa, może chodzi Ci o chat ?

@hawkeye116477 zerkniesz

**Comment by hawkeye116477** [comment]
`##.fb-customerchat, .fb_dialog_advanced`
