### ISSUE TITLE
fortnitepolska.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/PolishAnnoyanceFilters#538]
![2018-03-13-juz wkrotce miedzy platformowa rozgrywka w fortnite z xbox - fortnite polska](https://user-images.githubusercontent.com/5884000/37359684-895a1cd8-26ee-11e8-8e62-aa677d14590c.png)
`https://fortnitepolska.pl/juz-wkrotce-miedzy-platformowa-rozgrywka-w-fortnite-na-xbox#disqus_thread`

pasek na dole

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.41
Chrome 65.0.3325.146

</details>

**Comment by blocker999** [comment]
@KonoromiHimaries Ja tego niemam

@hawkeye116477 zerkniesz

**Comment by hawkeye116477** [comment]
`fortnitepolska.pl###single-sticky`
