### ISSUE TITLE
clivio.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/PolishAnnoyanceFilters#540]
![2018-03-13-clivio pl - tworzenie stron internetowych projektowanie graficzne](https://user-images.githubusercontent.com/5884000/37365350-873914e0-26fd-11e8-9f0d-310483f32a09.png)

przycisk up + kursor

<details><summary>moje ustawienia</summary>

moje filtry
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.41
Chrome 65.0.3325.146

</details>

**Comment by blocker999** [comment]
@KonoromiHimaries Jaki kursor?

**Comment by hawkeye116477** [comment]
Pewnie chodzi o ten kursor-ołówek, by zmienić go na normalny.

**Comment by blocker999** [comment]
@hawkeye116477 stezałke usune ale kursor zostawiam tobie ewentualnie może ktoś pomoże albo zostawiamy to

**Comment by hawkeye116477** [comment]
@blocker999 Łatwizna :stuck_out_tongue: 
```
||clivio.pl/wp-content/themes/clivio/img/cursor.png
||clivio.pl/wp-content/themes/clivio/img/cursorhover.png
```
