### ISSUE TITLE
lento.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/PolishAnnoyanceFilters#569]
![2018-03-15-ogloszenia - darmowe ogloszenia drobne lento pl](https://user-images.githubusercontent.com/5884000/37482645-0a805362-2885-11e8-985d-b71d6b17849e.png)

przycisk zgłoś opinię do usadzenia

**Comment by hawkeye116477** [comment]
Link do kontaktu już jest, więc przycisk zbędny, wywalimy.
