### ISSUE TITLE
kodiwpigulce.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#579]
![zrzut ekranu z 2018-03-19 00-49-47](https://user-images.githubusercontent.com/36385327/37572731-ba24b218-2b0f-11e8-8952-21541364365c.png)

**Comment by hawkeye116477** [comment]
@xMaap Jeśli chodzi o „zobacz również" to u mnie tego nie ma. Może to kwestia rozdzielczości i ja mam po prostu za małą.
