### ISSUE TITLE
info o chrome

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishAnnoyanceFilters#59]
@hawkeye116477 Co sądzisz o takiej dziwnej sytuacji mianowicie w Cyberfoxie jest info o chrome na stronie google.pl podczas gdy na innych przeglądarkach tego niema gdyż blokuje to ` ||google.*/gen_204?$image` w EasyPrivacy, może warto to dodać?, w jakiej formie by nierozwalić przyokazji pozostałych usług googla?

![chrome](https://user-images.githubusercontent.com/23176832/29169904-a1831cfe-7dd6-11e7-845e-1b48e04fb00d.png)

**Comment by hawkeye116477** [comment]
@blocker999 Korzystasz jeszcze z Cyberfoksa? Ja już od jakiegoś czasu przesiadłem się na Waterfoksa, który idzie teraz bardziej do przodu :smile:.
Jakie info o Chrome, jak tam tylko pisze czy chcesz ustawić Google jako stronę startową. Na Cyberfoksie 52.2.1 tego nie widzę, bo EasyPrivacy to blokuje. Jak u nich już to jest, to chyba nie ma po co duplikować.

**Comment by blocker999** [comment]
@hawkeye116477 OK, zostawie to

**Comment by krystian3w** [comment]
Wycieka z AG, oni filtr uznali za nie do obrony prywatności.
