### ISSUE TITLE
dziennikzbrojny.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/PolishAnnoyanceFilters#598]
![2018-03-25-offset na wisle podpisany - dziennikzbrojny pl](https://user-images.githubusercontent.com/5884000/37875075-9a552730-303a-11e8-8a2f-4aab1f827e9c.png)
`http://dziennikzbrojny.pl/aktualnosci/news,1,10867,aktualnosci-z-polski,offset-na-wisle-podpisany`

newsletter na dole strony + widget więcej polecanych artykułów

**Comment by hawkeye116477** [comment]
@KonoromiHimaries Newsletter widzę, ale widgetu nie ma. Poproszę screena.

**Comment by blocker999** [comment]
@hawkeye116477 Screen masz powyżej a nanim na dole w rogu " więcej polecanych artykułów "

@KonoromiHimaries Na przyszłość bardzo proszę oznaczać widzety

**Comment by hawkeye116477** [comment]
@blocker999 No teraz jest, bo @KonoromiHimaries edytował post i dodał :smile:.
