### ISSUE TITLE
szerokadroga.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/PolishAnnoyanceFilters#622]
newsletter na dole strony

**Comment by krystian3w** [comment]
chyba mają przeciążenia :coffin: 

> ### Internal Server Error :coffin: 
> 
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> 
> Please contact the server administrator at webmaster@szerokadroga.pl to inform them of the time this error occurred, and the actions you performed just before this error.
> 
> More information about this error may be available in the server error log.
> 
> Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

Z kopii Google, bo się załadowała jako-tako:
`##.gum_footer_widget.widget:nth-of-type(3)`
