### ISSUE TITLE
wiadomosci.wp.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [PolishFiltersTeam/PolishAnnoyanceFilters#628]
komunikat na topce `ustaw jako stronę startową`

**Comment by hawkeye116477** [comment]
@KonoromiHimaries Ja tego nie mam.

**Comment by krystian3w** [comment]
U mnie też działa, może jak będziesz jeszcze mieć to zapisz stronę, do zip i wrzuć jako "załącznik" (może się będzie nadawać do próby zablokowania jak odbiega od schematu.

**Comment by krystian3w** [comment]
@hawkeye116477  chyba sprawdzanie noodów lub coś popsuło #1433
