### ISSUE TITLE
helios.pl

### ISSUE THREAD

**Issue by WowDude** [PolishFiltersTeam/PolishAnnoyanceFilters#639]
1. Scrolling widget (https://www.helios.pl/33,Tczew/StronaGlowna/)
2. POPUP remains (https://www.helios.pl/33,Tczew/Repertuar/)

### Zrzut ekranu

1
![capture_087_04042018_215339](https://user-images.githubusercontent.com/37474031/38331151-c44dbf82-3852-11e8-999c-7109320beb5f.png)

2
![capture_086_04042018_215324](https://user-images.githubusercontent.com/37474031/38331152-c67a53d8-3852-11e8-9b05-850458f04e09.png)

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.15.24

### Filtry:

<details>
  <summary>Click to expand</summary>

Nano Defender 13.48
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Annoyances
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard’s Annoyance List
Adguard Base Filters
Adguard Spyware Filters
Adblock & uBlock polish filter - AdGuard supplement
Adblock Warning Removal List
EasyList
EasyList Polish
EasyPrivacy
Fanboy’s Annoyance List
Fanboy’s Anti-Thirdparty Social (see warning inside list)
Fanboy’s Cookiemonster List
Fanboy’s Enhanced Tracking List
Fanboy's Polish
Fanboy’s Social Blocking List
I'm OK with cookies​
I don't care about cookies
hpHosts’ Ad and tracking servers
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Anty-Donacyjne
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry RSS​
Polskie Filtry Społecznościowe​
Polskie Filtry Wewnętrzne
AlleBlock​
KAD - Przekręty

</details>

**Comment by hawkeye116477** [comment]
So I see this button, but I didn't see popup remains.

**Comment by WowDude** [comment]
> @WowDude : 1. Visit the page

I forgot that to add: 2. Scroll the webpage  to the bottom

**Comment by hawkeye116477** [comment]
@WowDude Unfortunately, I don't see it.
@blocker999 or @RikoDEV guys, can you look here?

**Comment by WowDude** [comment]
@hawkeye116477 I see it also on Opera/ Chrome
You don't see it with all my filters list enabled?

**Comment by WowDude** [comment]
@hawkeye116477

 I've just investigated and can only reproduce on Windows 7 DPI 125% medium:
http://www.lawfirmsoftware.com/support/change_dpi_settings_windows_7.htm

**Comment by hawkeye116477** [comment]
@WowDude I'm professional, I don't use „Winda", only Linux, but I also have that setting :smile:.
![screenshot_20180405_200620](https://user-images.githubusercontent.com/19818572/38383459-d6148312-390c-11e8-95f8-ecf7b24be714.png)

But I see that this is advertisement, so for @MajkiIT.
