### ISSUE TITLE
polsatsport.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#643]
### Link bezpośredni 
`http://www.polsatsport.pl/wiadomosc/2018-04-04/canelo-ggg-2-szczegoly-odwolania-walki-za-100-milionow/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Vivaldi 1.93.955.48
**Bloker:** uBlock Origin 1.0.0.40
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Ciasteczkowe
4. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
#644 / #2342
