### ISSUE TITLE
polsatnews.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#644]
### Link bezpośredni 
`http://www.polsatnews.pl/wiadomosc/2018-04-05/trump-chce-wzmocnic-straz-graniczna-na-granicy-z-meksykiem-skieruje-tam-gwardie-narodowa/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Vivaldi 1.93.955.48
**Bloker:** Nano Adblocker 1.0.0.40
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Ciasteczkowe
4. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
#2342

**Comment by krystian3w** [comment]
#2342

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2342 https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/643

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2342
