### ISSUE TITLE
stopnadwadze.pl

### ISSUE THREAD

**Issue by WowDude** [PolishFiltersTeam/PolishAnnoyanceFilters#648]
1 Scrolling Popup
2 Scrolling right panel

### 1 https://stopnadwadze.pl/
![capture_128_05042018_190515](https://user-images.githubusercontent.com/37474031/38380538-54e7dc38-3904-11e8-8faa-4abefe371cfe.png)

### 2 https://stopnadwadze.pl/cwiczenia/cwiczenia-na-uda/jedrne-posladki/
![capture_129_05042018_190730](https://user-images.githubusercontent.com/37474031/38380643-a0506a28-3904-11e8-8a8f-2470c12a4f23.png)

### Link bezpośredni

(1) https://stopnadwadze.pl/ 
(2) https://stopnadwadze.pl/cwiczenia/cwiczenia-na-uda/jedrne-posladki/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page (1)
2. Scroll down (2)

### Moja konfiguracja
Win 7 SP1 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.15.24

### Filtry:

<details>
  <summary>Click to expand</summary>

Nano Defender 13.48
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Annoyances
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard’s Annoyance List
Adguard Base Filters
Adguard Spyware Filters
Adblock & uBlock polish filter - AdGuard supplement
Adblock Warning Removal List
EasyList
EasyList Polish
EasyPrivacy
Fanboy’s Annoyance List
Fanboy’s Anti-Thirdparty Social (see warning inside list)
Fanboy’s Cookiemonster List
Fanboy’s Enhanced Tracking List
Fanboy's Polish
Fanboy’s Social Blocking List
I'm OK with cookies​
I don't care about cookies
hpHosts’ Ad and tracking servers
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Anty-Donacyjne
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry RSS​
Polskie Filtry Społecznościowe​
Polskie Filtry Wewnętrzne
AlleBlock​
KAD - Przekręty

</details>

**Comment by hawkeye116477** [comment]
Ok, I see widget „See also" and I will add that, but widget on top is for Polish Social Filters and right panel is for `https://github.com/yourduskquibbles/webannoyances` :smile:.

**Comment by WowDude** [comment]
@hawkeye116477 ok.
