### ISSUE TITLE
tvp.info

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#666]
### Link bezpośredni 
`https://www.tvp.info/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Vivaldi 1.93.955.48
**Bloker:** Nano Adblocker 1.0.0.40
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Ciasteczkowe
4. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
@F4z Możesz tu zerknąć? Takie coś `##script:inject(abort-on-property-read.js, parseFloat)`, że owszem ten ruchomy filmik znika, ale wtedy też ten na górze nie działa. Masz lepszy pomysł może?
