### ISSUE TITLE
rp.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#682]
### Link bezpośredni 
`http://www.rp.pl/`
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Vivaldi 1.93.955.48
**Bloker:** Nano Adblocker 1.0.0.40
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Ciasteczkowe
4. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
@blocker999 Na głównej tego nie widzę, może mam za niską rozdzielczość. Poproszę fotkę.

**Comment by blocker999** [comment]
![filmik rp](https://user-images.githubusercontent.com/23176832/38455093-0e211ace-3a73-11e8-847f-61260bd65df2.png)
