### ISSUE TITLE
kalisz.pl

### ISSUE THREAD

**Issue by WowDude** [PolishFiltersTeam/PolishAnnoyanceFilters#770]
Newsletter 

(btw @MajkiIT banned me yesterday morning from https://github.com/MajkiIT/polish-ads-filter/issues I can't neither contribute nor create issues, since 36 hours already, just wanted you to know about it, that's why I dissappeared from the POL repo, and that he quietly bans people).

### Zrzut ekranu

![capture_001_11042018_214341](https://user-images.githubusercontent.com/37474031/38639483-a3798e74-3dd1-11e8-8904-d6863abbc762.png)

### Link bezpośredni

 http://www.kalisz.pl/pl

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.15.24

### Filtry:

<details>
  <summary>Click to expand</summary>

Nano Defender 13.48
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Annoyances
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard’s Annoyance List
Adguard Base Filters
Adguard Spyware Filters
Adblock & uBlock polish filter - AdGuard supplement
Adblock Warning Removal List
EasyList
EasyList Polish
EasyPrivacy
Fanboy’s Annoyance List
Fanboy’s Anti-Thirdparty Social (see warning inside list)
Fanboy’s Cookiemonster List
Fanboy’s Enhanced Tracking List
Fanboy's Polish
I'm OK with cookies​
I don't care about cookies
hpHosts’ Ad and tracking servers
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Anty-Donacyjne
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry RSS​
Polskie Filtry Społecznościowe​
Polskie Filtry Wewnętrzne
AlleBlock​
KAD - Przekręty
Web Annoyances Ultralist

</details>

**Comment by hawkeye116477** [comment]
To jest gazeta „Newsletter", więc zostawimy :smile:.

**Comment by KonoromiHimaries** [comment]
@WowDude you can submit 1000+ new social issues on discord

**Comment by hawkeye116477** [comment]
@KonoromiHimaries Do not overdo it, 1000 is a bit too much :smiley:.

**Comment by WowDude** [comment]
@KonoromiHimaries  @hawkeye116477 

It's been 7 days already and I still have a ban, due to a small prank, it seems that he gave me a life sentence as if I was a murderer,  it seems that it's rather his private vengeance that I'm still banned, than a honest judgment, it seems that this guy @MajkiIT likes two things in his life: suck a dick and give bans, I'm wondering which one does he like more.

Tell me, isn't a 7 days ban long enought?
