### ISSUE TITLE
myfitnessplace.pl

### ISSUE THREAD

**Issue by WowDude** [PolishFiltersTeam/PolishAnnoyanceFilters#820]
1 popup
2 scrolling widget

### Zrzut ekranu

1
![capture_056_13042018_162238](https://user-images.githubusercontent.com/37474031/38740095-f913cb90-3f36-11e8-9fc7-594de10c587e.png)

2
![capture_057_13042018_162241](https://user-images.githubusercontent.com/37474031/38740096-f943757a-3f36-11e8-8119-2d81df979235.png)

### Link bezpośredni

https://www.myfitnessplace.pl/

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?

1. Visit the page

### Moja konfiguracja
Win 7 SP1 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.15.24

### Filtry:

<details>
  <summary>Click to expand</summary>

Nano Defender 13.48
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Annoyances
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard’s Annoyance List
Adguard Base Filters
Adguard Spyware Filters
Adblock & uBlock polish filter - AdGuard supplement
Adblock Warning Removal List
EasyList
EasyList Polish
EasyPrivacy
Fanboy’s Annoyance List
Fanboy’s Anti-Thirdparty Social (see warning inside list)
Fanboy’s Cookiemonster List
Fanboy’s Enhanced Tracking List
Fanboy's Polish
I'm OK with cookies​
I don't care about cookies
hpHosts’ Ad and tracking servers
Peter Lowe’s Ad and tracking server list
POL: polskie filtry do Adblocka i uBlocka
Polish Privacy Filters
Polskie Filtry Anty-Donacyjne
Polskie Filtry Ciasteczkowe​
Polskie Filtry Elementów Irytujących
Polskie Filtry RSS​
Polskie Filtry Społecznościowe​
Polskie Filtry Wewnętrzne
AlleBlock​
KAD - Przekręty
Web Annoyances Ultralist

</details>

**Comment by hawkeye116477** [comment]
Ja tam tego popupu nie widzę.

**Comment by WowDude** [comment]
Nor I, it seems that it just stopped to appear.
