### ISSUE TITLE
Ulepszenie

### ISSUE THREAD

**Issue by WowDude** [PolishFiltersTeam/PolishAnnoyanceFilters#928]
### Typ elementu/problemu
- [] błąd
- [] chat
- [] newsletter
- [] popup
- [] prawy klik
- [] przycisk
- [] push
- [x] pytanie
- [] scrollujący filmik
- [] strzałka
- [x] ulepszenie
- [] widżet

Add to bot a possibility to remove labels, example:
if change from `- [x] widżet` to `- [] widżet` bot should remove the label

### Moja konfiguracja
**Przeglądarka internetowa:**  FF 59.0.2 [64bit]
**System operacyjny:**  Win 7 SP1 [64bit]
**Bloker:**  uBO 1.15.25rc3 & ND 13.48

### Zrzut ekranu

**Używane filtry:**
<details>
  <summary>Szczegóły</summary>

1. Nano Defender filter
2. Nano Base filter
3. Nano Whitelist filter
4. uBlock filters
5. uBlock filters – Annoyances
6. uBlock filters – Badware risks
7. uBlock filters – Privacy
8. uBlock filters – Resource abuse​​​​​
9. uBlock filters – Unbreak
10. Adguard’s Annoyance List
11. Adguard Base Filters
12. Adguard Spyware Filters
13. Adblock & uBlock polish filter - AdGuard supplement
14. Adblock Warning Removal List
15. EasyList
16. EasyList Polish
17. EasyPrivacy
18. Fanboy’s Annoyance List
19. Fanboy’s Anti-Thirdparty Social (see warning inside list)
20. Fanboy’s Cookiemonster List
21. Fanboy’s Enhanced Tracking List
22. Fanboy's Polish
23. I'm OK with cookies​
24. I don't care about cookies
25. hpHosts’ Ad and tracking servers
26. Peter Lowe’s Ad and tracking server list
27. POL: polskie filtry do Adblocka i uBlocka
28. Polish Privacy Filters
29. Polskie Filtry Anty-Donacyjne
30. Polskie Filtry Ciasteczkowe​
31. Polskie Filtry Elementów Irytujących
32. Polskie Filtry RSS​
33. Polskie Filtry Społecznościowe​
34. Polskie Filtry Wewnętrzne
35. AlleBlock​
36. KAD - Przekręty
37. Web Annoyances Ultralist

</details>

**Comment by hawkeye116477** [comment]
Ok, co do pierwszej sugestii, to już poprawione. A co do tej drugiej, to prześlę prośbę do upstream i zobaczymy co oni powiedzą, no chyba, że @RikoDEV się tym zajmie :smile:.

**Comment by WowDude** [comment]
@hawkeye116477 as for Bot ok, as for `czat` is ok now, but as for popup I see now I'm not sure about `wyskakujące okienko ` coz it looks a bit too long, so maybe I've changed my mind and `popup` was ok, I'm undecided,  I just don't know now, I let you decide finally, feel free to decide `popup` vs `wyskakujące okienko`.

**Comment by WowDude** [comment]
@hawkeye116477 : why locking the thread: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/770#issuecomment-382279502 instead of answering a simply question and explain the situation? Don't you think that the ban is too long? Why don't you just answer? Don't you have your own brain/opinion or maybe it's damaged?  Whatever @MajkiIT does, you always accept it, like a whore, do you sleep with him? DO you make a sex with him? Is he your boyfriend / father? Or what? One whore ban me for too long, another whore lock the thread. You keep with the administration + he is your friend + you both are out of arguments = so you simply lock the thread and defend him and yourself? He ban me for too long and when I ask why so long, you lock the thread. Is that your and @MajkiIT ' s level of a civilized discussion? MajkiIT and you just abuse your rights/power.

 - #MajkiIT banned me for too long due to a small prank
- after 7 days I ask why so long I'm still banned
- you instead of answering just lock the thread

Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. Just ban. Just lock the thread. 

Consider banning yourselves and lock your damaged brains, whores.

**Comment by hawkeye116477** [comment]
@WowDude Z tobą zawsze nie idzie się dogadać, zawsze się tak samo kończy, więc nie mam ochoty wdawać się w dyskusję. A kary raczej dopasowujemy do osób, a nie do tego, co nabroili. A w przeszłości tobie trochę tego się nazbierało.
