### ISSUE TITLE
proline.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#938]
### Typ elementu/problemu
- [x] błąd
- [] czat
- [] newsletter
- [] popup
- [] prawy klik
- [] przycisk
- [] push
- [] pytanie
- [] scrollujący filmik
- [] strzałka
- [] ulepszenie
- [] widżet

Po dodaniu do Kosza np.
https://proline.pl/dysk-toshiba-p300-hdwd110uzsva-1tb-sata-iii-64mb-7200obr-min-bulk-p951166
wybraniu opcji płatności i następnie kliknięciu "Kontynuuj" nie wyświetla się logowanie.
![opera zdjecie_2018-04-21_214804_proline pl](https://user-images.githubusercontent.com/36385327/39088199-2fc61f12-45ae-11e8-8a76-2aff423ff2db.png)

**Comment by hawkeye116477** [comment]
```
proline.pl#@#td:nth-of-type(2) > .cell-round-title:nth-of-type(2)
proline.pl#?#td:nth-of-type(2) > .cell-round-title:nth-of-type(2):-abp-contains(Newsletter)
```
