### ISSUE TITLE
majsterkowo.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#943]
https://majsterkowo.pl/modularna-lampka-do-lutowania-oparta-na-tasmie-led/
### Typ elementu/problemu
- [] błąd
- [] czat
- [] newsletter
- [x] popup
- [] prawy klik
- [] przycisk
- [] push
- [] pytanie
- [] scrollujący filmik
- [] strzałka
- [] ulepszenie
- [] widżet
![opera zdjecie_2018-04-30_015634_majsterkowo pl](https://user-images.githubusercontent.com/36385327/39412293-56fb88f2-4c1a-11e8-95b8-0b159a22cd8c.png)

**Comment by krystian3w** [comment]
`##.et_bloom_popup ` lub`##.et_bloom_auto_popup`

**Comment by hawkeye116477** [comment]
Albo `||majsterkowo.pl/wp-content/plugins/bloom/js/custom.js` :smile:.
