### ISSUE TITLE
[adguard] kodowanie

### ISSUE THREAD

**Issue by FadeMind** [PolishFiltersTeam/PolishAnnoyanceFilters#956]
Proszę zamieńcie nasze polskie ąśćźż na asczz w plikach bo adguard nie ogarnia kodowania:
![20180531-006-screenshoot](https://user-images.githubusercontent.com/9846948/40798588-b2e0006c-650b-11e8-85c4-58be6e934212.png)
Po za tym nie widzę was w dostępnych filtrach w Adguard For Windows. 
Możecie dodać oficjalną prośbę w tym repo:

https://github.com/AdguardTeam/FiltersRegistry/issues

pozdrawiam serdecznie

**Comment by hawkeye116477** [comment]
Niby mogę zmienić, ale oni nadpisują nagłówek, więc to musi być rozwiązana po stronie AdGuarda => `https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_237_PolishAnnoyance/metadata.json`

**Comment by F4z** [comment]
O ile się nie mylę, to lista `Polskie Filtry Elementów Irytujących` jest dostępna w AdGuardzie dla Windowsa i u mnie to wygląda prawidłowo:
![image](https://user-images.githubusercontent.com/11742596/40800264-2f736638-6510-11e8-9582-9d46f053468e.png)

**Comment by FadeMind** [comment]
@hawkeye116477  Chodzi mi o **suplement do annoyance polish** z linku 
`abp:subscribe?location=https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB_uBlock_AdGuard.txt&title=Annoyance_supplement`

![20180531-008-screenshoot](https://user-images.githubusercontent.com/9846948/40800296-45c4f280-6510-11e8-98aa-e86cd38ff4a1.png)

Rejestr Adguarda nie posiada tego suplementu

**Comment by hawkeye116477** [comment]
@F4z To co pokazujesz to czy aby nie jest raczej filtr Teamu AdGuarda?
@FadeMind Jeżeli chodzi o suplement, to na głównej liście jest dodana instrukcja `#include`, która powinna chyba działać w AG albo będzie i ona jest po to by dwie listy były razem i by nie trzeba było drugiej subskrybować.

**Comment by FadeMind** [comment]
@hawkeye116477 adguard tego nie honoruje :P (mam betę)

CC @ameshkov

**Comment by F4z** [comment]
>@F4z To co pokazujesz to czy aby nie jest raczej filtr Teamu AdGuarda?

Tak było, ale już zmieniłem obrazek na prawidłowy.

>@F4z jest tam dostępny tylko normalny link do[...]

Zgadza się, ale wcześniej nie pisałeś, że chodzi o "suplement".

>Jeżeli chodzi o suplement, to na głównej liście jest dodana instrukcja #include, która powinna chyba działać w AG albo będzie[...]

Dopiero będzie w przyszłości.

**Comment by ameshkov** [comment]
Thx for mentioning me!

As I understand (from auto-translation), this problem is on AdGuard's side. 

@FadeMind could you please explain it in english just in case?

Regarding `#include`, we partly support it, I will file a request to this repo once we test it thoroughly.

**Comment by FadeMind** [comment]
@ameshkov hi

From the beginning:
At https://www.certyficate.it/adblock/ are listed all official adblock list for adblockers (see icons).
In Adguard for Windows, Adguard Chrome Ext. and Adguard for Android some of them are missing in Filters Registry.

I created this task issue after trying adding RULE from LINK
`abp:subscribe?location=https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB_uBlock_AdGuard.txt&title=Annoyance_supplement`
And now Adguard does not decoding valid special characters in names:
![20180531-008-screenshoot](https://user-images.githubusercontent.com/9846948/40801780-0f9069fc-6514-11e8-8ffa-9d291a639ffd.png)
Shuold be
`Polskie Filtry Elementów Irytujących - Uzupełnienie do uBlocka i AdGuarda`
is
![20180531-009-screenshoot](https://user-images.githubusercontent.com/9846948/40801849-42c1ba74-6514-11e8-8005-a499d1f210d4.png)

so, there are 2 task:
- error encoding names of repositories from external soursces (adb:)
- missing some suplements and main lists from Polish developers for block ads in Polish websites

**Comment by ameshkov** [comment]
@FadeMind got it, thank you!

Both issues are 100% on our side, I will file bug reports.

**Comment by FadeMind** [comment]
@ameshkov  thank you for your feedback.

**Comment by hawkeye116477** [comment]
Ok, a więc zamykam temat, skoro to zostało naprawione w 6.3.1118.3511 Beta.
`https://github.com/AdguardTeam/AdguardForWindows/releases/tag/v6.3.1118.3511-beta`
