### ISSUE TITLE
http://orteil.dashnet.org/cookieclicker/

### ISSUE THREAD

**Issue by skibbipl** [PolishFiltersTeam/PolishAnnoyanceFilters#958]
### Moja konfiguracja
**Przeglądarka internetowa:** 
Firefox Nightly 62.0a1 (2018-06-04) (64 bity)

**System operacyjny:** 
Windows 10 1804 x64

**Bloker:** 
UBO 1.16.8, ND 14.44

**Używane filtry:**
1. EasyList + EasyPrivacy
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
4. Nano Defender integration + filter + whitelist
5. Fanboy’s Cookiemonster List

### Link bezpośredni (opcjonalny)
http://orteil.dashnet.org/cookieclicker/

### Zrzut ekranu (opcjonalny)
Przeciągnij tutaj swój zrzut lub zamieść do niego link.
![obraz](https://user-images.githubusercontent.com/4746858/40943002-04fba30a-6850-11e8-84d0-a0b59bf93a3f.png)
![obraz](https://user-images.githubusercontent.com/4746858/40943068-3bd92a46-6850-11e8-8057-27ed315f7d11.png)

### Inne ważne informacje mogące mieć znaczenie (opcjonalne):
Problem polega na tym że z włączonymi filtrami znika overlay z liczbą ciasteczek. Problemem są te filtry:
```
##div[class*="Cookie"]
##:not(input)[id*="cookie"]
##:not(input)[id*="Cookie"]
###cookies:not(body):not(html):not(.section)
```
Jest to przypadek brzegowy więc w sumie nie wiem czy warto kombinować.

**Comment by hawkeye116477** [comment]
Warto, damy wyjątki.
Tyle powinno wystarczyć :smile:
```
orteil.dashnet.org#@#:not(input)[id*="cookie"]
orteil.dashnet.org#@##cookies
```
