### ISSUE TITLE
mojmac.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#972]
### Typ elementu/problemu
- [] błąd
- [] czat
- [x] newsletter
- [] otagowany link wewnętrzny
- [x] popup
- [] prawy klik
- [] przycisk
- [] push
- [] pytanie
- [] scrollujący filmik
- [] strzałka
- [] ulepszenie
- [] widżet

![opera zdjecie_2018-06-19_052810_mojmac pl](https://user-images.githubusercontent.com/36385327/41574677-b6ac2296-7381-11e8-9d66-911aa2e3f298.png)

![opera zdjecie_2018-06-19_115245_mojmac pl](https://user-images.githubusercontent.com/35370833/41590364-1c060884-73b7-11e8-88cf-292543d0867f.png)

**Comment by krystian3w** [comment]
`##.et_bloom_optin_57.et_bloom_make_form_visible.et_bloom_optin.et_bloom_inline_form`

`##.et_bloom_animated.et_bloom_visible.et_bloom_auto_close.et_bloom_hide_mobile_optin.et_bloom_trigger_idle.et_bloom_trigger_bottom.et_bloom_auto_popup.et_bloom_optin_23.et_bloom_resize.et_bloom_optin.et_bloom_popup`

**Comment by hawkeye116477** [comment]
```
mojmac.pl##.et_bloom_animated
mojmac.pl##.et_pb_code > .bloom-privacy
```
