### ISSUE TITLE
chocholowskietermy.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishAnnoyanceFilters#981]
### Typ elementu 
push,strzałka
### Link bezpośredni 
N/A
### Zrzut ekranu
N/A
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Mozilla Firefox 60.0
**Bloker:** uBlock Origin 1.16.10
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
`||cdn.onesignal.com^` -  muszę dopuścić z:

> Filtr statyczny `||cdn.onesignal.com^` znajdujący się w:
> 
>    * Peter Lowe’s Ad and tracking server list

by odtworzyć push.

\+

`##.mk-go-top`
