### ISSUE TITLE
onet.pl

### ISSUE THREAD

**Issue by xesarni** [PolishFiltersTeam/PolishAnnoyanceFilters#983]
### Typ elementu/problemu
- [] błąd
- [] czat
- [] newsletter
- [] otagowany link wewnętrzny
- [x] popup
- [] prawy klik
- [] przycisk
- [] push
- [] pytanie
- [] scrollujący filmik
- [] strzałka
- [] ulepszenie
- [] widżet

### Moja konfiguracja
**Przeglądarka internetowa:** 
Firefox 61
**System operacyjny:** 
Windows 10
**Bloker:** 
uBlock Origin 1.16.10
**Używane filtry:**
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących

### Link bezpośredni (opcjonalny)

onet.pl
### Inne ważne informacje mogące mieć znaczenie (opcjonalne):

Ukryty popup (reguła` pl##.cmp-app_gdpr:not(body):not(html)` ) blokuje przewijanie na stronach Onetu.

**Comment by hawkeye116477** [comment]
Powinno pomóc => `||cmp.dreamlab.pl/static/cmp.complete.bundle.js` :smile:

**Comment by xesarni** [comment]
Pomogło, dzięki.
