### ISSUE TITLE
dominospizza.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#993]
### Typ elementu/problemu
- [x] błąd
- [] czat
- [] newsletter
- [] otagowany link wewnętrzny
- [x] popup
- [] prawy klik
- [] przycisk
- [] push
- [] pytanie
- [] scrollujący filmik
- [] strzałka
- [] ulepszenie
- [] widżet

![opera zdjecie_2018-07-20_095312_dominospizza pl](https://user-images.githubusercontent.com/36385327/42990507-1cb2fd0a-8c03-11e8-8107-907a4531c604.png)

Dodatkowo po jakimś czasie wystakuje
![opera zdjecie_2018-07-20_095425_dominospizza pl](https://user-images.githubusercontent.com/36385327/42990519-2554586e-8c03-11e8-8492-88595a678d88.png)

**Comment by hawkeye116477** [comment]
```
||dominospizza.pl/js-libraries/bioep.min.js
dominospizza.pl##.popup_exit, .overlay, #jsNewsletterLayer
```
