### ISSUE TITLE
podaj.to

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishAnnoyanceFilters#995]
https://podaj.to/post/7738,1,policjanci-w-ostatniej-chwili-ratuj-przeraonego-dwulatka-z-nagrzanego-auta-podczas-gdy-jego-mama-bya-na-festiwalu.html
Po scrollowaniu strony
![opera zdjecie_2018-07-25_161602_podaj to](https://user-images.githubusercontent.com/36385327/43206532-3efeed3e-9026-11e8-806f-19821573ce25.png)

### Typ elementu/problemu
- [] błąd
- [] czat
- [] newsletter
- [] otagowany link wewnętrzny
- [x] popup
- [] prawy klik
- [] przycisk
- [] push
- [] pytanie
- [] scrollujący filmik
- [] strzałka
- [] ulepszenie
- [ ] widżet

**Comment by hawkeye116477** [comment]
```
podaj.to###popupbottom
||podaj.to/content/js/facebook.min.js
```
